phpbb/phpbb

phpBB/phpbb/db/migration/data/v310/mysql_fulltext_drop.php, phpBB/phpbb/db/migration/data/v310/postgres_fulltext_drop.php
https://tracker.phpbb.com/browse/PHPBB3-13238
The reason why this one works, in opposite to #3092 is, because we only get the list of indexes in the `effectively_installed()`.
This method is not called when generating the schema. So the schema can still be generated with the wrong db object. For live boards this does not matter, because when the update is run, `effectively_installed()` is called, filling the array with the indexes that need to be deleted:
https://github.com/phpbb/phpbb/blob/develop/phpBB/phpbb/db/migrator.php#L254
https://github.com/phpbb/phpbb/blob/develop/phpBB/phpbb/db/migrator.php#L283
=> [ticket/13238] Do not drop indexes that do not exist from fulltext search

phpBB/includes/acp/acp_bbcodes.php, phpBB/phpbb/db/migration/data/v31x/update_custom_bbcodes_with_idn.php
Custom BBCode URL tokens does not support IDN.
Custom BBCodes added earlier than IDN PR #3189 has been applied are unaffected.
<a href="https://tracker.phpbb.com/browse/PHPBB3-13492">PHPBB3-13492</a>.
=> [ticket/13492] Fix IDN support for custom BBCode URL tokens

phpBB/includes/acp/acp_prune.php
[PHPBB3-13420](https://tracker.phpbb.com/browse/PHPBB3-13420)
=> [ticket/13420] Correctly filter by lt/gt/equal to 0 posts when pruning users.

phpBB/phpbb/profilefields/type/type_bool.php
prepare_hidden_fields is expected to return null if the option is not sent
in the request. The boolean method returns false instead, which results in
the options being set as false in hidden fields when accessing the first edit
step.
When checking the "Default value" option, there is also a failure to check
whether the "Field type" option is set to checkbox, thus resulting in this
option getting lost as well.
[PHPBB3-12642](https://tracker.phpbb.com/browse/PHPBB3-12642)
=> [ticket/12642] Ensure CPF type specific options are set when editing booleans.

phpBB/phpbb/profilefields/type/type_bool.php
https://tracker.phpbb.com/browse/PHPBB3-13528
=> [ticket/13528] Return correct translation instead of is_set()

phpBB/includes/startup.php, tests/security/trailing_path_test.php
https://tracker.phpbb.com/browse/PHPBB3-13531
=> [ticket/13531] Explicitly disallow trailing paths (e.g. PATH_INFO).

phpBB/config/default/container/services_db.yml, phpBB/phpbb/db/tools/factory.php
This allows us to split up the large file one by one easily.
https://tracker.phpbb.com/browse/PHPBB3-13487
=> [ticket/13487] Add factory for db tool class

phpBB/phpbb/routing/router.php
https://tracker.phpbb.com/browse/PHPBB3-13372
PHPBB3-13372
=> [ticket/13372] Fix Url Generator/Matcher generation

phpBB/docs/events.md, phpBB/styles/prosilver/template/viewtopic_body.html, phpBB/styles/subsilver2/template/viewtopic_body.html
Add template events to viewtopic_body.html to allow extensions adding content
before/after the post details.
<a href="https://tracker.phpbb.com/browse/PHPBB3-13512">PHPBB3-13512</a>.
=> [ticket/13512] Add template events before/after the post details

phpBB/includes/functions.php
Adding core event core.markread_before to to funtion markread()
in functions.php, so that you now are able to add additional
stuff inside the markread process, for example notifications designed
in extensions.
PHPBB3-13518
=> Add core event to markread() in functions.php

phpBB/includes/functions.php
Adding core event core.get_unread_topics_modify_sql to to funtion
get_unread_topics() in functions.php, so that you now are able to modify
the sql query that retrieves the unread topics.
PHPBB3-13532
=> Add core event to get_unread_topics() in functions.php

phpBB/includes/ucp/ucp_profile.php
Add ucp_profile.php core event to allow modifying account settings on editing.
Event request: http://area51.phpbb.com/phpBB/viewtopic.php?f=111&t=45201.
<a href="https://tracker.phpbb.com/browse/PHPBB3-13535">PHPBB3-13535</a>.
=> [ticket/13535] Add core event to allow modifying account settings on editing

phpBB/includes/mcp/mcp_queue.php
Events added for the functions approve_posts(), approve_topics()
and disapprove_posts() in mcp_queue.php, so that you can send notifications
during approval and disapproval.
PHPBB3-13537
=> Add core events on mcp_queue for approval and disapproval

phpBB/includes/functions_admin.php
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13658
Event Request: http://area51.phpbb.com/phpBB/viewtopic.php?f=111&t=46255
Note: The old PR ( https://github.com/phpbb/phpbb/pull/3124 ) was not developed any further, so I made my own.
=> [ticket/13658] add event before and after topics are deleted

phpBB/docs/events.md, phpBB/styles/prosilver/template/overall_header.html
PHPBB3-13679
https://tracker.phpbb.com/browse/PHPBB3-13679
http://area51.phpbb.com/phpBB/viewtopic.php?f=111&t=47401
There is no search box in the header for subsilver2  therefore I didn't make any subsilver2 changes.
This event helps with the addition of social or other icons above or below the search box which is located in the prosilver header.
It is placed before the search box to make easier the placement of the icons when the search box is not shown, e.g. in the search page.
=> [ticket/13679] Add template event overall_header_searchbox_before

phpBB/phpbb/search/fulltext_native.php
This changes how the native FULLTEXT search calculates the total
match number for MySQL.
This should improve performance as there is one less query being made
and it is being searched using the technique mentioned in the manual
https://tracker.phpbb.com/browse/PHPBB3-13674
=> [ticket/13674] Change MySQL native total search results calculation

phpBB/phpbb/plupload/plupload.php
This prevents a PHP warning from being issued that results in an invalid JSON response being returned to the user.
[PHPBB3-13550](https://tracker.phpbb.com/browse/PHPBB3-13550)
=> [ticket/13550] Improve checks for Plupload temp directory writability

phpBB/posting.php
[PHPBB3-13555](https://tracker.phpbb.com/browse/PHPBB3-13555)
=> [ticket/13555] Render poll options separately when previewing.

phpBB/styles/prosilver/template/memberlist_email.html
Replacing of four ```:``` with four {L_COLON} in Contact us page.
Replaces #3511
https://tracker.phpbb.com/browse/PHPBB3-13736
=> [ticket/13736] Missing four colon in Contact us page

phpBB/styles/prosilver/template/forum_fn.js
Do not calculate width of hidden elements.
Set minimum width to make sure breadcrumbs are always shown.
https://tracker.phpbb.com/browse/PHPBB3-13726
=> [ticket/13726] Fix function that calculates responsive breadcrumbs width

phpBB/phpbb/avatar/driver/local.php
Prior to this change, the path might have been incorrect when using
PHPBB_USE_BOARD_URL_PATH.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13742
Replaces #3516
=> [ticket/13742] Use correct avatar path for local avatar

phpBB/phpbb/avatar/driver/upload.php
This change makes the uploaded avatars use the PHPBB_USE_BOARD_URL_PATH
constant, which is needed when trying to use the get_user_avatar()
function in a listener for index changes.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13703
Replaces #3500
=> [ticket/13703] Use correct avatar path for PHPBB_USE_BOARD_URL_PATH

phpBB/includes/message_parser.php
```message_parser.php``` performs include of bbcode.php at the very start using
```$phpbb_root_path``` and ```$phpEx``` vars, so there's a possibility those can be
undefined at that point, especially when message_parser.php is being included
in event listener or another extension file where ```$phpbb_root_path``` and ```$phpEx```
don't exist. This can be fixed by adding the appropriate vars definitions.
<a href="https://tracker.phpbb.com/browse/PHPBB3-13743">PHPBB3-13743</a>.
=> [ticket/13743] Add $phpbb_root_path and $phpEx definitions in message_parser.php

phpBB/install/install_install.php
This allows installing phpBB twice in the same database with a different
prefix
https://tracker.phpbb.com/browse/PHPBB3-8494
=> [ticket/8494] Ignore errors from the database schema preparation

phpBB/phpbb/passwords/manager.php
https://tracker.phpbb.com/browse/PHPBB3-13772
=> [ticket/13772] Fix typo in phpbb\passwords\manager::__construct()

phpBB/composer.lock, phpBB/includes/message_parser.php, tests/functional/posting_test.php
https://tracker.phpbb.com/browse/PHPBB3-12745
https://tracker.phpbb.com/browse/PHPBB3-13178
~~https://tracker.phpbb.com/browse/PHPBB3-11711~~
[This update to s9e\TextFormatter](https://github.com/s9e/TextFormatter/commit/42d614c08e5f3ce5d35a29867d58a7f50fed7c91) automatically encodes characters from the Supplementary Multilingual Plane, making it possible to use those characters in formatted text regardless of the database.
=> [ticket/12745] Allow Unicode characters from the SMP to be used in text

phpBB/includes/functions.php
The code was added as a workaround for bugs in very old versions of IIS,
dating back to 2002: see commit 849d76697444f4e3523845f8c96569ccde57d868.
Newer IIS versions handle the "Location" header just fine, so we can avoid
the unnecessary HTML page for redirects. Given that it seems to work fine
since IIS 6.0 (on WinServer 2003), I don't think it's worth adding a special
check for earlier versions as they are no longer supported by MS as well.
[PHPBB3-12101](https://tracker.phpbb.com/browse/PHPBB3-12101)
=> [ticket/12101] Remove HTML redirect workaround for Microsoft/IIS webserver

phpBB/install/install_convert.php, phpBB/install/install_install.php, phpBB/install/install_update.php, phpBB/phpbb/cache/driver/dummy.php, phpBB/phpbb/log/dummy.php, tests/cache/dummy_driver_test.php, tests/cache/null_driver_test.php, tests/console/cache/purge_test.php, tests/dbal/migrator_tool_module_test.php, tests/dbal/migrator_tool_permission_test.php, tests/functions_user/group_user_attributes_test.php, tests/notification/base.php, tests/notification/group_request_test.php, tests/notification/submit_post_base.php, tests/notification/user_list_trim_test.php, tests/test_framework/phpbb_functional_test_case.php, tests/version/version_helper_remote_test.php
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13782
=> [ticket/13782] Rename classes that use reserved PHP7 keywords

phpBB/phpbb/filesystem/filesystem.php
```phpbb_is_writable()``` of the ```filesystem``` class uses ```w``` mode to ```fopen()``` files
which causes checked files to be truncated. Use the 'c' mode instead.
<a href="https://tracker.phpbb.com/browse/PHPBB3-13814">PHPBB3-13814</a>.
=> [ticket/13814] Prevent phpbb_is_writable() method from truncating files

phpBB/includes/functions_display.php
Add generate_forum_nav() core event in includes/functions_display.php
to allow modifying navlinks text. Use case example: extension(s) implementing
multilanguage boards including translated forum names and so on.
<a href="https://tracker.phpbb.com/browse/PHPBB3-13750">PHPBB3-13750</a>.
=> [ticket/13750] Add core event to allow modifying navlinks text

phpBB/docs/events.md, phpBB/styles/prosilver/template/forumlist_body.html
https://tracker.phpbb.com/browse/PHPBB3-13753
PHPBB3-13753
I did not include subsilver in this PR because it's design does not seem to lend itself well to this event, partly because it's tabular but mostly because unlike in prosilver, this category/header section of subsilver is broken into three different locations.
=> [ticket/13753] Add template events to forum category row headers

tests/di/fixtures/config.php, tests/notification/submit_post_type_topic_test.php
Related to https://github.com/phpbb/phpbb/pull/3589
=> [ticket/13828] Renamed testing doubles to avoid PHP7 keywords

phpBB/docs/events.md, phpBB/styles/prosilver/template/viewtopic_body.html
The purpose is to allow adding custom post buttons outside of the original post
buttons conditionals/list in prosilver (for subsilver2 it's not the issue).
<a href="https://tracker.phpbb.com/browse/PHPBB3-13791">PHPBB3-13791</a>.
=> [ticket/13791] Add more post buttons template events to viewtopic_body.html

phpBB/composer.lock, phpBB/includes/message_parser.php, phpBB/posting.php, tests/functional/posting_test.php
https://area51.phpbb.com/phpBB/viewtopic.php?f=108&t=42779
https://tracker.phpbb.com/browse/PHPBB3-11530
Removes extra quotes before populating the posting form.
Removes extra quotes in the submitted text.
One caveat: does not remove extra quotes in the posting form if the quoted post is from the old parser. Fixes itself on preview.
=> [ticket/11530] Remove extra quotes when depth limit is exceeded

tests/text_processing/tickets_data/PHPBB3-8419.html, tests/text_processing/tickets_data/PHPBB3-8419.txt, tests/text_processing/tickets_data/PHPBB3-8419.xml
The original ticket has some formatting problem of its own but I tested it manually on my local board and indeed 3.1 removes the space at the end and 3.2 does not.
https://tracker.phpbb.com/browse/PHPBB3-8419
=> [ticket/8419] Custom tag eats up space character

phpBB/docs/events.md, phpBB/styles/prosilver/template/search_body.html, phpBB/styles/subsilver2/template/search_body.html
Extensions may be designed to add secondary search options,
such as Google search in the search_body.html.
There are no events in the searchbody, so this should be merged.
PHPBB3-13808
=> [ticket/13808] search_body_form_before

phpBB/styles/prosilver/template/posting_poll_body.html
When options are shown and poll delete is allowed, the option to
delete
polls is shown twice. This is fixed here by moving the if poll
delete
check out of the outer if, wich makes it also more consistent
with the
new event.
PHPBB3-13787
=> [ticket/13787] Remove duplicate entry of poll_delete in prosilver template

phpBB/styles/prosilver/template/overall_header.html
This PR adds typekit and Google's webfontloader and calls it
asyncronously, removing the SPOF in the header. Now, if google
goes down, some buttons display with a different font.
https://github.com/typekit/webfontloader
https://tracker.phpbb.com/browse/PHPBB3-13876
=> [ticket/13876] Use webfontloader asyncronously.

phpBB/composer.lock, phpBB/phpbb/textformatter/s9e/renderer.php, phpBB/styles/prosilver/template/bbcode.html, phpBB/styles/prosilver/theme/content.css, tests/text_formatter/s9e/default_formatting_test.php, tests/text_processing/tickets_data/PHPBB3-11742.html, tests/text_processing/tickets_data/PHPBB3-11742.txt
https://tracker.phpbb.com/browse/PHPBB3-11742
Previous PR: ~~https://github.com/phpbb/phpbb/pull/3570~~ (I accidentally closed it and I can't reopen it)
This PR removes the tabs-to-space conversion by preserving all space in code blocks, including new lines.
=> [ticket/11742] Remove tabs-to-space conversion in [code]

phpBB/includes/ucp/ucp_pm_compose.php, phpBB/phpbb/textformatter/s9e/utils.php, phpBB/phpbb/textformatter/utils_interface.php, phpBB/posting.php, tests/functional/posting_test.php, tests/functional/private_messages_test.php, tests/text_formatter/s9e/utils_test.php
https://tracker.phpbb.com/browse/PHPBB3-13847
The markup used for quotes, `[quote=".."]...[/quote]` is currently hardcoded in posting.php. This could be moved to a method in the `text_formatter.utils` service.
Ultimately, anything that manipulates markup should live in a `text_formatter.*` service.
=> [ticket/13847] Move quote generation to text_formatter.utils

build/build.xml, build/code_sniffer/phpbb/Sniffs/Commenting/FileCommentSniff.php, build/code_sniffer/phpbb/Sniffs/Namespaces/UnusedUseSniff.php, phpBB/composer.json, phpBB/composer.lock, phpBB/includes/functions.php, phpBB/includes/functions_module.php, phpBB/phpbb/auth/provider/oauth/token_storage.php, phpBB/phpbb/db/sql_insert_buffer.php, phpBB/phpbb/notification/method/base.php, phpBB/phpbb/template/twig/node/definenode.php, phpBB/phpbb/template/twig/node/event.php, phpBB/phpbb/template/twig/node/expression/binary/equalequal.php, phpBB/phpbb/template/twig/node/expression/binary/notequalequal.php, phpBB/phpbb/template/twig/node/includenode.php, phpBB/phpbb/template/twig/node/includephp.php, phpBB/phpbb/template/twig/node/php.php, phpBB/phpbb/template/twig/tokenparser/defineparser.php, phpBB/phpbb/template/twig/tokenparser/event.php, phpBB/phpbb/template/twig/tokenparser/includejs.php, phpBB/phpbb/template/twig/tokenparser/includeparser.php, phpBB/phpbb/template/twig/tokenparser/includephp.php, phpBB/phpbb/template/twig/tokenparser/php.php
https://tracker.phpbb.com/browse/PHPBB3-13790
PHPBB3-13790
=> [ticket/13790] Update phpcs

tests/functional/posting_test.php
https://tracker.phpbb.com/browse/PHPBB3-8420
Fixed as a side effect of the new text formatter.
=> [ticket/8420] Emoticon removes space before itself when using preview

phpBB/phpbb/db/migration/tool/permission.php, tests/dbal/fixtures/migrator_permission.xml, tests/dbal/migrator_tool_permission_test.php
Migrations' permission tool allows setting permissions to the role which
doesn't match the role type, e.g. m_ permissions for u_ role types and so on.
As one of side effects, this may lead to granting users moderative/admin
permissions silently.
With this patch the only new permissions matching the role type will be set.
<a href="https://tracker.phpbb.com/browse/PHPBB3-13779">PHPBB3-13779</a>.
=> [ticket/13779] Set new auth options to the role only if matching the role type

phpBB/includes/startup.php
While suppressing the output from the 'set_magic_quotes_runtime(0)'
is sufficient with normal phpBB installs, using this file in association
with the oauth plugin will cause an error on some versions of PHP.
This fixes a potential bug where set_magic_quotes_runtime is depreciated
in newer versions of PHP.
Replaces https://github.com/phpbb/phpbb/pull/3491
https://tracker.phpbb.com/browse/PHPBB3-13923
PHPBB3-13923
=> [ticket/13923] Update startup.php

build/build.xml, build/build_helper.php
Removed:
-w, --ignore-all-space       Ignore white space when comparing lines.
Added:
-Z, --ignore-trailing-space  Ignore white space at line end.
-b, --ignore-space-change    Ignore changes in the amount of white space.
https://tracker.phpbb.com/browse/PHPBB3-13823
PHPBB3-13823
=> [ticket/13823] Change diff options while packaging to not ignore all whitespaces

phpBB/includes/functions.php
In certain situations, an SQL error DUPLICATE ERROR for KEY 'PRIMARY'
in the forums_track table is produced when marking forums read
(viewforum.php?f=xx&mark=forums).
The problem happens when there are duplicates in the forum_id array.
The solution is to remove those duplicates.
https://tracker.phpbb.com/browse/PHPBB3-10711
=> [ticket/10711] Duplicate key error on forum_tracks_table

tests/test_framework/phpbb_functional_test_case.php
This will change the output from just saying that the status did not match
the expected one to actually showing any errors before complaining about a
possible difference in the status code.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-12952
PHPBB3-12952
=> [ticket/12952] Check obvious errors before status in functional tests

phpBB/posting.php, tests/functional/posting_test.php
PHPBB3-13906
I couldn't create a test for it because it requires a signature parsed with 3.1. Since it cannot be created in 3.2 it has to be inserted directly in the DB, and I don't know whether it's possible to access the database of the system being tested by a functional test.
=> [ticket/13906] Fixed old signatures in post preview

phpBB/includes/functions_user.php
Allow any space count in the ReferralServer string for whois services response.
<a href="https://tracker.phpbb.com/browse/PHPBB3-13948">PHPBB3-13948</a>.
=> [ticket/13948] Correctly forwarding to the RIR for whois feature

phpBB/includes/functions_posting.php, phpBB/posting.php
Allow a user, if they have the permission, to lock a topic upon creation of a topic.
[PHPBB3-13598](https://tracker.phpbb.com/browse/PHPBB3-13598)
=> [ticket/13598] Allow topic lock on topic creation

phpBB/includes/functions_posting.php
when using the submit_post function
PHPBB3-13759
=> [ticket/13759] Take post_time into account

phpBB/develop/check_flash_bbcodes.php, phpBB/includes/acp/acp_bbcodes.php, phpBB/includes/bbcode.php, phpBB/includes/message_parser.php, phpBB/includes/ucp/ucp_pm_options.php
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13832
=> [ticket/13832] Use preg_replace_callback instead of /e modifier

phpBB/adm/style/acp_ext_list.html, phpBB/adm/style/acp_language.html, phpBB/adm/style/acp_styles.html, phpBB/language/en/acp/extensions.php, phpBB/language/en/acp/language.php, phpBB/language/en/acp/styles.php
Adds a link to our extensions database in extension manager, and to our styles database in the styles manager. This makes it quick and easy to get to the right CDB section from within the ACP to help users browse released extensions and styles (opens in a new window of course).
Also add installing an extension quick guide to the existing updating and removing guides, so we have somewhere in phpBB itself that quickly explains to new users how to get and install a released/validated extension.
https://tracker.phpbb.com/browse/PHPBB3-13818
PHPBB3-13818
=> [ticket/13818] Add Extension and Style CDB Links into ACP Management pages

phpBB/posting.php
The quoting user would get the date of the quoted post instead of the server time.  `post_time` variable passed to the submit_post function within the `$data` array is never used in the submit_post function.
This commit corrects the regression.
PHPBB3-13759
=> [ticket/13759] Initial commit broke timestamps when quoting a post.

phpBB/phpbb/textreparser/base.php, phpBB/phpbb/textreparser/plugins/forum_description.php, phpBB/phpbb/textreparser/plugins/forum_rules.php, phpBB/phpbb/textreparser/plugins/group_description.php, phpBB/phpbb/textreparser/plugins/poll_option.php, phpBB/phpbb/textreparser/plugins/poll_title.php, tests/text_reparser/plugins/fixtures/forums.xml, tests/text_reparser/plugins/fixtures/groups.xml, tests/text_reparser/plugins/fixtures/poll_options.xml, tests/text_reparser/plugins/fixtures/polls.xml, tests/text_reparser/plugins/poll_option_test.php
https://tracker.phpbb.com/browse/PHPBB3-13990
https://area51.phpbb.com/phpBB/viewtopic.php?p=281441#p281441
Some plugins did not retrieve the *_options bitfield to determine which of BBCodes/smilies/magic URLs should be enabled. This fixes that.
=> [ticket/13990] Reparse markup inside of forum rules/description

phpBB/assets/javascript/editor.js, phpBB/config/default/container/services_text_formatter.yml, phpBB/includes/functions_posting.php, phpBB/includes/functions_privmsgs.php, phpBB/includes/ucp/ucp_pm_compose.php, phpBB/phpbb/textformatter/s9e/factory.php, phpBB/phpbb/textformatter/s9e/quote_helper.php, phpBB/phpbb/textformatter/s9e/renderer.php, phpBB/phpbb/textformatter/s9e/utils.php, phpBB/phpbb/textformatter/utils_interface.php, phpBB/posting.php, phpBB/styles/prosilver/template/bbcode.html, phpBB/styles/prosilver/template/posting_topic_review.html, phpBB/styles/prosilver/template/ucp_pm_history.html, phpBB/styles/prosilver/theme/content.css, tests/functional/posting_test.php, tests/functional/private_messages_test.php, tests/test_framework/phpbb_test_case_helpers.php, tests/text_formatter/s9e/default_formatting_test.php, tests/text_formatter/s9e/utils_test.php
https://area51.phpbb.com/phpBB/viewtopic.php?f=126&t=48026
=> [ticket/10620] Quote improvements

phpBB/docs/CHANGELOG.html, phpBB/docs/FAQ.html, phpBB/docs/INSTALL.html, phpBB/docs/README.html, phpBB/docs/auth_api.html, phpBB/docs/coding-guidelines.html, phpBB/includes/functions.php, phpBB/phpbb/template/twig/node/includecss.php, tests/template/template_includecss_test.php
Projection is a deprecated media type and should not be used.
Name is an invalid attribute in anchors and ID is used instead.
Avatars are invalid by missing a space between elements.
https://tracker.phpbb.com/browse/PHPBB3-13996
=> [ticket/13995] Fixes for invalid HTML in docs and phpBB

phpBB/assets/javascript/core.js
<a href="https://tracker.phpbb.com/browse/PHPBB3-13984">PHPBB3-13984</a>.
=> [ticket/13984] Fix the call of Ajax loading indicator

phpBB/phpbb/console/command/reparser/list_all.php, phpBB/phpbb/console/command/reparser/reparse.php
https://tracker.phpbb.com/browse/PHPBB3-14034
Current code removes "text_reparser." from service names to display short names such as "post_text" instead of "text_reparser.post_text". The issue is it removes it everywhere in the string, not just at the beginning. This fixes that.
=> [ticket/14034] Fix reparser names that contain "text_reparser" in the middle

phpBB/posting.php
Added draft_id to the core.posting_modify_template_vars event in posting.php,
to provide the ability to use the 'checked' draft_id in extensions,
in addition to the 'raw' draft_id provided in earlier events in posting.php
PHPBB3-13971
=> [ticket/13971] Add draft_id var to core.posting_modify_template_vars

phpBB/config/default/container/services_console.yml, phpBB/language/en/cli.php, phpBB/phpbb/console/command/reparser/reparse.php
https://tracker.phpbb.com/browse/PHPBB3-13986
~~https://tracker.phpbb.com/browse/PHPBB3-13989~~
Resumes where the last execution stopped. If the last execution stopped at 227600/583468,  ~~it resumes at 227600/583468. The caveat is that it skews the estimation in the progress bar.~~ Not anymore, it resumes at 0/355868 and the estimation is as accurate as a normal execution.
=> [ticket/13986] Add --resume option to reparser CLI

phpBB/posting.php
The submit and error parameters within the core.posting_modify_submit_post_before/after have no effect as the event is only allowed if submit and not error
[PHPBB3-13815] (https://tracker.phpbb.com/browse/PHPBB3-13815)
=> [ticket/13815] Event parameters in posting have no effect

tests/installer/installer_config_test.php
@covers annotations causing build failures on bamboo, so removed them
PHPBB3-14053
=> [ticket/14053] Fix tests for installer config

phpBB/phpbb/notification/method/messenger_base.php
Notifications are sent to inactive users for emails and jabber.  There is no check if a user is set to inactive.
[PHPBB3-13711] (https://tracker.phpbb.com/browse/PHPBB3-13711)
=> [ticket/13711] Notifications are sent to inactive users

phpBB/config/avatar.yml, phpBB/phpbb/avatar/driver/upload.php, tests/avatar/manager_test.php
=> [ticket/13981] Add events to capture avatar deletion or overwriting

phpBB/phpbb/user.php
It allows to execute code at the end of user setup.
It can replace the `phpbb_user_session_handler` hook.
https://tracker.phpbb.com/browse/PHPBB3-13968
=> [ticket/13968] Add core.user_setup_after event

phpBB/styles/prosilver/template/forum_fn.js
The setBaseAndExtent() in Microsoft's Edge browser is incompatible with
the one Webkit browsers use. As a result of that, we have to fall back to
setting the focusOffset to 1 instead of the text length.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14077
=> [ticket/14077] Fall back to 1 as focusOffset if length is unsupported

phpBB/download/file.php
<a href="https://tracker.phpbb.com/browse/PHPBB3-14101">PHPBB3-14101</a>.
=> [ticket/14101] Add core event to the download/file.php

phpBB/config/default/container/services.yml, phpBB/includes/acp/acp_groups.php, phpBB/includes/acp/acp_permissions.php, phpBB/includes/acp/acp_prune.php, phpBB/includes/acp/acp_users.php, phpBB/includes/acp/auth.php, phpBB/includes/functions_admin.php, phpBB/includes/functions_display.php, phpBB/includes/functions_privmsgs.php, phpBB/includes/functions_user.php, phpBB/includes/ucp/ucp_groups.php, phpBB/includes/ucp/ucp_pm_compose.php, phpBB/includes/ucp/ucp_pm_options.php, phpBB/index.php, phpBB/memberlist.php, phpBB/phpbb/group/helper.php, phpBB/phpbb/language/language.php, phpBB/viewonline.php, tests/group/helper_test.php, tests/language/language_test.php, tests/notification/fixtures/services_notification.yml, tests/notification/group_request_test.php
Yeah, so I did this... out of the old PR #2247 
I had to do a new method in language service - I think it should be fine to do that in this PR.
I want to create another class like this, which is based on the function get_username_string, but splitted up to several functions like get_name, get_color, etc.
These methods (get_name, get_color) can be added to this class to at a later point too, I guess.
[PHPBB3-12143](https://tracker.phpbb.com/browse/PHPBB3-12143)
=> [ticket/12143] Make it possible to use translated group names for non-special groups

phpBB/includes/acp/acp_attachments.php, phpBB/includes/constants.php, phpBB/includes/functions_content.php, phpBB/install/schemas/schema_data.sql, phpBB/language/en/acp/attachments.php, phpBB/language/en/common.php, phpBB/phpbb/db/migration/data/v320/remove_outdated_media.php, phpBB/styles/prosilver/template/attachment.html
Remove code for handling media in RealPlayer, QuickTime, and Windows Media
Player.
[PHPBB3-12505](https://tracker.phpbb.com/browse/PHPBB3-12505)
~~https://github.com/phpbb/phpbb/pull/2462~~
=> [ticket/12505] Remove outdated media handling in attachments

phpBB/includes/mcp/mcp_forum.php
The "bug" in the deleted code comment is non-existent now.
The PR is for 3.1 only.
<a href="https://tracker.phpbb.com/browse/PHPBB3-14106">PHPBB3-14106</a>.
=> [ticket/14106] Fix topics sorting in MCP for topics merging.

phpBB/phpbb/feed/helper.php, tests/functional/feed_test.php
Previously, atom feeds use relative links for image attachments
https://tracker.phpbb.com/browse/PHPBB3-13988
=> [ticket/13988] Use absolute path for image attachments in feeds

phpBB/docs/events.md, phpBB/styles/prosilver/template/viewtopic_body.html, phpBB/styles/subsilver2/template/viewtopic_body.html
Add content directly after the topic title link on the View topic screen
(outside of the h2 HTML tag).
PHPBB3-14126
=> [ticket/14126] Add viewtopic_topic_title_after template event

phpBB/includes/functions.php, phpBB/phpbb/avatar/driver/upload.php
The `$ignore_config` appears to never be used in any avatar driver. It is only passed to the upload driver, but not used in it. None of the other drivers even have an argument for it.
PHPBB3-14142
=> [ticket/14142] Remove unused ignore_configs from avatar drivers

tests/installer/database_helper_test.php
When sqlite3 was not installed, tests failed.
[PHPBB3-14178](https://tracker.phpbb.com/browse/PHPBB3-14178)
=> [ticket/14178] Fix installer's database helper test

phpBB/phpbb/template/twig/node/event.php
Check the templates events on runtime only when Twig debug is on
https://tracker.phpbb.com/browse/PHPBB3-12633
PHPBB3-12633
=> [ticket/12633] Doesn't use DEBUG to debug templates events

phpBB/styles/prosilver/template/mcp_topic.html, phpBB/styles/prosilver/template/overall_header.html, phpBB/styles/prosilver/template/pagination.html, phpBB/styles/prosilver/template/posting_buttons.html, phpBB/styles/prosilver/template/posting_topic_review.html, phpBB/styles/prosilver/template/search_results.html, phpBB/styles/prosilver/template/ucp_pm_history.html, phpBB/styles/prosilver/template/ucp_pm_message_header.html, phpBB/styles/prosilver/template/ucp_pm_viewmessage.html, phpBB/styles/prosilver/template/viewforum_body.html, phpBB/styles/prosilver/template/viewtopic_body.html, phpBB/styles/prosilver/template/viewtopic_topic_tools.html, phpBB/styles/prosilver/theme/bidi.css, phpBB/styles/prosilver/theme/buttons.css, phpBB/styles/prosilver/theme/colours.css, phpBB/styles/prosilver/theme/common.css, phpBB/styles/prosilver/theme/forms.css
ticket: https://tracker.phpbb.com/browse/PHPBB3-14193
PHPBB3-14193
=> [ticket/14193]Fix secondary buttons

phpBB/config/default/container/services_console.yml, phpBB/language/en/cli.php, phpBB/language/en/migrator.php, phpBB/phpbb/console/command/db/list_command.php, phpBB/phpbb/console/command/db/migrate.php, phpBB/phpbb/console/command/db/migration_command.php, phpBB/phpbb/console/command/db/revert.php, phpBB/phpbb/db/migrator.php
| Command | Description |
| ------------- | -------------- |
| db:list | List all installed and not installed migrations. |
| db:revert | Revert a migration. |
Note: For `db:list`, the class is named `list_command`, because `list` is a reserved word and can't be used as class name in PHP.
[PHPBB3-14162](https://tracker.phpbb.com/browse/PHPBB3-14162)
=> [ticket/14162] Add CLI commands to manage migrations

phpBB/includes/mcp/mcp_queue.php, phpBB/styles/prosilver/template/mcp_post.html, phpBB/styles/prosilver/template/viewtopic_body.html, phpBB/viewtopic.php
Changes:
- For permanent deletion of softdeleted post, disapprove mode has been changed
to delete mode;
- If post delete and softdelete are allowed, delete button triggers softdelete
mode;
- If a user can't permanently delete posts but can restore softdeleted posts,
delete button won't be displayed for softdeleted posts.
Subsilver2 is unaffected.
<a href="https://tracker.phpbb.com/browse/PHPBB3-13846">PHPBB3-13846</a>.
=> [ticket/13846] Fix softdelete feature workflow in viewtopic

phpBB/includes/acp/acp_inactive.php, phpBB/includes/acp/acp_users.php
Success message did not provide the expected "previous page" link
(acp_inactive was expected, but the link took users to acp_users) if the
acp_users module was accessed by navigating from the inactive user list to
acp_users and then deleting inactive user.
PHPBB3-13636
=> [ticket/13636] Deleting inactive user in acp_users gives unexpected link

phpBB/includes/acp/acp_profile.php
Make sure new step is calculated only if no error has been identified
during validation.  Also, cleanup redundant code in acp_profile.php.
PHPBB3-13960
=> [ticket/13960] Profile field validation breaks ACP

phpBB/adm/style/acp_profile.html, phpBB/adm/style/acp_users_profile.html, phpBB/styles/prosilver/template/ucp_register.html
Adds a template variable (the same) in all places where profile fields
may need an enctype clause in the corresponding forms.
PHPBB3-13934
=> [ticket/13934] Add enctype clause for profile fields

phpBB/includes/mcp/info/mcp_pm_reports.php, phpBB/includes/mcp/mcp_front.php, phpBB/install/schemas/schema_data.sql, phpBB/language/en/acp/permissions_phpbb.php, phpBB/phpbb/db/migration/data/v31x/m_pm_report.php, phpBB/phpbb/permissions.php
Anybody who has the permission to read reports in one forum can read PM reports.
Solving this problem by adding a new permission to read PM reports.
https://tracker.phpbb.com/browse/PHPBB3-8920
=> [ticket/8920] Add a MCP PM reports view permission

phpBB/styles/prosilver/template/navbar_header.html, phpBB/styles/prosilver/theme/buttons.css, phpBB/styles/prosilver/theme/common.css, phpBB/styles/prosilver/theme/responsive.css
ticket: https://tracker.phpbb.com/browse/PHPBB3-14194
PHPBB3-14194
=> [Ticket/14194] Responsive Quick Links Menu Broken

phpBB/download/file.php
`extension` must be `extensions`
Introduced in fix of [PHPBB3-14101](https://tracker.phpbb.com/browse/PHPBB3-14101) (PR GH-3831)
[PHPBB3-14161](https://tracker.phpbb.com/browse/PHPBB3-14161)
=> [ticket/14161] Wrong var name for core.download_file_send_to_browser_before

phpBB/includes/acp/acp_users.php, phpBB/includes/functions_content.php, phpBB/includes/ucp/ucp_profile.php
The implementation of PHPBB3-12516 changed the manual use of the message parser
to using generate_text_for_storage(). The function does not support
parse_message::parse()'s mode parameter, thus all the error checks on the sig
are invalid.
[PHPBB3-13993](https://tracker.phpbb.com/browse/PHPBB3-13993)
=> [ticket/13993] Do not parse signatures as posts when editing them.

phpBB/includes/functions_user.php
The idea is to be able to map with others CMS by exposing most commons user configuration & changes.
Difference between the event before and after group belonging removal is that
users belongs to multiple groups, so that the belonging into a group also
depends on the others groups (and not only the deleted one), which is not
reflected before as the user is not yet deleted
PHPBB-14212
https://tracker.phpbb.com/browse/PHPBB3-14215
=> [ticket/14212] Adding event after users have been removed to a group

phpBB/includes/acp/acp_styles.php
[PHPBB3-14188](https://tracker.phpbb.com/browse/PHPBB3-14188)
=> [ticket/14188] Add core.acp_styles_action_before event

phpBB/phpbb/db/driver/driver.php, tests/dbal/boolean_processor_test.php, tests/dbal/fixtures/boolean_processor.xml
Improve DBAL's query builder by adding a boolean query builder using a structured stack of arrays.
This can be used everywhere in an SQL query where boolean operations are used.
Currently, this can only be used in the WHERE and the JOINs' ON clause.
The main and general use-cases are:
To flexibly the build of the WHERE clause in SQL queries
To ease, simplify and prevent errors when doing SQL query editing by phpBB's extensions
Topic: https://area51.phpbb.com/phpBB/viewtopic.php?f=81&t=47306
https://tracker.phpbb.com/browse/PHPBB3-13652
Documentation: https://github.com/phpbb/documentation/pull/51
PHPBB3-13652
=> [feature/sql-bool-builder] Extending DBAL query builder for boolean generation

phpBB/includes/ucp/ucp_pm.php
The u_sendpm check in ucp_pm.php is merely for the purpose of displaying the
error message within the UCP template. Otherwise it could be removed as
compose_pm() will check the appropriate permission pertaining to the attempted
action.
[PHPBB3-9153](https://tracker.phpbb.com/browse/PHPBB3-9153)
=> [ticket/9153] Allow users without u_sendpm permission to delete existing PM's

phpBB/adm/style/acp_main.html, phpBB/includes/acp/acp_main.php
This also hide a link to an unreachable module (Check phpBB version).
We could have simply remove the link to the module, but if the user hasn't
the permission to access to the phpBB version check module, I think that
he shouldn't view any version information about phpBB.
[PHPBB3-14159](https://tracker.phpbb.com/browse/PHPBB3-14159)
=> [ticket/14159] Hide version info on ACP if we don't have the permission

phpBB/phpbb/notification/type/approve_post.php, phpBB/phpbb/notification/type/approve_topic.php, phpBB/phpbb/notification/type/bookmark.php, phpBB/phpbb/notification/type/post.php, phpBB/phpbb/notification/type/post_in_queue.php, phpBB/phpbb/notification/type/quote.php, phpBB/phpbb/notification/type/report_pm.php, phpBB/phpbb/notification/type/topic_in_queue.php
report_post inherits from post_in_queue, therefore using self:: instead of static:: results in the incorrect notification type being used to determine which users to exclude from the notification.
Updated all other instances of self in the notification types that may cause problems in the future.
[PHPBB3-13892](https://tracker.phpbb.com/browse/PHPBB3-13892)
=> [ticket/13892] Respect "Someone reports a post" notification setting.

phpBB/includes/mcp/mcp_queue.php
Without this change, posts that are approved by someone right before
another moderator is trying to disapprove a post are actually deleted
instead of disapproved.
https://tracker.phpbb.com/browse/PHPBB3-9252
PHPBB3-9252
=> [ticket/9252] Do not try to disapprove a post that was just approved

.travis.yml
We're currently doing a pretty good job at letting our test suite not fail on PHP7 and I really want us to be compatible with PHP7 so I think we should be safe now to remove this from the allowed failures.
[PHPBB3-14256](https://tracker.phpbb.com/browse/PHPBB3-14256)
=> [ticket/14256] Remove PHP7 from the allowed failures

phpBB/phpbb/auth/auth.php
Add a new event in the login method just before the session create so extensions can do some additional validation during login.
PHPBB3-14258
=> [ticket/14258] Add event into auth::login before session creation

phpBB/includes/mcp/mcp_post.php
Move the mcp_change_poster_after event to before renewing $post_info. I
changed the "since" version as this would be fixed in 3.1.7-RC1.
PHPBB3-14170
=> [ticket/14170] Fix mcp_change_poster_after event

phpBB/assets/javascript/core.js
If there is no success message after the action is confirmed, the indicator
is not currently removed.
[PHPBB3-14287](https://tracker.phpbb.com/browse/PHPBB3-14287)
Test script since this situation currently does not present itself in the core.
https://gist.github.com/prototech/8363883637fa78785887
Insert this into any template to call the script.
```
<a href="./confirm.php?mode=without" data-ajax="true">Without success message</a>
<a href="./confirm.php?mode=with" data-ajax="true">With success message</a>
```
=> [ticket/14287] Always remove loading indicator after confirming action.

phpBB/memberlist.php
This way, after clicking on posts or other, it will sort desc. so the high numbers will apear.
In asc mode, we need to click twice to be able to see who posted more, etc.
Just the username makes sense to be as asc mode.
[PHPBB3-14242](https://tracker.phpbb.com/browse/PHPBB3-14242)
=> [ticket/14242] Fix memberlist sort method

tests/datetime/from_format_test.php
The fix was introduced with #3826, now the PHP core bug has been fixed:
https://bugs.php.net/bug.php?id=70249
Original fix ticket: <a href="https://tracker.phpbb.com/browse/PHPBB3-14094">PHPBB3-14094</a>.
<a href="https://tracker.phpbb.com/browse/PHPBB3-14340">PHPBB3-14340</a>.
=> [ticket/14340] Revert fix for segmentation fault error on phpBB 3.2 PHP7 tests

phpBB/config/default/container/services_console.yml, phpBB/config/default/container/services_cron.yml, phpBB/config/default/container/services_text_reparser.yml, phpBB/language/en/acp/common.php, phpBB/phpbb/console/command/reparser/reparse.php, phpBB/phpbb/cron/task/text_reparser/reparser.php, phpBB/phpbb/db/migration/data/v320/reparse_fast.php, phpBB/phpbb/db/migration/data/v320/text_reparser.php, phpBB/phpbb/textreparser/manager.php, tests/text_reparser/fixtures/config_text.xml, tests/text_reparser/manager_test.php
One new cron task for each reparser.
Advantage of this approach is that the decision which reparser will run in the cron job is made before running it.
Disadvantage is that extension authors have to create their own cron task but since they only have to define that in the services.yml and they have to create their own reparser class anyway, I don't think this is a big issue.
So basically no disadvantages. :grinning: 
Cron job and console command can't interfere with eachother because the reparser acquires a lock, of course.
However, cron job and console command will be synced. So the console command can resume where the cron job stopped and vice versa.
This also means unfortunately that an administator can set weird values by using the console command (weird start, end, size IDs) which …
=> [ticket/14257] Reparse after update

phpBB/adm/style/admin.css, phpBB/assets/javascript/installer.js
The progress bar percentage is hardly readable during the installation once the filler passes the text.
This change will take care of this (see pictures below).
The text will always be inside the filler.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14310
=> [ticket/14310] Put progress percentage inside span and make more visible

phpBB/includes/functions.php, phpBB/includes/functions_acp.php, phpBB/phpbb/session.php
Currently, the unique way to disable the update of session_page is to pass `false` to the parameter of `session_begin()`. This method is directly called in `app.php`, so pages served from the routing system can't disable the update of session informations.
By moving the update to `page_footer`, we can allow controllers to tell to the session manager that we don't want to update the session infos.
[PHPBB3-14261](https://tracker.phpbb.com/browse/PHPBB3-14261)
=> [ticket/14261] Move the update of session informations to page_footer()

tests/functional/posting_test.php
Tests that the textarea's content is preserved, that no "http://"
is added to the text or to the preview's HTML and that the www
URL is linkified
PHPBB3-10628
https://tracker.phpbb.com/browse/PHPBB3-10628
=> [ticket/10628] http:// prepended to "www." urls

phpBB/includes/acp/acp_groups.php, phpBB/includes/acp/acp_users.php, phpBB/phpbb/avatar/driver/driver.php, phpBB/phpbb/avatar/driver/driver_interface.php, phpBB/phpbb/avatar/manager.php, tests/avatar/manager_test.php
Create a driver method to provide the driver config name, and use it
within the manager method. Default driver config name is the same as now.
But new drivers are able to override the config name with their own.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14387
PHPBB3-14387
=> [ticket/14387] Allow extending avatars by extensions in ACP

phpBB/includes/acp/acp_extensions.php, phpBB/phpbb/file_downloader.php, phpBB/phpbb/version_helper.php
Fixes Ticket 12618 (https://tracker.phpbb.com/browse/PHPBB3-12618)
In order to be able to use SSL with fsockopen, one has to append 'ssl://' to the host. Thus, the class file_downloader needed to be changed.
'ssl://' will always be appended now, if the port is 443.
I have checked, that this does not influence any other uses of that class (there are none).
=> [ticket/12618] Allow extension author to use SSL for version-check.

phpBB/adm/style/overall_header.html, phpBB/includes/functions_acp.php, phpBB/language/en/acp/common.php, phpBB/phpbb/di/container_builder.php
Automatically try to use a safe mode (no cached container, no extensions) when we fail to build the container and display the exception on every page in the ACP (do not display anything outside of the ACP).
PHPBB3-14306
=> [ticket/14306] Automatically enable a safe mode when container building fails

phpBB/phpbb/db/tools.php
In a migration file, if you try to add a column to a table and specify
the order, by specifying an "after" clause, it is not used at all, even
for databases that support it (like mysql).
This fixes the issue, for mysql databases.
PHPBB3-13908
=> [ticket/13908] "After" clause in migration not working

phpBB/styles/prosilver/template/search_results.html, phpBB/styles/prosilver/template/viewforum_body.html
Search results topic lists simply were not updated at the same time as the regular view forum topic lists, so they were not only inconsistent, but layout is broken in search results. This PR brings them in sync with each other, and fixes mistakes left over from previous PRs.
https://tracker.phpbb.com/browse/PHPBB3-14420
PHPBB3-14420
=> [ticket/14420] Fix up search results topic lists

phpBB/phpbb/db/migration/migration.php, phpBB/phpbb/db/migration/migration_interface.php, phpBB/phpbb/extension/base.php, tests/extension/ext/vendor2/bar/migrations/bar.php, tests/extension/ext/vendor2/bar/migrations/foo.php, tests/extension/extension_base_test.php
Currently any file in an extension's migration folder is considered a migration.
This means extensions can't keep migration helpers / abstract classes they may want to use in their migrations folder (like the way phpBB is able to do).
Only the classes implementing a migration interface should be loaded by the migrator.
Replaces #3626 
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13733
=> [ticket/13733] Allow non-migration files inside migrations folder

tests/test_framework/phpbb_functional_test_case.php
Cache still needs purging in functional tests, but only when setting up for testing extensions. This is __not__ a reversion of https://github.com/phpbb/phpbb/pull/4111 and only affects extensions running functional tests.
https://tracker.phpbb.com/browse/PHPBB3-14433
PHPBB3-14433
=> [ticket/14433] Purge cache setting up extension functional tests

phpBB/phpbb/di/container_builder.php
This is returning an extra / on my machine which throws off the next code block, and then the class can't be found.
PHPBB3-14489
=> [ticket/14489] Fix bug where extension custom compiler pass cannot be found

phpBB/includes/functions_content.php
Add core event to the function decode_message() in
includes/functions_content.php to allow extensions performing additional
message handling before/after decoding.
<a href="https://tracker.phpbb.com/browse/PHPBB3-14366">PHPBB3-14366</a>.
=> [ticket/14366] Add core events to the function decode_message()

phpBB/phpbb/notification/manager.php
This will prevent a race condition that might occur by two posts being
submitted at the same time with the notification type IDs not being
cached.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14132
=> [ticket/14132] Use transaction for adding notifications to type table

phpBB/assets/javascript/editor.js
Previous PR: https://github.com/phpbb/phpbb/pull/4134
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14422
=> [ticket/14422] Support cmd+enter & ctrl+enter for submitting message

travis/setup-phpbb.sh
The api rate limit has been removed by github. Therefore,
we no longer need --prefer-source
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14529
=> [ticket/14529] Stop using --prefer-source for composer

phpBB/phpbb/recursive_dot_prefix_filter_iterator.php
Swapping conditions in the function accept() of the class
\phpbb\recursive_dot_prefix_filter_iterator saves a lot of isDir() calls which
is more expensive than $filename[0] checks.
<a href="https://tracker.phpbb.com/browse/PHPBB3-14540">PHPBB3-14540</a>.
=> [ticket/14540] Adjust recursive_dot_prefix_filter_iterator for performance

phpBB/viewtopic.php
Moved the call to function phpbb_add_quickmod_option to being under the core
event core.viewtopic_assign_template_vars_before so as to enable the
modification of elements in the  BEFORE they are assigned to the
template, so that removed elements don't show up in a non-functional state.
Allows the user to perform additional permissions checks on the items within the
array.
PHPBB3-14395
=> [ticket/14395] Add event core.viewtopic_add_quickmod_option_before

phpBB/viewforum.php
$topics_count value was accidentally removed by #4238. Restore it.
<a href="https://tracker.phpbb.com/browse/PHPBB3-14051">PHPBB3-14051</a>.
=> [ticket/14051] Restore accidentally removed $topics_count value

phpBB/phpbb/user.php
This will ensure to prevent PHP fatal errors in case the passed timestamp
is an empty string or does not evaluate to an integer (i.e. strings like
foobar).
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14536
=> [ticket/14536] Force unix time stamps to be integer

phpBB/adm/style/install_header.html, phpBB/adm/style/install_update_diff.html, phpBB/adm/style/overall_header.html, phpBB/adm/style/simple_header.html, phpBB/docs/CHANGELOG.html, phpBB/docs/FAQ.html, phpBB/docs/INSTALL.html, phpBB/docs/README.html, phpBB/docs/auth_api.html, phpBB/docs/coding-guidelines.html, phpBB/includes/functions.php, phpBB/includes/functions_download.php, phpBB/install/database_update.php, phpBB/install/index.php, phpBB/phpbb/db/driver/driver.php, phpBB/styles/prosilver/template/overall_header.html, phpBB/styles/prosilver/template/simple_header.html, phpBB/styles/prosilver/template/ucp_pm_viewmessage_print.html, phpBB/styles/prosilver/template/viewtopic_print.html, phpBB/styles/subsilver2/template/overall_header.html, phpBB/styles/subsilver2/template/simple_header.html, phpBB/styles/subsilver2/template/ucp_pm_viewmessage_print.html, phpBB/styles/subsilver2/template/viewtopic_print.html
This was previously removed without needing to. Adding it back to force
users to not emulate the page for previous versions of IE. The
imagetoolbar http-equiv tag was not restored as IE does not contain that
anymore since IE7. Also, the chome=1 has been removed from the
X-UA-Compatible content as ChromeFrame does not receive any further
updates since 2014 and is potentially broken.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14136
=> [ticket/14136] Add back X-UA-Compatible meta tag

phpBB/phpbb/textreparser/base.php, tests/text_reparser/base_test.php, tests/text_reparser/fixtures/base.xml
The default mode is "post". By setting it to something else,
all limits pertaining to posts (min/max length, etc...) should
be disabled.
PHPBB3-14381
=> [ticket/14381] Set the mode in message parser to "reparse"

phpBB/includes/acp/acp_users.php, phpBB/includes/ucp/ucp_profile.php, phpBB/viewtopic.php
Otherwise data like the bbcode ID and the flags will not be set which will cause improper generation of text for edit by users.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14530
=> [ticket/14530] Only generate text again if sig was parsed for storage

phpBB/includes/ucp/ucp_pm_compose.php, phpBB/memberlist.php
[PHPBB3-13630](https://tracker.phpbb.com/browse/PHPBB3-13630)
Please note, that this is probably only one of many problematic parameters. For example, when you submit member search for every user that starts with "a", this URL is generated:
`http://localhost/phpbb/phpBB/memberlist.php?sk=c&sd=a&username=a&email=&search_group_id=0&joined_select=lt&active_select=lt&count_select=eq&joined=&active=&count=&ip=`
Apache's mod_security has no knowledge, that this URL was generated by browser's form instead of classical anchor. Further inspection is required.
=> [ticket/13630] Prevent empty parameter select_single

phpBB/language/en/acp/common.php, phpBB/language/en/captcha_qa.php, phpBB/phpbb/captcha/plugins/qa.php
Improper setup of the q&a captcha in combination with the admin choosing a
default language that does not have any questions and answers set might
result in the user being presented empty questions and answers. This
change will try to fall back to any question in case the admin incorrectly
set the default language and has no questions & answers set. If that does
not work, the captcha will not allow passing it and suggest to contact the
board admin to resolve this issue.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14241
=> [ticket/14241] Prevent empty q&a as a result of improper settings

phpBB/memberlist.php
While original ticket request is already fixed, livesearch did not reflect it.
[PHPBB3-10356](https://tracker.phpbb.com/browse/PHPBB3-10356)
=> [ticket/10356] Find inactive users in livesearch when having permissions

phpBB/phpbb/notification/type/quote.php
Some array_key calls were incorrect in the
notification checks for quotes. Two calls were
being made in a row, resulting in incorrect arrays.
PHPBB3-14572
=> [ticket/14572] Fix quote notification deletion

phpBB/phpbb/db/tools.php
The column default shouldn't be escaped for mssql. This is a regression
from 743d816631292a2081af4c5f7fc2fad2aff17c58. Prior to that commit, the
default value for the column was not escaped. Escaping it will cause SQL
errors while altering columns.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14532
=> [ticket/14532] Do not escape column default in mssql

phpBB/phpbb/language/language_file_helper.php
Symfony finder does not follow symlinks by default.
With this change it does, so a user is able to have the language pack outside
the phpBB directory, and linked with a symlink into phpBB/language/
PHPBB3-14645
=> [ticket/14645] Language pack not reconised when using a symlink

phpBB/phpbb/notification/type/base.php
When a new user signs up, they have an email preference set but no board notification preference set. The default board preference should work. Also when a user checks the email box for any notification preference, the default board preference should still work.
PHPBB3-14648
=> [ticket/14648] Fix bug where default notifications stop working if another setting is set.

phpBB/includes/acp/acp_board.php, phpBB/includes/functions_messenger.php, phpBB/language/en/email/forum_notify.txt, phpBB/language/en/email/newtopic_notify.txt, phpBB/language/en/email/short/newtopic_notify.txt, phpBB/language/en/email/short/topic_notify.txt, phpBB/language/en/email/topic_notify.txt, tests/email/email_parsing_test.php
The fix is for 3.2.x/master only.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14660">PHPBB3-14660</a>.
=> [ticket/14660] Fix parsing board email messages through template engine.

phpBB/includes/acp/acp_board.php, phpBB/language/en/acp/board.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14184
This should help users trying to figure out why their mail config is not working when they forgot to use a protocol prefix.
PHPBB3-14184
=> [ticket/14184] Add a _EXPLAIN translation entry for the SMTP server option

phpBB/includes/questionnaire/questionnaire.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14692
Subexpression `($ip_address_ary[0] == '192' && $ip_address_ary[1] == '168')`
is repeated.
PHPBB3-14692
Replaces https://github.com/phpbb/phpbb/pull/4369
=> [ticket/14692] Remove duplicate subexpression in questionnaire.php

phpBB/includes/mcp/mcp_main.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14709
Add the missing post_id value to the moderator log entry created upon
deleting one or more posts in the MCP topic view.
PHPBB3-14709
=> [ticket/14709] add post_id to mod log

phpBB/composer.json, phpBB/composer.lock, phpBB/phpbb/textformatter/s9e/factory.php, tests/text_formatter/s9e/default_formatting_test.php, tests/text_processing/tickets_data/PHPBB3-14706.html, tests/text_processing/tickets_data/PHPBB3-14706.txt
Renders `[list]text[/list]` into `<ul><li>text</li></ul>`. Fixes issues with missing list items. Produces valid HTML. The updated BBCode definition requires [s9e\TextFormatter v0.5.4](https://github.com/s9e/TextFormatter/releases/tag/0.5.4) or newer.
http://area51.phpbb.com/phpBB/viewtopic.php?f=126&p=293551
Checklist:
PHPBB3-14706
=> [ticket/14706] Updated [list] BBCode to automatically create a list item

phpBB/config/default/container/services_auth.yml, tests/di/fixtures/config/production/container/environment.yml, tests/di/fixtures/config/test/container/environment.yml, tests/di/fixtures/other_config/production/container/environment.yml, tests/di/fixtures/other_config/test/container/environment.yml, tests/functional/fixtures/ext/foo/bar/config/services.yml
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14717
This type of use was deprecated in symfony 2.8 and will be dropped in 3.x.
Also see: https://github.com/symfony/symfony/pull/16285
PHPBB3-14717
=> [ticket/14717] Quote strings beginning with @ or % in yaml definitions

phpBB/composer.lock, tests/text_processing/tickets_data/PHPBB3-14740.html, tests/text_processing/tickets_data/PHPBB3-14740.txt, tests/text_processing/tickets_data/PHPBB3-14740.xml
Allows defining a BBCode as `[foo="{TEXT}"]` in addition to the usual `[foo={TEXT}]`
The syntax is not explicitly defined in [the phpBB docs](https://www.phpbb.com/support/docs/en/3.1/kb/article/adding-custom-bbcodes-in-phpbb3/) but it's apparently allowed and in use.
The actual feature/fix was implemented in https://github.com/s9e/TextFormatter/commit/c8253c9249f19ff18721de69241b485033ed38d5, this PR only contains the updated `composer.json` and a regression test.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14740
PHPBB3-14740
=> [ticket/14740] Added support for quoted attributes in BBCode definitions

phpBB/phpbb/session.php
Old PR: #3553
Older PR: #3536
Now all users are just removed from the group when the limit is set to 0. :)
[PHPBB3-12230](https://tracker.phpbb.com/browse/PHPBB3-12230)
=> [ticket/12230] Disable newly registered group when post limit is set to 0

phpBB/docs/events.md, phpBB/styles/prosilver/template/viewforum_body.html, phpBB/styles/subsilver2/template/viewforum_body.html
[PHPBB3-14469](https://tracker.phpbb.com/browse/PHPBB3-14469)
=> Add viewforum_body_topicrow_before template event

phpBB/adm/index.php, phpBB/includes/acp/acp_groups.php, phpBB/includes/acp/acp_inactive.php, phpBB/includes/acp/acp_main.php, phpBB/includes/acp/acp_permissions.php, phpBB/includes/acp/acp_users.php, phpBB/includes/functions.php, phpBB/includes/functions_privmsgs.php, phpBB/includes/mcp/mcp_logs.php, phpBB/includes/mcp/mcp_queue.php, phpBB/includes/mcp/mcp_reports.php, phpBB/includes/ucp/ucp_activate.php, phpBB/includes/ucp/ucp_groups.php, phpBB/includes/ucp/ucp_pm.php, phpBB/includes/ucp/ucp_pm_compose.php, phpBB/includes/ucp/ucp_pm_viewmessage.php, phpBB/includes/ucp/ucp_profile.php, phpBB/includes/ucp/ucp_remind.php, phpBB/mcp.php, phpBB/memberlist.php, phpBB/phpbb/feed/forum.php, phpBB/phpbb/feed/topic.php, phpBB/phpbb/message/topic_form.php, phpBB/viewforum.php, phpBB/viewonline.php, phpBB/viewtopic.php
[PHPBB3-10961](https://tracker.phpbb.com/browse/PHPBB3-10961)
=> [ticket/10961] Send HTTP 403 when applicable

phpBB/includes/functions_download.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-12133
All browser engines that descend from WebKit declare themselves as
Safari in the user agent, including Chrome. Currently, the code
assumes that any Safari-like browser cannot handle the RFC-compliant
filename syntax. At least for recent versions of Safari, this is no
longer the case, and the legacy syntax results in URI-quoted
filenames. Using the standard syntax works as expected in both Safari
9 and Chrome 45.
The ticket reporting this issue is from January 2014, so we can safely
ignore compatibility: any browser still relying on the previous
behaviour is unlikely to receive security updates.
PHPBB3-12133
=> [ticket/12133] fix download file names for WebKit-derived browsers

phpBB/includes/functions_download.php, tests/download/http_byte_range_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14774
phpBB already had limited support for partial downloads, but only for
resuming downloads, disregarding any range ending before EOF.
WebKit on iOS and OS X uses partial downloads when fetching media
files. Previously, only MP3 attachments could play directly in the
browser, reported as a live stream, but with this change, all
supported media formats should render as expected.
Tested using cURL by verifying that partial downloads give exactly the
same results compared to Apache.
PHPBB3-14774
=> [ticket/14774] Support partial downloads of attachments

phpBB/phpbb/content_visibility.php
Checklist:
Events added for both changing the content visibility for both posts and topics,
executing right before and after the SQL UPDATE query for setting the
visibillity.
https://tracker.phpbb.com/browse/PHPBB3-14581
PHPBB3-14581
=> [ticket/14581] Add core events to content_visibility

phpBB/phpbb/log/log.php
Checklist:
Replaces https://github.com/phpbb/phpbb/pull/4393
https://tracker.phpbb.com/browse/PHPBB3-14796
Was still using the old LOG_TABLE constant in the delete method.
PHPBB3-14796
=> [ticket/14796] Use log_table class member instead of table constant

phpBB/phpbb/notification/manager.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14799
When running purge_notifications(), if a notification type does not exist
then a db transaction is started but never completed.
On an error in get_notification_type_id(), end the transaction.
PHPBB3-14799
=> [ticket/14799] purge_notifications() should not leave open transactions.

phpBB/phpbb/event/kernel_exception_subscriber.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14821
Everything else will still be escaped. This will however add back support for
bold text in exception messages.
PHPBB3-14821
=> [ticket/14821] Replace escaped strong tags with actual tags

phpBB/includes/functions.php
I consider this a bug because extensions that use the `add_form_key()` function without thinking twice will run into issues if they use it on a page where phpBB (or another extension) already called that function. Forms will only validate for whoever called the function last.
The solution is for the extension to use the `$template_variable_suffix` argument that is added in this PR and set it to `_{VENDOR}_{EXT}`, for example, to ensure they don't overwrite anyone else's form elements.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14827
=> [ticket/14827] Fix adding multiple form keys

phpBB/phpbb/db/migration/tool/module.php, tests/dbal/fixtures/migrator_module.xml, tests/dbal/migrator_tool_module_test.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14831">PHPBB3-14831</a>.
=> [ticket/14831] Fix extension modules installation issues

phpBB/includes/functions.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14818
if $config['force_server_vars'] is enabled no need to calculate $request
That is a really useful for my sending PM extension - it is totally haven't $request object so without this changes my function is fails.
=> [ticket/14818] Optimize generate_board_url function

phpBB/includes/acp/acp_profile.php, phpBB/includes/acp/acp_search.php, tests/functional/search/base.php
Checklist:
Caused by #4452.
<a href="https://tracker.phpbb.com/browse/PHPBB3-14830">PHPBB3-14830</a>.
=> [ticket/14830] Fix FORM_INVALID error during some ACP setting operations

phpBB/includes/acp/acp_users.php, tests/functional/user_password_reset_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-11483
The force reactivation action in the ACP will no longer overwrite the
generated activation key in case the key stored in the database is empty.
It will also save the generated key back to the database to actually allow
the activation by the user.
PHPBB3-11483
=> [ticket/11483] Generate user act key if database entry is empty

phpBB/includes/mcp/mcp_forum.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14795
Merging topics should not result in topic views being added up but rather in
the highest topic view showing up for the merged topic.
PHPBB3-14795
=> [ticket/14795] Use maximum topic views instead of adding up views in merge

phpBB/includes/mcp/mcp_forum.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14804
Renamed $topic_data and defined $to_topic_data in order to avoid ambiguity
and to stop overwriting a variable.
PHPBB3-14804
=> [ticket/14804] Add core event to MCP after merging topics

phpBB/phpbb/notification/type/report_pm.php
Tracker ticket (set the ticket ID to your ticket ID):
https://tracker.phpbb.com/browse/PHPBB3-14859
This addresses the problem that notifications of new PM reports were not sent out to moderators that weren't global moderators but did have the permission "Can close/delete PM reports". 
PHPBB3-14859
=> [ticket/14859] Send notifications for PM reports to all users with correct permissions

phpBB/phpbb/db/migration/data/v31x/migrations_deduplicate_entries.php, phpBB/phpbb/db/migration/data/v31x/remove_duplicate_migrations.php, phpBB/phpbb/db/migrator.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14831
The migration system expects every migration to start with a backslash.
If depends on definitions do not supply that leading backslash, we should
make sure it's added manually before calling the depends on migration.
PHPBB3-14831
=> [ticket/14831] Make sure migrations always start with backslash

phpBB/includes/acp/acp_users.php, phpBB/includes/functions_user.php, phpBB/language/en/ucp.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14842
PHPBB3-14842
=> [ticket/14842] Don't display filesize limit if there is none

phpBB/composer.json, phpBB/composer.lock, phpBB/phpbb/template/twig/lexer.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14867
The revert of twig back to 1.26.* is necessary due to a breaking
change in the way the Filesystem loader returns the paths to
template files.
PHPBB3-14867
=> [ticket/14867] Revert back to twig 1.26.* and update dependencies

phpBB/phpbb/event/kernel_exception_subscriber.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14876
All exception messages are sanitized via type_caster::set_var()
which is called with $multibyte = false.
This commit allows to pass multibyte messages as well.
PHPBB3-14876
=> [ticket/14876] Allows multibyte strings for exception messages

phpBB/includes/functions_privmsgs.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13757
Sometimes the user_unread_privmsg flag in users table can become negative.
It happens when the unread message is requested by simultaneous concurrent
requests. Both requests will decrement the value of the flag.
This commit prevents updating the flag if the message already marked as read.
PHPBB3-13757
=> [ticket/13757] Prevents the count of unread PMs from being negative

phpBB/includes/functions_privmsgs.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13757
The fix from PR #4548 doesn't work as expected because
in phpBB the sql_affectedrows() method always returns
a count of matched rows instead of affected rows.
This commit fixes bug properly.
PHPBB3-13757
=> [ticket/13757] Properly fix bug with negative PM count

phpBB/config/default/container/services_password.yml, phpBB/phpbb/passwords/driver/base.php, phpBB/phpbb/passwords/driver/bcrypt.php, phpBB/phpbb/passwords/driver/driver_interface.php, phpBB/phpbb/passwords/driver/rehashable_driver_interface.php, phpBB/phpbb/passwords/manager.php, tests/passwords/drivers_test.php, tests/passwords/manager_test.php
This will need another pull request for 3.2.x.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14733
PHPBB3-14733
=> [ticket/14733] Support increasing hashing cost factor

phpBB/includes/acp/acp_profile.php
Checks if a profile field type is enabled before using it.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14888
=> [ticket/14888] Missing check for disabled profile field types

phpBB/composer.json, phpBB/composer.lock
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14892
Twig 1.25 and after introduced a way of handling both relative and
absolute paths. However, it seems to handle absolute windows paths as
relative paths. This breaks any assets or similar ways of including files
into the main template files.
PHPBB3-14892
=> [ticket/14892] Revert to twig 1.24 to have working assets again

phpBB/adm/style/acp_ext_details.html, phpBB/includes/acp/acp_extensions.php
Checklist:
Tracker ticket
https://tracker.phpbb.com/browse/PHPBB3-14901
Extensions without version check should not display a notice on the
details page in the ACP.
PHPBB3-14901
=> [ticket/14901] Remove notice for extension without version check

phpBB/config/default/container/services_console.yml, phpBB/language/en/cli.php, phpBB/phpbb/console/command/cache/purge.php, phpBB/phpbb/console/command/config/command.php, phpBB/phpbb/console/command/config/delete.php, phpBB/phpbb/console/command/config/get.php, phpBB/phpbb/console/command/config/increment.php, phpBB/phpbb/console/command/config/set.php, phpBB/phpbb/console/command/config/set_atomic.php, phpBB/phpbb/console/command/cron/cron_list.php, phpBB/phpbb/console/command/db/list_command.php, phpBB/phpbb/console/command/db/migrate.php, phpBB/phpbb/console/command/db/migration_command.php, phpBB/phpbb/console/command/db/revert.php, phpBB/phpbb/console/command/dev/migration_tips.php, phpBB/phpbb/console/command/extension/disable.php, phpBB/phpbb/console/command/extension/enable.php, phpBB/phpbb/console/command/extension/purge.php, phpBB/phpbb/console/command/extension/show.php, phpBB/phpbb/console/command/fixup/recalculate_email_hash.php, phpBB/phpbb/console/command/reparser/list_all.php, tests/console/cron/cron_list_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14895
PHPBB3-14895
=> [ticket/14895] CLI should use SymfonyStyle

phpBB/phpbb/template/context.php
Allows inserting elements in a loop specified as 'outer[3].inner'.
This was coded, but malfunctioning.
PHPBB3-14943
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14943
=> [ticket/14943] Fix template loop access by index

phpBB/composer.json, phpBB/composer.lock, tests/test_framework/phpbb_ui_test_case.php, tests/ui/permission_roles_test.php, tests/ui/quick_links_test.php
```
$ composer update phpunit/phpunit --with-dependencies
Dependency "symfony/yaml" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Installing sebastian/global-state (1.1.1)
Loading from cache
- Installing doctrine/instantiator (1.0.5)
Loading from cache
- Removing phpunit/phpunit-mock-objects (2.1.5)
- Installing phpunit/phpunit-mock-objects (2.3.8)
Loading from cache
- Removing phpunit/php-file-iterator (1.3.4)
- Installing phpunit/php-file-iterator (1.4.2)
Loading from cache
- Installing phpdocumentor/reflection-docblock (2.0.4)
Downloading: 100%
- Installing phpspec/prophecy (v1.6.2)
Loading from cache
- Removing phpunit/phpunit (4.1.6)
- Installing …
```
=> [ticket/14947] Updates phpunit to 4.8

phpBB/includes/mcp/mcp_forum.php
by this correct $redirect will go to clean mcp page after merge
PHPBB3-14549
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14549
=> [ticket/14549] fix mcp page redirect back after topic merge and rised warning

phpBB/phpbb/textformatter/s9e/parser.php, tests/text_processing/tickets_data/PHPBB3-15008.before.php, tests/text_processing/tickets_data/PHPBB3-15008.html, tests/text_processing/tickets_data/PHPBB3-15008.txt
Will effectively disable emoji shortname and won't replace emoji
with images but will not prevent a browser or OS from displaying
emoji as images.
PHPBB3-15008
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15008
=> [ticket/15008] Disable emoji when smilies are disabled

phpBB/install/phpinfo.php
In 3.1.x there's a phpinfo.php in the /install folder which seems to be removed in 3.2.x, perhaps by accident?
https://github.com/phpbb/phpbb/commits/3.2.x/phpBB/install/phpinfo.php
Let's add it back for easier troubleshooting potential issues during installation.
PHPBB3-15035
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15035
=> [ticket/15035] Add phpinfo.php to 3.2.x install directory

phpBB/styles/prosilver/template/search_results.html
Fixing position as it is correctly on subsilver, or else it will appear
some problems when using polls or on topics with page numbers.
PHPBB3-14997
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14997
=> [ticket/14997] Fixing topiclist_row_topic_title_after position

phpBB/common.php, phpBB/install/app.php
Rhea version of #4649 which also adds a simple `die()` for when people try to upgrade to 3.2 with an old PHP version.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-11076
=> [ticket/11076] State current and minimum required versions in old PHP notice

phpBB/phpbb/install/module/update_filesystem/task/diff_files.php
Instead of trying to diff the new file against a pre-existing file,
we're just going to use the new file. It's impossible to know whether
the pre-existing file is newer or older than the new file. As the
system will rely on the files being in the "new" state it's better
to simply use the file in "new" state.
PHPBB3-15050
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15050
=> [ticket/15050] Use new file when new file already exists

phpBB/phpbb/template/base.php, phpBB/phpbb/template/context.php, phpBB/phpbb/template/template.php, tests/template/template_test.php
Adds a new function to the template interface, and implements it in the
context class.  The function returns the ordinal index for a specified key,
with the same structure that the key for alter_block_array.
Reuses same code.
PHPBB3-14944
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14944
=> [ticket/14944] Add search for template loop indexes by key

phpBB/styles/prosilver/theme/common.css
3.2.x/master only.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15124">PHPBB3-15124</a>.
Before the fix:
After the fix:
=> [ticket/15124] Hide navbar icon titles in repsonsive view

phpBB/phpbb/textformatter/s9e/quote_helper.php
I can't reproduce the issue, that's why there's no test case attached. Regardless, `append_sid()`'s third argument should be set to `false` since we don't want an HTML-encoded URL.
PHPBB3-15126
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15126
=> [ticket/15126] Disable HTML entities in quote helper

phpBB/viewforum.php
The element $config['topics_per_page'] was assigned a value after the
template was included, which led to incorrect page number display in the
header when pagination.
Now this var is assigned the correct value before the template is included
PHPBB3-15139
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15139
=> [ticket/15139] Assigned 'topics_per_page' before template included

phpBB/includes/acp/acp_extensions.php, phpBB/phpbb/version_helper.php, tests/version/version_test.php
PHPBB3-15142
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15142
=> [ticket/15142] Check extension updates on current branch

phpBB/includes/acp/acp_extensions.php, phpBB/phpbb/console/command/update/check.php, phpBB/phpbb/extension/manager.php, phpBB/phpbb/extension/metadata_manager.php, tests/extension/metadata_manager_test.php
Caching is done in ext_manager, and metadata_manager is further simplified
by reducing the number of parameters needed.  Also, move template output
function from metadata_manager to acp_extensions, where it belongs.
Included here are 3.2 versions of the following PRs:
- https://github.com/phpbb/phpbb/pull/4581 [ticket/14919] Do not directly use globals in acp_extensions
- https://github.com/phpbb/phpbb/pull/4592 [ticket/14938] Inconsistency in ext_mgr all_available vs is_available
- https://github.com/phpbb/phpbb/pull/4689 [ticket/15080] Save unneeded file loads for extension metadata
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15087
=> [ticket/15087] Optimize creation of metadata objects by caching

phpBB/phpbb/extension/manager.php, phpBB/phpbb/extension/metadata_manager.php, tests/mock/extension_manager.php
Made is_available much more strict, in line with the checks in all_available
PHPBB3-14938
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14938
=> [ticket/14938] Inconsistency in ext_mgr all_available vs is_available

phpBB/phpbb/extension/metadata_manager.php
PHPBB3-15080
Save unneeded file loads for extension metadata.  Currently, each time get_metadata() is called, the metadata file gets reloaded from disk.  This is happening multiple times per instance of metadata_manager created, so saving these calls and replacing by one, on first time call, would improve execution time.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15080
=> [ticket/15080] Save unneeded file loads for extension metadata

phpBB/composer.lock
This fixes issues with filename casing and JPEG files only using
EXIF header data.
PHPBB3-15103
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15103
=> [ticket/15103] Update fast-image-size to 1.1.3

phpBB/adm/style/acp_main.html, phpBB/includes/acp/acp_main.php, phpBB/language/en/acp/common.php
The ACP main page shows the phpBB version and the database version, but didn't show the PHP version. With this change the PHP version is displayed as part of the Board statistics.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15097
=> [ticket/15097] Add PHP version to Board statistics

phpBB/styles/prosilver/theme/forms.css
Use the same CSS already used in the ACP: 
https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/adm/style/admin.css#L1143
This way, input type number show correctly on Firefox.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13735
=> [ticket/13735] Fix input type number for Firefox in prosilver

phpBB/includes/acp/acp_extensions.php
Update the mentioned ticket to 3.2 by using exception_inteface
instead of the actual exception class.
Also, use adm_back_link consistently.
PHPBB3-15011
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15011
=> [ticket/15011] Use exception interface for 3.2

phpBB/styles/prosilver/template/ajax.js, phpBB/styles/prosilver/template/navbar_header.html, phpBB/styles/prosilver/template/notification_dropdown.html, phpBB/styles/prosilver/theme/bidi.css, phpBB/styles/prosilver/theme/colours.css, phpBB/styles/prosilver/theme/common.css, tests/functional/notification_test.php
Checklist:
PHPBB3-15192
https://tracker.phpbb.com/browse/PHPBB3-15192
No visual changes just code smell fixes
should be merged before https://github.com/phpbb/phpbb/pull/4787
=> [ticket/15192] Fix dropdown-extended & notification code

phpBB/includes/acp/acp_extensions.php, phpBB/phpbb/extension/manager.php
When enabling an extension its paths aren't added immediately to
the template which results in ACP template events not being registered in
the compiled template files.
PHPBB3-15187
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15187
=> [ticket/15187] Add paths of newly enabled extensions to template

phpBB/phpbb/db/migration/data/v32x/user_notifications_table_reduce_column_sizes.php, phpBB/phpbb/db/migration/data/v32x/user_notifications_table_remove_duplicates.php, phpBB/phpbb/db/migration/data/v32x/user_notifications_table_temp_index.php
This migration got removed when trying to resolve the build error. It is actually needed in order for the deduplication migration to complete on larger databases (i.e. phpbb.com's).
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14992
=> [ticket/14992] Add temp index migration for removing duplicates

phpBB/styles/prosilver/template/index_body.html, phpBB/styles/prosilver/template/viewforum_body.html, phpBB/styles/prosilver/template/viewtopic_body.html
When the user permission 'Can view profiles, memberlist and online list' is
set to No (or Never), the user should not be able to see which members are
online in the following places, index page, view topic and view forum.
Before this change, guests and bots would see the list of members who are
online, which doesn't match with the user permission and could create privacy
issues where guests or bots could track when a member was online.
PHPBB3-14498
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14498
=> [ticket/14498] Don't display 'Who is online' members when permission is No

phpBB/common.php, phpBB/includes/startup.php, phpBB/phpbb/files/filespec.php, phpBB/phpbb/passwords/driver/md5_phpbb2.php
- Move PHP version check from `common.php` to `startup.php` to be effective in more cases.
- Remove redundant code in `startup.php`, only applicable to versions < 5.4
PHPBB3-15227
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15227
=> [ticket/15227] Check PHP version and remove old unused code

phpBB/config/console.yml, phpBB/language/en/cli.php, phpBB/phpbb/console/command/fixup/fix_left_right_ids.php
For 3.1.x only.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15238">PHPBB3-15238</a>.
=> [ticket/15238] Add console command to fix forums/modules left/right IDs

phpBB/phpbb/db/tools/tools.php, tests/dbal/db_tools_test.php
PHPBB3-15259
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15259
The tools code was changed with some remaining issues that resulted into Fatal error during the update to phpBB 3.2.1-RC1 on SQLite database.
What I've tried to fix in this commit:
- `check_index_name_length` does not take the third parameter into account when calls itself recursively.
- `check_index_name_length` reduces one more symbol from `index_name` when tries to remove `table_prefix` (it is not separated from the remaining `table_suffix` with `_` like `table_name` from `index_name`).
- `check_index_name_length` incorrectly tries to remove `table_name` after it has removed `table_prefix` (instead we need to remove the remaining part of `table_name` - …
=> [ticket/15259] Fatal error on SQLite/Oracle database update

phpBB/phpbb/db/migrator.php, tests/dbal/migration/if.php, tests/dbal/migration/if_params.php, tests/dbal/migration/recall.php, tests/dbal/migration/recall_params.php, tests/dbal/migrator_test.php
Add the possibility to have custom migrations with parameters,
allowing the use of a single function for several uses.
PHPBB3-15274
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15274
=> [ticket/15274] Allow "custom" migrations to use parameters

phpBB/includes/ucp/ucp_notifications.php, phpBB/phpbb/notification/manager.php, phpBB/phpbb/notification/method/email.php, phpBB/phpbb/notification/method/jabber.php, phpBB/phpbb/notification/method/messenger_base.php, phpBB/styles/prosilver/template/ucp_notifications.html
Stuffing the instances into the `type` and `method` data arrays in `manager.php` doesn't feel like an elegant solution but it's the best I could find that is extensible.
As an alternative, it could all be done in the UCP module, probably with some `instanceof` checks, but that would make it deal with things that it shouldn't deal with, in my opinion. Other suggestions are welcome.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15328
=> [ticket/15328] Disable checkbox if notification method isn't supported

phpBB/styles/prosilver/template/search_results.html, phpBB/styles/prosilver/template/viewforum_body.html, phpBB/styles/prosilver/theme/common.css, phpBB/styles/prosilver/theme/responsive.css
This is my attempt at fixing the pagination overlap problem.  Backward-compatibility is mostly preserved, except that non-adapted derived styles will have an extra line for paginated topics even when not needed.  The change to the responsive style is optional (credits to @v12mike for noticing the redundancy).
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15309
=> [ticket/15309] Fix pagination overlap in prosilver via "left-box"

phpBB/phpbb/cache/driver/redis.php
In some functions like sql_save in cache/memory.php, code try to save a key/value in cache with ttl = 0 so key should never expire. In current redis.php cache driver, it fails so key never get cached. 
This cause for example that when you create a subforum, it not appear imediatly in the forum box in the admincp.
To solve, if ttl is 0, we use redis->set instead of setex
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15320
=> [ticket/15320] 	Redis cache does not save keys withouth expiration

phpBB/includes/functions_content.php, tests/text_processing/generate_text_for_display_test.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15318">PHPBB3-15318</a>.
=> [ticket/15318] Make user option to disable word censoring effective again

phpBB/includes/functions.php, phpBB/phpbb/path_helper.php, phpBB/phpbb/session.php, tests/session/extract_page_test.php
PHPBB3-15351
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15351
=> [ticket/15351] Makes confirm_works in a router context (app.php)

phpBB/styles/prosilver/template/memberlist_email.html, phpBB/styles/prosilver/theme/responsive.css
Checklist:
PHPBB3-13214
https://tracker.phpbb.com/browse/PHPBB3-13214
=> [ticket/13214] Contact us page textarea looks narrow in responsive mode

phpBB/adm/style/acp_ext_list.html, phpBB/adm/style/admin.css
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14677
=> [ticket/14677] Add exclamation mark to outdated extensions

phpBB/phpbb/db/migrator.php, tests/dbal/migration/revert_table.php, tests/dbal/migration/revert_table_with_dependency.php, tests/dbal/migrator_test.php
When applying database changes, [the `try_apply` method _returns_ after applying a migration step from a dependency](https://github.com/phpbb/phpbb/blob/release-3.2.1/phpBB/phpbb/db/migrator.php#L351). When reverting database changes, there is no _return_, which causes the migrator to apply the first step of a depending migration, then the steps of the migration itself, and all remaining steps of the depending migration afterwards.
With these changes, the migrator _returns_ after each `revert_do` of depending migrations and continues at the correct next step, therefore handling all dependencies' steps in correct order.
Deleting data of the test extension from the ticket, @blitze's SiteMaker 3.0.1 and @VSEphpbb's Ad Manangement 1.0.2 works fine.
Some tests coming right up.
PHPBB3-15396 …
=> [ticket/15396] Fix revert_schema() steps not executed in correct order

phpBB/includes/functions.php
Option B:
- change the get_avatar function to always trigger the event
PHPBB3-15331
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15331
=> [ticket/15331] Allow gravatars to be overridden by existing event - B

phpBB/includes/acp/acp_styles.php, phpBB/phpbb/db/migration/data/v310/style_update_p1.php, phpBB/phpbb/db/migration/data/v32x/fix_user_styles.php, phpBB/phpbb/user.php, tests/test_framework/phpbb_functional_test_case.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15201
=> [ticket/15201] Set user style to default style when it is disabled or uninstalled

phpBB/docs/nginx.sample.conf
Checklist:
Tracker ticket: https://tracker.phpbb.com/browse/PHPBB3-15385
according to the latest wiki info:
http://wiki.nginx.org/Pitfalls#Taxing_Rewrites
`return 301` is preferred over a `rewrite`.
also, the 'security' regex breaks some official extensions because it 
will match and deny access to `/ext/phpbb`.
looking through the names of dirs and files containing `phpbb`, it 
looks like the intent of the regex was to only disallow the folder 
`phpbb` in the root dir and not other `/phpbb` matches.
a negative lookbehind was added to specifically not match `/ext/phpbb` 
but still match other occurrences of `/phpbb`.
=> [ticket/15385] nginx.sample.conf: www redirection, security regex

phpBB/phpbb/event/dispatcher.php, phpBB/phpbb/event/php_exporter.php, tests/event/dispatcher_test.php, tests/event/fixtures/event_migration.test, tests/event/php_exporter_test.php
Reasoning is in the tracker.
This change is fully backwards compatible, of course. Nothing in the existing core events or in any extension must be changed.
This change will only allow the short array syntax for the event names and will allow both array syntaxes for multi line event vars instead of just the old syntax.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15389
=> [ticket/15389] Allow arrays in event dispatcher

phpBB/phpbb/search/fulltext_sphinx.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15419">PHPBB3-15419</a>.
=> [ticket/15419] Fix Sphinx UTF8 search in delta index

phpBB/assets/javascript/core.js
My fix for https://tracker.phpbb.com/browse/PHPBB3-15332 is broken, there's a `typeof` missing
PHPBB3-15432
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15432
=> [ticket/15432] Don't remove dark background if fadedark is false

phpBB/includes/acp/acp_bbcodes.php
This PR updates the BBCodes ACP to normalize `foo=` to `foo` on addition/modification, meaning only one version of the BBCode can be created manually. The current behaviour is to let the admin create both versions even though only one of the two ends up working.
Existing duplicates are left untouched but it will prevent `foo=` from being saved if edited.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15408
=> [ticket/15408] Reject duplicate BBCodes in ACP

phpBB/adm/style/admin.css, phpBB/adm/style/permission_mask.html
Fix a vertical bar and menu text running through the Admin Permission Role Tooltip pop-up caused by z-index on menu div (and opacity of the popup of .95 rather than 1).
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15390
=> [ticket/15390] Fix vertical bar permission tooltip

phpBB/includes/acp/acp_users.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15460">PHPBB3-15460</a>.
=> [ticket/15460] Fix group name displayed in the manage users ACP module

phpBB/language/en/cli.php, phpBB/phpbb/console/command/extension/enable.php
Fix phpbbcli can enable non-existent extension
PHPBB3-15433
Checklist:
Tracker ticket :
https://tracker.phpbb.com/browse/PHPBB3-15433
=> [ticket/15433] Fix phpbbcli can enable non-existent extension

phpBB/includes/ucp/ucp_register.php
I moved the `phpbb_timezone_select()` call below the event so that changes to the `$data['tz']` field in event handlers can take effect.
PHPBB3-15431
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15431
=> [ticket/15431] Add event core.ucp_register_modify_template_data

.travis.yml
It stopped working on the 3.2.x branch because of Travis's default clone depth of 50. Fixing it by setting the remote branch and fetching it. Also now comparing the commit range to `$TRAVIS_PULL_REQUEST_SHA` instead of `FETCH_HEAD` since that might be set to the newly fetched (3.2.x) branch.
Error message:
Result of commit message validation in this PR:
Commit messages validation still worked on master. I've also tested this PR on master and it keeps working as well. Result of my test to master: (on my own fork so different commit hash)
So the only difference is that it doesn't add a [new branch] because master was already available.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15475
=> [ticket/15475] Fix Travis pull request commit messages validation

phpBB/download/file.php, phpBB/includes/functions_download.php, phpBB/includes/functions_mcp.php, phpBB/phpbb/content_visibility.php, phpBB/viewforum.php, phpBB/viewtopic.php
Fixes core.phpbb_content_visibility_get_visibility_sql_before,
core.phpbb_content_visibility_get_forums_visibility_before,
core.phpbb_content_visibility_get_global_visibility_before
Does not modify the events, but fixes some comments, and changes
the rest of the function to allow (at least) the documented
event functionality.
PHPBB3-15266
Checklist:
Tracker ticket PHPBB3-15266:
https://tracker.phpbb.com/browse/PHPBB3-15266
=> [ticket/15266] Fix events in content_visibility

phpBB/phpbb/datetime.php
Throw `S` (ordinal suffix) from dateformat for non English languages
PHPBB3-14857
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14857
=> [ticket/14857] Throw `S` from dateformat for non English languages

phpBB/includes/acp/acp_language.php
Add core event after language deleted in acp_language.php
PHPBB3-15453
Checklist:
Tracker ticket (15453):
https://tracker.phpbb.com/browse/PHPBB3-15453
=> [ticket/15453] Add core event after language deleted in acp_language.php

phpBB/phpbb/db/migration/data/v30x/release_3_0_6_rc1.php, phpBB/phpbb/db/migration/data/v30x/release_3_0_8_rc1.php, phpBB/phpbb/db/migration/data/v310/auth_provider_oauth.php, phpBB/phpbb/db/migration/data/v310/contact_admin_acp_module.php, phpBB/phpbb/db/migration/data/v310/dev.php, phpBB/phpbb/db/migration/data/v310/extensions.php, phpBB/phpbb/db/migration/data/v310/notifications.php, phpBB/phpbb/db/migration/data/v310/softdelete_mcp_modules.php, phpBB/phpbb/db/migration/data/v320/add_help_phpbb.php, phpBB/phpbb/db/migration/tool/module.php, tests/dbal/migrator_tool_module_test.php
PR for master: #5017 
This will fix cases where the module is deleted in later
versions and the migrator thus cannot retrieve the info.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15339
=> [ticket/15339] Use manual method when adding modules

phpBB/language/en/viewforum.php, phpBB/styles/prosilver/template/viewforum_body.html
The message will now only be displaced for categories without subforums. (including if you don't have permissions to view subforums). Regression from https://github.com/phpbb/phpbb/pull/4934
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15489
=> [ticket/15489] Remove NO_FORUMS message for categories with subforums

phpBB/includes/functions_posting.php
The attachrow_template_vars array needs to be defined once in front of the
foreach instead of resetting the array on every iteration of the foreach.
PHPBB3-15506
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15506
=> [ticket/15506] Assign attachrow_template_vars before foreach

phpBB/includes/acp/acp_forums.php
For 3.2.3 or later.
Should prevent the forums table from getting messed up if an error or
concurrent execution happens.
PHPBB3-15495
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15495
=> [ticket/15495] Use transaction in ACP move_forum

phpBB/styles/prosilver/template/overall_footer.html
The diff looks worse than it is. I just wrapped the whole CookieConsent initialization in a `typeof` check and added some line breaks at the end for improved readability.
PHPBB3-15523
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15523
=> [ticket/15523] Fix AdBlocker causing JS error when using CookieConsent

phpBB/adm/style/acp_main.html, phpBB/includes/acp/acp_main.php
Link Orphan attachments in ACP General to Orphaned attachments page
if Orphan attachments>0
PHPBB3-15510
Checklist:
Tracker ticket :
https://tracker.phpbb.com/browse/PHPBB3-15510
=> [ticket/15510] Link Orphan attachments in ACP General to its page

phpBB/phpbb/db/migration/data/v32x/merge_duplicate_bbcodes.php, phpBB/phpbb/textformatter/s9e/bbcode_merger.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15527
=> [ticket/15527] Skip malformed BBCodes during merge_duplicate_bbcodes migration

phpBB/includes/functions_messenger.php
By pre assign `$extra_headers` to array.
PHPBB3-15507
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15507
=> [ticket/15507] Fix PHP 7.2 warning in functions_messenger.php

phpBB/phpbb/search/fulltext_mysql.php, phpBB/phpbb/search/fulltext_native.php, phpBB/phpbb/search/fulltext_postgres.php
The PR adds 5 events:
- `core.search_native_delete_index_before`
- `core.search_mysql_create_index_before`
- `core.search_mysql_delete_index_before`
- `core.search_postgres_create_index_before`
- `core.search_postgres_delete_index_before`
There is no `core.search_native_create_index_before` because the `native` backend doesn't have a `create_index()` method and there is no need for an event to add columns. The `core.search_native_delete_index_before` event isn't needed for adding columns either, I just added it for completeness sake.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15561
=> [ticket/15561] Add events for adding columns to search index

phpBB/docs/INSTALL.html, phpBB/language/en/install.php
PHPBB3-15569
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15569
=> [ticket/15569] Suggest using file replacing instead of automatic updater

phpBB/config/default/container/parameters.yml, phpBB/config/default/container/services_password.yml, phpBB/phpbb/passwords/driver/argon2i.php, tests/passwords/drivers_test.php
This PR implements Argon2i as the preferred password driver where available. It uses the [default cost factors](https://wiki.php.net/rfc/argon2_password_hash#resolved_cost_factors).
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15646
=> [ticket/15646] Add support for Argon2i passwords

phpBB/phpbb/db/migration/tool/module.php, tests/dbal/ext/foo/bar/acp/acp_test_info.php, tests/dbal/ext/foo/bar/acp/acp_test_module.php, tests/dbal/ext/foo/bar/composer.json, tests/dbal/ext/foo/bar/ucp/ucp_test_info.php, tests/dbal/ext/foo/bar/ucp/ucp_test_module.php, tests/dbal/migrator_tool_module_test.php
PHPBB3-15586
`$data` isn't used anymore in this method. The code that is deleted in this commit causes an undefined index error when adding a module the automatic way when only specifying the `module_basename` key.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15586
=> [ticket/15586] Fixed adding module the automatic way without specifying modes

phpBB/includes/acp/acp_logs.php
This link was added to the MCP view in GH-3870 ([PHPBB3-9485](https://tracker.phpbb.com/browse/PHPBB3-9485)) but I completely forgot the ACP…
Consistency is back!
[PHPBB3-15656](https://tracker.phpbb.com/browse/PHPBB3-15656)
Checklist:
=> [ticket/15656] Add "View post" link in the mod logs on the ACP

phpBB/adm/style/acp_main.html, phpBB/adm/style/admin.css
Master Improving UI of Board Statistics in ACP
Board Statistics table was divided into two categories in  acp_main.html .Before
PHPBB3-15610
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15610
=> [ticket/15610] Improving UI of Board Statistics in ACP

phpBB/styles/prosilver/theme/responsive.css
Checklist:
Tracker ticket (set the ticket ID to **15605**):
https://tracker.phpbb.com/browse/PHPBB3-15605
=> [ticket/15605] Correct Right-Margin for ribbon image

phpBB/styles/prosilver/theme/responsive.css
Corrects misaligned header text when viewing a user profile in prosilver mobile layout by force clearing the columns.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15611
=> [ticket/15611] Fix misaligned text in responsive user profile

phpBB/phpbb/session.php
PHPBB3-15583
The check if the `session_page` needs to be updated was done in two places but they didn't check for the same thing:
* line 1618: `$this->update_session_page && $this->data['session_page'] != $this->page['page'])`
* line 1623: `$this->update_session_page && !$request->is_ajax()`
On AJAX requests, the first condition always passed, so the `if` block was entered and the `session_time` was prepared to be sent to the sessions table, but the second condition never passed, resulting in the `session_page` never actually being updated and only the `session_time` mistakenly being updated.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15583
=> [ticket/15583] Update session time in AJAX request only once a minute

phpBB/styles/prosilver/theme/common.css
Add required css rule to common.css
This rule was not required before this https://github.com/phpbb/phpbb/pull/3941 and the bug did not exist before.
but after the above PR, I think this rule is required to fix the bug.
PHPBB3-15673
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15673
=> [ticket/15673] Fix Duplicated links in QuickLinks and main nav bar

phpBB/phpbb/di/container_builder.php, phpBB/phpbb/filesystem/filesystem.php
1. During procedure of building container we have to check both required files
in cache: container_* and autoload_*. This files should be "fresh" and if one 
of the does not exist then we have to build it and put into a cache one more 
time.
2. Fix typo 'posic_getuid' does not exist, so $php_uid is alwasy was false.
PHPBB3-15678
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15678
=> [ticket/15678] Fix build and cache flow for container

git-tools/hooks/commit-msg
When someone tries to do a pull request with incorrect line breaks in the commit message, the error message as given by Travis is "Unexpected EOF encountered". The error message should be clearer that CR/LF was the problem. This change adds a separate check for CRLF line endings.
PHPBB3-15683
=> [ticket/15683] Better error message when commit message has CRLF

phpBB/phpbb/cache/driver/memory.php
function `_read` in classes inherited from `memory`
may returns `false` but `$vars` must be an array
PHPBB3-15791
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15791
=> [ticket/15791] fix php 7.2 count() bug in memory cache driver

phpBB/docs/events.md, phpBB/styles/prosilver/template/posting_preview.html, phpBB/styles/prosilver/template/posting_topic_review.html, phpBB/styles/prosilver/template/search_results.html, phpBB/styles/prosilver/template/viewtopic_body.html
Needed for extensions who adds information at the end of the message (such as moderator messages).
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15735
=> [ticket/15735] Add *_content_after template event

phpBB/includes/functions.php
PHPBB3-15723
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15723
=> [ticket/15723] Rewrite gen_rand_string() and gen_rand_string_friendly()

phpBB/phpbb/db/migration/data/v330/extensions_composer_2.php
PHPBB3-15795
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15795
Surprised this got through since the migration causes installs (at least for me) to fail.
=> [ticket/15795] Fix broken migration, $config is not a method

phpBB/includes/functions_content.php, phpBB/includes/ucp/ucp_pm_compose.php, phpBB/posting.php
Before parsing the private message to be loaded a simple BBCode status
check is done to verify that BBCodes are enabled. Depending on that
option the quote will be formated as BBCode or as plain text, similarly
to what is done in posting.php.
PHPBB3-15622
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15622
=> [ticket/15622] Fix quoting in PMs when BBCodes are disabled

phpBB/styles/prosilver/template/mcp_ban.html
Technically it is possible to store multiline ban reasons in database, however this breaks unescaped JavaScript code stored in template.
I suggest to use TWIG e('js') function to fix this issue.
PHPBB3-15600
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15600
=> [ticket/15600] Escaped ban reasons in JavaScript code of mcp_warn.html

phpBB/ucp.php
[ticket/15788] Fix return button for Privacy Policy
Change the text from "Return to Login Page" to "Return to Previous page" as the privacy policy can now be accessed through the footer so we could return to any random previous page instead of just the login page.
Approved by @Nicofuma in previous ticket #5358 which was from a wrong branch (sorry :) ) Deleted that branch now and used a proper fork. 
PHPBB3-15788
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15788
=> [ticket/15788] Fix return button for Privacy Policy

phpBB/includes/ucp/ucp_pm_compose.php
Event added for the handle_message_list_actions() function in ucp_pm_compose
so that extensions can perform additional actions.
PHPBB3-15803
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15803
=> [ticket/15803] Add events on ucp_pm_compose for additional message list actions

phpBB/includes/functions_posting.php
Events added to allow modifying notification data before in the database.
Useful to change variables in the notification message, such as usernames.
Includes some other residual data to allow this event to be versatile.
PHPBB3-15819
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15819
=> [ticket/15819] Add core event to functions_posting to modify notifications

phpBB/docs/events.md, phpBB/styles/prosilver/template/forumlist_body.html, phpBB/styles/prosilver/template/memberlist_view.html, phpBB/styles/prosilver/template/search_results.html, phpBB/styles/prosilver/template/viewforum_body.html, phpBB/styles/prosilver/template/viewonline_body.html
PHPBB3-15827
Explanation: Needed for extensions which adds information at the beginning & ending of the username of member
PS Note: this is my first Issue at tracker & Pull Request at phpBB, so if there are any mistakes then kindly please help me out.
Best Regards.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15827
=> [ticket/15827] Add *_username_{prepend/append} template events

phpBB/viewforum.php
PHPBB3-15863
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15863
=> [ticket/15863] Add core.viewforum_modify_sort_direction

phpBB/posting.php
Allows the modification of default variables put into post_data.
Also allows you to unset variables in post_data to inherit the default ones.
PHPBB3-15879
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15879
=> [ticket/15879] Add core.posting_modify_default_variables

phpBB/phpbb/captcha/plugins/qa.php
Add MySQL 5.7+ support for Q&A captcha plugin
Checklist:
Tracker ticket: https://tracker.phpbb.com/browse/PHPBB3-15876
=> [ticket/15876] MySQL 5.7+ support for Q&A captcha plugin

phpBB/composer.json, phpBB/composer.lock, phpBB/config/default/container/services_twig.yml, phpBB/phpbb/template/twig/extension.php, phpBB/phpbb/template/twig/loader.php, phpBB/phpbb/template/twig/node/definenode.php, phpBB/phpbb/template/twig/node/includeasset.php, phpBB/phpbb/template/twig/node/includephp.php, phpBB/phpbb/template/twig/tokenparser/defineparser.php, phpBB/phpbb/template/twig/tokenparser/event.php, phpBB/phpbb/template/twig/tokenparser/includecss.php, phpBB/phpbb/template/twig/tokenparser/includejs.php, phpBB/phpbb/template/twig/tokenparser/includeparser.php, phpBB/phpbb/template/twig/tokenparser/includephp.php, phpBB/phpbb/template/twig/tokenparser/php.php, tests/controller/common_helper_route.php, tests/email/email_parsing_test.php, tests/extension/metadata_manager_test.php, tests/template/template_allfolder_test.php, tests/template/template_events_test.php, tests/template/template_includecss_test.php, tests/template/template_test_case.php, tests/template/template_test_case_with_tree.php
Checklist:
Tracker ticket: [PHPBB3-15508](https://tracker.phpbb.com/browse/PHPBB3-15508)
Changes introduced by Twig 2.x:
- `Twig_NodeInterface` was removed, `Twig_Node` should be used instead.
- `Twig_Parser::getEnvironment()` was removed
- `Twig_Loader_Filesystem::findTemplate()` has a new argument `$throw = true`
- `Twig_Loader_Filesystem::validateName()` visibility changed from protected to private.
To install Twig 2.x here's the composer command I launched (in order to ignore platform requirements as Twig 2 require php >= 7.0): `php composer.phar update twig/twig --with-dependencies --ignore-platform-reqs`
=> [ticket/15508] Support Twig 2.x

phpBB/includes/acp/acp_groups.php, phpBB/includes/functions_user.php, phpBB/includes/ucp/ucp_groups.php, phpBB/language/en/acp/groups.php
Update the ACP and the UCP so that when bulk adding users to a group, if invalid usernames are submitted alongside valid usernames then a message will be displayed to inform the user what the invalid usernames are.
I'm using the old `$user->lang[]` format for now so I don't interfere with PR #5447.
PHPBB3-15883
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15883
=> [ticket/15883] New error message for when users try adding invalid usernames to a group

travis/setup-php-extensions.sh
Travis fails when the APCu install fails due to it already being installed
A check is added here to make sure that it does nothing in that case
PHPBB3-15935
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15935
=> [ticket/15935] Don't install APCu if it's already installed

phpBB/includes/mcp/mcp_ban.php, phpBB/includes/mcp/mcp_front.php, phpBB/includes/mcp/mcp_main.php, phpBB/includes/mcp/mcp_topic.php, phpBB/includes/ucp/ucp_groups.php, phpBB/includes/ucp/ucp_main.php, phpBB/includes/ucp/ucp_pm.php, phpBB/includes/ucp/ucp_pm_compose.php, phpBB/includes/ucp/ucp_profile.php
All functions and classes that are being checked for are actually the ones being used, except for the check in ucp_groups.php: https://github.com/kasimi/phpbb/commit/75007697ae55632200eb7f2c6579026e23fe3d7d#diff-ec446c980dec86d6991a822a459adfe6R404 I couldn't find out which of the functions in `includes/functions_display.php` is needed so I picked a random one for the `function_exists()` check.
PHPBB3-15954
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15954
=> [ticket/15954] Add safeguards to include() calls

phpBB/includes/functions_posting.php
Replace MAX SQL function with faster query using order by and limit.
The ajacent query could also be optimized to eliminate the usage of MAX.
Note that adding a compound key as suggested by EXPLAIN SQL yields an
improvement, but not nearly as fast as ORDER + LIMIT.
PHPBB3-15941
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15941
=> [ticket/15941] Replace MAX to speed up query in update_post_information

phpBB/docs/events.md, phpBB/styles/prosilver/template/ucp_profile_signature.html
PHPBB3-15949
It adds a template event in the signature posting editor to add custom options to be consistent with the default posting editor.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15949
=> [ticket/15949] Add ucp_profile_signature_posting_editor_options_prepend

phpBB/language/en/common.php, phpBB/styles/prosilver/template/forumlist_body.html
Fix for a minor bug whereby if a forum had no posts and someone added a topic which required approval, for privileged users it would say "No posts" in the forumlist while in the topic/post count it would have a number that indicated there were posts.
This change makes it so in this rare case (which has actually happened at .com a few times recently), instead of "No posts" it will either say "Topic awaiting approval" or "Topics awaiting approval".
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15917
=> [ticket/15917] Unapproved topics message for forums with no other posts

phpBB/phpbb/textformatter/s9e/link_helper.php, tests/text_formatter/s9e/default_formatting_test.php
Links that were created by a [url=] BBCode are not meant to be shortened. However, if the text content of the link is a valid URL, that valid URL gets shortened.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16034
=> [ticket/16034] Fix [url=] links being incorrectly shortened

.travis.yml
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
"_If you currently specify __sudo:__ in your __.travis.yml__, we recommend removing that configuration_"
https://tracker.phpbb.com/browse/PHPBB3-16058
=> [ticket/16058] Travis CI: "sudo: required" not longer is

phpBB/phpbb/search/fulltext_mysql.php
The max and min search length for the MySQL database vary based on the
engine for the underlying table. For MyISAM tables, the variables are
ft_max_word_len and ft_min_word_len, but for InnoDB tables the
variables are innodb_ft_max_token_size and innodb_ft_min_token_size.
Take the posts table type into account when setting the max and min
search length.
*Note*: I've based this against 3.2.x, but this is in 3.3.x and master as well.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16096
=> [ticket/16096] Use InnoDB fulltext limits for InnoDB tables

tests/group/helper_test_case.php, tests/notification/group_request_test.php
PHPBB3-15886
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15886
=> [ticket/15886] Use getMockBuilder instead of removed getMock()

phpBB/includes/functions.php
PHPBB3-16066
After the introduction of add_form_key() and check_form_key() calls to
login_box() in phpBB 3.2.6 and later, if a banned user attempts to login,
they receive a "The submitted form was invalid. Try submitting again."
A recursive call into login_box() by the check_ban() processing was not
taken into account by the phpBB 3.2.6 change, and was impossible to succeed.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16066
=> [ticket/16066] Fix FORM_INVALID always returned for banned user.

phpBB/styles/prosilver/template/viewforum_body.html
PHPBB3-16040
Change proSilver's viewforum_body.html template to be in line with existing
viewtopic_body.html behavior, in which the topic icon path will be surrounded
in quotes, and presence of a space in the topic icon file name will not fail.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16040
=> [ticket/16040] Forum list won't display topic icons containing a space.

phpBB/includes/functions.php, phpBB/index.php, phpBB/viewforum.php
PHPBB3-16054
Moving the login form's add_form_key() work into page_header(), so that the
template variables required for presenting a login form are again available
to any template that chooses to consume them.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16054
=> [ticket/16054] Restore ability to login from any template.

phpBB/adm/style/acp_database.html, phpBB/includes/acp/acp_database.php
PHPBB3-16084
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16084
=> [ticket/16084] Remove redundant backup radio button

phpBB/assets/javascript/plupload.js, phpBB/phpbb/plupload/plupload.php, phpBB/styles/prosilver/template/plupload.html
PHPBB3-16076
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16076
=> [ticket/16076] addFileFilter to check max file size per mime type

phpBB/adm/style/acp_posting_buttons.html, phpBB/assets/javascript/editor.js, phpBB/includes/functions_display.php, phpBB/styles/prosilver/template/posting_buttons.html
PHPBB3-15422
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15422
--- 
Follow up of https://github.com/phpbb/phpbb/pull/5188
He was on the right track with his PR already, as those `LA_` variables are functions, and do not have to be defined anywhere. And the 'regular' help lines are still used in `title` attributes.
Some small unrelated (automatic) changes to the editor.js file, removing redundant spaces. Gotta love phpstorm.
=> [ticket/15422] Remove redundant BBCode helpline

phpBB/memberlist.php, phpBB/styles/prosilver/template/memberlist_body.html
PHPBB3-14815
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14815
--- 
Continuation of https://github.com/phpbb/phpbb/pull/5164
As to Elsensee's last comment (https://github.com/phpbb/phpbb/pull/5164#issuecomment-425417254), this is not completely true. If the profile field does not have a value, it is not included in the list. There is however a need to check if the field is a contact field or not.
=> [ticket/14815] Enable contact links in memberlist

phpBB/includes/functions.php
Backported to 3.3.x
This is only happening when there is basicly an error during
init of the container.
PHPBB3-16043
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16043
=> [ticket/16043] Check if not null before getting anything from the container

phpBB/phpbb/plupload/plupload.php, tests/plupload/plupload_test.php
PHPBB3-16141
Change get_chunk_size() calculation to correctly calculate limits without
letting a zero "unlimited" value always win.  Also ensure get_chunk_size()
can only return zero if all of the limits were in fact set to unlimited.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16141
=> [ticket/16141] plupload chunk_size incorrect when 'unlimited' is involved.

phpBB/styles/prosilver/template/mcp_topic.html, phpBB/styles/prosilver/template/posting_review.html, phpBB/styles/prosilver/template/posting_topic_review.html, phpBB/styles/prosilver/template/viewtopic_body.html, tests/functional/download_test.php, tests/functional/feed_test.php, tests/functional/posting_test.php, tests/functional/prune_shadow_topic_test.php, tests/functional/visibility_softdelete_test.php
The previous version was relative to a &start= which was
sometimes wrong.
PHPBB3-16150
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16150
=> [ticket/16150] Make post subject link an absolute url

phpBB/phpbb/di/service_collection.php
PHPBB-16206
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16206
Problem is / was, that `isset()` also checks if value is not `null`.
This is an issue for the test environment, where the actual items for the service collections are not added.
So wasn't a PHP bug after all 😅 
Referencing #5732
=> [ticket/16206] Remove no longer needed workaround for PHP bug #66834

phpBB/config/default/container/services_text_formatter.yml, phpBB/includes/acp/acp_bbcodes.php, phpBB/language/en/acp/posting.php, phpBB/phpbb/textformatter/acp_utils_interface.php, phpBB/phpbb/textformatter/s9e/acp_utils.php, tests/functional/acp_bbcodes_test.php, tests/text_formatter/s9e/acp_utils_test.php
This PR is against 3.3.x, not sure whether this is considered a new feature.
This PR adds a new service used in the ACP. It doesn't change the ACP's behaviour but it changes what kinds of BBCodes produce an error.
PHPBB3-16250
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16250
https://area51.phpbb.com/phpBB/viewtopic.php?f=126&t=72401
=> [ticket/16250] Add a service to check BBCodes safeness in ACP

phpBB/docs/nginx.sample.conf
It blocks an image in the ACP.
PHPBB3-16209
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16209
=> [ticket/16209] Match exactly "phpbb" in nginx example configuration file

phpBB/styles/prosilver/template/posting_attach_body.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15592
=> [ticket/15592] Fix attachments place inline button if BBCode is disabled

phpBB/phpbb/db/driver/driver.php
Checklist:
In addition to #5267.
This code https://github.com/phpbb/phpbb/blob/3.3.x/phpBB/includes/functions.php#L4323 is preventing SQL report page (when `?explain=1`) from being displayed to non-admins.
<a href="https://tracker.phpbb.com/browse/PHPBB3-16307">PHPBB3-16307</a>.
=> [ticket/16307] Fix SQL time reporting when debug.sql_explain parameter is set

phpBB/config/default/container/services_password.yml, phpBB/phpbb/passwords/driver/argon2i.php, tests/passwords/drivers_test.php
Time bumped to 4, new PHP default.  
Memory bumped to 65536, new PHP default.
Threads left at 2 even though some PHP installations will default to 1.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16342
=> [ticket/16342] Increase default hashing costs for Argon2 passwords

phpBB/includes/acp/acp_attachments.php, phpBB/install/schemas/schema_data.sql, phpBB/language/en/acp/attachments.php, phpBB/phpbb/db/migration/data/v32x/add_plupload_config.php, phpBB/phpbb/db/migration/data/v32x/enable_plupload_config.php, phpBB/phpbb/plupload/plupload.php, tests/plupload/plupload_test.php
Adds ACP options to configure the compression level used by Plupload (default 85%) and whether Exif metadata is stripped from image attachments (default yes).
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16329
https://tracker.phpbb.com/browse/PHPBB3-16330
=> [ticket/16329] Add configuration options for Plupload

phpBB/phpbb/profilefields/manager.php
I removed the check for `field_show_novalue` when un-initialized profile field rows are added to the result. It doesn't matter if or where the profile field is supposed to be displayed at this point. The caller of this function is responsible to check this. With this change, the function correctly returns information about all available profile fields for users who haven't updated their profile.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16149
=> [ticket/16149] Always return default profile field data

phpBB/includes/functions_content.php
PHPBB3-16335
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16335
=> [ticket/16335] Ensure attachment event variables are always defined

phpBB/includes/functions_admin.php, phpBB/phpbb/cron/task/core/prune_all_forums.php, phpBB/phpbb/cron/task/core/prune_forum.php
PHPBB3-16060
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16060
Cron job should now update the correct column.
And I made it so it only logs it once per forum, rather that (potentially) 3 times.
=> [ticket/16060] Correct auto prune column for cron job

phpBB/install/startup.php, phpBB/phpbb/filesystem/filesystem.php
This will introduce a shutdown function that will try display a nicer error message and also try to recover from typical issues that are caused by the installer cache.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16354
=> [ticket/16354] Improve installer error handling and cache issues

phpBB/posting.php, phpBB/viewtopic.php
An user may not be able to edit - but lock and unlock.
It is terribly inconvenient for users being only able to un/lock threads to have to first unlock a topic, then reply and then re-lock it.
Thus in reply mode we check for lock permissions instead of edit.
This also includes editing if the user could normally edit his post if it
weren't for the lock.
Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): https://tracker.phpbb.com/browse/PHPBB3-16363
=> [ticket/16363] Allow replying to locked topics if user has m_lock permissions

phpBB/composer.json, phpBB/composer.lock
The dependency has been renamed and updated.
PHPBB3-16396
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16396
=> [ticket/16396] Use new php-webdriver instead facebook webdriver

phpBB/includes/mcp/mcp_queue.php, phpBB/includes/mcp/mcp_reports.php, phpBB/styles/prosilver/template/mcp_reports.html
PHPBB3-15609
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15609
---
- This truncates the forum names in the select dropdown in MCP reports (like in MCP queue)
- This allows actually unchecking the "Only this topic" in MCP reports
- added a default input value, which is overriden by the checkbox
- added a check if `t` was set in `POST`, so it can override the `GET` `t` parameter
- This makes the forum select box in MCP queue work properly
- If "Go" was pressed (and thus `sort` is set in `POST`), then the topic id should not determine the forum id
=> [ticket/15609] MCP Queue and Report forum and topic identifiers

phpBB/includes/functions_posting.php, phpBB/posting.php
PHPBB3-15979
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15979
---
This must of been broken for a while..
`soft_delete` is a variable that is never set to begin with, so now the if check is correct.
If the item is soft deleted (`visibility == ITEM_DELETED`) and the 'Delete post' check box is not ticked during editing, it means the post should be restored. So that is now correctly done, which then resulted in the fact that the `first_post`|`last_post` checks were incorrect. They were not the first or last post id, as those were amended correctly to only show approved posts. Which was fixed by using `>=` and `<=` (similar as mcp restore).
Fixing that bug, resulted in posting.php thinking it had to delete the post permanently. …
=> [ticket/15979] Fix restoring/deleting when editing soft-deleted post

phpBB/includes/mcp/mcp_logs.php
PHPBB3-16391
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16391
---
The ticket suggested including the `info_mcp_` into the ACP.
However, the core includes the `acp/common` into the MCP.
So I opted to stick with that approach, where `$p_master` is also already available.
=> [ticket/16391] Add extensions info_acp_ lang file to MCP logs

phpBB/bin/phpbbcli.php, phpBB/install/phpbbcli.php, phpBB/phpbb/console/application.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16417">PHPBB3-16417</a>.
=> [ticket/16417] Fix CLI database migration for phpBB 3.0.x

phpBB/phpbb/user.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-13426">PHPBB3-13426</a>.
=> [ticket/13426] Improve user timezone initialization

phpBB/styles/prosilver/template/bbcode.html, phpBB/styles/prosilver/theme/content.css, tests/text_formatter/s9e/default_formatting_test.php, tests/text_formatter/s9e/fixtures/styles/prosilver/template/bbcode.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15572
=> [ticket/15572] Fix W3C validation error for quote BBCode

phpBB/styles/prosilver/theme/content.css
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16474">PHPBB3-16474</a>.
<table>
<tr>
<td>Before</td><td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> [ticket/16474] Hide vertical scrollbar for attachbox

phpBB/styles/prosilver/theme/tweaks.css
**For 3.3.x only**.
Images were deleted with #5769.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16476">PHPBB3-16476</a>.
=> [ticket/16476] Eliminate links to deleted background images in tweaks.css

phpBB/includes/ucp/ucp_groups.php
PHPBB3-15194
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15194
Groups avatars are now properly removed through the UCP.
And the correct no_avatar image is shown.
=> [ticket/15194] Group avatar delete

phpBB/develop/create_variable_overview.php, phpBB/phpbb/controller/helper.php, tests/test_framework/phpbb_session_test_case.php
A variant of restoring BC broken in #5831.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16435">PHPBB3-16435</a>.
=> [ticket/16435] Restore calling page_footer() events in controllers

phpBB/adm/style/acp_posting_buttons.html, phpBB/includes/functions_display.php, phpBB/styles/prosilver/template/posting_buttons.html
PHPBB3-16496
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16496
=> [ticket/16496] Fix html special chars in custom BBcode help line

phpBB/styles/prosilver/theme/icons.css
**For the master branch only**.
The line was added in #5957 but is missing from the master branch.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16477">PHPBB3-16477</a>.
=> [ticket/16477] Restore .icon class selector in icons.css

phpBB/cache/.htaccess, phpBB/config/.htaccess, phpBB/files/.htaccess, phpBB/images/avatars/upload/.htaccess, phpBB/includes/.htaccess, phpBB/store/.htaccess
Checklist:
- I'll backport to 3.3.x & 3.2.x once accepted
https://tracker.phpbb.com/browse/PHPBB3-16554
___________
While the main .htaccess as well as the ones in phpbb/db/migration/data/vXYZ/
do already support the Apache 2.4 mod_authz_core directive "Require all denied",
all others still use only the deprecated "Deny from All". To not force modern
system to use the mod_access_compat module, the modern directives should be
supported in every case.
For this, the method of phpbb/db/migration/data/vXYZ/.htaccess is copied to
update and align all .htaccess files across the source code.
I'm sorry for not following the branch name guidelines (I hit "edit" in the GitHub UI), I'd need to open a new PR to change it, just ask.
=> [ticket/16554] Align all .htaccess files to support Apache 2.4 directives

phpBB/includes/ucp/ucp_register.php
mysqli_insert_id() returns 0 if there was no previous query on the connection
or if the query did not update an AUTO_INCREMENT value for some reason.
https://www.php.net/manual/en/mysqli.insert-id.php#refsect1-mysqli.insert-id-returnvalues
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16605">PHPBB3-16605</a>.
=> [ticket/16605] Fix possible SQL error on user registration

phpBB/includes/acp/acp_board.php, tests/functional/acp_avatar_settings_test.php
This is unfortunately no longer possible to do on master. See also #6049 
PHPBB3-16604
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16604
=> [ticket/16604] Remove checks for avatar upload path in avatar settings

phpBB/includes/functions_content.php, phpBB/phpbb/textformatter/s9e/utils.php, phpBB/phpbb/textformatter/utils_interface.php, tests/text_formatter/s9e/utils_test.php
PHPBB3-16630
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16630
=> [ticket/16630] Restore clean_formatting()'s behaviour

phpBB/includes/mcp/mcp_main.php, phpBB/mcp.php
Allow modification of permissions for normal users to access the mcp
Also allows modification of the hidden form fields when deleting topics
This lets normal users delete their own topics with replies
PHPBB3-15951
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15951
=> [ticket/15951] Add core events to mcp

phpBB/includes/ucp/ucp_pm_compose.php, phpBB/posting.php
Replacement for #6065.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16617">PHPBB3-16617</a>.
=> [ticket/16617] Add events to override message/PM BBCode status indications

phpBB/phpbb/di/container_builder.php, tests/di/container_cache_directory_test.php
Replacement for #5707.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16178">PHPBB3-16178</a>.
=> [ticket/16178] Make container_builder use same cache directory as Container

phpBB/config/default/container/services_text_reparser.yml, phpBB/phpbb/textreparser/plugins/poll_option.php, tests/text_reparser/plugins/poll_option_test.php
It's a minor change that could be merged into 3.3.x but it changes the constructor's signature, that's why it's against master.
PHPBB3-16645
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16645
=> [ticket/16645] Simplified text_reparser.poll_option

phpBB/styles/prosilver/template/mcp_ban.html, phpBB/styles/prosilver/template/mcp_notes_front.html, phpBB/styles/prosilver/template/mcp_notes_user.html, phpBB/styles/prosilver/template/mcp_warn_front.html, phpBB/styles/prosilver/template/mcp_warn_post.html, phpBB/styles/prosilver/template/mcp_warn_user.html, phpBB/styles/prosilver/template/memberlist_search.html, phpBB/styles/prosilver/template/search_body.html, phpBB/styles/prosilver/template/ucp_avatar_options.html, phpBB/styles/prosilver/template/ucp_groups_manage.html, phpBB/styles/prosilver/template/ucp_main_drafts.html, phpBB/styles/prosilver/template/ucp_prefs_personal.html, phpBB/styles/prosilver/template/ucp_prefs_post.html, phpBB/styles/prosilver/template/ucp_prefs_view.html, phpBB/styles/prosilver/template/ucp_profile_profile_info.html, phpBB/styles/prosilver/template/ucp_profile_reg_details.html, phpBB/styles/prosilver/template/ucp_profile_signature.html, phpBB/styles/prosilver/template/ucp_register.html, phpBB/styles/prosilver/template/ucp_resend.html, phpBB/styles/prosilver/template/ucp_reset_password.html, phpBB/styles/prosilver/template/ucp_zebra_foes.html, phpBB/styles/prosilver/template/ucp_zebra_friends.html
This will improved the UX and UI for the moderator and user of a phpBB, because they are no longer "tricked" into purge the whole input from the last seconds. 
PHPBB3-16660
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16660
=> [ticket/16660] Remove not needed RESET button from MCP and UCP

phpBB/phpbb/console/command/fixup/update_hashes.php, phpBB/phpbb/cron/task/core/update_hashes.php, phpBB/phpbb/passwords/manager.php
The $CP$ prefix is not part of the actual password hash.
phpBB2 passwords converted do currently include a phpass hash of the md5 of
the password. Make sure these are correctly checked.
PHPBB3-16697
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16697
=> [ticket/16697] Remove $CP$ prefix when updating hashes and support phpBB2 check

phpBB/viewforum.php
PHPBB3-16696
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16696
=> [ticket/16696] Fix unsupported operand types in viewforum - PHP8

.github/workflows/tests.yml
PHP 8.1 builds keep failing. Don't use them until there is a release.
PHPBB3-16707
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16707
=> [ticket/16707] Disable unstable PHP 8.1 builds

phpBB/includes/constants.php, phpBB/install/app.php
PHPBB3-16719
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16719
=> [ticket/16719] Fix PHP notice/warnings on update/install - PHP 8

phpBB/styles/prosilver/theme/icons.css
PHPBB3-16763
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16763
Before:
After:
=> [ticket/16763] fix imageset mine pip alignment

phpBB/phpbb/db/migrator.php
If a migration has an unfulfillable dependency, the migration causing the dependency to be unfulfillable is now shown in the error message instead of just the dependency.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16767
=> [ticket/16767] Report missing migration instead of dependency

phpBB/phpbb/db/migration/data/v310/contact_admin_acp_module.php
Checks to see if the ACP_CONTACT_SETTINGS module is already installed prior to running migration.
PHPBB3-16765
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16765
=> [ticket/16765] Check if ACP_CONTACT_SETTINGS module already installed

phpBB/install/startup.php
Tries to pass near-fatal errors to the frontend before throwing a probably unhandled runtime exception. Should cause "Timeout detected" to more commonly be replaced with an actual error message.
Checklist:
Tracker ticket: https://tracker.phpbb.com/browse/PHPBB3-16292
=> [ticket/16292] Propagate more errors to the installer UI

phpBB/includes/functions_admin.php, phpBB/includes/functions_posting.php, phpBB/includes/mcp/mcp_main.php
Add core events to modify topic and forum info when syncing
Also add core events to account for missing variables when using mcp functions
Custom post, topic, or forum columns use these events to account for their data
PHPBB3-15925
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15925
=> [ticket/15925] Add core events for sync and mcp functions

phpBB/language/en/acp/common.php
PHPBB3-16240
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16240
---
Not sure if `LOG_` language strings should not be removed for some sort of BC requirement?
Here's the PR in any case.
=> [ticket/16240] Remove deprecated LOG_ template/theme language strings

phpBB/assets/javascript/mentions.js
PHPBB3-16782
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16782
This will change the BBCode from:
```
[mention=u:2]test[/mention]
[mention=g:5]testGroup[/mention]
```
to:
```
[mention user_id=2]test[/mention]
[mention group_id=5]testGroup[/mention]
```
Both types are supported by the current BBCode implementation and will continue to work.
=> [ticket/16782] Use alternative template for mention BBCode

phpBB/phpbb/config/db.php, phpBB/phpbb/console/command/db/migrate.php
PHPBB3-13700
The goal of this is to be able to re-initialize the config entries after a cache purge, e.g. when running db migrations via CLI.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13700
=> [ticket/13700] Add method for initializing config after cache purge

phpBB/styles/prosilver/template/login_body.html
Added missing dt element to autologin
PHPBB3-16812
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16812
=> [ticket/16812] login_body.html missing dt tag for autologin

phpBB/styles/prosilver/theme/links.css
Fix text decoration on hover for forumtitle and last subject
PHPBB3-16829
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16829
=> [ticket/16829] forumtitle and lastsubject text decoration hover

phpBB/phpbb/template/twig/twig.php, tests/template/twig_test.php
PHPBB3-16243
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16243
---
Also updated array syntax to the new syntax `[]`.
And fixed all `getLoader()->*()` functions not being found.
Had this change for a couple of days on my extension development board for a couple of days and everything works as it should.
---
This will include paths for all the folders within a style folder. 
Such as `twig/`, `js/`, `css/`, `svg/`, `png/` but also `template/` and `theme/`.
=> [ticket/16243] Update template paths

phpBB/config/default/container/services.yml, phpBB/phpbb/extension/manager.php, phpBB/phpbb/routing/router.php, tests/dbal/migrator_test.php, tests/extension/manager_test.php, tests/extension/metadata_manager_test.php, tests/mock/dummy_router.php, tests/mock/extension_manager.php, tests/test_framework/phpbb_functional_test_case.php
When enabling an extension, it should be considered as not being enabled for the entire request as if the "enabled" flag is switch furing the request, the extension will stay not loaded (same when disabling an extension).
Example when it can be an issue today : if the router is called for the first time after enabling the extension and if the extension uses a custom route loader (like phpbb/pages) then the router will fail because the custom route will be found but the custom loader will not be loaded and available.
PHPBB3-16891
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16891
=> [ticket/16891] Do not change an extension status in the midle of a request

phpBB/includes/functions_mcp.php, phpBB/includes/functions_module.php, tests/functional/mcp/mcp_logs_test.php, tests/functional/mcp/mcp_main_test.php, tests/functional/mcp/mcp_quickmod_tools_test.php, tests/functional/mcp/mcp_test.php, tests/test_framework/phpbb_functional_test_case.php
Regression was introduced in #5760.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16904">PHPBB3-16904</a>.
=> [ticket/16904] Fix regression in MCP for topics selection

phpBB/includes/acp/acp_search.php
- Use `sql_query_limit` instead of `sql_query`
- Update SQL query to reflect the above change
- Assign proper last `post_id` to `$post_counter`
> As-per previous code, between 2 post_ids there may or may not be 100/100 posts,
> sometimes or most of the times some posts might be deleted
> and hence no of post can be less than 100, eg. 80/100.
> 
> I optimized such that there will be always be 100/100 posts to index it in one `while(...)` loop.
> Example (Approx, since it's system depended):
>  
> Step is no of refresh, inside each step there are no of `while(...)` loops.
>  
> In Previous code:
> Step 1: 80 | 60 | 100 = 240 - (1 min)
> Step 2: 40 | 90 | 70 = 200 - (1 min)
> Step 3: 50 | 70 | 90 = 210 - (1 min)
>  
> PR code:
> Step 1: 100 | 100 | 100 = 300 - (1 min)
> Step 2: 100 | 100 | …
=> [ticket/16940] Optimize phpBB Native Search [3.3.x]

phpBB/phpbb/search/backend/base.php
- Use `sql_query_limit` instead of `sql_query`
- Update SQL query to reflect the above change
- Assign proper last `post_id` to `$post_counter`
> As-per previous code, between 2 post_ids there may or may not be 100/100 posts,
> sometimes or most of the times some posts might be deleted
> and hence no of post can be less than 100, eg. 80/100.
> 
> I optimized such that there will be always be 100/100 posts to index it in one `while(...)` loop.
> Example (Approx, since it's system depended):
>  
> Step is no of refresh, inside each step there are no of `while(...)` loops.
>  
> In Previous code:
> Step 1: 80 | 60 | 100 = 240 - (1 min)
> Step 2: 40 | 90 | 70 = 200 - (1 min)
> Step 3: 50 | 70 | 90 = 210 - (1 min)
>  
> PR code:
> Step 1: 100 | 100 | 100 = 300 - (1 min)
> Step 2: 100 | 100 | …
=> [ticket/16940] Optimize phpBB Native Search [master]

phpBB/includes/functions_messenger.php, tests/email/headers_encoding_test.php
Alternative to #6327.
Based on <a href="https://github.com/symfony/polyfill-iconv/blob/fd324208ec59a39ebe776e6e9ec5540ad4f40aaa/Iconv.php#L355">iconv_mime_encode()</a> implementation from <a href="https://github.com/symfony/polyfill-iconv">symfony/polyfill-iconv</a>.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16912">PHPBB3-16912</a>.
=> [ticket/16912] Rewrite email headers encoding method

phpBB/styles/prosilver/template/memberlist_email.html
The id of the language select element referenced by it's label was missing.
PHPBB3-16914
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16914
=> [ticket/16914] Added missing id to language select element

phpBB/docs/INSTALL.html, phpBB/docs/README.html, phpBB/language/en/install.php
Also made it clear that it's only for expert users.
PHPBB3-15028
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15028
=> [ticket/15028] Rename automatic to advanced update

phpBB/language/en/common.php
PHPBB3-15947
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15947
A minor language issue reported by Kovi/Tuft in PHPBB3-15947. I've reproduced it and added a fix by covering an extra translation case for 0/unlimited.
=> [ticket/15947] Fix X out of 0 messages stored bug

README.md, phpBB/includes/functions.php
PHPBB3-16871
Checklist:
Tracker ticket (PHPBB3-16871):
https://tracker.phpbb.com/browse/PHPBB3-16871
**Brief description:**
I can replicate the issue that Snover described on the bug tracker. If forum feeds are enabled, and you try going to the URL of a _valid_ post or topic whilst also supplying another argument for an _invalid_ (negative integer) forum or topic, then it will throw a few exception errors.
**Example URLs:**
http://localhost:8001/phpBB3/phpBB/viewtopic.php?t=1&f=-1
http://localhost:8001/phpBB3/phpBB/viewtopic.php?p=1&f=-1
http://localhost:8001/phpBB3/phpBB/viewtopic.php?p=1&t=-1
**Returns:**
Fatal error: Uncaught Symfony\Component\Routing\Exception\InvalidParameterException: 
Parameter "forum_id" for route "phpbb_feed_forum" must match "\d+" ("-1" given) to generate a …
=> [ticket/16871] Do not allow negative forum and topic IDs in page_header

phpBB/phpbb/notification/type/forum.php
Some phpBB forum notification emails send URLs to the forum with redundant URL parameters, notably a forum IDs with topic URLs.
To have shorter and cleaner URLs, those are hereby removed.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16959
=> [ticket/16959] Remove redundant URL parameters from notification mails

phpBB/includes/ucp/ucp_main.php, phpBB/styles/prosilver/template/forumlist_body.html, phpBB/styles/prosilver/template/ucp_main_subscribed.html
PHPBB3-16800
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16800
I was able to reproduce the bug that stevemaury discovered in the ticket by setting the custom date format to `0` (which would fail the conditional in the template, causing the "No posts" message to appear in the forum list / subscription list even when there are topics and posts in the forum).
It's an extreme edge case, because it makes no sense for a user to pick a custom date format like this, but nonetheless it is a bug because it shouldn't say there are "No posts" when there are posts.
The fix is to use the RFC3339 date format as the conditional in the template file because that can't be influenced by any user input.
=> [ticket/16800] Fix 'No Posts' bug when no date format supplied

phpBB/styles/prosilver/template/posting_editor.html
The code present in the prosilver style template causes the wrong checkbox to be displayed in the post editor if the combination `f_delete`:true and `f_softdelete`:false is active in the user context. With this combination, this effectively prevents a forum post from being deleted via the editor options.
Corrected the relevant section and switched to Twig syntax
PHPBB3-16990
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16990
=> [ticket/16990] Fix for the style template code in the post editor

phpBB/phpbb/db/migration/data/v33x/profilefield_youtube_update.php
Per [the tracker issue](https://tracker.phpbb.com/browse/PHPBB3-13859) from May 2015:
> In 3.1 a youtube profilefield was added in which we can insert our youtube username to link to it.... There is just one major problem though...
>
> New youtube members no longer get an username. So I think we should decide on providing different ways to access their profile.
This PR will allow users to use any valid YouTube-domain URL, which allows for
all 3 formats (`/channel/...`, `/c/...`, and the now-legacy `/user/...`).
Per [YouTube's docs](https://support.google.com/youtube/answer/6180214?hl=en):
> ## Channel URL (ID-based)
> Example: youtube.com/channel/UCUZHFZ9jIKrLroW8LcyJEQQ
>
> This is the standard URL that YouTube channels use.
>
> ## Custom URL
> Example: youtube.com/c/YouTubeCreators
>
> …
=> [ticket/13859] Allow up-to-date format for Youtube profile field URLs

phpBB/includes/startup.php, phpBB/install/app.php
If the PHP version is too low, an error is displayed during installation and normal startup. This error does not include the current PHP version number, which often becomes a debate with users who believe they are running a supported version. It's usually a misconfiguration or custom php/user.ini somewhere that the user is unaware of. This at least removes one step of the support and debugging process.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16916
=> [ticket/16916] Include PHP version number in startup/install error

build/build.xml
Changes default permissions of `bin/phpbbcli.php` in the release archive so those that want to use a system level cron on *nix can save a step.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16917
=> [ticket/16917] Update phpbbcli.php's permissions in release archive

phpBB/includes/ucp/ucp_main.php, phpBB/styles/prosilver/template/ucp_main_front.html
Prosilver already supports rendering topic icons on this view, but the backend didn't populate the needed topicrow values.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17003
=> [ticket/17003] Include topic icon on UCP front page

phpBB/memberlist.php
In `memberlist.php` the `session_viewonline` is not defined,
hence the function `phpbb_show_profile(...)` does not have the required data to produce online status of user.
This is helpful for extensions and styles.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17026
=> [ticket/17026] Session viewonline not defined in Memberlist

phpBB/phpbb/db/tools/mssql.php, phpBB/phpbb/db/tools/postgres.php, phpBB/phpbb/db/tools/tools.php, tests/functional/acp_permissions_test.php
The "${var}" style of string interpolation is deprecated in PHP 8.2, using "{$var}" syntax instead.
PHPBB3-17056
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17056
=> [ticket/17056] Fix PHP 8.2 deprecation warning about ${var} syntax

phpBB/includes/functions_messenger.php
PHPBB3-17058
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17058
=> [ticket/17058] Add if-sentence for $encode_eol for email headers

phpBB/language/en/acp/board.php
Concerns the description of the switch "APC > GENERAL > Load settings > Allow usage of third party content delivery networks:".
* The text gives the impression that the choice of the switch state is a personal preference of individual administrators. In fact, this is a matter of local privacy laws.
* Missing mention that the switch also controls the integration of Font Awesome, part of phpBB's GUI and extensions.
PHPBB3-17068
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17068
=> [ticket/17068] ALLOW_CDN_EXPLAIN: Refines and expands the description

phpBB/language/en/acp/common.php, phpBB/phpbb/session.php
Switches to using callbacks for each DNSBL so that special cases can be handled when needed. Adds support for Spamhaus error codes and disables DNSBL checking if errors are encountered since they probably won't be resolved in a timely manner by the owner or host. An error log entry is generated as well to inform the owner of why DNSBL checking was disabled.
To test, set your resolver to 1.1.1.1 or 9.9.9.9, enable DNSBL checking under Security Settings, and attempt to post. Without the changes, you should get a message stating that you're on the Spamhaus blacklist. With the changes, it should go through, but disables DNSBL checking and generates a log in the Error log of the ACP.
Checklist: …
=> [ticket/17092] Check for Spamhaus error codes

phpBB/adm/style/acp_search.html, phpBB/includes/acp/acp_search.php, phpBB/language/en/acp/search.php, tests/functional/search/base.php
PR for **[phpbb:master](https://github.com/phpbb/phpbb/tree/master)** is at #6441 .
---
ScreenShot:
.
1st run (On Submit) : 
.
2nd & consecutive run (On each Refresh) : 
.
Continue to run (In-case the Indexing was Interrupted) : 
.
Changes :
- Update SQL for count of posts
- Update search index test
- Removed "Pop-up Progress Bar".
- For first run display the "Success Message".
- Display the Info from "Pop-up Progress Bar" to "Success Message".
- Only display "Redirect" & "Rate" of post refreshed "Success Message".
- Minor Language Fix.
- Use `ORDER BY post_id ASC` for progress stats.
- Removed HTML from Lang String.
- Moved HTML to PHP file.
- Increased the size of Progress-Bar by 2x.
Checklist: …
=> [ticket/16913] Add Search Index Progress Bar with Stats [3.3.x]

phpBB/includes/mcp/mcp_topic.php
Move post destination topic field should not be populated with a zero (via @stevemaury)
PHPBB3-17025
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17025
=> [ticket/17025] Move post destination topic field should not be populated with a zero

phpBB/styles/prosilver/theme/content.css
This is a fix for the Posts and Views alignment on index page in the header of category/forum.
Replaces https://github.com/phpbb/phpbb/pull/6235
PHPBB3-16796
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16796
=> [ticket/16796] Fixing misalignment of header items in category on index

phpBB/styles/prosilver/template/ucp_attachments.html
PHPBB3-17045
Before:
After this fix:
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17045
=> [ticket/17045] Use NUM_ATTACHMENTS in UCP and right css classes

phpBB/includes/message_parser.php
The error occurs when BBcode is used but there is no whitespace. In this case, a part of the RegEx that is designed to be greedy is responsible for selecting all BBcode tag containers and their content that do not contain whitespace. This, in combination with the replace string, effectively reduces the entire signature to a single space. This is the explanation for the reported behavior of phpBB.
In addition, the bug also generally prevents the correct removal of BBcode containers if their content does not contain whitespace. In such cases, the BBcode tags are removed along with the content, which also results in incorrect calculation of the text length.
* Changed the corresponding RegEx part from greedy to non-greedy.
* Removed an unnecessary class definition.
* Changed an unnecessary …
=> [ticket/17076] Fix signature length calculation

phpBB/phpbb/db/driver/driver.php, phpBB/phpbb/db/driver/driver_interface.php, phpBB/phpbb/db/driver/factory.php, phpBB/phpbb/db/driver/mssql_odbc.php, phpBB/phpbb/db/driver/mssqlnative.php, phpBB/phpbb/db/driver/mysqli.php, phpBB/phpbb/db/driver/oracle.php, phpBB/phpbb/db/driver/postgres.php, phpBB/phpbb/db/driver/sqlite3.php
Fixes [DBAL function sql_nextid - name is misleading](https://tracker.phpbb.com/browse/PHPBB3-8071).
Per the tracker issue:
> This function gets the ID of the last inserted row, not the ID of the next row to be inserted (which is difficult due to different autoincrement steps and also lends itself nicely to race conditions).
@iwisdom replied that the naming is consistent with how PHP itself names this functionality, but the link they posted doesn't support that (I guess this is referring to a much older version of PHP? The comment is from 2009).
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-8071
=> [ticket/8071] Add sql_last_inserted_id alias for sql_nextid

phpBB/phpbb/attachment/upload.php, phpBB/phpbb/auth/auth.php, phpBB/phpbb/config/config.php, phpBB/phpbb/datetime.php, phpBB/phpbb/event/data.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17097
=> [ticket/17097] Fix PHP 8.2 deprecation warnings

phpBB/phpbb/db/migration/profilefield_base_migration.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17145
=> Change static to private variable due to php81 inheritance

.github/workflows/tests.yml, phpBB/phpbb/db/tools/postgres.php
Fix `3.3.x` only as `master` doesn't have this code.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17148">PHPBB3-17148</a>.
=> [ticket/17148] Fix sql_table_exists() error for PostgreSQL 9.3 and earlier - 3.3.x

phpBB/docs/INSTALL.html
`master` version of #6493.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17148">PHPBB3-17148</a>.
=> [ticket/17148] Fix sql_table_exists() error for PostgreSQL 9.3 and earlier - master

phpBB/phpbb/path_helper.php, tests/path_helper/path_helper_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17141
=> [ticket/17141] Improve stability of path_helper and increase test coverage

phpBB/adm/style/acp_users.html, phpBB/includes/acp/acp_users.php
It will still be possible from the manage groups page though is discouraged now by hiding the delete entry when managing users.
In addition to this, the manage user page will now show that no group is specified for the user when viewing the groups page of a user.
PHPBB3-8777
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-8777
=> [ticket/8777] Discourage deleting user from group with only one group

phpBB/styles/prosilver/theme/responsive.css
The content property is not supported by the placeholder pseudo-element and hence the rules do not have any effect and can be removed.
PHPBB3-17171
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17171
=> [ticket/17171] Remove unsupported CSS rules for placeholder

phpBB/language/en/acp/board.php, phpBB/language/en/ucp.php
This fixes the outdated links we had to the date format page on php.net. PHP moved the date format syntax definition from the date() page to one of their DateTime pages.
Unrelated, but funnily after we spoke earlier @marc1706 I restarted the Codespace and it started acting normally again. Must have been a glitch with the container 🤣 
PHPBB3-17128
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17128
Screenshots:
ACP
UCP
=> [ticket/17128] Fix outdated link to php.net date format page

phpBB/phpbb/request/type_cast_helper.php, tests/request/type_cast_helper_test.php
Change set_var to check for multiline strings if multibyte
PHPBB3-17188
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17188
=> [ticket/17188] Allow request variable to check multiline unicode

phpBB/language/en/mcp.php
PHPBB3-17237
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17237
=> [ticket/17237] Use single quotes for QUICKMOD_ACTION_NOT_ALLOWED var

phpBB/phpbb/db/driver/mssql_odbc.php, phpBB/phpbb/db/driver/mssqlnative.php, phpBB/phpbb/db/driver/mysqli.php, phpBB/phpbb/db/driver/postgres.php, phpBB/phpbb/db/driver/sqlite3.php, phpBB/phpbb/db/tools/factory.php, phpBB/phpbb/db/tools/sqlite3.php
PHP 7 changes how most errors are reported by PHP. Instead of reporting errors through the traditional error reporting mechanism used by PHP 5, most errors are now reported by throwing Error exceptions.
Use it to display meaningful SQL error messages instead of PHP fatal errors for SQL errors.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17232">PHPBB3-17232</a>.
=> [ticket/17232] Improve SQL error messages handling

phpBB/phpbb/notification/manager.php, tests/notification/fixtures/submit_post_notification.type.bookmark.xml
Non-existent or disabled notification methods (f.e. added by extensions which were later disabled/purged) should not be loaded.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17117">PHPBB3-17117</a>.
=> [ticket/17117] Do not load non-existent/disabled notification methods

phpBB/styles/prosilver/template/index_body.html, phpBB/styles/prosilver/template/login_body.html, phpBB/styles/prosilver/template/login_forum.html, phpBB/styles/prosilver/template/ucp_login_link.html, phpBB/styles/prosilver/template/ucp_register.html, phpBB/styles/prosilver/template/viewforum_body.html
PHPBB3-17235
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17235
=> [ticket/17235] missing autocomplete for username

phpBB/includes/acp/acp_users.php, phpBB/includes/functions_display.php, phpBB/includes/functions_user.php, phpBB/install/convertors/convert_phpbb20.php, phpBB/memberlist.php, phpBB/phpbb/db/migration/data/v33x/add_user_last_active.php, phpBB/phpbb/session.php, tests/auth/provider_apache_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17312
=> [ticket/17312] Add column for tracking user last active time

phpBB/includes/ucp/ucp_prefs.php, phpBB/posting.php, phpBB/styles/prosilver/template/ucp_prefs_post.html
This fixes a bug on the posting page and on the UCP posting preferences page, the attach signature option was being displayed even if the user had the "Can use signature" option set to "never" in their user permissions.
PHPBB3-17109
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17109
=> [ticket/17109] Don't show the attach signature option if the user doesn't have permission

phpBB/styles/prosilver/template/forum_fn.js
The forum_fn.js file contained a small block of code that was commented out so there is no need to keep it in the codebase, especially as it was a fix for IE8 and older browsers.
PHPBB3-17320
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17320
=> [ticket/17320] Remove unused js code from prosilver

.devcontainer/resources/phpbb-config.yml, .devcontainer/resources/setup.sh, phpBB/includes/mcp/mcp_post.php, phpBB/includes/mcp/mcp_reports.php, phpBB/styles/prosilver/template/mcp_post.html
This PR fixes the module not accessible error which appears when trying to approve or disapprove (through the `MCP -> Reported Messages` page) a post which has been reported. 
To summarise: `U_APPROVE_ACTION` was not present on the mcp_reports page, so the form action was empty and clicking it led to a General Error.
The fix involves making sure that action is passed through to the template. I've also added an `S_CAN_APPROVE` permissions check.
PHPBB3-16553
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16553
**BEFORE:**
**AFTER:**
=> [ticket/16553] Fix for General Error when approving/disapproving a reported post through the MCP

phpBB/styles/prosilver/template/posting_pm_header.html, phpBB/styles/prosilver/theme/common.css
I've updated the text on the submit button used to remove recipients from a PM that is currently being composed. It used to just be a small `x` that was hard (for me and of course others) to see.
I've updated it to say `Remove` which is already an existing language string so no new translations are required for this change. I also added a 2px padding so the text isn't flush to the edges of the button.
It makes it more readable and actually looks styled as opposed to looking like an element that was forgotten about. I think this makes the interface much better to use.
PHPBB3-17317
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17317
=> [ticket/17317] Change button text for pm recipient to increase readability

phpBB/docs/events.md, phpBB/styles/prosilver/template/ucp_groups_manage.html
Add new template events to the UCP group management page allowing extension developers to replicate group management forms from the ACP into the UCP.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17316
=> [ticket/17316] Add template events to ucp_groups_manage

phpBB/memberlist.php
PHPBB3-17175
This fixes a bug whereby the wrong topic title would show in the breadcrumbs when emailing a topic. (The cause was that the SQL query was missing `t.topic_id = ' . (int) $topic_id`)
Checklist:
https://tracker.phpbb.com/projects/PHPBB3/issues/PHPBB3-17175
Screenshot:
(Previously, no matter what the topic id was it would always show the name of the first topic posted in that forum. Now, the breadcrumb will reflect the correct topic title associated with the topic id.)
=> [ticket/17175] Fix topic title in the breadcrumbs when emailing a topic

phpBB/phpbb/db/driver/mysqli.php, tests/dbal/write_test.php, tests/test_framework/phpbb_database_test_case.php
For `3.3.x`.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17337">PHPBB-17337</a>.
=> [ticket/17337] Fix mysqli driver is missing transaction begin statement - 3.3.x

phpBB/styles/prosilver/template/memberlist_view.html, phpBB/styles/prosilver/theme/common.css, phpBB/styles/prosilver/theme/responsive.css
Users that had very long rank titles would cause the rest of their profile details to be pushed down below the avatar and rank details breaking the layout. This change limits the width of the avatar and rank details.
PHPBB-17352
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17352
=> [ticket/17352] Fix overflow of long rank titles on profile page

phpBB/phpbb/install/module/install_finish/task/install_extensions.php, phpBB/phpbb/install/module/update_database/task/update_extensions.php
Adds the IP address of the user completing the installation process while extensions are being installed or updated. Prior to this change the IP address field was being left blank however other logs created during the install process for other actions does record the users IP.
PHPBB-17350
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17350
=> [ticket/17350] Add IP Address of user during install process

phpBB/viewtopic.php
Added the forum_id to the approve action link which ensures that when a topic is permanently deleted, the forum_id is present so that it can be used in the redirection link to go to the previous forum. This addresses a bug in which the forum_id is not provided and after deleting a topic, the user will be taken to a 404 page as the forum id fallbacks to 0.
PHPBB-17369
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17369
=> [ticket/17369] Add forum id to approve action url for redirection

phpBB/phpbb/search/fulltext_native.php, tests/search/native_test.php
Provided `$countable_keywords` wherein the existing `$keywords` value is modified so that any `-`, `+` and `|` characters without preceding spaces is replaced with the same but with a space in front of each. 
These spaces allow the string to be more accurately split when used instead of $keywords inside the $num_keywords calculation. 
This prevents the word limit being bypassed in search by the use of operators without whitespace.
PHPBB-17365
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17365
=> [ticket/17365] Prevent search limit being bypassed with operators

tests/test_framework/phpbb_test_case.php
`master` version of #6706.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17384">PHPBB-17384</a>.
=> [ticket/17384] Handle E_USER_ERROR for PHP 8.4 tests - master

tests/test_framework/phpbb_test_case.php, tests/test_framework/phpbb_test_case_helpers.php
Master version of https://github.com/phpbb/phpbb/pull/6710
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17384
=> [ticket/17384] Stop overriding error handler in test case and ignore E_DEPRECATED for expecting errors

phpBB/styles/prosilver/template/navbar_header.html, phpBB/styles/prosilver/theme/common.css
The quick links menu in the header navbar had an additional horizontal line at the bottom which did not need to be there. Additionally the separators for links that always display in the quick links menu had dotted underlines rather than the solid underlines that were under the links that only show up for mobile users when there's less screen space.
PHPBB-17373
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17373
=> [ticket/17373] Remove extra separator and change all separators to solid lines

phpBB/includes/mcp/mcp_queue.php
Fixes a bug that was introduced in 558b8ae whereby a template variable was added to wrap around the approve / disapprove UI however that variable was not set in mcp_queue so the check failed every time meaning you couldn't approve from the MCP.
PHPBB-17390
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17390
=> [ticket/17390] Fix unset template variable for topic approval in mcp

phpBB/includes/acp/acp_groups.php, tests/functional/acp_groups_test.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17391">PHPBB-17391</a>.
=> [ticket/17391] Fix PHP warning on creating group with the name already in use

phpBB/language/en/viewtopic.php, phpBB/styles/prosilver/template/bbcode.html, tests/text_formatter/s9e/default_formatting_test.php
Adds an aria label attribute to the quoted post reference link so that screen readers can inform the user of what the link is used for. Before this change the link was too vague and would not have been well described to users of its purpose if they couldn't see it.
PHPBB-17376
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17376
=> [ticket/17376] Add aria label to quote reference link

phpBB/search.php
Normally the links within `search.php` always include sorting parameters and is joined with the show results parameter using `&`. Which is fine if the sorting parameters are always populated, which they are, except when searching for new or unread posts. This fix adds a check for when those sorting parameters are empty.
PHPBB-17463
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17463
=> [ticket/17463] Remove extraneous '&' from search page urls

.github/workflows/tests.yml, phpBB/composer.json, phpBB/composer.lock, phpBB/config/default/container/parameters.yml, phpBB/config/default/container/services.yml, phpBB/config/default/container/services_updater.yml, phpBB/includes/acp/acp_update.php, phpBB/language/en/install.php, phpBB/phpbb/install/module/requirements/task/check_server_environment.php, phpBB/phpbb/update/controller.php, phpBB/phpbb/update/get_updates.php, tests/update/controller_test.php, tests/update/get_updates_test.php
PHPBB3-15851
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15851
=> [ticket/15851] Automatic update downloader

phpBB/adm/style/acp_bbcodes.html, phpBB/adm/style/admin.js, phpBB/includes/acp/acp_bbcodes.php, phpBB/includes/functions_display.php, phpBB/language/en/acp/posting.php, phpBB/language/en/common.php, phpBB/phpbb/db/migration/data/v400/add_bbcode_font_icon.php, phpBB/styles/prosilver/template/posting_buttons.html, tests/functional/acp_bbcodes_test.php
Adds a new field to the custom BBCode add/edit form that allows admins to define a Font Awesome icon to be displayed instead of the BBCodes name on the posting.php editor page.
PHPBB-17326
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17326
=> [ticket/17326] Add font icon field for custom BBCodes

phpBB/phpbb/feed/controller/feed.php, tests/functional/feed_test.php
The `feed_enable` config is never checked before generating the feeds. The effective result is that feeds are always enabled, regardless of the setting.
PHPBB-17470
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17470
=> [ticket/17470] Feed enable config not enforced

phpBB/phpbb/db/migration/data/v33x/topic_views_update.php
The user mentioned in the ticket that they were getting an error `SQL ERROR [ mysqli ] Out of range value for column 'topic_views' at row 1 [1264]` and I was able to replicate this by forcing the topic_views for a topic to to 16777215 and trying to load the page.
This fix validates that the incremented topic_views value won't exceed that mediumint maximum figure.
Note: I was hesitant to use a magic number for this, but that's how we've previously handled this exact use case in two other places:
https://github.com/phpbb/phpbb/blob/259d086e456cf642aca1b822dc63323512dead34/phpBB/phpbb/session.php#L147 https://github.com/phpbb/phpbb/blob/259d086e456cf642aca1b822dc63323512dead34/phpBB/includes/acp/acp_groups.php#L464
PHPBB-17381
Checklist: …
=> [ticket/17381] Topic view count validation

phpBB/phpbb/db/migration/data/v310/bot_update.php
Ensure `v310/bot_update` runs after `v310/avatars` migration which changes `user_avatar_type` column type from `tinyint(2)` to `varchar(255)`.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17486">PHPBB-17486</a>.
=> [ticket/17486] Fix SQL error on phpBB v.3.0 to v.3.3 upgrade

.github/workflows/tests.yml
There's no MSSQL-2017 runner image reliably working on Ubuntu 22.04+ currently, so dropping it in favor of MSSQL-2022.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17498">PHPBB-17498</a>.
=> [ticket/17498] Move to Ubuntu 22.04 runner images for SQLite and MSSQL tests - 3.3.x

.github/workflows/tests.yml
`master` version of #6804.
There's no MSSQL-2017 runner image reliably working on Ubuntu 22.04+ currently, so dropping it in favor of MSSQL-2022.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17498">PHPBB-17498</a>.
=> [ticket/17498] Move to Ubuntu 22.04 runner images for SQLite and MSSQL tests - master

phpBB/phpbb/db/doctrine/connection_parameter_factory.php
Check pdo_mysql extension for being loaded
to use respective \PDO::MYSQL_ATTR_FOUND_ROWS constant.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17488">PHPBB-17488</a>.
=> [ticket/17488] Fix PHP error when MySQL PDO driver is not enabled

phpBB/adm/style/installer_header.html, phpBB/phpbb/install/controller/helper.php, phpBB/phpbb/language/language_file_helper.php
This fixes a bug where a user could have other languages in the installer but the language dropdown did not match the language shown (e.g., in the ticket example, Danish was uploaded and shown as the selected option in the dropdown menu due to its index positioning, but English was actually the language being displayed). 
This change also sorts the languages alphabetically by their name rather than ISO code to avoid the funny situation shown by the bug submitter in https://www.phpbb.com/community/viewtopic.php?p=16032040
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17399
=> [ticket/17399] Fix selected language bug in installer

phpBB/memberlist.php
Add a new event inside `memberlist.php` that allows extension developers to modify the memberrow data before the template variables are assigned. This will allow developers to alter user data shown within the table of users.
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17522
=> [ticket/17522] Add event to member list to modify template vars

phpBB/adm/style/acp_ranks.html
A user on the board (https://www.phpbb.com/community/viewtopic.php?t=2627491) found that in the ACP you would get a database error if you tried to set a rank with min_posts above 16777215 (mediumint limit). This change just brings the browser-side validation down to that value from 9999999999 so the user can't submit such a high value.
Interestingly, this fix is only required for 3.3.x. In master, rank_min:UINT maps to unsigned integer and not mediumint (see https://tracker.phpbb.com/projects/PHPBB/issues/PHPBB-17035 for more on that)
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17034
=> [ticket/17034] Fix minimum posts rank validation

phpBB/search.php, phpBB/styles/prosilver/template/search_results.html, phpBB/styles/prosilver/template/viewforum_body.html, phpBB/viewforum.php
This addresses an interesting bug someone noticed whereby if someone has `f_list_topics = yes` permissions for a forum but `f_read = no`, then they get an incomplete listing in the search results. (i.e., the use case is the admin has set it up so a user is allowed to see the topic name, but can't click into it to read the post)
The fix in this PR is, for cases where those permission options above are in effect, to check if the search is for topic titles only (and results are displayed as topics; because we don't want posts being exposed), and if it is then allow any forums the user has `f_list_topics = yes` permission back into the search results but with the links removed, matching the viewforum.php behaviour.
Furthermore, if there is a forum where this permission set up applies for a …
=> [ticket/17157] Fix for allowing user to see search results for topics if f_list_topics = yes

tests/functional/acp_test.php, tests/functional/extension_acp_test.php, tests/functional/fixtures/files/extensions_catalog.json
PHPBB-17554
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17554
**Reproduction steps**
Open `phpBB/phpbb/composer/manager.php`
Find: `$this->available_packages = $this->installer->get_available_packages($this->package_type);`
Before this line, add something like `die('no crawling');` and run the functional test suite.
Then all tests that connect to satis.phpbb.com or repo.packagist.org will fail.
=> [ticket/17554] Mock Extensions Catalog cache in tests
