phpbb/phpbb

phpBB/includes/acp/acp_users.php

[ticket/13439] Add event core.acp_users_overview_before

---

phpBB/includes/functions.php

[ticket/13440] Add event core.login_box_failed

---

phpBB/includes/acp/acp_users.php

[ticket/13439] Update event version to 3.1.3-RC1

---

phpBB/includes/functions.php

[ticket/13440] Update event version to 3.1.3-RC1

---

phpBB/viewforum.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-13449">PHPBB3-13449</a>.

[ticket/13449] Add viewforum event after the topic's been assigned to template

---

phpBB/mcp.php

[ticket/13141] Implement core.mcp_global_f_read_auth_after
PHPBB3-13141

[Event] Allow applying additional permissions to MCP access besides f_read

---

phpBB/phpbb/log/log.php

https://tracker.phpbb.com/browse/PHPBB3-13148
PHPBB3-13148

[ticket/13148] Creating a final way to modify edit logs output

---

phpBB/phpbb/session.php
phpBB/ucp.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-13422">PHPBB3-13422</a>

[ticket/13422] New events for save custom cookies and set custom ban type

---

phpBB/includes/functions_admin.php

https://tracker.phpbb.com/browse/PHPBB3-13430
PHPBB3-13430

[ticket/13430] Add event core.prune_sql

---

phpBB/includes/functions_posting.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-13435">PHPBB3-13435</a>.

[ticket/13435] Add core event to modify submit_post() sql data

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/viewtopic_body.html
phpBB/styles/subsilver2/template/viewtopic_body.html

[ticket/13437] Add template event viewtopic_body_post_author_before/after

---

phpBB/includes/message_parser.php

https://tracker.phpbb.com/browse/PHPBB3-13466

[ticket/13466] Add bitfield and uid to event core.message_parser_check_message

---

phpBB/phpbb/db/migration/tool/module.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13432

[ticket/13432] Make sure to add language file when including acp_modules

---

phpBB/includes/acp/acp_email.php

https://tracker.phpbb.com/browse/PHPBB3-13470

[ticket/13470] Fix non-empty username array if no usernames are given

---

phpBB/includes/bbcode.php

https://tracker.phpbb.com/browse/PHPBB3-13478

[ticket/13478] Add event core.bbcode_cache_init_end

---

phpBB/phpbb/config/db.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13385

[ticket/13385] Free result in \phpbb\config\db::set_atomic()

---

phpBB/install/install_install.php

Added support for cyrillic domains as database hosts.
PHPBB3-13442

[ticket/13442] UTF-8 symbols for database host

---

phpBB/phpbb/db/migration/data/v31x/plupload_last_gc_dynamic.php

[PHPBB3-13366](https://tracker.phpbb.com/browse/PHPBB3-13366)

[ticket/13366] Ensure plupload_last_gc config entry is dynamic.

---

phpBB/phpbb/error_collector.php
tests/error_collector_test.php

https://tracker.phpbb.com/browse/PHPBB3-13306
PHPBB3-13306

[ticket/13306] add error level to collector

---

phpBB/viewforum.php
phpBB/viewtopic.php

https://tracker.phpbb.com/browse/PHPBB3-13453
PHPBB3-13453

[ticket/13453] Sort param in Canonical URL

---

phpBB/config/content.yml
phpBB/phpbb/content_visibility.php
tests/content_visibility/delete_post_test.php
tests/content_visibility/get_forums_visibility_sql_test.php
tests/content_visibility/get_global_visibility_sql_test.php
tests/content_visibility/get_visibility_sql_test.php
tests/content_visibility/set_post_visibility_test.php
tests/content_visibility/set_topic_visibility_test.php
tests/notification/submit_post_base.php

https://tracker.phpbb.com/browse/PHPBB3-13146
PHPBB3-13146
Fixed branch to push on #3198

[ticket/13146] Allow changing the result of calling get_forums_visibility_sql

---

phpBB/phpbb/db/migration/data/v31x/profilefield_remove_underscore_from_alpha.php

https://tracker.phpbb.com/browse/PHPBB3-13486

[ticket/13486] Fix typo in method name

---

phpBB/phpbb/content_visibility.php

https://tracker.phpbb.com/browse/PHPBB3-13147
fixing pushing branch on #3200

[ticket/13147] Change get_global_visibility_sql()'s results

---

phpBB/styles/prosilver/template/posting_editor.html

[PHPBB3-13346](https://tracker.phpbb.com/browse/PHPBB3-13346)

[ticket/13346] Fix indentation, spacing and missing divs

---

build/package.php

https://tracker.phpbb.com/browse/PHPBB3-13272

[ticket/13272] Add vendor/ folder to "changed files" package

---

phpBB/phpbb/user_loader.php

https://tracker.phpbb.com/browse/PHPBB3-13498
PHPBB3-13498

[ticket/13498] Change get_user_avatar() calls with phpbb_get_avatar()

---

phpBB/posting.php

https://tracker.phpbb.com/browse/PHPBB3-13490

[ticket/13490] Allow multibyte characters in edit reason

---

phpBB/viewtopic.php

https://tracker.phpbb.com/browse/PHPBB3-13160
PHPBB3-13160

[ticket/13160] Viewtopic; before viewing permissions event

---

phpBB/config/notification.yml
phpBB/phpbb/notification/manager.php
tests/notification/base.php
tests/notification/submit_post_base.php

https://tracker.phpbb.com/browse/PHPBB3-13154
PHPBB3-13154

[ticket/13154] Event to edit user list for notification in notifications

---

phpBB/includes/functions_admin.php
phpBB/includes/functions_compatibility.php
tests/functions/get_remote_file_test.php

https://tracker.phpbb.com/browse/PHPBB3-13499
PHPBB3-13499

[ticket/13499] Move get_remote_file() to functions_compatibility.php

---

phpBB/includes/acp/acp_search.php
phpBB/includes/functions.php
phpBB/includes/functions_jabber.php
phpBB/includes/functions_messenger.php
phpBB/includes/startup.php

https://tracker.phpbb.com/browse/PHPBB3-12487
PHPBB3-12487

[ticket/12487] Update PHP code

---

build/code_sniffer/phpbb/Sniffs/Namespaces/UnusedUseSniff.php

https://tracker.phpbb.com/browse/PHPBB3-13511
PHPBB3-13511

[ticket/13511] Call the check() method with the phpcsFile object

---

phpBB/includes/functions.php
phpBB/phpbb/path_helper.php
tests/path_helper/path_helper_test.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13192

[ticket/13192] Add method for generating valid user page links based on mod_rewrite

---

phpBB/styles/prosilver/theme/content.css

https://tracker.phpbb.com/browse/PHPBB3-13507
PHPBB3-13507

[ticket/13507] Fix horizontal scrollbar for large images in posts

---

phpBB/styles/prosilver/theme/bidi.css

https://tracker.phpbb.com/browse/PHPBB3-13431
PHPBB3-13431

[ticket/13431] Fix responsive RTL media queries for <IE11

---

phpBB/includes/bbcode.php

[PHPBB3-10985](https://tracker.phpbb.com/browse/PHPBB3-10985)

[ticket/10985] Error bbcode.html not found when updating with custom style inheriting from prosilver

---

phpBB/phpbb/search/fulltext_native.php

https://tracker.phpbb.com/browse/PHPBB3-13504

[ticket/13504] Fix invalid variable $user

---

.travis.yml
travis/install-phpunit-5-2.sh

Alternative attempt to #3309 
https://tracker.phpbb.com/browse/PHPBB3-13523

[ticket/13523] Install PHPUnit manually instead of from PEAR.

---

phpBB/includes/acp/acp_attachments.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13519

[ticket/13519] Correctly validate imagick path as path and not string

---

phpBB/includes/ucp/ucp_pm_options.php

https://tracker.phpbb.com/browse/PHPBB3-13526

[ticket/13526] Correctly validate the ucp_pm_options form key.

---

phpBB/includes/acp/acp_update.php

https://tracker.phpbb.com/browse/PHPBB3-13527

[ticket/13527] Escape information received from version server

---

phpBB/config/db.yml
phpBB/phpbb/db/migration/container_aware_migration.php
phpBB/phpbb/db/migration/data/v30x/release_3_0_5_rc1.php
phpBB/phpbb/db/migration/data/v310/soft_delete_mod_convert.php
phpBB/phpbb/db/migration/profilefield_base_migration.php
phpBB/phpbb/db/migrator.php
phpBB/phpbb/event/dispatcher.php
phpBB/phpbb/event/dispatcher_interface.php
tests/dbal/migrator_test.php
tests/extension/manager_test.php
tests/extension/metadata_manager_test.php
tests/test_framework/phpbb_functional_test_case.php

https://tracker.phpbb.com/browse/PHPBB3-13489
PHPBB3-13489

[ticket/13489] Disable the event dispatcher in the migrator

---

phpBB/phpbb/db/migration/data/v30x/release_3_0_5_rc1.php
tests/functional/prune_shadow_topic_test.php

https://tracker.phpbb.com/browse/PHPBB3-13530

[ticket/13530] Fix undefined variables

---

phpBB/phpbb/template/twig/twig.php

[ticket/13133] Fix variable name in set_custom_style()

---

phpBB/phpbb/db/tools.php
tests/dbal/db_tools_test.php
tests/functional/acp_profile_field_test.php

Needs different patch for develop.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13282

[ticket/13282] Use 0 as default for integer type columns in postgresql

---

tests/test_framework/phpbb_functional_test_case.php

https://tracker.phpbb.com/browse/PHPBB3-12089

[ticket/12089] Add assert message on HTTP status code check

---

phpBB/download/file.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13414

[ticket/13414] Set Content-Length header only if status is not 304

---

phpBB/includes/search/fulltext_native.php

Cherry-picked from #3346
https://tracker.phpbb.com/browse/PHPBB3-12933

[ticket/12933] Handle case when * is last character of word

---

phpBB/adm/style/acp_update.html

https://tracker.phpbb.com/browse/PHPBB3-13554

[ticket/13554] Show feature release upgrades in blue rather than red.

---

phpBB/phpbb/controller/helper.php

https://tracker.phpbb.com/browse/PHPBB3-13553

[ticket/13553] Add a method to the controller helper to display a message

---

phpBB/phpbb/db/migration/tool/permission.php

https://tracker.phpbb.com/browse/PHPBB3-13544
PHPBB3-13544

[ticket/13544] Fixing wrong SQL query for permission_unset() for roles

---

phpBB/phpbb/file_downloader.php
phpBB/phpbb/version_helper.php

https://tracker.phpbb.com/browse/PHPBB3-13556
@marc1706

[ticket/13556] Fix exception translation with filedownloader

---

phpBB/phpbb/db/migration/data/v30x/release_3_0_13.php
phpBB/phpbb/db/migration/data/v30x/release_3_0_13_pl1.php

https://tracker.phpbb.com/browse/PHPBB3-13557

[ticket/13557] Add migrations for 3.0.13 and 3.0.13-PL1

---

build/build.xml
phpBB/docs/CHANGELOG.html
phpBB/includes/constants.php
phpBB/install/schemas/schema_data.sql
phpBB/phpbb/db/migration/data/v31x/v313rc2.php

[phpBB 3.1.3 RC2 released](https://area51.phpbb.com/phpBB/viewtopic.php?f=81&t=46871), but the develop-ascraeus doesn't contain the latest updates on the [prep-release-3.1.3] branch.

Update develop-ascraeus to 3.1.3-RC2

---

phpBB/phpbb/template/twig/extension.php
phpBB/phpbb/template/twig/lexer.php
phpBB/styles/prosilver/template/captcha_recaptcha.html
phpBB/styles/prosilver/template/memberlist_body.html
tests/template/template_test.php

https://tracker.phpbb.com/browse/PHPBB3-10388
PHPBB3-10388

Ticket/10388 Use Twig's JS escape filter instead of addslashes on LA_ keys

---

phpBB/includes/ucp/ucp_prefs.php

Update the event so extensions will be able to validate (and deny) changes.
PHPBB3-13542

[ticket/13542] Update core.ucp_prefs_personal_data to include $error

---

phpBB/includes/acp/acp_email.php

https://tracker.phpbb.com/browse/PHPBB3-13313

[ticket/13313] Add event core.acp_email_display

---

phpBB/includes/functions_user.php

Add core event to the function user_active_flip() in
includes/functions_user.php to allow checking/modifying activated/deactivated
users data before submitting it to the database.
Event request: http://area51.phpbb.com/phpBB/viewtopic.php?f=111&t=44941
<a href="https://tracker.phpbb.com/browse/PHPBB3-13336">PHPBB3-13336</a>.

[ticket/13336] Add core events to the function user_active_flip()

---

phpBB/includes/acp/acp_users.php
phpBB/includes/ucp/ucp_profile.php

Event request: http://area51.phpbb.com/phpBB/viewtopic.php?f=111&t=33744
<a href="https://tracker.phpbb.com/browse/PHPBB3-13536">PHPBB3-13536</a>.

[ticket/13536] Add ACP/UCP core events to allow modifying user profile data on editing

---

phpBB/includes/functions_posting.php
phpBB/includes/mcp/mcp_topic.php

Added event core.topic_review_modify_row in function topic_review() in
functions_posting for modifying template data blocks for topic reviews.
PHPBB3-13540

[ticket/13540] Add core event for modifying topic review block data

---

phpBB/composer.json
phpBB/composer.lock
phpBB/phpbb/template/asset.php
tests/template/template_includecss_test.php

dev dependencies not updated
https://tracker.phpbb.com/browse/PHPBB3-13139
PHPBB3-13139

[ticket/13139] Update Twig to 1.18.0

---

phpBB/download/file.php
phpBB/includes/acp/acp_attachments.php
phpBB/includes/compatibility_globals.php
phpBB/includes/functions.php
phpBB/includes/functions_admin.php
phpBB/includes/functions_compatibility.php
phpBB/includes/functions_posting.php
phpBB/includes/functions_privmsgs.php
phpBB/includes/functions_user.php
phpBB/includes/mcp/mcp_main.php
phpBB/includes/mcp/mcp_topic.php
phpBB/install/database_update.php
phpBB/install/install_convert.php
phpBB/install/install_install.php
phpBB/install/install_update.php
tests/content_visibility/delete_post_test.php
tests/functions_user/delete_user_test.php
tests/notification/submit_post_base.php
tests/notification/user_list_trim_test.php
tests/test_framework/phpbb_functional_test_case.php

https://tracker.phpbb.com/browse/PHPBB3-13496
PHPBB3-13496

[ticket/13496] Change set_config_count() calls with $config->increment()

---

phpBB/feed.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13348

[ticket/13348] Use close method to free query result handle

---

phpBB/phpbb/file_downloader.php

https://tracker.phpbb.com/browse/PHPBB3-13588
PHPBB3-13588

[ticket/13588] Fixes wrong message in info fsockopen() disabled

---

phpBB/develop/create_schema_files.php
phpBB/develop/mysql_upgrader.php
phpBB/includes/acp/acp_database.php
phpBB/includes/functions_install.php
phpBB/install/convertors/functions_phpbb20.php
phpBB/install/install_install.php
phpBB/phpbb/captcha/plugins/qa.php
phpBB/phpbb/db/tools/factory.php
phpBB/phpbb/db/tools/mssql.php
phpBB/phpbb/db/tools/tools.php
phpBB/phpbb/search/fulltext_sphinx.php
tests/dbal/auto_increment_test.php
tests/dbal/db_tools_test.php
tests/dbal/migrator_test.php
tests/extension/manager_test.php
tests/extension/metadata_manager_test.php
tests/migrator/convert_timezones_test.php
tests/migrator/schema_generator_test.php
tests/notification/convert_test.php
tests/test_framework/phpbb_database_test_case.php
tests/test_framework/phpbb_database_test_connection_manager.php
tests/test_framework/phpbb_functional_test_case.php

PHPBB3-10748
Surely the final implementation can be improved even more, but the first task is to reduce the size of tools.php
**PS:** Do NOT close the ticket on merge

[ticket/10748] Split MS SQL from the db tools file into it's own

---

phpBB/develop/add_permissions.php
phpBB/includes/acp/acp_profile.php
phpBB/includes/functions_content.php
phpBB/includes/functions_messenger.php
phpBB/includes/functions_privmsgs.php
phpBB/includes/functions_user.php
phpBB/install/install_convert.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13597

[ticket/13597] Modify variable-variable syntax to be compatible with PHP7

---

phpBB/includes/functions_compatibility.php
phpBB/includes/functions_install.php
phpBB/install/install_convert.php

https://tracker.phpbb.com/browse/PHPBB3-13497
https://tracker.phpbb.com/browse/PHPBB3-9907
PHPBB3-13497

[ticket/13497] Change get_tables() calls with $db_tools->sql_list_tables()

---

phpBB/styles/subsilver2/template/ucp_avatar_options_local.html

Avatar Gallery shows categories but no images in subsilver2.
The ID was not specified in the template. Also, the correct parent template
loop is called avatar_local_row and not avatar_local_col.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13615

[ticket/13615] Correctly display images for gallery avatar in subsilver2

---

phpBB/config/default/container/services_db.yml
phpBB/includes/acp/acp_profile.php
phpBB/phpbb/db/tools/factory.php
phpBB/phpbb/db/tools/mssql.php
phpBB/phpbb/db/tools/postgres.php
phpBB/phpbb/db/tools/tools.php

PHPBB3-10748
Surely the final implementation can be improved even more, but the first task is to reduce the size of tools.php
**PS:** Do NOT close the ticket on merge

[ticket/10748][Part2] Split postgres DB tools into it's own class

---

build/build.xml

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13619

[ticket/13619] Remove unneeded files and folders from vendor in release package

---

phpBB/language/en/help_faq.php

[PHPBB3-13618](https://tracker.phpbb.com/browse/PHPBB3-13618)

[ticket/13618] Small grammatical typo in the English FAQ

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/ucp_profile_profile_info.html
phpBB/styles/prosilver/template/ucp_profile_reg_details.html
phpBB/styles/subsilver2/template/ucp_profile_profile_info.html
phpBB/styles/subsilver2/template/ucp_profile_reg_details.html

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13628
Replaces #3419

[ticket/13628] Allow ability for extension to add entries to user's profile

---

phpBB/faq.php

https://tracker.phpbb.com/browse/PHPBB3-13600

[ticket/13600] Allow extensions to create a custom help page

---

README.md

https://tracker.phpbb.com/browse/PHPBB3-13634
PHPBB3-13634

[ticket/13634] Update branch names on README

---

phpBB/includes/ucp/ucp_profile.php

Missing sql_ary in event
PHPBB3-13635

[ticket/13635] Add sql_ary to ucp profile event

---

phpBB/phpbb/content_visibility.php

I don't get this... I was positive I, at some point, had it right... I don't getwhat happened...
https://tracker.phpbb.com/browse/PHPBB3-13631
PHPBB3-13631

[ticket/13631] Fix wrong variable in get_global_visibility_sql()'s event

---

phpBB/phpbb/content_visibility.php
phpBB/phpbb/notification/manager.php

https://tracker.phpbb.com/browse/PHPBB3-13644
PHPBB3-13644

[ticket/13644] Always type hint dispatch_interface

---

phpBB/phpbb/auth/provider/ldap.php

[PHPBB3-13551](https://tracker.phpbb.com/browse/PHPBB3-13551)

[ticket/13551] Fix incorrectly named template variable: AUTH_LDAP_DN

---

phpBB/includes/ucp/ucp_register.php

https://tracker.phpbb.com/browse/PHPBB3-13578

[ticket/13578] Add ucp_register.php core events

---

phpBB/phpbb/event/kernel_terminate_subscriber.php

https://tracker.phpbb.com/browse/PHPBB3-13643
PHPBB3-13643

[ticket/13643] Change the priority of kernel_terminate_subscriber to -10000

---

phpBB/includes/acp/acp_prune.php

Fix SQL syntax errors
PHPBB3-13587

[ticket/13587] SQL syntax errors in get_prune_users()

---

phpBB/includes/ucp/ucp_profile.php

You can change data on profile but can not generate an event to check input (eg, run it through the validate phpBB function) on that change.
PHPBB3-13650

[ticket/13650] Validate ucp profile data changes

---

phpBB/styles/subsilver2/template/memberlist_body.html

The PM link was intentionally dropped due to excessive query requirements, thus the column is without purpose now. See PHPBB3-13229
[PHPBB3-13563](https://tracker.phpbb.com/browse/PHPBB3-13563)

[ticket/13563] Remove PM column from subsilver2's memberlist_body.html.

---

phpBB/includes/functions_mcp.php

https://tracker.phpbb.com/browse/PHPBB3-13655
PHPBB3-13652

[ticket/13652] Added $phpbb_dispatcher from global to phpbb_mcp_sorting()

---

phpBB/styles/prosilver/template/forumlist_body.html
phpBB/styles/subsilver2/template/forumlist_body.html

[PHPBB3-13649](https://tracker.phpbb.com/browse/PHPBB3-13649)

[ticket/13649] Fix incorrect subforum tooltip title when unread.

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/viewtopic_body.html
phpBB/styles/subsilver2/template/viewtopic_body.html

Add a new template event within viewtopic body directly after the pagination
PHPBB3-13510

[ticket/13510] Add template even viewtopic_body_pagination_after

---

phpBB/includes/session.php

https://tracker.phpbb.com/browse/PHPBB3-13617
Ascraeus version at https://github.com/phpbb/phpbb/pull/3444

[ticket/13617] Enforce column size limit for session_forum_id

---

phpBB/styles/prosilver/template/mcp_logs.html
phpBB/styles/prosilver/template/mcp_notes_user.html
phpBB/styles/prosilver/template/ucp_profile_autologin_keys.html
phpBB/styles/prosilver/theme/common.css
phpBB/styles/subsilver2/template/ucp_profile_autologin_keys.html
phpBB/styles/subsilver2/theme/stylesheet.css

[ticket/13590] Headers of remember me login keys are not centered

---

.travis.yml

https://tracker.phpbb.com/browse/PHPBB3-13657

[ticket/13657] Run travis builds on PHP 7.0

---

phpBB/phpbb/cache/driver/file.php

[ticket/13477] Update file cache driver for extension paths

---

phpBB/styles/prosilver/theme/buttons.css

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13667

[ticket/13667] Fix buttons alignment in Chrome for Windows

---

tests/functional/common_avatar_test_case.php

https://tracker.phpbb.com/browse/PHPBB3-13670

[ticket/13670] Modify variable-variable syntax in common avatar test for PHP/

---

phpBB/assets/javascript/core.js

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13666

[ticket/13666] Remove data-clicked attribute from all of form's submit buttons

---

phpBB/includes/ucp/ucp_pm_compose.php

Add a new PHP event to ucp_pm_compose to alter the default vars
PHPBB3-13637

[ticket/13637] Add core.ucp_pm_compose_alter_vars PHP event

---

phpBB/includes/functions_mcp.php

Followup to:
https://github.com/phpbb/phpbb/pull/3197
Placing the event in a more meaningful place.
Requires
#3447
to work.
https://tracker.phpbb.com/browse/PHPBB3-13142

[ticket/13142] Before query to get the total number of reports

---

phpBB/adm/style/acp_users_profile.html
phpBB/docs/events.md
phpBB/includes/acp/acp_users.php

for acp users profile
PHPBB3-13675

[ticket/13675] Add validate to acp_profile event and add template events

---

phpBB/phpbb/template/twig/twig.php
tests/template/template_test.php
tests/template/templates/loop_advanced_twig.html
tests/template/templates/loop_expressions.html
tests/template/templates/loop_expressions_twig.html
tests/template/templates/loop_expressions_twig2.html
tests/template/templates/loop_include1_twig.html
tests/template/templates/loop_include_twig.html
tests/template/templates/loop_nested2_twig.html
tests/template/templates/loop_nested_deep_multilevel_ref_twig.html
tests/template/templates/loop_nested_include1_twig.html
tests/template/templates/loop_nested_include_twig.html
tests/template/templates/loop_nested_multilevel_ref_twig.html
tests/template/templates/loop_nested_twig.html
tests/template/templates/loop_reuse_twig.html
tests/template/templates/loop_size_twig.html
tests/template/templates/loop_twig.html
tests/template/templates/loop_underscore_twig.html
tests/template/templates/loop_vars_twig.html

https://tracker.phpbb.com/browse/PHPBB3-13132
PHPBB3-13132

[ticket/13132] Twig: Add the loops content to the root context

---

phpBB/includes/ucp/ucp_profile.php

Move core event and rename other
PHPBB3-13650

[ticket/13650] Move core event

---

phpBB/styles/prosilver/theme/bidi.css

[PHPBB3-13463](https://tracker.phpbb.com/browse/PHPBB3-13463)

[ticket/13463] Correctly position notification mark read icon in RTL.

---

phpBB/adm/style/install_header.html
phpBB/adm/style/install_update_diff.html
phpBB/adm/style/overall_header.html
phpBB/adm/style/simple_header.html
phpBB/styles/prosilver/template/overall_header.html
phpBB/styles/prosilver/template/simple_header.html

https://tracker.phpbb.com/browse/PHPBB3-13702

[ticket/13702] Add initial-scale to viewport in page header

---

phpBB/phpbb/captcha/plugins/captcha_abstract.php

[ticket/13718] Added missing global declaration

---

phpBB/includes/acp/acp_search.php

https://tracker.phpbb.com/browse/PHPBB3-13719

[ticket/13719] Remove superfluous $search_options in acp_search.

---

phpBB/web.config

Fix by german user Tecwar from phpBB.de: https://www.phpbb.de/community/viewtopic.php?f=150&t=232730
[PHPBB3-13271](https://tracker.phpbb.com/browse/PHPBB3-13271)

[ticket/13271] Fix URL Rewriting on IIS7

---

phpBB/includes/functions.php

[PHPBB3-13698](https://tracker.phpbb.com/browse/PHPBB3-13698)

[ticket/13698] Pass parameters for link in LOGIN_ERROR_PASSWORD error message.

---

phpBB/docs/AUTHORS

https://tracker.phpbb.com/browse/PHPBB3-13723
PHPBB3-13723

[ticket/13723] Add Elsensee to authors list

---

phpBB/phpbb/db/tools/tools.php
phpBB/phpbb/event/kernel_exception_subscriber.php
phpBB/phpbb/event/kernel_terminate_subscriber.php
phpBB/phpbb/notification/type/admin_activate_user.php
phpBB/phpbb/notification/type/approve_post.php
phpBB/phpbb/notification/type/approve_topic.php
phpBB/phpbb/notification/type/base.php
phpBB/phpbb/notification/type/bookmark.php
phpBB/phpbb/notification/type/disapprove_post.php
phpBB/phpbb/notification/type/disapprove_topic.php
phpBB/phpbb/notification/type/group_request.php
phpBB/phpbb/notification/type/group_request_approved.php
phpBB/phpbb/notification/type/pm.php
phpBB/phpbb/notification/type/post.php
phpBB/phpbb/notification/type/post_in_queue.php
phpBB/phpbb/notification/type/quote.php
phpBB/phpbb/notification/type/report_pm.php
phpBB/phpbb/notification/type/report_post.php
phpBB/phpbb/notification/type/topic.php
phpBB/phpbb/notification/type/topic_in_queue.php
phpBB/phpbb/notification/type/type_interface.php

https://tracker.phpbb.com/browse/PHPBB3-13725
PHPBB3-13725

[ticket/13725] Coding guidelines: static public

---

phpBB/styles/prosilver/template/forum_fn.js

https://tracker.phpbb.com/browse/PHPBB3-13727

[ticket/13727] Fix JS that resizes breadcrumbs

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/overall_header.html
phpBB/styles/subsilver2/template/overall_header.html

Event for overall_header_navbar_before.html
Event Request: http://area51.phpbb.com/phpBB/viewtopic.php?p=274786#p274786
PHPBB3-13602

[ticket/13602] Adding a new event overall_header_navbar_before

---

build/sami-all.conf.php

https://tracker.phpbb.com/browse/PHPBB3-13738

[ticket/13738] Use new branch names in sami-all.conf.php.

---

phpBB/styles/prosilver/theme/bidi.css
phpBB/styles/prosilver/theme/buttons.css
phpBB/styles/prosilver/theme/common.css
phpBB/styles/prosilver/theme/content.css

https://tracker.phpbb.com/browse/PHPBB3-13741

Ticket/13741 Remove outdated comments and references in css files

---

phpBB/phpbb/db/migration/data/v310/avatars.php

Try to set the avatar type to string value to check if new avatar
types are supported.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-12368

[ticket/12368] Correctly check if avatars migration is installed

---

tests/captcha/qa_test.php

PHPBB3-13522
Follow up for #3333

[ticket/13522] Fix globals for 3.2 in Q&A tests

---

tests/functions_acp/validate_config_vars_test.php

https://tracker.phpbb.com/browse/PHPBB3-13747
PHPBB3-13747

[ticket/13747] Add assertions to test_validate_path_linux

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/posting_poll_body.html
phpBB/styles/subsilver2/template/posting_poll_body.html

Template event added for the poll options while posting a topic
so that you may add additional options for polls.
PHPBB3-13739

[ticket/13739] Add template core event posting_poll_body_options_after

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/posting_pm_layout.html

These events wrap the includes of posting_pm_header.html to add some
content before and after it.
https://tracker.phpbb.com/browse/PHPBB3-13701
PHPBB3-13701

[ticket/13701] Adds two new events to posting_pm_layout.html

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/posting_editor.html
phpBB/styles/subsilver2/template/posting_body.html

[PHPBB3-13710] (https://tracker/phpbb.com/browse/PHPBB3-13710)

[ticket/13710] Allow template events near smilies display

---

tests/controller/helper_route_slash_test.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13749

[ticket/13749] Add missing slash to base uri in helper route tests

---

phpBB/phpbb/plupload/plupload.php
tests/plupload/plupload_test.php

[PHPBB3-13756](https://tracker.phpbb.com/browse/PHPBB3-13756)

[ticket/13756] Fix resize after upload with plupload

---

phpBB/language/en/acp/extensions.php

Spelling error in extension.php file
[PHPBB3-13763] (https://tracker.phpbb.com/browse/PHPBB3-13763)

[ticket/13763] Fix typo in extension lang file

---

build/build.xml

[ticket/13767] Remove vendor/s9e/text-formatter/.git during build

---

phpBB/composer.lock

For context:
* https://github.com/phpbb/phpbb/pull/3541#issuecomment-95196634
* https://github.com/s9e/TextFormatter/commit/559f3c4def03e5fbbf5301198ccd69c91d902659

[ticket/13774] Update s9e\TextFormatter

---

phpBB/includes/functions.php
phpBB/includes/startup.php

https://tracker.phpbb.com/browse/PHPBB3-13765

[ticket/13765] Verify SERVER_PROTOCOL has the expected format before using it.

---

phpBB/includes/functions_upload.php
tests/upload/filespec_test.php

[PHPBB3-13755](https://tracker.phpbb.com/browse/PHPBB3-13755)

[ticket/13755] Ignore dots in path when determining file extension.

---

phpBB/language/en/captcha_recaptcha.php

https://tracker.phpbb.com/browse/PHPBB3-13778
PHPBB3-13778

[ticket/13778] Update wording of the reCaptcha instructions

---

travis/setup-webserver.sh

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13792

[ticket/13792] Use hhvm instead of manually installing nightlys for now

---

phpBB/config/default/container/services.yml
phpBB/includes/acp/acp_extensions.php
phpBB/phpbb/controller/exception.php
phpBB/phpbb/controller/resolver.php
phpBB/phpbb/extension/exception.php
phpBB/phpbb/extension/manager.php
phpBB/phpbb/extension/metadata_manager.php
phpBB/phpbb/notification/exception.php
phpBB/phpbb/notification/manager.php
tests/controller/controller_test.php
tests/dbal/migrator_test.php
tests/extension/manager_test.php
tests/extension/metadata_manager_test.php
tests/test_framework/phpbb_functional_test_case.php

[PHPBB3-13793](https://tracker.phpbb.com/browse/PHPBB3-13793)

[ticket/13793] Remove translation on throwing exceptions

---

.travis.yml
tests/lint_test.php
travis/phpunit-mysqli-travis.xml

Replaces #3587 so it's on 3.1 aswell
https://tracker.phpbb.com/browse/PHPBB3-13809

[ticket/13809] Perform the lint test prior to normal tests

---

phpBB/language/en/migrator.php

https://tracker.phpbb.com/browse/PHPBB3-11521
PHPBB3-11521

[ticket/11521] Add missing lang strings for migration exceptions

---

travis/check-image-icc-profiles.sh

https://tracker.phpbb.com/browse/PHPBB3-13516
Appears to work: https://travis-ci.org/phpbb-extensions/collapsible-categories/builds/60437862
Verified it fails before this change: https://travis-ci.org/phpbb-extensions/collapsible-categories/builds/60441272
PHPBB3-13516

[ticket/13516] Do not search ICC profiles in extension vendors

---

phpBB/config/default/container/services_twig.yml
phpBB/includes/bbcode.php
phpBB/includes/functions_messenger.php
phpBB/install/index.php
phpBB/phpbb/template/asset.php
phpBB/phpbb/template/twig/environment.php
phpBB/phpbb/template/twig/node/includeasset.php
tests/controller/common_helper_route.php
tests/extension/metadata_manager_test.php
tests/template/asset_test.php
tests/template/template_allfolder_test.php
tests/template/template_events_test.php
tests/template/template_includecss_test.php
tests/template/template_test_case.php
tests/template/template_test_case_with_tree.php

https://tracker.phpbb.com/browse/PHPBB3-13638
PHPBB3-13638

[ticket/13638] Prepend the assets path phpbb root

---

phpBB/includes/acp/acp_database.php
phpBB/includes/mcp/mcp_reports.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13819
Replaces https://github.com/phpbb/phpbb/pull/3594

[ticket/13819] Add missing sql_freeresult() to files in includes/

---

phpBB/develop/export_events_for_wiki.php
phpBB/includes/ucp/ucp_prefs.php
phpBB/phpbb/event/md_exporter.php
phpBB/phpbb/event/php_exporter.php

https://tracker.phpbb.com/browse/PHPBB3-13807

Ticket/13807 Allow building changesets for the event list

---

phpBB/viewtopic.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-13745">PHPBB3-13745</a>.

[ticket/13745] Add viewtopic.php core event to allow manipulating poll data

---

tests/text_processing/tickets_data/PHPBB3-13425.html
tests/text_processing/tickets_data/PHPBB3-13425.txt
tests/text_processing/tickets_data/PHPBB3-13425.xml

https://tracker.phpbb.com/browse/PHPBB3-13425
https://area51.phpbb.com/phpBB/viewtopic.php?f=7&t=46515

[ticket/13425] Smiley code at start of text being quoted doesn't show smiley image in quote

---

tests/text_processing/tickets_data/PHPBB3-9073.html
tests/text_processing/tickets_data/PHPBB3-9073.txt
tests/text_processing/tickets_data/PHPBB3-9073.xml

https://tracker.phpbb.com/browse/PHPBB3-9073

[ticket/9073] Word censoring in URLs

---

tests/text_processing/tickets_data/PHPBB3-10268.html
tests/text_processing/tickets_data/PHPBB3-10268.txt

PHPBB3-10268 got fixed by PHPBB3-11768
https://tracker.phpbb.com/browse/PHPBB3-10268

[ticket/10268] Added regression test

---

phpBB/includes/mcp/mcp_front.php

https://tracker.phpbb.com/browse/PHPBB3-13660

[ticket/13660] Allow changing the query for total reports in mcp_front

---

phpBB/phpbb/permissions.php

https://tracker.phpbb.com/browse/PHPBB3-13822
PHPBB3-13822

[ticket/13822] Correctly display softdelete and post detail perms

---

phpBB/includes/mcp/mcp_front.php

https://tracker.phpbb.com/browse/PHPBB3-13664

[ticket/13664] Add event to allow changing number of unapproved posts in mcp_front

---

phpBB/viewonline.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-13752">PHPBB3-13752</a>.

[ticket/13752] Add viewonline.php core event to allow modifying forum data SQL

---

phpBB/includes/functions_posting.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13825

[ticket/13825] Correctly call phpbb_filesystem in create_thumbnail

---

build/code_sniffer/phpbb/Sniffs/Namespaces/UnusedUseSniff.php

https://tracker.phpbb.com/browse/PHPBB3-13830
PHPBB3-13830

[ticket/13830] Check class used in catch statements

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/viewforum_body.html
phpBB/styles/subsilver2/template/viewforum_body.html

[PHPBB3-13699] (https://tracker.phpbb.com/browse/PHPBB3-13699)

[ticket/13699] Add event before and after forum title in viewforum

---

phpBB/config/default/container/services.yml
phpBB/config/default/container/services_routing.yml
phpBB/phpbb/routing/router.php
tests/controller/common_helper_route.php
tests/controller/controller_test.php
tests/pagination/pagination_test.php

[PHPBB3-13800](https://tracker.phpbb.com/browse/PHPBB3-13800)

[ticket/13800] Make router's extension manager dependency optional

---

phpBB/config/default/container/services.yml
phpBB/config/default/container/services_twig.yml
phpBB/includes/bbcode.php
phpBB/includes/functions_messenger.php
phpBB/install/index.php
phpBB/phpbb/template/exception/user_object_not_available.php
phpBB/phpbb/template/twig/twig.php
tests/controller/common_helper_route.php
tests/extension/metadata_manager_test.php
tests/template/template_allfolder_test.php
tests/template/template_events_test.php
tests/template/template_includecss_test.php
tests/template/template_test_case.php
tests/template/template_test_case_with_tree.php

[PHPBB3-13804](https://tracker.phpbb.com/browse/PHPBB3-13804)

[ticket/13804] Make template's user dependency optional

---

phpBB/includes/functions_content.php
tests/text_processing/generate_text_for_storage_test.php

https://tracker.phpbb.com/browse/PHPBB3-13805

[ticket/13805] Updated generate_text_for_storage() to match message_parser

---

build/code_sniffer/phpbb/Sniffs/Namespaces/UnusedUseSniff.php

https://tracker.phpbb.com/browse/PHPBB3-13830
PHPBB3-13830

[ticket/13830] Fix unsused used statements and catch blocks

---

tests/template/asset_test.php

https://tracker.phpbb.com/browse/PHPBB3-13839
PHPBB3-13839

[ticket/13839] Don't be dependent on the phpBB root directory name in tests

---

phpBB/config/default/container/services_twig.yml
phpBB/config/development/config.yml
phpBB/phpbb/di/extension/container_configuration.php
phpBB/phpbb/di/extension/core.php
phpBB/phpbb/template/twig/environment.php
tests/di/fixtures/config/test/container/environment.yml
tests/di/fixtures/other_config/test/container/environment.yml

https://tracker.phpbb.com/browse/PHPBB3-12632
https://tracker.phpbb.com/browse/PHPBB3-13206
PHPBB3-13206
PHPBB3-12632

[ticket/12632] Add twig.debug and twig.auto_reload in config.yml

---

build/code_sniffer/phpbb/Sniffs/ControlStructures/OpeningBraceBsdAllmanSniff.php
build/code_sniffer/ruleset-minimum.xml
phpBB/includes/acp/acp_board.php
phpBB/phpbb/auth/provider/oauth/token_storage.php
phpBB/phpbb/template/twig/loader.php
phpBB/phpbb/template/twig/node/definenode.php
phpBB/phpbb/template/twig/node/includephp.php
phpBB/phpbb/template/twig/tokenparser/defineparser.php
phpBB/phpbb/template/twig/tokenparser/includephp.php

https://tracker.phpbb.com/browse/PHPBB3-13838
PHPBB3-13838

[ticket/13838] Check braces for control structures

---

phpBB/phpbb/controller/helper.php

https://tracker.phpbb.com/browse/PHPBB3-13827

[ticket/13827] Correctly return JSON instead of HTML when valled from AJAX

---

phpBB/includes/acp/acp_bbcodes.php
phpBB/includes/functions.php
phpBB/includes/functions_compatibility.php
phpBB/includes/functions_user.php
tests/regex/censor_test.php

Previous PR: https://github.com/phpbb/phpbb/pull/3399

[ticket/13614] Removed code that relies on phpbb_pcre_utf8_support()

---

phpBB/config/default/container/services_text_formatter.yml
phpBB/includes/message_parser.php
phpBB/phpbb/textformatter/parser_interface.php
phpBB/phpbb/textformatter/s9e/parser.php
tests/test_framework/phpbb_test_case_helpers.php
tests/text_formatter/s9e/parser_test.php

https://tracker.phpbb.com/browse/PHPBB3-13801
This PR depends on https://tracker.phpbb.com/browse/PHPBB3-13802

[ticket/13801] Remove user dependency from text_formatter.s9e.parser

---

tests/text_processing/tickets_data/PHPBB3-13641.html
tests/text_processing/tickets_data/PHPBB3-13641.txt
tests/text_processing/tickets_data/PHPBB3-13641.xml

https://tracker.phpbb.com/browse/PHPBB3-13641
https://www.phpbb.com/community/viewtopic.php?f=438&t=2298266

[ticket/13641] Proper parsing of custom BBCode for inline code

---

phpBB/config/default/container/services_notification.yml
phpBB/phpbb/notification/type/quote.php
phpBB/phpbb/textformatter/s9e/utils.php
phpBB/phpbb/textformatter/utils_interface.php
tests/notification/base.php
tests/notification/manager_helper.php
tests/notification/submit_post_base.php
tests/notification/submit_post_type_quote_test.php
tests/text_formatter/s9e/utils_test.php

Added get_quote_authors() to text_formatter.utils service to retrieve the names used in first-level quotes.
https://tracker.phpbb.com/browse/PHPBB3-13680

[ticket/13680] Updated quote notifications

---

phpBB/phpbb/routing/router.php

https://tracker.phpbb.com/browse/PHPBB3-13829
PHPBB3-13829

[ticket/13829] Don't fail if the cache isn't writeable

---

phpBB/phpbb/db/migration/data/v310/style_update_p1.php

https://tracker.phpbb.com/browse/PHPBB3-13861
PHPBB3-13861

[ticket/13861] Fix undefined variables in style update migration

---

phpBB/bin/phpbbcli.php

https://tracker.phpbb.com/browse/PHPBB3-13769

[ticket/13769] Move environment check in phpbbcli.php lower

---

phpBB/includes/functions_module.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-13868">PHPBB3-13868</a>.

[ticket/13868] Correctly handle acp/mcp/ucp modules lang files for extensions

---

phpBB/includes/bbcode.php
phpBB/includes/message_parser.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-13648">PHPBB3-13648</a>.

[ticket/13648] Allow extensions using custom bbcode validation methods

---

phpBB/install/database_update.php

[PHPBB3-13871](https://tracker.phpbb.com/browse/PHPBB3-13871)

Fix call to undefined member function when running database_update.php

---

phpBB/docs/events.md

[ticket/13808] Fix version

---

phpBB/phpbb/log/log.php

https://tracker.phpbb.com/browse/PHPBB3-13661

[ticket/13661] Add event to allow editing the queries used to get the logs

---

phpBB/includes/mcp/mcp_reports.php

https://tracker.phpbb.com/browse/PHPBB3-13668

[ticket/13668] Allow changing the query to obtain the user-submitted report

---

phpBB/includes/mcp/mcp_reports.php

https://tracker.phpbb.com/browse/PHPBB3-13672

[ticket/13672] Allow changing the data from the user-submitted report

---

phpBB/assets/javascript/core.js
phpBB/assets/javascript/editor.js
phpBB/styles/prosilver/theme/colours.css
phpBB/styles/prosilver/theme/forms.css

Ticket: https://tracker.phpbb.com/browse/PHPBB3-12542
Video: https://www.m-a-styles.de/download/drag_n_drop.mp4
Works for both posts and private messages if the attachment tab exists (attachments are enabled).

[ticket/12542] Highlight textarea when files are dragged onto editor

---

phpBB/phpbb/event/md_exporter.php
phpBB/phpbb/event/php_exporter.php
tests/event/fixtures/normal_events.md.test
tests/event/md_exporter_test.php

https://tracker.phpbb.com/browse/PHPBB3-13872

[ticket/13872] Allow template events to have a changed version

---

phpBB/styles/prosilver/template/overall_header.html

I also made the other stylesheets work on all devices. In addition to being effort to fix, the print stylesheet was hurting performance.
https://tracker.phpbb.com/browse/PHPBB3-13873

[ticket/13873] Removed broken print stylesheet.

---

phpBB/styles/prosilver/theme/common.css

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13878

[ticket/13878] Display background images when printing topic in webkit

---

phpBB/assets/javascript/plupload.js

[PHPBB3-13858](https://tracker.phpbb.com/browse/PHPBB3-13858)

[ticket/13858] Make Plupload uploader available in the global namespace.

---

phpBB/bin/phpbbcli.php
phpBB/common.php
phpBB/download/file.php
phpBB/install/database_update.php
phpBB/install/index.php
phpBB/install/install_convert.php
phpBB/install/install_install.php
phpBB/install/install_update.php
phpBB/phpbb/di/container_builder.php
tests/di/create_container_test.php
tests/di/fixtures/config.php
tests/di/fixtures/config/production/config.yml
tests/di/fixtures/config/production/container/environment.yml

https://tracker.phpbb.com/browse/PHPBB3-13770
blocked by #3605 
PHPBB3-13770

[ticket/13770] Wither interface for container_builder

---

tests/event/md_exporter_test.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13872
PHPBB3-13872

[ticket/13872] Remove subsilver2 from md exporter test

---

phpBB/phpbb/textformatter/s9e/parser.php
tests/text_processing/message_parser_test.php

https://tracker.phpbb.com/browse/PHPBB3-13860

[ticket/13860] Fixed array-to-string conversion

---

tests/di/fixtures/config/production/container/environment.yml

https://tracker.phpbb.com/browse/PHPBB3-13890
PHPBB3-13890

[ticket/13890] Fix di tests

---

tests/lint_test.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13875

[ticket/13875] Ignore cache, ext, and store folder in lint test

---

phpBB/assets/javascript/core.js

https://tracker.phpbb.com/browse/PHPBB3-13771
PHPBB3-13771

[ticket/13771] Allow AJAX errors to support exceptions messages

---

phpBB/phpbb/language/language_file_loader.php

https://tracker.phpbb.com/browse/PHPBB3-13896

Fix conding style

---

phpBB/assets/javascript/core.js
phpBB/assets/javascript/editor.js
phpBB/assets/javascript/plupload.js
phpBB/styles/prosilver/template/ajax.js
phpBB/styles/subsilver2/template/posting_body.html

https://tracker.phpbb.com/browse/PHPBB3-13887

JS Refactoring

---

build/sami-all.conf.php

https://tracker.phpbb.com/browse/PHPBB3-13874

[ticket/13874] Add master to sami API docs

---

phpBB/config/default/container/services_routing.yml
phpBB/phpbb/routing/router.php
tests/controller/common_helper_route.php
tests/controller/controller_test.php
tests/controller/ext/vendor2/foo/config/routing.yml
tests/pagination/pagination_test.php

https://tracker.phpbb.com/browse/PHPBB3-13388
PHPBB3-13388

[ticket/13388] Integrate routing and di parameters resolution

---

phpBB/assets/javascript/core.js
phpBB/styles/prosilver/template/overall_footer.html

https://tracker.phpbb.com/browse/PHPBB3-13905

[ticket/13905] Don't load loading.gif until needed.

---

phpBB/includes/functions_user.php
phpBB/phpbb/auth/provider/base.php
phpBB/phpbb/auth/provider/oauth/oauth.php
phpBB/phpbb/auth/provider/provider_interface.php
tests/functions/fixtures/user_delete.xml
tests/functions/user_delete_test.php
tests/functions_user/delete_user_test.php

Previous PR: #3364 
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13564

[ticket/13564] Unlink user accounts upon deleting user

---

phpBB/includes/functions_admin.php

[ticket/13841] Fix tests on 3.1 and master branch

---

tests/functions/user_delete_test.php

[ticket/13564] Fix user_delete_test on master

---

phpBB/adm/style/acp_jabber.html
phpBB/styles/prosilver/template/index_body.html
phpBB/styles/prosilver/template/login_body.html
phpBB/styles/prosilver/template/login_forum.html
phpBB/styles/prosilver/template/ucp_login_link.html
phpBB/styles/prosilver/template/ucp_profile_reg_details.html
phpBB/styles/prosilver/template/ucp_register.html
phpBB/styles/prosilver/template/viewforum_body.html
phpBB/styles/subsilver2/template/index_body.html
phpBB/styles/subsilver2/template/login_body.html
phpBB/styles/subsilver2/template/login_forum.html
phpBB/styles/subsilver2/template/ucp_login_link.html
phpBB/styles/subsilver2/template/ucp_profile_reg_details.html
phpBB/styles/subsilver2/template/ucp_register.html
phpBB/styles/subsilver2/template/viewforum_body.html

https://tracker.phpbb.com/browse/PHPBB3-13200
PHPBB3-13200

[ticket/13200] Disable autocomplete for sensitive input fields

---

phpBB/phpbb/passwords/driver/helper.php

https://tracker.phpbb.com/browse/PHPBB3-13917
PHPBB3-13917

[ticket/13917] Use hash_equals() if possible in password driver helper

---

phpBB/includes/functions_display.php

https://tracker.phpbb.com/browse/PHPBB3-9563
PHPBB3-9563

[ticket/9563] Do not show empty categories on index

---

tests/functions_acp/build_cfg_template_test.php

Fix tests on 3.1 and master branches
https://tracker.phpbb.com/browse/PHPBB3-13928

[ticket/sec-184] Fix tests

---

phpBB/includes/acp/acp_prune.php

This changes the line with non-whitespace changes, so the packaging script
should correctly detect them as changed and put the file into the update.
https://tracker.phpbb.com/browse/PHPBB3-13823

[ticket/13823] Remove the unnecessary brackets

---

phpBB/phpbb/search/fulltext_native.php

[PHPBB3-13888](https://tracker.phpbb.com/browse/PHPBB3-13888)
PR against the correct branch, replacing #3688.

[ticket/13888] Fix sql_freeresult() error on author searches

---

phpBB/styles/prosilver/theme/content.css

https://tracker.phpbb.com/browse/PHPBB3-13902

[ticket/13902] Increased CSS margin around quotes

---

phpBB/includes/ucp/ucp_pm_compose.php
phpBB/posting.php

3.1.x PR: #3663 
[PHPBB3-13833](https://tracker.phpbb.com/browse/PHPBB3-13833)

[ticket/13833] Prevent flooding if type=submit doesn't exist

---

phpBB/develop/search_fill.php
phpBB/includes/acp/acp_main.php
phpBB/includes/acp/acp_search.php
phpBB/includes/functions_admin.php
phpBB/includes/functions_posting.php
phpBB/includes/mcp/mcp_main.php
phpBB/includes/mcp/mcp_post.php
phpBB/install/install_convert.php
phpBB/install/install_install.php
phpBB/phpbb/search/fulltext_mysql.php
phpBB/phpbb/search/fulltext_native.php
phpBB/phpbb/search/fulltext_postgres.php
phpBB/phpbb/search/fulltext_sphinx.php
phpBB/search.php
tests/search/mysql_test.php
tests/search/native_test.php
tests/search/postgres_test.php

https://tracker.phpbb.com/browse/PHPBB3-13685

[ticket/13685] Allow modifying the query for mysql native fulltext search

---

phpBB/develop/search_fill.php
phpBB/includes/acp/acp_main.php
phpBB/includes/acp/acp_search.php
phpBB/includes/functions_admin.php
phpBB/includes/functions_posting.php
phpBB/includes/mcp/mcp_main.php
phpBB/includes/mcp/mcp_post.php
phpBB/install/install_convert.php
phpBB/install/install_install.php
phpBB/phpbb/search/fulltext_mysql.php
phpBB/phpbb/search/fulltext_native.php
phpBB/phpbb/search/fulltext_postgres.php
phpBB/phpbb/search/fulltext_sphinx.php
phpBB/search.php
tests/search/mysql_test.php
tests/search/native_test.php
tests/search/postgres_test.php

https://tracker.phpbb.com/browse/PHPBB3-13689

[ticket/13689] Allow modifying the query for postgres native fulltext search

---

phpBB/develop/search_fill.php
phpBB/includes/acp/acp_main.php
phpBB/includes/acp/acp_search.php
phpBB/includes/functions_admin.php
phpBB/includes/functions_posting.php
phpBB/includes/mcp/mcp_main.php
phpBB/includes/mcp/mcp_post.php
phpBB/install/install_convert.php
phpBB/install/install_install.php
phpBB/phpbb/search/fulltext_mysql.php
phpBB/phpbb/search/fulltext_native.php
phpBB/phpbb/search/fulltext_postgres.php
phpBB/phpbb/search/fulltext_sphinx.php
phpBB/search.php
tests/search/mysql_test.php
tests/search/native_test.php
tests/search/postgres_test.php

https://tracker.phpbb.com/browse/PHPBB3-13686

[ticket/13686] Allow modify query used for counting in fulltext_native

---

phpBB/develop/search_fill.php
phpBB/includes/acp/acp_main.php
phpBB/includes/acp/acp_search.php
phpBB/includes/functions_admin.php
phpBB/includes/functions_posting.php
phpBB/includes/mcp/mcp_main.php
phpBB/includes/mcp/mcp_post.php
phpBB/install/install_convert.php
phpBB/install/install_install.php
phpBB/phpbb/search/fulltext_mysql.php
phpBB/phpbb/search/fulltext_native.php
phpBB/phpbb/search/fulltext_postgres.php
phpBB/phpbb/search/fulltext_sphinx.php
phpBB/search.php
tests/search/mysql_test.php
tests/search/native_test.php
tests/search/postgres_test.php

https://tracker.phpbb.com/browse/PHPBB3-13691

[ticket/13691] Allow modifying the fulltext native search query for total results for author

---

phpBB/develop/search_fill.php
phpBB/includes/acp/acp_main.php
phpBB/includes/acp/acp_search.php
phpBB/includes/functions_admin.php
phpBB/includes/functions_posting.php
phpBB/includes/mcp/mcp_main.php
phpBB/includes/mcp/mcp_post.php
phpBB/install/install_convert.php
phpBB/install/install_install.php
phpBB/phpbb/search/fulltext_mysql.php
phpBB/phpbb/search/fulltext_native.php
phpBB/phpbb/search/fulltext_postgres.php
phpBB/phpbb/search/fulltext_sphinx.php
phpBB/search.php
tests/search/mysql_test.php
tests/search/native_test.php
tests/search/postgres_test.php

https://tracker.phpbb.com/browse/PHPBB3-13694

[ticket/13694] Allow modifying the Postgres native author search query for results

---

phpBB/develop/search_fill.php
phpBB/includes/acp/acp_main.php
phpBB/includes/acp/acp_search.php
phpBB/includes/functions_admin.php
phpBB/includes/functions_posting.php
phpBB/includes/mcp/mcp_main.php
phpBB/includes/mcp/mcp_post.php
phpBB/install/install_convert.php
phpBB/install/install_install.php
phpBB/phpbb/search/fulltext_mysql.php
phpBB/phpbb/search/fulltext_native.php
phpBB/phpbb/search/fulltext_postgres.php
phpBB/phpbb/search/fulltext_sphinx.php
phpBB/search.php
tests/search/mysql_test.php
tests/search/native_test.php
tests/search/postgres_test.php

https://tracker.phpbb.com/browse/PHPBB3-13693

[ticket/13693] Allow modifying the MySQL author search query

---

build/code_sniffer/phpbb/Sniffs/ControlStructures/OpeningParenthesisSniff.php
build/code_sniffer/ruleset-php-legacy.xml
build/code_sniffer/ruleset-php-strict.xml
phpBB/includes/acp/acp_database.php
phpBB/includes/acp/acp_extensions.php
phpBB/includes/acp/acp_styles.php
phpBB/includes/functions_convert.php
phpBB/includes/ucp/ucp_notifications.php
phpBB/phpbb/cache/driver/memcache.php
phpBB/phpbb/captcha/plugins/qa.php
phpBB/phpbb/log/log.php
phpBB/phpbb/search/fulltext_sphinx.php
phpBB/viewtopic.php

The codesniffer should check for a correct spacing between keywords like
if or foreach and its opening parenthesis.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13930
PHPBB3-13930

[ticket/13930] Check for correct spacing between keyword & parenthesis

---

phpBB/phpbb/tree/nestedset.php

https://tracker.phpbb.com/browse/PHPBB3-13941
PHPBB3-13941

[ticket/13941] Workaround to fix the bug on php 5.5 with sqlite3

---

phpBB/phpbb/user.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13942
PHPBB3-13942

[ticket/13942] Check if path to language file contains language path

---

phpBB/docs/CREDITS.txt

PHPBB3-13947
@CHItA Welcome to the devs, see https://wiki.phpbb.com/Git#Merging_to_3.1.x

[ticket/13947] Add CHItA to the list of developers

---

phpBB/assets/javascript/core.js
phpBB/includes/functions.php
phpBB/includes/functions_compatibility.php
phpBB/phpbb/notification/type/admin_activate_user.php
phpBB/phpbb/notification/type/group_request.php
phpBB/phpbb/notification/type/pm.php
phpBB/phpbb/notification/type/post.php
phpBB/phpbb/notification/type/report_pm.php
phpBB/phpbb/notification/type/report_pm_closed.php
phpBB/phpbb/notification/type/report_post.php
phpBB/phpbb/notification/type/report_post_closed.php
phpBB/phpbb/notification/type/topic.php
phpBB/phpbb/user_loader.php

This moves them further down the waterfall, making the page load
quicker.
sorry for my crap php
https://tracker.phpbb.com/browse/PHPBB3-13882

[ticket/13882] Lazy load the notification avatars.

---

phpBB/docs/events.md

Reordered alphabetically (mcp before memberlist).
PHPBB3-13931

[ticket/13931] Wrong order in docs/events.md

---

phpBB/phpbb/di/container_builder.php

Replacement of the path creation based on a blacklist by a md5 filename to
support broader configurations
https://tracker.phpbb.com/browse/PHPBB3-13903
Replaces #3672

[ticket/13903] Replacing regexp path naming for container by md5.

---

phpBB/adm/style/acp_permissions.html
phpBB/adm/style/admin.css
phpBB/adm/style/permission_mask.html
phpBB/adm/style/tooltip.js
phpBB/includes/acp/auth.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-6466
PHPBB3-6466

[ticket/6466] Use jQuery and custom dropdown for permission roles tooltips

---

phpBB/styles/prosilver/theme/content.css

[ticket/13946] Increase the CSS margin around [code] and [list]

---

phpBB/includes/functions.php

Fixes an issue left out in https://github.com/phpbb/phpbb/pull/3653
PHPBB3-13882

[ticket/13882] Add lazy load avatars to phpbb avatar wrappers

---

phpBB/styles/prosilver/theme/buttons.css
phpBB/styles/prosilver/theme/common.css
phpBB/styles/prosilver/theme/cp.css

We're using ems basically everywhere else so ¯\\\_(ツ)_/¯
This will make it much easier for people to change the font-size of their board. I can now double the size of all the text in my board by just increasing the font-size of the body.
https://tracker.phpbb.com/browse/PHPBB3-13879

[ticket/13879] Replaced px with em where appropriate.

---

phpBB/styles/prosilver/template/memberlist_search.html

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13949
PHPBB3-13949

[ticket/13949] Replace colon with colon lang key in memberlist search page

---

phpBB/config/cron.yml
phpBB/phpbb/cron/task/core/tidy_search.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-13952">PHPBB3-13952</a>.

[ticket/13952] Inject event dispatcher dependency to the tidy search cron task

---

phpBB/composer.lock
tests/text_processing/tickets_data/PHPBB3-13921.html
tests/text_processing/tickets_data/PHPBB3-13921.txt
tests/text_processing/tickets_data/PHPBB3-13921.xml

https://tracker.phpbb.com/browse/PHPBB3-13921
https://area51.phpbb.com/phpBB/viewtopic.php?f=126&t=47976

[ticket/13921] Fix block BBCodes inside of inline BBCodes

---

phpBB/includes/ucp/ucp_pm_compose.php
phpBB/phpbb/textformatter/s9e/utils.php
phpBB/posting.php
tests/functional/private_messages_test.php
tests/text_formatter/s9e/default_formatting_test.php
tests/text_formatter/s9e/utils_test.php

https://tracker.phpbb.com/browse/PHPBB3-13901
This adds newlines in and around quotes in the posting form. This has no effect on the quote as it's displayed.

[ticket/13901] Add more whitespace to long quotes for readability

---

phpBB/includes/mcp/mcp_queue.php

...can get bigger than screen size.
[PHPBB3-13962] (https://tracker.phpbb.com/browse/PHPBB3-13962)

[ticket/13962] MCP Queue dropdown for forum selection

---

phpBB/styles/prosilver/template/forum_fn.js

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13951
PHPBB3-13951

[ticket/13951] Make sure the page number is an integer

---

phpBB/phpbb/textformatter/s9e/factory.php
tests/text_formatter/s9e/default_formatting_test.php

[ticket/13970] Save the value of the optional [code] parameter

---

phpBB/includes/message_parser.php
phpBB/posting.php
tests/functional/posting_test.php

https://tracker.phpbb.com/browse/PHPBB3-13880
Same behaviour as 3.2.

[ticket/13880] Automatically remove quotes that are nested too deep

---

phpBB/phpbb/console/command/reparser/reparse.php

[ticket/13891] Fix CS for code sniffer

---

phpBB/composer.lock
tests/text_processing/tickets_data/PHPBB3-10989.html

https://tracker.phpbb.com/browse/PHPBB3-13985

[ticket/13985] Updated s9e\TextFormatter

---

phpBB/styles/prosilver/template/overall_header.html
phpBB/styles/prosilver/template/simple_header.html

Fix overall_header's WebFontConfig section to load fonts correctly
in all browsers.
PHPBB3-13955

[ticket/13955] Fix WebFontConig to load web fonts correctly

---

phpBB/language/en/cli.php
phpBB/phpbb/console/command/reparser/reparse.php
phpBB/phpbb/textreparser/base.php
phpBB/phpbb/textreparser/reparser_interface.php
tests/text_reparser/plugins/contact_admin_info_test.php
tests/text_reparser/plugins/poll_option_test.php
tests/text_reparser/plugins/test_row_based_plugin.php

https://tracker.phpbb.com/browse/PHPBB3-13987

[ticket/13987] Add --dry-run option to reparser CLI

---

tests/template/template_includecss_test.php

[ticket/13995] Fix errors in tests from merge conflict

---

phpBB/composer.lock
phpBB/phpbb/textformatter/s9e/factory.php
tests/functional/posting_test.php
tests/text_formatter/s9e/default_formatting_test.php

https://tracker.phpbb.com/browse/PHPBB3-14000
https://area51.phpbb.com/phpBB/viewtopic.php?f=126&t=48141

[ticket/14000] Added support for emoji

---

phpBB/phpbb/textformatter/s9e/utils.php
tests/text_formatter/s9e/utils_test.php

https://tracker.phpbb.com/browse/PHPBB3-14008

[ticket/14008] Do not add a user_id value to quotes from guests

---

phpBB/phpbb/avatar/driver/upload.php

Remove the previously uploaded avatar when a new one with a different
extension is uploaded
PHPBB3-13980

[ticket/13980] Uploaded avatar not removed when new is uploaded

---

phpBB/includes/ucp/ucp_pm_viewmessage.php

[PHPBB3-14004] (https://tracker.phpbb.com/browse/PHPBB3-14004)

[ticket/14004] Add user_info to core event

---

phpBB/phpbb/console/command/reparser/reparse.php
phpBB/phpbb/filesystem/filesystem_interface.php
phpBB/phpbb/help/manager.php
phpBB/phpbb/user.php

Should help to pass https://github.com/phpbb/phpbb/pull/3773
PHPBB3-14033

[ticket/14033] Fix errors in docblocks

---

phpBB/composer.lock

```
- Removing symfony/filesystem (2.8.x-dev 45cc231)
- Installing symfony/filesystem (2.8.x-dev 9f70c56)
Cloning 9f70c5625a32b2f1e6fc37222f52b4e0eb437b0e
- Removing symfony/config (2.8.x-dev 291e3f1)
- Installing symfony/config (2.8.x-dev 358ec92)
Cloning 358ec929e494b6f12d8508d88357cbd7383a10ca
- Removing symfony/console (2.8.x-dev 7e857a2)
- Installing symfony/console (2.8.x-dev fd85e75)
Cloning fd85e7517e79a2bceafcee8f7e8b7bbd0919a90a
- Removing symfony/dependency-injection (2.8.x-dev 90a7527)
- Installing symfony/dependency-injection (2.8.x-dev f279142)
Cloning f279142fb6bc21e83fcd40e0a01a62ff527268be
- Removing symfony/finder (2.8.x-dev fd26bdb)
- Installing symfony/finder (2.8.x-dev 8712d5e)
Cloning 8712d5e8c4ad65e6b936ed9b6a581e5e6a87fddf
- Removing symfony/http-foundation …
```

[ticket/14015] Update Symfony

---

phpBB/phpbb/session.php

Add core.update_session event in \phpbb\session.php
PHPBB3-13817

[ticket/13817] Add core.update_session event

---

phpBB/includes/mcp/mcp_post.php

Create a new event to perform additional tasks after chainging a post's
poster.
PHPBB3-13974

[ticket/13974] Add core.mcp_change_poster_after event

---

tests/test_framework/phpbb_test_case_helpers.php

https://tracker.phpbb.com/browse/PHPBB3-14036

[ticket/14036] Replace path_helper with a mock

---

phpBB/styles/prosilver/theme/common.css

https://tracker.phpbb.com/browse/PHPBB3-14018
PHPBB3-14018

[ticket/14018] Fix responsive quick link menus

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/ucp_main_front.html
phpBB/styles/subsilver2/template/ucp_main_front.html

<a href="https://tracker.phpbb.com/browse/PHPBB3-14002">PHPBB3-14002</a>.

[ticket/14002] Add template events before/after user details in ucp_main_front.html

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/posting_editor.html
phpBB/styles/prosilver/template/posting_layout.html

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13843
Replaces #3612 
PHPBB3-13843

[ticket/13843] Add templates events to insert custom panel in posting editor

---

phpBB/includes/acp/acp_forums.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13311
Replaces #3610 
PHPBB3-13311

[ticket/13311] Add core event on acp_forums for forum content deletes

---

phpBB/adm/style/acp_profile.html
phpBB/docs/events.md
phpBB/includes/acp/acp_profile.php

Adds core events to includes/acp/acp_profile.php and template events
to adm/style/acp_profile.html to support adding configuration options
to profile fields.
PHPBB3-13911

[ticket/13911] Add events to configure options for profile fields

---

phpBB/develop/add_permissions.php
phpBB/includes/functions_posting.php
phpBB/includes/mcp/mcp_forum.php
phpBB/includes/mcp/mcp_main.php
phpBB/install/convertors/functions_phpbb20.php
phpBB/install/schemas/schema_data.sql
phpBB/language/en/acp/permissions_phpbb.php
phpBB/mcp.php
phpBB/phpbb/db/migration/data/v320/announce_global_permission.php
phpBB/phpbb/permissions.php
phpBB/posting.php
phpBB/styles/prosilver/template/mcp_forum.html
phpBB/viewtopic.php

Old PR: #2746 
Older PR: #2329
[PHPBB3-8708](https://tracker.phpbb.com/browse/PHPBB3-8708)

[ticket/8708] Add extra permission for posting global announcements

---

phpBB/search.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13899
Replaces #3678 
PHPBB3-13899

[ticket/13899] Add items to core.search_results_modify_search_title

---

phpBB/docs/events.md

[ticket/13982] Remove extra new line

---

phpBB/config/installer/container/services_install_console.yml
phpBB/install_new/phpbbcli.php
phpBB/language/en/install_new.php

https://tracker.phpbb.com/browse/PHPBB3-14052
PHPBB3-14052

[ticket/14052] Translate installer commands

---

phpBB/assets/javascript/plupload.js

[PHPBB3-14049](https://tracker.phpbb.com/browse/PHPBB3-14049)

[ticket/14049] Use headers from config when sending Plupload delete request.

---

phpBB/includes/ucp/ucp_notifications.php

https://tracker.phpbb.com/browse/PHPBB3-14074
PHPBB3-14074

[ticket/14074] Fix mark notifications as read in the ucp

---

phpBB/phpbb/notification/manager.php

https://tracker.phpbb.com/browse/PHPBB3-14076
PHPBB3-14076

[ticket/14076] Fix notification settings

---

phpBB/phpbb/notification/manager.php
phpBB/phpbb/notification/type/base.php
phpBB/phpbb/notification/type/type_interface.php

https://tracker.phpbb.com/browse/PHPBB3-14079
PHPBB3-14079

[ticket/14079] Correctly mark notifications as read

---

phpBB/includes/ucp/ucp_register.php

It allows to execute code before the agreements are displayed.
https://tracker.phpbb.com/browse/PHPBB3-14006

[ticket/14006] Add core.ucp_register_agreement event

---

phpBB/adm/style/acp_forums.html
phpBB/docs/events.md

https://tracker.phpbb.com/browse/PHPBB3-14013

[ticket/14013] Add acp_forums_custom_settings event

---

phpBB/phpbb/search/fulltext_native.php

Fixing variables wrongly attributed in PHPBB3-13686
https://tracker.phpbb.com/browse/PHPBB3-14082

[ticket/14082] Fix wrong variables from previous commit

---

phpBB/phpbb/search/fulltext_mysql.php

Fixing variables wrongly attributed in PHPBB3-13693
https://tracker.phpbb.com/browse/PHPBB3-14083

[ticket/14083] Fix wrong variables from previous commit

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
phpBB/styles/prosilver/template/viewtopic_body.html

<a href="https://tracker.phpbb.com/browse/PHPBB3-14005">PHPBB3-14005</a>.

[ticket/14005] Allow extensions control post buttons displaying

---

phpBB/includes/mcp/mcp_forum.php

This event can be used to get some data in order to execute other actions.
https://tracker.phpbb.com/browse/PHPBB3-14014

[ticket/14014] Add core.mcp_forum_view_before event

---

phpBB/includes/functions.php

[PHPBB3-14043](https://tracker.phpbb.com/browse/PHPBB3-14043)

[ticket/14043] Add core.get_avatar_after php event

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/posting_layout.html
phpBB/styles/subsilver2/template/posting_body.html

Allows to add some information on the left of the topic title in the posting form
https://tracker.phpbb.com/browse/PHPBB3-14019

[ticket/14019] Add posting_topic_title_before template event

---

phpBB/phpbb/db/migration/data/v310/style_update_p1.php

Changed the sql_fetchfield() call to comply to the function definition.
PHPBB3-14069

[ticket/14069] Corrected sql_fetchfield() in style_update_p1 migration

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/mcp_forum.html
phpBB/styles/subsilver2/template/mcp_forum.html

Allows to add some information before/after the topic title.
https://tracker.phpbb.com/browse/PHPBB3-14086

[ticket/14086] Add mcp_forum_topic_title_* template events

---

phpBB/styles/prosilver/template/ucp_pm_viewfolder.html
phpBB/styles/subsilver2/template/ucp_pm_viewfolder.html

<a href="https://tracker.phpbb.com/browse/PHPBB3-14093">PHPBB3-14093</a>.

[ticket/14093] Hardcoded language in ucp_pm_viewfolder.html

---

tests/datetime/from_format_test.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-14094">PHPBB3-14094</a>.

[ticket/14094] Fix segmentation fault error on PHP 7 tests

---

phpBB/composer.lock

[5.7MB/0.39s] Loading composer repositories with package information
[5.9MB/5.49s] Updating dependencies (including require-dev)
[103.4MB/202.14s]   - Updating symfony/config 2.8.x-dev (358ec92 => 3f49553)
[103.4MB/202.17s]     Checking out 3f495530550377a55c0cced5ddf8f58cfcd9ce5b
[103.4MB/223.29s] 
[103.4MB/223.29s]   - Updating symfony/console 2.8.x-dev (fd85e75 => eb0fcf6)
[103.4MB/223.32s]     Checking out eb0fcf6f58054ac9d07539451e27aa4e17aebfe0
[103.4MB/244.55s] 
[103.4MB/244.56s]   - Updating symfony/dependency-injection 2.8.x-dev (f279142 => b0e1cef)
[103.4MB/244.58s]     Checking out b0e1cef8acbc3b6df877c47b8e0b8449defcfc5f
[103.4MB/265.86s] 
[103.4MB/265.86s]   - Updating symfony/http-foundation 2.8.x-dev (5339030 => caede1f)
[103.4MB/265.88s]     Checking out …

[ticket/14096] Update Symfony

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/posting_editor.html
phpBB/styles/subsilver2/template/posting_body.html

https://tracker.phpbb.com/browse/PHPBB3-13997

[ticket/13997] Add posting_editor_submit_buttons template event

---

phpBB/adm/style/admin.css
phpBB/styles/prosilver/theme/common.css
phpBB/styles/subsilver2/theme/stylesheet.css

https://tracker.phpbb.com/browse/PHPBB3-14103

[ticket/14103] Reset text-decoration in abbr element

---

phpBB/phpbb/config/db_text.php
phpBB/phpbb/db/driver/driver.php

https://tracker.phpbb.com/browse/PHPBB3-14116
PHPBB3-14116

[ticket/14116] sql_affectedrows method has no arguments

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/mcp_topic.html
phpBB/styles/subsilver2/template/mcp_topic.html

Allows to add some information before/after the topic title
https://tracker.phpbb.com/browse/PHPBB3-14090

[ticket/14090] Add mcp_topic_topic_title_* template events

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/viewtopic_body.html

Allows an extension to create a custom dropdown menu.
https://tracker.phpbb.com/browse/PHPBB3-14041
https://tracker.phpbb.com/browse/PHPBB3-14042

[ticket/14041] Add viewtopic_dropdown_*_custom template event

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/mcp_forum.html
phpBB/styles/subsilver2/template/mcp_forum.html

[PHPBB3-13863] (https://tracker.phpbb.com/browse/PHPBB3-13863)

[ticket/13863] Add topic_row_append/prepend to mcp_forum.html

---

phpBB/phpbb/profilefields/manager.php

Replaces https://github.com/phpbb/phpbb/pull/3779
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14037

[ticket/14037] Allows adapting memberlist profile fields headline

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/attachment.html
phpBB/styles/subsilver2/template/attachment.html

Additionally remove some unnecessary empty lines.
<a href="https://tracker.phpbb.com/browse/PHPBB3-14065">PHPBB3-14065</a>.

[ticket/14065] Add template events to attachment.html

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/overall_header.html
phpBB/styles/subsilver2/template/overall_header.html

<a href="https://tracker.phpbb.com/browse/PHPBB3-14067">PHPBB3-14067</a>.

[ticket/14067] Add template events to overall_header.html around feeds

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/ucp_pm_history.html
phpBB/styles/subsilver2/template/ucp_pm_history.html

<a href="https://tracker.phpbb.com/browse/PHPBB3-14064">PHPBB3-14064</a>.

[ticket/14064] Add template events to ucp_pm_history.html

---

phpBB/includes/message_parser.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-14072">PHPBB3-14072</a>.

[ticket/14072] Add core event to the function format_display()

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/mcp_topic.html
phpBB/styles/subsilver2/template/mcp_topic.html

Add some options (field, checkbox, ...) before/after the subject field when split a subject.
https://tracker.phpbb.com/browse/PHPBB3-14091

[ticket/14091] Add mcp_topic_subject_* template events

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/viewtopic_body.html
phpBB/styles/subsilver2/template/viewtopic_body.html

Replaces #3807 
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14068

[ticket/14068] Add template events before and after poll panel in viewtopic

---

phpBB/phpbb/search/fulltext_native.php

Fixing variables wrongly attributed in PHPBB3-13691
PHPBB3-14104

[ticket/14104] Fix missing  variables from previous commit

---

phpBB/includes/ucp/ucp_activate.php

[ticket/14087] Add an event to ucp_activate.php.

---

phpBB/phpbb/install/installer.php

[PHPBB3-14097](https://tracker.phpbb.com/browse/PHPBB3-14097)

[ticket/14097] Improve error and failure handling in the installer

---

phpBB/phpbb/textformatter/s9e/factory.php
tests/text_formatter/s9e/default_formatting_test.php
tests/text_formatter/s9e/fixtures/styles/bar/template/bbcode.html
tests/text_formatter/s9e/fixtures/styles/barplus/template/bbcode.html
tests/text_formatter/s9e/fixtures/styles/foo/template/bbcode.html
tests/text_formatter/s9e/renderer_test.php
tests/text_processing/generate_text_for_display_test.php
tests/text_processing/tickets_data/PHPBB3-12195.html

https://tracker.phpbb.com/browse/PHPBB3-14128
PHPBB3-14128

[ticket/14128] Fix img bbcode regression, lost postimage class

---

phpBB/includes/functions.php

[ticket/13897] Make dependency to the filesystem optional in error handler

---

phpBB/bin/phpbbcli.php
phpBB/language/en/cli.php
phpBB/phpbb/console/application.php

https://tracker.phpbb.com/browse/PHPBB3-14125
PHPBB3-14125

[ticket/14125] Add --env option to all CLI commands

---

phpBB/includes/functions.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14070

[ticket/14070] Properly pass whether config should be ignored for avatars

---

phpBB/styles/subsilver2/template/memberlist_email.html

https://tracker.phpbb.com/browse/PHPBB3-14061

[ticket/14058] Contact us form missing email subject field in subsilver2

---

phpBB/styles/prosilver/template/jumpbox.html
phpBB/styles/prosilver/theme/colours.css
phpBB/styles/prosilver/theme/common.css
phpBB/styles/prosilver/theme/links.css

Provide some visualization back to the jumpbox
Tracker: https://tracker.phpbb.com/browse/PHPBB3-14038
PHPBB3-14038

[Ticket/14038] Jumpbox improvements

---

phpBB/includes/functions_display.php

[ticket/14133] Comment fix for phpbb_get_user_rank()

---

phpBB/includes/acp/auth.php
phpBB/phpbb/permissions.php

This hides the permissions of the disabled extensions
https://tracker.phpbb.com/browse/PHPBB3-13950

[ticket/13950] Hide undefined permissions

---

phpBB/styles/prosilver/theme/common.css

https://github.com/phpbb/phpbb/pull/3866 caused layout issue with notification menu
PHPBB3-14137

[Ticket/14137] Fix Notification Menu Layout issue

---

phpBB/phpbb/controller/helper.php

https://tracker.phpbb.com/browse/PHPBB3-11468

[ticket/11468] Allow controllers to set paramters of page_header()

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/posting_preview.html
phpBB/styles/subsilver2/template/posting_preview.html

Replaces #3815 
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14075

[ticket/14075] Add template event after poll preview panel

---

phpBB/composer.lock

```
$ php7 ../composer.phar update 'symfony/*'
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Removing symfony/filesystem (2.3.21)
- Installing symfony/filesystem (v2.3.32)
Downloading: 100%         
- Removing symfony/config (2.3.21)
- Installing symfony/config (v2.3.32)
Downloading: 100%         
- Removing symfony/console (2.3.21)
- Installing symfony/console (v2.3.32)
Downloading: 100%         
- Removing symfony/dependency-injection (2.3.21)
- Installing symfony/dependency-injection (v2.3.32)
Downloading: 100%         
- Removing symfony/debug (2.3.21)
- Installing symfony/debug (v2.3.32)
Downloading: 100%         
- Removing symfony/http-foundation (2.3.21)
- Installing symfony/http-foundation (v2.3.32)
Downloading: 100% …
```

[ticket/14140] Update Symfony to 2.3.32

---

phpBB/includes/functions_messenger.php

https://tracker.phpbb.com/browse/PHPBB3-14143
PHPBB3-14143

[ticket/14143] Flush the mail queue when writing it

---

phpBB/composer.json
phpBB/composer.lock
phpBB/config/default/container/services.yml
phpBB/includes/functions_upload.php
phpBB/includes/message_parser.php
phpBB/phpbb/avatar/driver/driver.php
phpBB/phpbb/textformatter/s9e/parser.php
tests/avatar/manager_test.php
tests/upload/imagesize_test.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14150

[ticket/14150] Update fast-image-size to newest version

---

phpBB/phpbb/db/driver/sqlite3.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13423

[ticket/13423] Set busyTimeout on connect to prevent db locking

---

phpBB/includes/functions.php
phpBB/language/en/common.php

https://tracker.phpbb.com/browse/PHPBB3-14138
PHPBB3-14138

[ticket/14138] Use span tags instead of abbr

---

phpBB/includes/functions_posting.php
phpBB/includes/mcp/mcp_logs.php
phpBB/includes/mcp/mcp_main.php
phpBB/includes/mcp/mcp_post.php
phpBB/includes/mcp/mcp_queue.php
phpBB/includes/mcp/mcp_reports.php
phpBB/includes/mcp/mcp_warn.php
phpBB/language/en/mcp.php
phpBB/phpbb/db/migration/data/v320/log_post_id.php
phpBB/phpbb/log/log.php
tests/log/fixtures/delete_log.xml
tests/log/fixtures/empty_log.xml
tests/log/fixtures/full_log.xml
tests/log/function_view_log_test.php

https://tracker.phpbb.com/browse/PHPBB3-9485

[ticket/9485] Add a "View post" link in the moderation logs

---

phpBB/includes/functions_posting.php
phpBB/styles/prosilver/template/posting_editor.html
phpBB/styles/subsilver2/template/posting_body.html

https://tracker.phpbb.com/browse/PHPBB3-7362

[ticket/7362] Add alt attribute on topic icons

---

phpBB/styles/prosilver/theme/common.css
phpBB/styles/subsilver2/theme/stylesheet.css

https://tracker.phpbb.com/browse/PHPBB3-14153

[ticket/14153] Fix floating elements in notifications dropdown header

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/posting_layout.html
phpBB/styles/subsilver2/template/posting_body.html

Allows to add some information after the topic title in the posting form
https://tracker.phpbb.com/browse/PHPBB3-14089

[ticket/14089] Add posting_topic_title_after template event

---

phpBB/docs/events.md

[ticket/14089] Remove subsilver2 file from events.md

---

phpBB/phpbb/language/language.php

https://tracker.phpbb.com/browse/PHPBB3-14158
PHPBB3-14158

[ticket/14158] Add language::lang_array() to avoid using call_user_func_array

---

phpBB/config/event.yml

https://tracker.phpbb.com/browse/PHPBB3-14156
PHPBB3-14156

[ticket/14156] Add Symfony ResponseListener

---

phpBB/phpbb/notification/type/quote.php

[PHPBB3-14078](https://tracker.phpbb.com/browse/PHPBB3-14078)

[ticket/14078] Fix SQL error when editing a post with a quote

---

phpBB/styles/prosilver/template/jumpbox.html
phpBB/styles/prosilver/template/viewtopic_body.html
phpBB/styles/prosilver/theme/bidi.css

[ticket/14107] Fix dropdown rtl states
https://tracker.phpbb.com/browse/PHPBB3-14107
PHPBB3-14107

[ticket/14107] Fix dropdown rtl states

---

phpBB/styles/prosilver/template/overall_header.html
phpBB/styles/prosilver/template/simple_header.html

https://tracker.phpbb.com/browse/PHPBB3-13992

[ticket/13992] Fix HTML5 error from w3.org validator

---

phpBB/styles/prosilver/template/mcp_header.html
phpBB/styles/prosilver/template/ucp_header.html

Fix layout of ucp/mcp after 14139
ticket: https://tracker.phpbb.com/browse/PHPBB3-14165
PHPBB3-14165

[ticket/14165] Fix layout of ucp/mcp after 14139

---

phpBB/adm/style/acp_ext_list.html
phpBB/includes/acp/acp_extensions.php

[PHPBB3-14154](https://tracker.phpbb.com/browse/PHPBB3-14154)

[ticket/14154] Add extension composer name as tooltip

---

phpBB/includes/mcp/mcp_topic.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-14102">PHPBB3-14102</a>.

[ticket/14102] Add core event to the mcp_topic.php

---

phpBB/phpbb/passwords/manager.php

https://tracker.phpbb.com/browse/PHPBB3-12577
PHPBB3-12577

[ticket/12577] Lazy initialize the password manager

---

phpBB/includes/functions_mcp.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14186

[ticket/14186] Do correct string concatenation in phpbb_mcp_sorting()

---

phpBB/styles/prosilver/theme/content.css

Ticket: https://tracker.phpbb.com/browse/PHPBB3-12554
PHPBB3-12554

[ticket/12554] Fix blockquote overflow in lists

---

phpBB/styles/prosilver/theme/utilities.css

ticket: https://tracker.phpbb.com/browse/PHPBB3-14195
PHPBB3-14195

[ticket/14195]Fix pupload & polls hiding

---

phpBB/styles/prosilver/template/forum_fn.js
phpBB/styles/prosilver/template/mcp_post.html
phpBB/styles/prosilver/template/mcp_topic.html
phpBB/styles/prosilver/template/overall_header.html
phpBB/styles/prosilver/template/posting_topic_review.html
phpBB/styles/prosilver/template/search_results.html
phpBB/styles/prosilver/template/ucp_pm_history.html
phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
phpBB/styles/prosilver/template/viewtopic_body.html

ticket: https://tracker.phpbb.com/browse/PHPBB3-14202
PHPBB3-14202

[ticket/14202]Add missing sr-only classes

---

tests/console/thumbnail_test.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14216
PHPBB3-14216

[ticket/14216] Do not run thumbnail test if gd is disabled

---

phpBB/styles/prosilver/template/jumpbox.html
phpBB/styles/prosilver/theme/colours.css
phpBB/styles/prosilver/theme/common.css

ticket: https://tracker.phpbb.com/browse/PHPBB3-14206
PHPBB3-14206

[Ticket/14206]Fix jumpbox UI consistency

---

phpBB/styles/prosilver/template/viewtopic_body.html

[ticket/14199] Correctly resolve merge conflicts

---

phpBB/bin/phpbbcli.php
phpBB/config/default/container/services_console.yml
phpBB/config/development/config.yml
phpBB/config/installer/container/services.yml
phpBB/install_new/phpbbcli.php
phpBB/phpbb/console/application.php
phpBB/phpbb/console/command/cron/run.php
phpBB/phpbb/console/exception_subscriber.php
phpBB/phpbb/di/extension/container_configuration.php
phpBB/phpbb/di/extension/core.php
tests/console/cron/run_test.php

https://tracker.phpbb.com/browse/PHPBB3-14124
PHPBB3-14124

[ticket/14124] Automatically translate exceptions in CLI 

---

phpBB/includes/acp/acp_board.php
phpBB/language/en/acp/board.php
phpBB/language/en/email/test.txt

https://tracker.phpbb.com/browse/PHPBB3-10165

[ticket/10165] Add a "Send test email" feature

---

phpBB/includes/acp/acp_users.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14222

[ticket/14222] Use request class instead of request_var in acp_users

---

phpBB/styles/prosilver/template/viewforum_body.html

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14221
PHPBB3-14221

[ticket/14221]Fix the header

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/viewforum_body.html
phpBB/styles/subsilver2/template/viewforum_body.html

<a href="https://tracker.phpbb.com/browse/PHPBB3-14080">PHPBB3-14080</a>.

[ticket/14080] Add template events around the topic row in viewforum_body.html

---

phpBB/config/default/container/services.yml
phpBB/config/default/container/services_routing.yml
phpBB/phpbb/routing/file_locator.php
phpBB/phpbb/routing/loader_resolver.php
phpBB/phpbb/routing/resources_locator/chained_resources_locator.php
phpBB/phpbb/routing/resources_locator/default_resources_locator.php
phpBB/phpbb/routing/resources_locator/resources_locator_interface.php
phpBB/phpbb/routing/router.php
tests/controller/common_helper_route.php
tests/controller/controller_test.php
tests/pagination/pagination_test.php

https://tracker.phpbb.com/browse/PHPBB3-14220
PHPBB3-14220

[ticket/14220] Move route loading to services

---

phpBB/search.php

Also add more vars to the ```core.search_get_topic_data``` event.
<a href="https://tracker.phpbb.com/browse/PHPBB3-14088">PHPBB3-14088</a>.

[ticket/14088] Add more core events to the search.php

---

phpBB/adm/style/acp_inactive.html
phpBB/includes/acp/acp_inactive.php

in ACP.  May help in spotting spam accounts quickly
PHPBB-14219
https://tracker.phpbb.com/browse/PHPBB3-14219

[ticket/14219] Add email to inactive user listing

---

phpBB/memberlist.php

Add core events to the memberlist.php for customizing members search.
<a href="https://tracker.phpbb.com/browse/PHPBB3-14113">PHPBB3-14113</a>.

[ticket/14113] Add core events for customizing members search

---

phpBB/includes/functions_admin.php

Add core events to the functions move_posts(), delete_posts(), delete_attachments().
<a href="https://tracker.phpbb.com/browse/PHPBB3-14073">PHPBB3-14073</a>.

[ticket/14073] Add several core events to the functions_admin.php

---

phpBB/includes/functions_admin.php

Fix #3814.
https://tracker.phpbb.com/browse/PHPBB3-14224

[ticket/14073] Fix trailing whitespaces

---

phpBB/phpbb/routing/loader_resolver.php

https://tracker.phpbb.com/browse/PHPBB3-14225
PHPBB3-14225

[ticket/14225] Inject the loader resolver when using the delegating loader

---

phpBB/search.php
phpBB/styles/prosilver/template/search_results.html

https://tracker.phpbb.com/browse/PHPBB3-8800

[ticket/8800] Add "mark topics read" link to "View unread posts"

---

phpBB/styles/prosilver/template/overall_header.html
phpBB/styles/prosilver/template/simple_header.html
phpBB/styles/prosilver/theme/responsive.css
phpBB/styles/prosilver/theme/stylesheet.css

The current way we include and use the responsive stylesheet is very dated and improperly handled. All media queries should be handled in the file itself and all code should be consolidated by breakpoint. This makes for setting of a style at a specific breakpoint very simplistic.
ticket: https://tracker.phpbb.com/browse/PHPBB3-14175
PHPBB3-14175

[ticket/14175] Refactor responsive implementation for easier manipulation

---

phpBB/includes/mcp/mcp_queue.php

https://tracker.phpbb.com/browse/PHPBB3-14181

[ticket/14181] Fix empty denial reason if the reason isn't translated

---

phpBB/adm/style/acp_ext_list.html
phpBB/adm/style/acp_styles.html
phpBB/adm/style/admin.css

https://tracker.phpbb.com/browse/PHPBB3-14155
PHPBB3-14155

[ticket/14155] Row highlighting for extension/styles management

---

phpBB/adm/style/acp_icons.html
phpBB/includes/acp/acp_icons.php
phpBB/includes/functions_posting.php
phpBB/language/en/common.php
phpBB/phpbb/cache/service.php
phpBB/phpbb/db/migration/data/v320/icons_alt.php
phpBB/styles/prosilver/template/posting_editor.html
phpBB/styles/prosilver/template/viewtopic_body.html
phpBB/viewtopic.php

[PHPBB3-14157](https://tracker.phpbb.com/browse/PHPBB3-14157)

[ticket/14157] Allow to set the alt/title attribute on post icons

---

phpBB/styles/prosilver/template/navbar_footer.html
phpBB/styles/prosilver/template/navbar_header.html

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14231
PHPBB3-14231

[ticket/14231]Fix double icon issue

---

phpBB/styles/prosilver/template/viewtopic_body.html

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14230

[ticket/14230] Show unread post icon in different color

---

phpBB/includes/functions.php
phpBB/viewonline.php

[PHPBB3-14200](https://tracker.phpbb.com/browse/PHPBB3-14200)

[ticket/14200] Allow hidden users to see himself on viewonline

---

phpBB/includes/functions.php

extension authors to modify SQL query
PHPBB-13591
https://tracker.phpbb.com/browse/PHPBB3-14217

[ticket/13591] Change SQL query into array to allow

---

phpBB/adm/style/acp_styles.html
phpBB/docs/events.md

[PHPBB3-14187](https://tracker.phpbb.com/browse/PHPBB3-14187)

[ticket/14187] Add acp_styles_list_before event

---

phpBB/phpbb/avatar/driver/gravatar.php

[PHPBB3-14191](https://tracker.phpbb.com/browse/PHPBB3-14191)

[ticket/14191] Add core.get_gravatar_url_after event

---

phpBB/docs/INSTALL.html

[PHPBB3-14164](https://tracker.phpbb.com/browse/PHPBB3-14164)

[ticket/14164] Add instructions to use the CLI for database updates

---

phpBB/styles/prosilver/template/forum_fn.js

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14163
PHPBB3-14163

[ticket/14163] Properly fix select all for code tag in Edge

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/quickreply_editor.html
phpBB/styles/subsilver2/template/quickreply_editor.html

[PHPBB3-14144](https://tracker.phpbb.com/browse/PHPBB3-14144)

[ticket/14144] Add quickreply_editor_subject_before event

---

phpBB/phpbb/search/fulltext_mysql.php
phpBB/phpbb/search/fulltext_native.php
phpBB/phpbb/search/fulltext_postgres.php
phpBB/phpbb/search/fulltext_sphinx.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-14098">PHPBB3-14098</a>.

[ticket/14098] Add core events to the search backends

---

phpBB/docs/INSTALL.html

[PHPBB3-14114](https://tracker.phpbb.com/browse/PHPBB3-14114)

[ticket/14114] Update 3.0.x version references in INSTALL.html.

---

phpBB/phpbb/plupload/plupload.php

[PHPBB3-13835](https://tracker.phpbb.com/browse/PHPBB3-13835)

[ticket/13835] Normalize filename for attachments uploaded in chunks.

---

phpBB/includes/acp/acp_forums.php
phpBB/includes/functions_acp.php
phpBB/includes/functions_content.php
phpBB/includes/functions_display.php
phpBB/includes/functions_mcp.php
phpBB/includes/functions_posting.php
phpBB/includes/functions_privmsgs.php
phpBB/includes/mcp/mcp_forum.php
phpBB/includes/ucp/ucp_pm_compose.php
phpBB/posting.php
phpBB/search.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14234

[ticket/14234] Use replacement variables instead of references in events

---

phpBB/includes/acp/acp_attachments.php
phpBB/includes/acp/acp_ban.php
phpBB/includes/acp/acp_bots.php
phpBB/includes/acp/acp_disallow.php
phpBB/includes/acp/acp_email.php
phpBB/includes/acp/acp_groups.php
phpBB/includes/acp/acp_inactive.php
phpBB/includes/acp/acp_jabber.php
phpBB/includes/acp/acp_language.php
phpBB/includes/acp/acp_permission_roles.php
phpBB/includes/acp/acp_permissions.php
phpBB/includes/acp/acp_profile.php
phpBB/includes/acp/acp_prune.php
phpBB/includes/acp/acp_send_statistics.php
phpBB/includes/acp/acp_users.php

[ticket/10572] Unguarded includes in acp files

---

.travis.yml
travis/setup-php-extensions.sh

https://tracker.phpbb.com/browse/PHPBB3-14236
PHPBB3-14236

[ticket/14236] Disable Opcache on Travis when running the tests

---

phpBB/composer.lock

https://tracker.phpbb.com/browse/PHPBB3-14238
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Updating symfony/http-kernel 2.8.x-dev (3300799 => 8f2cb3d)
Checking out 8f2cb3dfac5090be80fdf71e13f41aadaefc31e0
- Updating symfony/twig-bridge 2.8.x-dev (f85dc88 => ff97292)
Checking out ff97292bc36ca33214e7bdff355085143ead11f6
- Updating symfony/yaml 2.8.x-dev (1a0bd40 => ff7f886)
Checking out ff7f886a33f5b7a26a94d62f6e14bb9cf0e3bf5d
- Removing symfony/process (2.8.x-dev fc18e37)
- Installing symfony/process (2.8.x-dev 4e1daf5)
Cloning 4e1daf58b375ea7c506d525dc7801df1c9a6ebbd
- Removing symfony/dom-crawler (2.8.x-dev be577b3)
- Installing symfony/dom-crawler (2.8.x-dev 93bfc2c)
Cloning 93bfc2cc94cdfc16c728c663658117a25acd1aa5
- …
```

[ticket/14238] Updates Symfony

---

.travis.yml

[ticket/14236] Don't dump Opcache config in Travis

---

phpBB/styles/prosilver/theme/plupload.css

Replaces #3482 
https://tracker.phpbb.com/browse/PHPBB3-13684

[ticket/13684] Prevent horizontal resize of attach comment textarea

---

phpBB/includes/acp/acp_users.php

[ticket/10572] Remove excessive new line

---

phpBB/posting.php

[PHPBB3-13851](https://tracker.phpbb.com/browse/PHPBB3-13851)

[ticket/13851] Fix ignore flood limit check

---

phpBB/memberlist.php
phpBB/styles/prosilver/template/memberlist_body.html
phpBB/styles/prosilver/template/memberlist_team.html
phpBB/styles/prosilver/theme/content.css

https://tracker.phpbb.com/browse/PHPBB3-10343

[ticket/10343] Allows a_user to show inactive accounts in memberlist

---

phpBB/memberlist.php

[PHPBB3-14192](https://tracker.phpbb.com/browse/PHPBB3-14192)

[ticket/14192] Add core.memberlist_memberrow_before event

---

phpBB/styles/prosilver/template/simple_header.html

[ticket/14235] Font Awesome in simple_header.html

---

phpBB/phpbb/db/driver/driver.php

https://tracker.phpbb.com/browse/PHPBB3-13652
PHPBB3-13652

[ticket/13652] Fix coding style

---

phpBB/adm/style/captcha_recaptcha.html
phpBB/composer.json
phpBB/composer.lock
phpBB/language/en/captcha_recaptcha.php
phpBB/phpbb/captcha/plugins/recaptcha.php
phpBB/styles/prosilver/template/captcha_recaptcha.html
phpBB/styles/prosilver/theme/responsive.css

[PHPBB3-13789](https://tracker.phpbb.com/browse/PHPBB3-13789)

[ticket/13789] Upgrade reCaptcha plugin to 2.0 API.

---

phpBB/includes/functions_admin.php

[PHPBB3-12616](https://tracker.phpbb.com/browse/PHPBB3-12616)

[ticket/12616] Remove report notifications when post is deleted/disapproved.

---

phpBB/includes/ucp/ucp_profile.php
phpBB/language/en/common.php
phpBB/language/en/ucp.php

[PHPBB3-13945](https://tracker.phpbb.com/browse/PHPBB3-13945)

[ticket/13945] Send reactivation requests to admins using notifications system.

---

phpBB/install/index.php

[PHPBB3-13371](https://tracker.phpbb.com/browse/PHPBB3-13371)

[ticket/13371] Fix language loading for the old installer

---

build/package.php
phpBB/config/default/config.yml

[PHPBB3-14240](https://tracker.phpbb.com/browse/PHPBB3-14240)

[ticket/14240] Fix packaging script for 3.2

---

build/build.xml

https://tracker.phpbb.com/browse/PHPBB3-14243
PHPBB3-14243

[ticket/14243] Exclude every .git directory from the pakages

---

phpBB/language/en/install_new.php

[PHPBB3-14174](https://tracker.phpbb.com/browse/PHPBB3-14174)

[ticket/14174] Refine wording of error descriptions in new installer.

---

phpBB/adm/style/acp_avatar_options_local.html
phpBB/phpbb/avatar/driver/local.php
phpBB/styles/prosilver/template/ucp_avatar_options_local.html
phpBB/styles/subsilver2/template/ucp_avatar_options_local.html

Otherwise the directory seperator will incorrectly be transformed to its
HTML replacement.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13799
PHPBB3-13799

[ticket/13799] Do not rawurlencode category in gallery avatar

---

phpBB/phpbb/passwords/driver/salted_md5.php

[PHPBB3-13976](https://tracker.phpbb.com/browse/PHPBB3-13976)
Replaces #3736 (due to invalid commit message format)

[ticket/13976] Fix comment typo in salted_md5.php

---

phpBB/includes/functions.php

[PHPBB3-14249](https://tracker.phpbb.com/browse/PHPBB3-14249)

[ticket/14249] Fix online list order

---

phpBB/config/default/container/services_notification.yml
phpBB/phpbb/notification/manager.php
phpBB/phpbb/notification/method/board.php
phpBB/phpbb/notification/method/messenger_base.php
phpBB/phpbb/notification/type/admin_activate_user.php
phpBB/phpbb/notification/type/base.php
phpBB/phpbb/notification/type/disapprove_post.php
phpBB/phpbb/notification/type/disapprove_topic.php
phpBB/phpbb/notification/type/group_request.php
phpBB/phpbb/notification/type/group_request_approved.php
phpBB/phpbb/notification/type/pm.php
phpBB/phpbb/notification/type/post.php
phpBB/phpbb/notification/type/quote.php
phpBB/phpbb/notification/type/report_pm.php
phpBB/phpbb/notification/type/report_pm_closed.php
phpBB/phpbb/notification/type/report_post.php
phpBB/phpbb/notification/type/report_post_closed.php
phpBB/phpbb/notification/type/topic.php
tests/mock/notification_type_post.php
tests/notification/base.php
tests/notification/fixtures/services_notification.yml
tests/notification/submit_post_base.php
tests/notification/user_list_trim_test.php

Includes other minor fixes to the notifications classes I found while working on this.
PHPBB3-14237

[ticket/14237] Use $language class for notifications

---

phpBB/config/default/container/tables.yml

[PHPBB3-14265](https://tracker.phpbb.com/browse/PHPBB3-14265)

[ticket/14265] Make all tables available in container

---

phpBB/includes/mcp/mcp_queue.php

[PHPBB3-13831](https://tracker.phpbb.com/browse/PHPBB3-13831)

[ticket/13831] Store provided reason when deleting from Mod. Queue module.

---

phpBB/styles/prosilver/theme/content.css

https://tracker.phpbb.com/browse/PHPBB3-14228
PHPBB3-14228

[ticket/14228] Vertical align of numbers in polls

---

phpBB/config/default/container/services_text_reparser.yml
phpBB/phpbb/textreparser/plugins/forum_description.php
phpBB/phpbb/textreparser/plugins/forum_rules.php
phpBB/phpbb/textreparser/plugins/group_description.php
phpBB/phpbb/textreparser/plugins/pm_text.php
phpBB/phpbb/textreparser/plugins/poll_title.php
phpBB/phpbb/textreparser/plugins/post_text.php
phpBB/phpbb/textreparser/plugins/user_signature.php
phpBB/phpbb/textreparser/row_based_plugin.php
tests/text_reparser/plugins/forum_description_test.php
tests/text_reparser/plugins/forum_rules_test.php
tests/text_reparser/plugins/group_description_test.php
tests/text_reparser/plugins/pm_text_test.php
tests/text_reparser/plugins/poll_title_test.php
tests/text_reparser/plugins/post_text_test.php
tests/text_reparser/plugins/test_row_based_plugin.php
tests/text_reparser/plugins/user_signature_test.php

This will prevent BC breaking in the future if we decide to get rid of constants.
[PHPBB3-14264](https://tracker.phpbb.com/browse/PHPBB3-14264)

[ticket/14264] Don't use constants as return values

---

phpBB/adm/style/acp_captcha.html
phpBB/includes/acp/acp_captcha.php

[PHPBB3-11971](https://tracker.phpbb.com/browse/PHPBB3-11971)

[ticket/11971] Validate "Spambot countermeasures" settings before saving

---

phpBB/phpbb/install/module/install_data/task/add_bots.php

[ticket/14274] Include user functions during installer

---

phpBB/config/default/container/services_files.yml
phpBB/phpbb/files/upload.php

[PHPBB3-14273](https://tracker.phpbb.com/browse/PHPBB3-14273)

[ticket/14273] Remove unused core.root_path dependency in files.upload service

---

phpBB/assets/javascript/installer.js
phpBB/phpbb/db/migration/tool/module.php

[PHPBB3-14277](https://tracker.phpbb.com/browse/PHPBB3-14277)

[ticket/14277] Fix undefined index error in migrations

---

phpBB/phpbb/install/module/update_database/task/update.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14278

[ticket/14278] Check if user_id is set and fall back to ANONYMOUS

---

phpBB/adm/style/acp_ban.html
phpBB/adm/style/acp_email.html
phpBB/adm/style/acp_forums.html
phpBB/adm/style/acp_groups.html
phpBB/adm/style/acp_groups_position.html
phpBB/adm/style/acp_logs.html
phpBB/adm/style/acp_permissions.html
phpBB/adm/style/acp_prune_forums.html
phpBB/adm/style/acp_prune_users.html
phpBB/adm/style/acp_users.html
phpBB/adm/style/permission_forum_copy.html
phpBB/docs/events.md

<a href="https://tracker.phpbb.com/browse/PHPBB3-14201">PHPBB3-14201</a>.

[ticket/14201] Add multiple ACP template events

---

phpBB/language/en/acp/common.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14280

[ticket/14280] Add missing language strings for version check

---

phpBB/includes/functions_privmsgs.php

Lang file ucp.php requires int on current number of private messages for  `FOLDER_STATUS_MSG` so int current number
https://tracker.phpbb.com/browse/PHPBB3-14276
PHPBB3-14276

[ticket/14276] Adjust function get_folder_status

---

phpBB/index.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-14117">PHPBB3-14117</a>.

[ticket/14117] Add core events to index.php to allow modifying birthdays list

---

phpBB/styles/prosilver/template/ajax.js

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14284

[ticket/14284] Correctly remove link to first unread post

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/search_body.html
phpBB/styles/subsilver2/template/search_body.html

<a href="https://tracker.phpbb.com/browse/PHPBB3-14066">PHPBB3-14066</a>.

[ticket/14066] Add template events to search_body.html

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/viewtopic_body.html
phpBB/styles/subsilver2/template/viewtopic_body.html

[PHPBB3-14146](https://tracker.phpbb.com/browse/PHPBB3-14146)

[ticket/14146] Add viewtopic_body_post_subject_before event

---

phpBB/styles/prosilver/template/viewforum_body.html
phpBB/styles/prosilver/theme/common.css
phpBB/styles/prosilver/theme/content.css
phpBB/styles/prosilver/theme/links.css
phpBB/styles/prosilver/theme/responsive.css

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14229
PHPBB3-14229

[ticket/14229]Responsive topic specific paging

---

phpBB/styles/prosilver/template/ajax.js
phpBB/styles/prosilver/template/search_results.html
phpBB/styles/prosilver/template/ucp_main_bookmarks.html
phpBB/styles/prosilver/template/ucp_main_front.html
phpBB/styles/prosilver/template/ucp_main_subscribed.html
phpBB/styles/prosilver/template/viewforum_body.html
phpBB/styles/prosilver/template/viewtopic_body.html

PHPBB3-14294
ticket: https://tracker.phpbb.com/browse/PHPBB3-14294#add-comment

[ticket/14294]Fix removal of wanted icons on mark read

---

phpBB/install/phpbbcli.php
phpBB/language/en/install.php
phpBB/phpbb/install/console/command/install/config/show.php
phpBB/phpbb/install/console/command/install/install.php
travis/check-executable-files.sh

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14281

[ticket/14281] Fix installer CLI after recent changes

---

phpBB/config/installer/container/services.yml
phpBB/config/installer/container/services_installer.yml
phpBB/install/app.php
phpBB/install/startup.php
phpBB/phpbb/install/installer.php
tests/test_framework/phpbb_functional_test_case.php
tests/test_framework/phpbb_ui_test_case.php

[PHPBB3-14270](https://tracker.phpbb.com/browse/PHPBB3-14270)

[ticket/14270] Purge cache when the installer is finished

---

phpBB/phpbb/install/module/obtain_data/task/obtain_admin_data.php
phpBB/phpbb/install/module/obtain_data/task/obtain_board_data.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-14308">PHPBB3-14308</a>.

[ticket/14308] Fix multibyte input for installer

---

phpBB/styles/prosilver/theme/responsive.css

PHPBB3-14293
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14293

[ticket/14293]Fix postbody and profile responsive widths

---

phpBB/composer.lock

[ticket/13656] Updates Symfony to fix the DB password issue

---

phpBB/styles/prosilver/template/viewforum_body.html

[ticket/12649] Remove duplicated code from viewforum_body

---

phpBB/styles/prosilver/template/mcp_post.html
phpBB/styles/prosilver/template/mcp_topic.html
phpBB/styles/prosilver/template/viewtopic_body.html
phpBB/styles/prosilver/theme/bidi.css
phpBB/styles/prosilver/theme/common.css

PHPBB3-14295
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14295

[ticket/14295]Add approval icon

---

phpBB/viewtopic.php

https://tracker.phpbb.com/browse/PHPBB3-14313
PHPBB3-14313

[ticket/14313] Don't display quote button on unapproved posts

---

phpBB/viewtopic.php

[ticket/14313] Check for item approved explicitly

---

phpBB/language/en/memberlist.php
phpBB/memberlist.php
phpBB/styles/prosilver/template/memberlist_body.html
phpBB/styles/subsilver2/template/memberlist_group.html

https://tracker.phpbb.com/browse/PHPBB3-14283
PHPBB3-14283

[ticket/14283] Add a Manage Group link on a group page

---

phpBB/includes/acp/acp_forums.php
phpBB/includes/functions_acp.php
phpBB/includes/functions_content.php
phpBB/includes/functions_display.php
phpBB/includes/functions_mcp.php
phpBB/includes/functions_posting.php
phpBB/includes/functions_privmsgs.php
phpBB/includes/mcp/mcp_forum.php

[PHPBB3-14325](https://tracker.phpbb.com/browse/PHPBB3-14325)

[ticket/14325] Preserve event variable BC

---

phpBB/phpbb/install/controller/helper.php

[PHPBB3-14320](https://tracker.phpbb.com/browse/PHPBB3-14320)

[ticket/14320] Fix language selector in the installer

---

phpBB/phpbb/install/module/update_filesystem/task/show_file_status.php
phpBB/phpbb/install/module/update_filesystem/task/update_files.php

[PHPBB3-14326](https://tracker.phpbb.com/browse/PHPBB3-14326)

[ticket/14326] Decode diffed file's content during update

---

phpBB/install/startup.php

[PHPBB3-14311](https://tracker.phpbb.com/browse/PHPBB3-14311)

[ticket/14311] Show errors in installer invoked by trigger_error

---

phpBB/phpbb/user_loader.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14334

[ticket/14334] Use phpbb_get_avatar() in user_loader

---

phpBB/config/installer/container/services.yml
phpBB/language/en/install.php
phpBB/phpbb/install/controller/install.php
phpBB/phpbb/install/controller/update.php
phpBB/phpbb/install/event/kernel_exception_subscriber.php

[PHPBB3-14269](https://tracker.phpbb.com/browse/PHPBB3-14269)

[ticket/14269] Use http_exceptions in the installer instead of die()

---

phpBB/phpbb/install/helper/iohandler/cli_iohandler.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14345

[ticket/14345] Check if description exists in message ary

---

phpBB/includes/mcp/mcp_main.php

[PHPBB3-14343](https://tracker.phpbb.com/browse/PHPBB3-14343)

[ticket/14343] Add event when locking/unlocking posts/topics

---

phpBB/composer.json
phpBB/docs/INSTALL.html
phpBB/docs/README.html

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14339

[ticket/14339] Properly state PHP version support

---

phpBB/adm/style/acp_main.html

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14346

[ticket/14346] Do not turn version red if update status is unknown

---

phpBB/install/index.html

[PHPBB3-14348](https://tracker.phpbb.com/browse/PHPBB3-14348)

[ticket/14348] Add install/index.html

---

phpBB/phpbb/install/helper/iohandler/cli_iohandler.php
phpBB/phpbb/install/helper/iohandler/iohandler_base.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14344

[ticket/14344] Improve output of HTML errors trigged during install

---

phpBB/includes/functions_user.php

The idea is to be able to map with others CMS by exposing most commons user configuration & changes
[PHPBB-14213](https://tracker.phpbb.com/browse/PHPBB3-14213)
Replaces #3943

[ticket/14213] Adding event after users have been added to a group

---

phpBB/docs/nginx.sample.conf

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14271

[ticket/14271] Update sample config

---

phpBB/includes/functions_user.php

@Nicofuma seems to have been caused by you fixing the merge conflict :)
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14350

[ticket/14350] Remove duplicate semi-colon in functions_user

---

phpBB/includes/constants.php
phpBB/install/phpbbcli.php
phpBB/install/startup.php
phpBB/language/en/install.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14349

[ticket/14349] Improve error messages and remove output of suppressed messages

---

phpBB/develop/create_schema_files.php

[ticket/14358] Includes the composer autoloader in create_schema_files.php

---

phpBB/config/default/container/services_console.yml

[ticket/14359] Fix console.command.reparser.reparse service definition

---

phpBB/language/en/install.php

https://tracker.phpbb.com/browse/PHPBB3-14362
PHPBB3-14362

[ticket/14362] Missing lang var in install file

---

phpBB/styles/prosilver/theme/colours.css

https://tracker.phpbb.com/browse/PHPBB3-14368
PHPBB3-14368

[ticket/14368] Fix color of post editor input boxes

---

phpBB/common.php
phpBB/phpbb/debug/debug.php
phpBB/phpbb/debug/error_handler.php

[ticket/14177] Uses Symfony's Debug ErrorHandler in development environment

---

phpBB/phpbb/install/helper/iohandler/iohandler_base.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14373
PHPBB3-14373

[ticket/14373] Do not pass arrays to strpos()

---

phpBB/adm/style/install_footer.html
phpBB/adm/style/overall_footer.html
phpBB/adm/style/simple_footer.html
phpBB/styles/prosilver/template/overall_footer.html
phpBB/styles/prosilver/template/simple_footer.html

[ticket/14374] Update dynamic fallback jquery CDN script tag

---

phpBB/adm/style/installer_footer.html
phpBB/adm/style/installer_header.html
phpBB/adm/style/installer_update_file_status.html
phpBB/phpbb/install/controller/helper.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14378

[ticket/14378] Use consistent template variable paths

---

phpBB/adm/style/installer_install.html
phpBB/adm/style/installer_update.html

[PHPBB3-14380](https://tracker.phpbb.com/browse/PHPBB3-14380)

[ticket/14380] Maintain consistent template var paths in 3.2 installer

---

phpBB/styles/prosilver/template/memberlist_im.html
phpBB/styles/subsilver2/template/memberlist_im.html

When making a Jabber message, the page says the message has been sent
when loading the page for the first time, This message should only be
shown after the message has actually been sent
PHPBB3-14046

[ticket/14046] Jabber message incorrect

---

build/code_sniffer/phpbb/Sniffs/Namespaces/UnusedUseSniff.php
phpBB/phpbb/di/container_builder.php

[ticket/14377] Allow extensions to register compiler pass

---

phpBB/styles/prosilver/theme/common.css

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14371

[ticket/14371] Small fix for the quick links alignment

---

phpBB/language/en/app.php

Replaces #4038 
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14303

[ticket/14303] Use UTF8 quotes in app.php lang file

---

tests/text_processing/tickets_data/PHPBB3-12221.html
tests/text_processing/tickets_data/PHPBB3-12221.txt

https://tracker.phpbb.com/browse/PHPBB3-12221

[ticket/12221] URLs Containing javascript: are Garbled

---

phpBB/includes/functions_upload.php

[ticket/14386] Fix for open_basedir restriction in effect with remote upload avatar

---

phpBB/includes/mcp/mcp_main.php

Replaced #4101 
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14343

[ticket/14343] Added missing $phpbb_dispatcher

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/viewtopic_body.html
phpBB/styles/subsilver2/template/viewtopic_body.html

<a href="https://tracker.phpbb.com/browse/PHPBB3-14356">PHPBB3-14356</a>.

[ticket/14356] Add template events to viewtopic around back2top link

---

tests/functional/extension_acp_test.php
tests/functional/extension_global_lang_test.php
tests/functional/feed_test.php
tests/functional/metadata_manager_test.php
tests/functional/plupload_test.php
tests/test_framework/phpbb_functional_test_case.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14394

[ticket/14394] Only purge cache in functional tests if necessary

---

phpBB/includes/ucp/ucp_prefs.php

[PHPBB3-14190](https://tracker.phpbb.com/browse/PHPBB3-14190)

[ticket/14190] Add core.ucp_prefs_view_after event

---

phpBB/adm/style/acp_users_prefs.html
phpBB/includes/acp/acp_users.php
phpBB/includes/ucp/ucp_prefs.php
phpBB/phpbb/db/migration/data/v31x/increase_size_of_dateformat.php
phpBB/styles/prosilver/template/ucp_prefs_personal.html
phpBB/styles/subsilver2/template/ucp_prefs_personal.html

Replaces #4052
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13180

[ticket/13180] Increase dateformat field size

---

phpBB/includes/ucp/ucp_prefs.php

[PHPBB3-14397](https://tracker.phpbb.com/browse/PHPBB3-14397)

[ticket/14397] Fix @since tag in event 'core.ucp_prefs_view_after'

---

phpBB/phpbb/db/migration/data/v31x/increase_size_of_dateformat.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14396

[ticket/14396] Use VCHAR_UNI and correct depends_on() version

---

phpBB/composer.json
phpBB/phpbb/composer.json

[ticket/14382] Specify the branch-alias in the composer.json files

---

phpBB/phpbb/session.php

[PHPBB3-14407](https://tracker.phpbb.com/browse/PHPBB3-14407)

[ticket/14407] Fix removing users from Newly Registered Users group

---

phpBB/bin/phpbbcli.php
phpBB/phpbb/log/log.php
tests/log/add_test.php

[PHPBB3-14403](https://tracker.phpbb.com/browse/PHPBB3-14403)

[ticket/14403] Don't expect user_id and user_ip in phpbb\log

---

phpBB/includes/acp/acp_bbcodes.php
phpBB/includes/functions.php
phpBB/includes/mcp/mcp_front.php
phpBB/includes/mcp/mcp_reports.php

[ticket/14412] Comment fixes for PHPDoc in the events

---

phpBB/includes/functions_admin.php

Code changes were taken from [this post](https://www.phpbb.com/community/viewtopic.php?p=13611421#p13611421).
PHPBB3-12441

[ticket/12441] Correct database size detection in MariaDB 10

---

phpBB/composer.lock

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14419

[ticket/14419] Update composer dependencies and lock file

---

phpBB/install/schemas/postgres_schema.sql
phpBB/phpbb/db/migration/data/v320/default_data_type_ids.php
phpBB/phpbb/db/tools/mssql.php
phpBB/phpbb/db/tools/postgres.php
phpBB/phpbb/db/tools/tools.php

Replaces #2064 
Ticket: https://tracker.phpbb.com/browse/PHPBB3-11875

[ticket/11875] Use 4-byte integer instead of 3-byte integer for ID columns

---

phpBB/config/default/container/services_cron.yml
phpBB/phpbb/cron/task/core/tidy_plupload.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14402

[ticket/14402] Tidy plupload cron should not rely on user id/ip being available

---

phpBB/includes/functions_admin.php

[ticket/14423] Display database size for Aria storage engine

---

phpBB/memberlist.php

https://tracker.phpbb.com/browse/PHPBB3-14427
PHPBB3-14427

[ticket/14427] Memberlist displays inaccurate information

---

tests/files/types_remote_test.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14428

[ticket/14428] Fix files types remote tests

---

tests/test_framework/phpbb_database_test_connection_manager.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14425

[ticket/14425] Allow setting unix socket in database tests

---

phpBB/posting.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14411

[ticket/14411] Permanently delete post if delete_permanent is set

---

phpBB/phpbb/template/assets_bag.php
phpBB/phpbb/template/twig/environment.php
phpBB/phpbb/template/twig/node/includeasset.php
phpBB/phpbb/template/twig/node/includecss.php
phpBB/phpbb/template/twig/node/includejs.php

The goal being to be able to call INCLUDECSS/JS from anywhere in any tempalte or event
PHPBB3-13717

[ticket/13717] Set the assets after rendering the whole template

---

phpBB/phpbb/cache/driver/base.php
phpBB/phpbb/di/container_builder.php
tests/mock/phpbb_di_container_builder.php

Replaces #3885
https://tracker.phpbb.com/browse/PHPBB3-14129
PHPBB3-14129

[ticket/14129] Caches extensions autoloaders

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/navbar_header.html

Before notification area and after user drop down area
https://tracker.phpbb.com/browse/PHPBB3-14289
PHPBB3-14289

[ticket/14289] Add events to navbar header

---

phpBB/includes/acp/acp_users.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-14439">PHPBB3-14439</a>.

[ticket/14439] Do not call avatar manager if avatars are disabled

---

phpBB/adm/style/admin.css
phpBB/assets/javascript/installer.js

[PHPBB3-14438](https://tracker.phpbb.com/browse/PHPBB3-14438)

[ticket/14438] Allign progressbar text to center

---

phpBB/phpbb/language/language.php
tests/language/language_test.php

[ticket/14432] Adds a method to get raw language values

---

phpBB/phpbb/db/migration/data/v320/default_data_type_ids.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14436

[ticket/14436] Add dependency on oauth_states migration

---

phpBB/composer.json
phpBB/composer.lock
tests/functional/plupload_test.php
tests/test_framework/phpbb_functional_test_case.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14442

[ticket/14442] Use Goutte 2.0 for functional tests

---

phpBB/phpbb/console/command/db/list_command.php
phpBB/phpbb/console/command/db/migration_command.php
phpBB/phpbb/db/migration/schema_generator.php
phpBB/phpbb/db/migrator.php
phpBB/phpbb/extension/base.php
phpBB/phpbb/install/module/update_database/task/update.php
tests/mock/migrator.php

https://tracker.phpbb.com/browse/PHPBB3-14434
PHPBB3-14434

[ticket/14434] Allow non-migration files inside migrations folder (continued)

---

phpBB/includes/functions_messenger.php

[ticket/14444] Fix fatal error in functions_messenger.php

---

phpBB/phpbb/install/controller/archive_download.php

[PHPBB3-14321](https://tracker.phpbb.com/browse/PHPBB3-14321)
This bug should have been solved by the solution of [14269](https://tracker.phpbb.com/browse/PHPBB3-14269) so this is more of a clean up then anything else.

[ticket/14321] Clean up arcihve controller logic

---

phpBB/phpbb/install/helper/config.php
phpBB/phpbb/install/module/install_database/task/create_schema.php

[PHPBB3-14445](https://tracker.phpbb.com/browse/PHPBB3-14445)

[ticket/14445] Force refresh before schema generation

---

phpBB/phpbb/template/twig/definition.php
phpBB/phpbb/template/twig/node/includeasset.php

[ticket/14446] Add predefined placeholder variables to twig definition

---

phpBB/includes/functions_upload.php

Allow HTTPS images to be remotely uploaded.
Also includes support for redirects (currently up to 5)
PHPBB3-14431

[ticket/14431] Remote avatar uploading

---

phpBB/assets/javascript/installer.js

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14452

[ticket/14452] Define $progressFillerText in installer.js

---

phpBB/docs/events.md

Fixing the #4079 event description.
https://tracker.phpbb.com/browse/PHPBB3-14455

[ticket/14356] Fix viewtopic_body_postrow_back2top_append description

---

phpBB/phpbb/db/migration/data/v320/text_reparser.php

[PHPBB3-14461](https://tracker.phpbb.com/browse/PHPBB3-14461)

[ticket/14461] Correctly count up $processed_records

---

phpBB/config/installer/container/services_update_requirements.yml
phpBB/phpbb/install/module/obtain_data/task/obtain_update_settings.php
phpBB/phpbb/install/module/requirements/task/check_update.php
phpBB/phpbb/install/module/update_database/task/update.php

[PHPBB3-14312](https://tracker.phpbb.com/browse/PHPBB3-14312)

[ticket/14312] Enable running database update only

---

phpBB/phpbb/install/controller/helper.php
phpBB/phpbb/install/controller/install.php
phpBB/phpbb/install/controller/update.php
phpBB/phpbb/install/helper/config.php
phpBB/phpbb/install/helper/iohandler/factory.php

[PHPBB3-14460](https://tracker.phpbb.com/browse/PHPBB3-14460)

[ticket/14460] Use the selected language with AJAX requests as well

---

phpBB/assets/javascript/core.js

https://tracker.phpbb.com/browse/PHPBB3-14467

[ticket/14467] Fix height calculation in autoResize

---

phpBB/language/en/install.php

https://tracker.phpbb.com/browse/PHPBB3-14307 
PHPBB3-14307

[ticket/14307] Fixes wording in install.php file/dir exist/writeable

---

phpBB/phpbb/path_helper.php
tests/path_helper/path_helper_test.php

https://tracker.phpbb.com/browse/PHPBB3-14440
PHPBB3-14440

[ticket/14440] Correctly remove the web root path in update_web_root_path

---

phpBB/includes/functions.php
phpBB/includes/functions_acp.php
phpBB/phpbb/session.php
phpBB/viewonline.php

[PHPBB3-14409](https://tracker.phpbb.com/browse/PHPBB3-14409)

[ticket/14409] Update session page info before displaying online list

---

phpBB/includes/functions_user.php

[ticket/14475] Do not log removal of users from newly registered group

---

phpBB/composer.lock

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14477

[ticket/14477] Update text-formatter dependency

---

phpBB/styles/prosilver/template/navbar_footer.html

https://tracker.phpbb.com/browse/PHPBB3-14416
PHPBB3-14416

[ticket/14416] footer nav links have incorrect tooltip styling applied

---

phpBB/composer.lock

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14485

[ticket/14485] Update composer.lock

---

phpBB/adm/style/admin.css
phpBB/adm/style/permission_mask.html
phpBB/adm/style/tooltip.js
phpBB/includes/acp/auth.php
tests/functional/permission_roles_test.php
tests/test_framework/phpbb_ui_test_case.php
tests/ui/permission_roles_test.php

The previous code was based on multiple false implications. These changes should fix those.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14315

[ticket/14315] Correctly set permission roles for multiple groups

---

build/build.xml
phpBB/composer.json
phpBB/composer.lock
phpBB/config/installer/container/services.yml
phpBB/includes/functions.php
phpBB/phpbb/template/twig/definition.php
phpBB/phpbb/template/twig/environment.php
phpBB/phpbb/template/twig/twig.php
tests/template/template_test_case.php

https://tracker.phpbb.com/browse/PHPBB3-14457
PHPBB3-14457

[ticket/14457] Uses a random placeholder to inject css and js

---

phpBB/includes/functions_messenger.php
phpBB/phpbb/cache/driver/base.php
phpBB/phpbb/cache/driver/file.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13681

[ticket/13681] Invalidate and reset opcache where necessary

---

tests/test_framework/phpbb_ui_test_case.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14488

[ticket/14488] Delete cookies to get correct session ID during login

---

build/build.xml
phpBB/composer.json
phpBB/composer.lock
phpBB/docs/README.html
phpBB/includes/constants.php
phpBB/install/convertors/convert_phpbb20.php
phpBB/install/phpbbcli.php
phpBB/install/schemas/schema_data.sql
phpBB/language/en/install.php
phpBB/phpbb/composer.json
phpBB/styles/prosilver/style.cfg

[ticket/14495] Updates the version to 3.3.0-a1-dev

---

build/build.xml

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14500

[ticket/14500] Specify prevversion instead of duplicate newversion

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/memberlist_view.html
phpBB/styles/subsilver2/template/memberlist_view.html

<a href="https://tracker.phpbb.com/browse/PHPBB3-14316">PHPBB3-14316</a>.

[ticket/14316] Add events before/after the custom/zebra fields in pfile view

---

phpBB/includes/functions_posting.php

Add core event to the function topic_review() in includes/functions_posting.php
to allow modifying posts list to review.
<a href="https://tracker.phpbb.com/browse/PHPBB3-14365">PHPBB3-14365</a>.

[ticket/14365] Add core event to the function topic_review()

---

phpBB/includes/functions_messenger.php
phpBB/phpbb/notification/method/messenger_base.php

See https://tracker.phpbb.com/browse/PHPBB3-14443
PHPBB3-14443

[ticket/14443] Introduce additional parameter to messenger

---

phpBB/install/phpbbcli.php

This is for example needed for outputting help on commands.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14503

[ticket/14503] Enable superglobals in cli

---

phpBB/config/installer/container/services_install_console.yml
phpBB/docs/update-config.sample.yml
phpBB/language/en/install.php
phpBB/phpbb/install/console/command/install/config/show.php
phpBB/phpbb/install/console/command/update/config/show.php
phpBB/phpbb/install/console/command/update/config/validate.php
phpBB/phpbb/install/console/command/update/update.php
phpBB/phpbb/install/module/obtain_data/task/obtain_update_settings.php
phpBB/phpbb/install/module/requirements/task/check_update.php
phpBB/phpbb/install/updater_configuration.php

https://tracker.phpbb.com/browse/PHPBB3-14499
PHPBB3-14499

[ticket/14499] Add command to update the board from CLI

---

phpBB/assets/javascript/installer.js
phpBB/config/installer/container/services_install_controller.yml
phpBB/config/installer/container/services_install_finish.yml
phpBB/config/installer/container/services_installer.yml
phpBB/config/installer/routing/installer.yml
phpBB/phpbb/install/controller/timeout_check.php
phpBB/phpbb/install/event/kernel_exception_subscriber.php
phpBB/phpbb/install/helper/iohandler/ajax_iohandler.php
phpBB/phpbb/install/installer.php

[PHPBB3-14487](https://tracker.phpbb.com/browse/PHPBB3-14487)

[ticket/14487] Try to handle connection timeouts

---

phpBB/phpbb/install/module/install_data/task/add_bots.php

[PHPBB3-14510](https://tracker.phpbb.com/browse/PHPBB3-14510)

[ticket/14510] Prevent infinite loop in add_bots task

---

phpBB/phpbb/db/migration/data/v310/passwords_convert_p1.php

[PHPBB3-14514](https://tracker.phpbb.com/browse/PHPBB3-14514)

[ticket/14514] Don't skip users when converting passwords

---

phpBB/includes/functions.php
phpBB/phpbb/controller/helper.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14483

[ticket/14483] Do not send headers by default on access via controller

---

phpBB/phpbb/notification/manager.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14519

[ticket/14519] Skip query if all unread notifications are retrieved

---

phpBB/includes/functions_posting.php

Post visibility is used if it is set to a valid value.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-13264

[ticket/13264] Do not force approved state if post visibility is known

---

phpBB/includes/functions_posting.php

The previous PR broke 3.2 because of different variable names
PHPBB3-13264

[ticket/13264]  Don't force approved state if post visibility is known (3.2)

---

phpBB/install/install_update.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14496

[ticket/14496] Cache last update of update list instead of using filemtime

---

phpBB/includes/functions.php

[PHPBB3-14486](https://tracker.phpbb.com/browse/PHPBB3-14486)

[ticket/14486] Add an event and fix an event in login_box()

---

phpBB/config/default/container/services.yml
phpBB/config/default/container/services_attachment.yml
phpBB/config/default/container/services_captcha.yml
phpBB/config/default/container/services_db.yml
phpBB/config/default/container/services_feed.yml
phpBB/config/default/container/services_files.yml
phpBB/config/default/container/services_notification.yml
phpBB/config/default/container/services_report.yml
phpBB/config/installer/container/services_install_navigation.yml

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14523

[ticket/14523] Replace prototype definition with shared services

---

phpBB/phpbb/notification/method/messenger_base.php

[ticket/14533] U_NOTIFICATION_SETTINGS doesn't return the correct URL

---

phpBB/styles/prosilver/template/navbar_header.html

Replaces #4220 
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14528

[ticket/14528] Update navbar_header.html for valid microdata

---

phpBB/composer.lock

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14538

[ticket/14538] Update composer dependencies

---

phpBB/includes/functions.php

https://tracker.phpbb.com/browse/PHPBB3-14550
PHPBB3-14450

[ticket/14550] Fix the number of characters returned by unique_id()

---

phpBB/phpbb/avatar/driver/upload.php

[PHPBB3-14471](https://tracker.phpbb.com/browse/PHPBB3-14471)

[ticket/14471] Add $filedata to core.avatar_driver_upload_move_file_before event

---

phpBB/viewforum.php

https://tracker.phpbb.com/browse/PHPBB3-14051
PHPBB3-14051

[ticket/14051] Replace sql array of viewforum sort topics function

---

phpBB/phpbb/db/migration/data/v320/notifications_board.php

[PHPBB3-14318](https://tracker.phpbb.com/browse/PHPBB3-14318)

[ticket/14318] Fix SQL error in Notifications Board migration

---

phpBB/config/default/container/services_cron.yml
phpBB/config/default/container/services_routing.yml
phpBB/config/default/container/services_text_formatter.yml
phpBB/config/default/container/services_twig.yml
phpBB/config/installer/container/services.yml
phpBB/includes/bbcode.php
phpBB/includes/functions_messenger.php
phpBB/install/convert/convertor.php
phpBB/phpbb/cache/driver/file.php
phpBB/phpbb/cache/driver/memory.php
phpBB/phpbb/cron/task/core/queue.php
phpBB/phpbb/di/container_builder.php
phpBB/phpbb/routing/router.php
tests/controller/common_helper_route.php
tests/controller/controller_test.php
tests/pagination/pagination_test.php
tests/session/testable_factory.php
tests/test_framework/phpbb_functional_test_case.php

https://tracker.phpbb.com/browse/PHPBB3-14555
PHPBB3-14555

[ticket/14555] Uniformize cache directory usages

---

phpBB/includes/functions_download.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14290

[ticket/14290] Correctly use modified since header

---

phpBB/docs/nginx.sample.conf
tests/functional/visit_installer_test.php
travis/setup-webserver.sh

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14497

[ticket/14497] Support second app.php script in install folder

---

phpBB/includes/functions_content.php
phpBB/posting.php
phpBB/viewtopic.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14437

[ticket/14437] Correctly assume index from attachment display order

---

phpBB/web.config

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13842

[ticket/13842] Prevent internal server errors without rewrite module on IIS

---

phpBB/includes/mcp/mcp_warn.php

[ticket/14134] Send warning notification PM in user's language.

---

phpBB/config/default/container/services_console.yml
phpBB/language/en/acp/common.php
phpBB/language/en/cli.php
phpBB/phpbb/console/command/user/add.php
tests/console/user/add_test.php
tests/console/user/fixtures/config.xml

This replaces https://github.com/phpbb/phpbb/pull/2585
https://tracker.phpbb.com/browse/PHPBB3-12684
PHPBB3-12684

[ticket/12684] Add console command user:add

---

phpBB/viewforum.php

https://tracker.phpbb.com/browse/PHPBB3-13625
PHPBB3-13625

[ticket/13625] Fix types of properties

---

phpBB/includes/bbcode.php
phpBB/includes/constants.php
phpBB/includes/functions_display.php
phpBB/includes/message_parser.php

[PHPBB3-9435](https://tracker.phpbb.com/browse/PHPBB3-9435)

[ticket/9435] Replace BBcode magic numbers with constants

---

phpBB/common.php
phpBB/includes/functions.php
phpBB/phpbb/auth/provider/oauth/oauth.php
phpBB/phpbb/request/request.php
tests/request/request_test.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-14481

[ticket/14481] Respect HTTP_X_FORWARDED headers for implying https

---

phpBB/language/en/acp/common.php

https://tracker.phpbb.com/browse/PHPBB3-14329
PHPBB3-14329

[ticket/14329] Add missing ACP language vars

---

phpBB/phpbb/install/module/install_database/task/add_config_settings.php

[PHPBB3-14564](https://tracker.phpbb.com/browse/PHPBB3-14564)

[ticket/14564] Fix cookie domain calculation

---

CONTRIBUTING.md
README.md

[ticket/14568] Update the repository readme

---

phpBB/phpbb/install/module/update_database/task/update.php
phpBB/phpbb/install/module/update_filesystem/task/file_check.php
phpBB/phpbb/install/module/update_filesystem/task/show_file_status.php

[PHPBB3-14393](https://tracker.phpbb.com/browse/PHPBB3-14393)

[ticket/14393] Fix updater behaviour

---

phpBB/includes/acp/acp_attachments.php
phpBB/includes/acp/acp_forums.php
phpBB/includes/acp/acp_modules.php
phpBB/includes/functions_convert.php
phpBB/install/install_convert.php

For loops that modify the size of the looped arrays were obviously not
changed.
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14577

[ticket/14577] Do not calculate size of array in for loop

---

phpBB/composer.json
phpBB/composer.lock
phpBB/docs/README.html
phpBB/install/convertors/convert_phpbb20.php
phpBB/install/phpbbcli.php
phpBB/language/en/install.php
phpBB/styles/prosilver/style.cfg

DO NOT apply these changes into master when merging it. This means that
you'll have to checkout the latest files from upstream after merging this
into master (possibly while resolving likely merge conflicts).
PHPBB3-14495

[ticket/14495] Specify correct version numbers in 3.2.x

---

phpBB/includes/functions_admin.php

Continuation of https://github.com/phpbb/phpbb/pull/4254
How should I name the branch that has the fix for 3.2.x?
PHPBB3-14562

[ticket/14562] Language fallback for extension permissions

---

phpBB/includes/functions_admin.php

Continuation of https://github.com/phpbb/phpbb/pull/4254 for `3.2.x` using @CHItA's suggestion.
[PHPBB3-14562](https://tracker.phpbb.com/browse/PHPBB3-14562)

[ticket/14562] Language fallback for extension permissions (3.2.x)

---

tests/text_processing/tickets_data/PHPBB3-14260.html
tests/text_processing/tickets_data/PHPBB3-14260.txt

The issue is absent from the 3.2 line. This is only a regression test.
PHPBB3-14260

[ticket/14260] Added regression test

---

phpBB/phpbb/controller/resolver.php
tests/controller/controller_test.php
tests/controller/ext/vendor2/foo/controller.php

Ticket: https://tracker.phpbb.com/browse/PHPBB3-13502

[ticket/13502] Handle callable functions/objects in controller resolver

---

phpBB/config/default/container/services_console.yml
phpBB/language/en/cli.php
phpBB/phpbb/console/command/user/activate.php
phpBB/phpbb/console/command/user/add.php
phpBB/phpbb/console/command/user/delete.php
phpBB/phpbb/console/command/user/reclean.php
tests/console/user/activate_test.php
tests/console/user/add_test.php
tests/console/user/base.php
tests/console/user/delete_test.php
tests/console/user/fixtures/config.xml
tests/console/user/reclean_test.php

https://tracker.phpbb.com/browse/PHPBB3-14561
PHPBB3-14561

[ticket/14561] Add more user commands

---

phpBB/posting.php

<a href="https://tracker.phpbb.com/browse/PHPBB3-14559">PHPBB3-14559</a>.

[ticket/14559] Remove attachment BBCode tags from the quoted message

---

phpBB/install/database_update.php

https://tracker.phpbb.com/browse/PHPBB3-14408
PHPBB3-14408

[ticket/14408] Remove span tags from file

---

phpBB/phpbb/di/container_builder.php

https://tracker.phpbb.com/browse/PHPBB3-14198
PHPBB3-14198

[ticket/14198] Use the build option to calculate the container cache filename

---

phpBB/phpbb/controller/helper.php
tests/controller/common_helper_route.php

https://tracker.phpbb.com/browse/PHPBB3-14134
PHPBB3-13683

[ticket/13683] Respects force_server_vars settings when generating URLs

---

phpBB/web.config

Section can cause errors on IIS installations.
PHPBB3-14587

[ticket/14587] Remove sectionGroup from web.config

---

phpBB/phpbb/install/module_base.php

[PHPBB3-14590](https://tracker.phpbb.com/browse/PHPBB3-14590)

[ticket/14590] Prevent refresh requests after the last tasks in modules

---

phpBB/language/en/install.php
phpBB/phpbb/install/module/requirements/task/check_filesystem.php

[PHPBB3-14589](https://tracker.phpbb.com/browse/PHPBB3-14589)

[ticket/14589] Add error messages for failable installer requirements

---

build/build.xml
phpBB/bin/phpbbcli.php
phpBB/common.php
phpBB/composer.json
phpBB/composer.lock
phpBB/config/default/container/services_twig.yml
phpBB/config/installer/container/services.yml
phpBB/includes/bbcode.php
phpBB/includes/compatibility_globals.php
phpBB/includes/functions_messenger.php
phpBB/phpbb/di/container_builder.php
phpBB/phpbb/di/extension/core.php
phpBB/phpbb/install/helper/container_factory.php
phpBB/phpbb/template/twig/environment.php
tests/controller/common_helper_route.php
tests/extension/metadata_manager_test.php
tests/template/template_allfolder_test.php
tests/template/template_events_test.php
tests/template/template_includecss_test.php
tests/template/template_test_case.php
tests/template/template_test_case_with_tree.php
tests/test_framework/phpbb_functional_test_case.php
tests/test_framework/phpbb_ui_test_case.php

https://tracker.phpbb.com/browse/PHPBB3-13616
PHPBB3-13616

[ticket/13616] Uses symfony/proxy-manager-bridge to lazy load twig lexer

---

build/code_sniffer/phpbb/Sniffs/Namespaces/UnusedUseSniff.php

https://tracker.phpbb.com/browse/PHPBB3-14598
PHPBB3-14598

[ticket/14598] Support vars docblock in sniffer

---

phpBB/composer.lock

[ticket/14601] Fix composer.lock

---

phpBB/phpbb/attachment/delete.php
phpBB/phpbb/attachment/upload.php

[ticket/14589] Fix @var usage

---

phpBB/phpbb/console/command/command.php
phpBB/phpbb/console/command/reparser/reparse.php
phpBB/phpbb/console/command/thumbnail/delete.php
phpBB/phpbb/console/command/thumbnail/generate.php
phpBB/phpbb/console/command/user/reclean.php

https://tracker.phpbb.com/browse/PHPBB3-14569
PHPBB3-14569

[ticket/14569] Extract CLI progress bar creation to a method

---

phpBB/install/schemas/schema.json
phpBB/phpbb/db/migration/data/v320/report_id_auto_increment.php

Replaces #4299 
Ticket: https://tracker.phpbb.com/browse/PHPBB3-14607

[ticket/14607] Add missing auto_increment to report_id

---

phpBB/docs/CHANGELOG.html
phpBB/docs/FAQ.html
phpBB/docs/INSTALL.html
phpBB/docs/coding-guidelines.html

I just updated the head and some titles and a few section-titles and some "3.1.0" infos in the coding-guidelines, to keep the example up to date. 
The INSTALL.html and README.html need further work to describe the updates from 3.1 to 3.2, 3.0 to 3.2 and 2.0 to 3.2. 
I could do that, if you think i should and it should be done now. 
https://tracker.phpbb.com/projects/PHPBB3/issues/PHPBB3-14619
PHPBB3-14619

[ticket/14619] Updates "docs" from 3.1.x/ascraeus to 3.2.x/rhea

---

phpBB/phpbb/captcha/plugins/qa.php

https://tracker.phpbb.com/browse/PHPBB3-14610
PHPBB3-14610

[ticket/14610] Don't log an error if the Q&A captcha has been solved

---

phpBB/includes/ucp/ucp_profile.php

https://tracker.phpbb.com/browse/PHPBB3-14624
PHPBB3-14624

[ticket/14624] Add event to ucp_profile in signature section

---

phpBB/includes/ucp/ucp_profile.php

Fixes issue caused by merge conflict.
PHPBB3-14624

[ticket/14624] Remove no longer existing event argumemt

---

phpBB/phpbb/install/helper/iohandler/cli_iohandler.php

[ticket/14628] Supports translatable error messages in the CLI installer

---

phpBB/includes/ucp/ucp_profile.php

https://tracker.phpbb.com/browse/PHPBB3-14649
PHPBB3-14649

[ticket/14649] Add preview variable back to ucp_profile for event

---

phpBB/phpbb/notification/manager.php

[PHPBB3-11446](https://tracker.phpbb.com/browse/PHPBB3-11446)

[ticket/11446] Use sql_in_set properly in phpbb_notification_manager

---

phpBB/cron.php

Should replace [PHPBB3-14012](https://tracker.phpbb.com/browse/PHPBB3-14012).
[PHPBB3-14466](https://tracker.phpbb.com/browse/PHPBB3-14466)

[ticket/14466] Add an event to cron.php

---

phpBB/adm/style/acp_database.html

[PHPBB3-14643](https://tracker.phpbb.com/browse/PHPBB3-14643)

[ticket/14643] Offer latest backup to restore by default

---

phpBB/styles/prosilver/template/mcp_approve.html

https://tracker.phpbb.com/browse/PHPBB3-14612

[ticket/14612] Fix incorrect class for fieldset in mcp_approve.html

---

phpBB/phpbb/cron/manager.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14664
PHPBB3-14664

[ticket/14664] Fix PHPDoc comment in cron manager

---

phpBB/phpbb/template/twig/twig.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14661
PHPBB3-14661

[ticket/14661] Fix a typo in twig.php

---

phpBB/includes/functions_download.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14291
PHPBB3-14291

[ticket/14291] Do not update filesize if displaying thumbnail

---

phpBB/includes/functions_content.php

Checklist:
Replaces #4313 
https://tracker.phpbb.com/browse/PHPBB3-14626

[ticket/14626] Event core.make_jumpbox_modify_tpl_ary

---

phpBB/includes/ucp/ucp_pm_compose.php

https://tracker.phpbb.com/browse/PHPBB3-14630
PHPBB3-14630

[ticket/14630] Add event to modify pm message

---

phpBB/search.php

[PHPBB3-13865](https://tracker.phpbb.com/browse/PHPBB3-13865)

[ticket/13865] Add id_ary, show_results to core.search_modify_param_before

---

phpBB/includes/functions.php

[PHPBB3-14429](https://tracker.phpbb.com/browse/PHPBB3-14429)

[ticket/14429] Add core.obtain_users_online_string_before_modify

---

phpBB/includes/ucp/ucp_profile.php

[PHPBB3-13978](https://tracker.phpbb.com/browse/PHPBB3-13978)

[ticket/13978] Add core.ucp_profile_modify_signature_sql_ary

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/mcp_forum.html
phpBB/styles/prosilver/template/search_results.html
phpBB/styles/prosilver/template/viewforum_body.html
phpBB/styles/subsilver2/template/mcp_forum.html
phpBB/styles/subsilver2/template/search_results.html
phpBB/styles/subsilver2/template/viewforum_body.html

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14672
PHPBB3-14672

[ticket/14672] Add template event after topic title

---

phpBB/includes/mcp/mcp_queue.php

https://tracker.phpbb.com/browse/PHPBB3-14680

[ticket/14680] Fix wrong function name being checked in mcp_queue.

---

phpBB/language/en/install.php

PHPBB3-14640
https://tracker.phpbb.com/browse/PHPBB3-14640

[ticket/14640] Changes docu-link in language/en/install.php from 3.3 to 3.2

---

phpBB/language/en/email/forum_notify.txt
phpBB/language/en/email/newtopic_notify.txt
phpBB/language/en/email/short/newtopic_notify.txt
phpBB/language/en/email/short/topic_notify.txt
phpBB/language/en/email/topic_notify.txt

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14683">PHPBB3-14683</a>.

[ticket/14683] Fix typos in email templates.

---

phpBB/includes/ucp/ucp_profile.php

Checklist:
Not related to the https://tracker.phpbb.com/browse/PHPBB3-14660 but was accidentally added with 70b04016eb.

[ticket/14660] Remove redundant empty line in ucp_profile.php

---

.gitignore
README.md
Vagrantfile
phpBB/composer.json
phpBB/composer.lock
phpBB/docs/vagrant.md
vagrant/after.sh
vagrant/bootstrap.yaml
vagrant/phpbb-install-config.yml

https://tracker.phpbb.com/browse/PHPBB3-14547
This should be tested and evaluated first, to determine if it's a useful development addition/tool for phpBB to have. I made a pretty in depth documentation for it, the idea being to make coding, testing, debugging easier for contributors, especially the more casual contributors.

[ticket/14547] Add Vagrant support to phpBB

---

phpBB/includes/functions_messenger.php

For 3.2/master only.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14690">PHPBB3-14690</a>.

[ticket/14690] Create email queue cache file in the current env cache folder

---

tests/email/email_parsing_test.php

Checklist:
[PHPBB3-14696](https://tracker.phpbb.com/browse/PHPBB3-14696)
This PR adds the test for `0` username fixed in #1685.
See #4358 for more information.

[ticket/14696] Fix email template test for '0' username

---

travis/ext-sniff.sh

[ticket/14684] Add and use $NOTESTS for ext-sniff.sh

---

phpBB/docs/INSTALL.html
phpBB/includes/functions_posting.php
phpBB/install/install_install.php
phpBB/language/en/acp/attachments.php
phpBB/language/en/install.php

[PHPBB3-14654](https://tracker.phpbb.com/browse/PHPBB3-14654)

[ticket/14654] Change Imagemagick to ImageMagick

---

build/sami-all.conf.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14689
PHPBB3-14689

[ticket/14689] Build API docs for 3.2.x

---

phpBB/phpbb/db/migration/data/v320/report_id_auto_increment.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14665
PHPBB3-14665

[ticket/14665] Remove invalid syntax in report_id_auto_increment migration

---

phpBB/phpbb/content_visibility.php

[PHPBB3-14631](https://tracker.phpbb.com/browse/PHPBB3-14631)

[ticket/14631] Load truncate_string() if needed

---

phpBB/includes/functions_admin.php

[PHPBB3-14616](https://tracker.phpbb.com/browse/PHPBB3-14616)

[ticket/14616] Fixed auto-prune failing on large forums

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/mcp_move.html
phpBB/styles/subsilver2/template/mcp_move.html

[PHPBB3-14506](https://tracker.phpbb.com/browse/PHPBB3-14506)

Add mcp_move_before template event

---

phpBB/docs/events.md

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14506
PHPBB3-14506

[ticket/14506] Remove subsilver2 from docs/events.md

---

phpBB/phpbb/avatar/driver/gravatar.php
phpBB/phpbb/avatar/driver/remote.php

[PHPBB3-14615](https://tracker.phpbb.com/browse/PHPBB3-14615)
Empty is default. So why do we default it "0"? Giving it proper default value fixes validation errors as well.

[ticket/14615] Fix HTML5 validation errors on avatar deletion

---

phpBB/viewforum.php

[ticket/14685] Add viewforum_get_announcement_topic_ids_data event

---

phpBB/viewforum.php

[ticket/14687] Modify viewforum_modify_topicrow event

---

phpBB/search.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14712">PHPBB3-14712</a>.

[ticket/14712] Add search core event to allow modifying the forum select list

---

phpBB/includes/functions_admin.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14713">PHPBB3-14713</a>.

[ticket/14713] Add core event to the admin function get_forum_list()

---

phpBB/config/feed.yml
phpBB/feed.php
phpBB/phpbb/feed/base.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14688">PHPBB3-14688</a>.

[ticket/14688] Add core events to the feeds

---

phpBB/composer.lock

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14714

[ticket/14714] Update dependencies to latest versions

---

phpBB/composer.lock

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14538
PHPBB3-14538

[ticket/14538] Update symfony dependencies to latest versions

---

phpBB/config/default/container/services_auth.yml
phpBB/language/en/common.php
phpBB/phpbb/auth/provider/oauth/oauth.php
phpBB/phpbb/auth/provider/oauth/service/twitter.php
phpBB/phpbb/auth/provider/oauth/token_storage.php

[PHPBB3-14586](https://tracker.phpbb.com/browse/PHPBB3-14586)

[ticket/14586] Add OAuth1 support

---

phpBB/phpbb/textformatter/s9e/factory.php
tests/text_formatter/s9e/factory_test.php
tests/text_formatter/s9e/fixtures/smilies_duplicate.xml

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14700
PHPBB3-14700

[ticket/14700] Prevent an exception on duplicate smilies in text_formatter

---

.jshintrc

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14720
PHPBB3-14720

[ticket/14720] Add "phpbb" as allowed global to jshintrc

---

phpBB/index.php

[PHPBB3-14652](https://tracker.phpbb.com/browse/PHPBB3-14652)

Fix typos in core.index_modify_birthdays_list vars descriptions

---

.travis.yml
phpBB/composer.json
phpBB/composer.lock
phpBB/config/default/container/services_routing.yml
phpunit.xml.dist
tests/mock/container_builder.php
tests/notification/fixtures/services_notification.yml
tests/upload/fileupload_test.php
travis/phpunit-mariadb-travis.xml
travis/phpunit-mysql-travis.xml
travis/phpunit-mysqli-travis.xml
travis/phpunit-postgres-travis.xml
travis/phpunit-sqlite3-travis.xml

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14670

[ticket/14670] Use symfony 3.x in master branch

---

phpBB/language/en/install.php
phpBB/phpbb/install/module/requirements/task/check_server_environment.php

[PHPBB3-14633](https://tracker.phpbb.com/browse/PHPBB3-14633)

[ticket/14633] Check for XML extension support on install

---

phpBB/includes/functions_user.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14721
PHPBB3-14721

[ticket/14721] Avoid renaming deleted users

---

phpBB/phpbb/report/controller/report.php
phpBB/phpbb/report/report_handler.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14729

[ticket/14729] Make reports take config base class

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/memberlist_email.html
phpBB/styles/subsilver2/template/memberlist_email.html

[PHPBB3-14516](https://tracker.phpbb.com/browse/PHPBB3-14516)

[ticket/14516] Add memberlist_email_before event

---

build/build.xml

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14731
PHPBB3-14731

[ticket/14731] Skip composer when exporting old versions

---

phpBB/phpbb/textformatter/s9e/factory.php
tests/text_formatter/s9e/default_formatting_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14734
PHPBB3-14734

[ticket/14734] Use SVG emoji

---

phpBB/includes/compatibility_globals.php
phpBB/includes/constants.php
phpBB/includes/functions.php
phpBB/includes/functions_admin.php
phpBB/includes/functions_compatibility.php
phpBB/includes/functions_display.php
phpBB/includes/functions_posting.php
phpBB/phpbb/controller/helper.php
phpBB/phpbb/filesystem.php
phpBB/phpbb/user.php

[PHPBB3-14584](https://tracker.phpbb.com/browse/PHPBB3-14584)

[ticket/14548] Move deprecated globals and functions

---

phpBB/config/default/container/services_cron.yml
phpBB/config/default/routing/cron.yml
phpBB/config/default/routing/routing.yml
phpBB/cron.php
phpBB/phpbb/cron/controller/cron.php
phpBB/phpbb/cron/event/cron_runner_listener.php
phpBB/phpbb/cron/manager.php
phpBB/phpbb/cron/task/wrapper.php
tests/console/cron/cron_list_test.php
tests/console/cron/run_test.php
tests/cron/manager_test.php
tests/functional/controllers_compatibility_test.php
tests/functional/prune_shadow_topic_test.php

[PHPBB3-14542](https://tracker.phpbb.com/browse/PHPBB3-14542)

[ticket/14542] Move cron to controller

---

phpBB/install/database_update.php
phpBB/language/en/migrator.php
phpBB/phpbb/db/migration/helper.php
phpBB/phpbb/db/migration/tool/config.php
phpBB/phpbb/db/migration/tool/config_text.php
phpBB/phpbb/db/migration/tool/module.php
phpBB/phpbb/db/migration/tool/permission.php
phpBB/phpbb/db/migrator.php
tests/dbal/migration/if.php
tests/dbal/migrator_test.php
tests/migrator/reverse_update_data_test.php

Schema step will be "paused" now after every update step, so the code, that's running the migrator has better control over how much time the update takes.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14742

[ticket/14742] Improvements to migrator

---

phpBB/language/en/migrator.php
phpBB/phpbb/db/migration/helper.php
phpBB/phpbb/db/migration/tool/config.php
phpBB/phpbb/db/migration/tool/config_text.php
phpBB/phpbb/db/migration/tool/module.php
phpBB/phpbb/db/migration/tool/permission.php
phpBB/phpbb/db/migrator.php
phpBB/phpbb/install/module/update_database/task/update.php
tests/dbal/migration/if.php
tests/dbal/migrator_test.php
tests/migrator/reverse_update_data_test.php

**This is the patch for the 3.2.x branch.
To the PR for 3.1.x: #4409** 
Schema step will be "paused" now after every update step, so the code, that's running the migrator has better control over how much time the update takes.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14742

[ticket/14742-32x] Improvements to migrator

---

phpBB/phpbb/notification/method/messenger_base.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14745
Changed the HTML ampersand entity in U_NOTIFICATION_SETTINGS into a bare
ampersand character.
PHPBB3-14745

[ticket/14745] Removed unneeded HTML ampersand

---

phpBB/phpbb/db/migration/tool/config.php
phpBB/phpbb/db/migration/tool/config_text.php
phpBB/phpbb/db/migration/tool/module.php
phpBB/phpbb/db/migration/tool/permission.php
phpBB/phpbb/db/migrator.php
phpBB/phpbb/db/migrator_output_handler_interface.php

This Pull Request fixes some things that were forgotten in the last PRs (#4409 and #4410) since they were merged after some miscommunication.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14742
PHPBB3-14742

[ticket/14742] Further improvements to migrator

---

phpBB/phpbb/db/migration/tool/config.php
phpBB/phpbb/db/migration/tool/config_text.php
phpBB/phpbb/db/migration/tool/module.php
phpBB/phpbb/db/migration/tool/permission.php
phpBB/phpbb/db/migrator.php
phpBB/phpbb/db/output_handler/migrator_output_handler_interface.php
phpBB/phpbb/install/helper/iohandler/cli_iohandler.php
phpBB/phpbb/install/module/update_database/task/update.php

**This is the PR for 3.2.x. The PR for 3.1 is #4419**
This Pull Request fixes some things that were forgotten in the last PRs (#4409 and #4410) since they were merged after some miscommunication.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14742
PHPBB3-14742

[ticket/14742-32x] Further improvements to migrator

---

.travis.yml

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14743
PHPBB3-14743

[ticket/14743] Remove PHP7 from travis tests in 3.1.x

---

phpBB/includes/compatibility_globals.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14636
PHPBB3-13573
PHPBB3-14636

[ticket/14636] Restore BC with compatibility functions

---

phpBB/install/startup.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14746
PHPBB3-14746

[ticket/14746] Make msg_handler in installer independent from container

---

phpBB/styles/prosilver/template/mcp_forum.html

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14749
PHPBB3-14749

[ticket/14749] Adds missing } in mcp_forum.html to {TOPIC_DELETED

---

phpBB/styles/prosilver/template/forumlist_body.html
phpBB/styles/prosilver/template/mcp_forum.html
phpBB/styles/prosilver/template/mcp_post.html
phpBB/styles/prosilver/template/search_results.html
phpBB/styles/prosilver/template/ucp_main_bookmarks.html
phpBB/styles/prosilver/template/ucp_main_subscribed.html
phpBB/styles/prosilver/template/viewforum_body.html

Checklist:
Missing L parameter in language strings
https://tracker.phpbb.com/browse/PHPBB3-14753
PHPBB3-14753

[ticket/14753] Fix language prefix

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/mcp_topic.html
phpBB/styles/prosilver/template/posting_topic_review.html
phpBB/styles/subsilver2/template/mcp_topic.html
phpBB/styles/subsilver2/template/posting_topic_review.html

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14715
The events will allow adding content before and after the post details in topic review and topic moderation.
PHPBB3-14715

[ticket/14715] Add template events in posting_topic_review & mcp_topic

---

phpBB/styles/prosilver/theme/bidi.css

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14588
PHPBB3-14588

[ticket/14588] fix header search rtl

---

phpBB/includes/mcp/mcp_forum.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14673
PHPBB3-14673

[ticket/14673] Changes wrong language variable in mcp_forum

---

phpBB/language/en/migrator.php
phpBB/phpbb/db/migration/tool/module.php
tests/dbal/fixtures/migrator_module.xml
tests/dbal/migrator_tool_module_test.php

The PR is for 3.1.x, 3.2.x and master.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14703">PHPBB3-14703</a>.

[ticket/14703] Fix parent module selection for custom extension modules

---

phpBB/includes/functions_module.php
phpBB/mcp.php
phpBB/memberlist.php
phpBB/phpbb/help/controller/bbcode.php
phpBB/phpbb/help/controller/faq.php
phpBB/search.php
phpBB/ucp.php
phpBB/viewonline.php

[PHPBB3-14573](https://tracker.phpbb.com/browse/PHPBB3-14573)

[ticket/14573] Extend breadcrumb to support more pages

---

phpBB/search.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14727
PHPBB3-14727

[ticket/14727] Event core.search_modify_submit_parameters

---

travis/setup-database.sh

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14761
PHPBB3-14761

[ticket/14761] myisam tests should be setup on PHP 5.5 (5.4 removed)

---

phpBB/config/default/container/services_files.yml

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14763
PHPBB3-14763

[ticket/14763] Specify correct class for local files class type

---

phpBB/config/installer/routing/installer.yml

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14765">PHPBB3-14765</a>.

[ticket/14765] Fix the typo in the installer routing config

---

phpBB/includes/acp/acp_update.php
phpBB/language/en/install.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14764
PHPBB3-14764

[ticket/14764] Wrong link to database update script has been fixed

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/posting_editor.html
phpBB/styles/subsilver2/template/posting_body.html

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14695
PHPBB3-14695

[ticket/14695] Add posting_editor_subject_prepend/append template events

---

phpBB/adm/style/acp_posting_buttons.html
phpBB/docs/events.md

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14783
PHPBB3-14783

[ticket/14783] Add template event before custom BBCodes in ACP

---

phpBB/phpbb/search/fulltext_native.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14782

[ticket/14782] Use the $select variable in "Your Posts" search

---

phpBB/phpbb/search/fulltext_native.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14782

[ticket/14782] Don't use 'DISTINCT' when using 'SQL_CALC_FOUND_ROWS'

---

phpBB/includes/acp/acp_forums.php
phpBB/includes/functions_admin.php
phpBB/includes/functions_content.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14738">PHPBB3-14738</a>.

[ticket/14738] Add core events to improve modifying forum lists

---

phpBB/includes/functions_user.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14781">PHPBB3-14781</a>.

[ticket/14781] Add core event to the function group_user_attributes()

---

phpBB/docs/CREDITS.txt

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14788
PHPBB3-14788

[ticket/14788] Update CREDITS.txt

---

phpBB/includes/acp/acp_database.php
phpBB/includes/acp/acp_icons.php
phpBB/includes/acp/acp_language.php
phpBB/includes/acp/acp_modules.php
phpBB/includes/acp/acp_permission_roles.php
phpBB/includes/acp/acp_profile.php
phpBB/includes/acp/acp_reasons.php
phpBB/includes/acp/acp_search.php
tests/functional/search/base.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14789

[ticket/14789] Further harden ACP link and form checks

---

phpBB/search.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14787">PHPBB3-14787</a>.

[ticket/14787] Add more parameters to the core.search_modify_url_pameters

---

tests/functional/search/base.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14791
PHPBB3-14791

[ticket/14791] Get form tokens from correct button in search test base

---

phpBB/search.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14787">PHPBB3-14787</a>.

[ticket/14787] Add more parameters to the core.search_modify_url_parameters

---

phpBB/search.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14592
PHPBB3-14592

[ticket/14592] [PHP] core.search_backend_search_after
