- .travis.yml
- phpBB/includes/functions.php
- phpBB/phpbb/db/migration/data/v310/timezone.php
- phpBB/phpbb/search/base.php
This PR is for 3.2.x and master branches only.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14793">PHPBB3-14793</a>.
> [ticket/14793] Fix "A non-numeric value encountered" PHP warning on PHP 7.1+

- phpBB/includes/functions.php
For 3.2.x and master only.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14794">PHPBB3-14794</a>.
> [ticket/14794] Adjust redirect() behavior for PHP 7.1+ compatibility

- phpBB/docs/lighttpd.sample.conf
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14784
PHPBB3-14784
> [ticket/14784] missing rewrite for lighttpd

- phpBB/posting.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14747
PHPBB3-14747
> [ticket/14747] Add post_data to core.modify_posting_auth

- phpBB/phpbb/session.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14762
PHPBB3-14762
> [ticket/14762] Add core event to session.php

- phpBB/includes/functions_messenger.php
Also add a fallback to english for the core like we do it in `$user->add_lang()`
[PHPBB3-13709](https://tracker.phpbb.com/browse/PHPBB3-13709)
> [ticket/13709] Add fallback for email templates used by extensions

- tests/test_framework/phpbb_ui_test_case.php
Checklist:
Rhea version of https://github.com/phpbb/phpbb/pull/4394
https://tracker.phpbb.com/browse/PHPBB3-14484
> [ticket/14484] Add possibility to use extensions in UI tests

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/overall_header.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14785
PHPBB3-14785
> [ticket/14785] Add template event overall_header_headerbar_after/before

- .travis.yml
- phpBB/composer.json
- phpBB/composer.lock
- phpBB/docs/INSTALL.html
- phpBB/docs/README.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14797
PHPBB3-14797
> [ticket/14797] Support PHP 7.1 and clearly state support for latest versions

- phpBB/phpbb/notification/manager.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14799">PHPBB3-14799</a>.
> [ticket/14799] Remove accidentally added whitespaces into 3.2.x and master

- phpBB/phpbb/db/migration/data/v31x/add_log_time_index.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-8301
PHPBB3-8301
> [ticket/8301] Add log_time index

- phpBB/includes/mcp/mcp_forum.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14795
PHPBB3-14795
> [ticket/14795] Merge topic views when merging topics

- build/build.xml
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14805
PHPBB3-14805
> [ticket/14805] Ignore platform requirements while building packages

- phpBB/includes/acp/acp_database.php
- phpBB/includes/acp/acp_icons.php
- phpBB/includes/acp/acp_users.php
Checklist:
**Merge to prep-release-3.1.10 only !!**
https://tracker.phpbb.com/browse/PHPBB3-14789
PHPBB3-14789
> [ticket/14789] Move form key checks to where they actually do something

- phpBB/search.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14801">PHPBB3-14801</a>.
> [ticket/14801] Highlighting utf8 strings in search results

- phpBB/search.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14787">PHPBB3-14787</a>.
> [ticket/14787] Add 1 more parameter to the core.search_modify_url_parameters

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/mcp_forum.html
- phpBB/styles/subsilver2/template/mcp_forum.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14786
PHPBB3-14786
> [ticket/14786] Add mcp_forum_actions_before/after events

- phpBB/includes/message_parser.php
- tests/functional/posting_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14802
PHPBB3-14802
> [ticket/14802] Empty/blank lines should not be additional poll options

- phpBB/bin/phpbbcli.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14813
PHPBB3-14813
> [ticket/14813] Add missing functions_compatibiity in phpbbcli

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/overall_header.html
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14808">PHPBB3-14808</a>.
> [ticket/14808] Add template event overall_header_searchbox_after

- phpBB/composer.lock
- tests/text_processing/tickets_data/PHPBB3-14846.html
- tests/text_processing/tickets_data/PHPBB3-14846.txt
- tests/text_processing/tickets_data/PHPBB3-14846.xml
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14846
PHPBB3-14846
> [ticket/14846] Updated s9e\TextFormatter

- phpBB/phpbb/console/command/reparser/reparse.php
- phpBB/phpbb/cron/task/text_reparser/reparser.php
- phpBB/phpbb/db/migration/data/v320/text_reparser.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14814
PHPBB3-14814
> [ticket/14814] Fix reparser cron

- phpBB/styles/prosilver/template/ucp_main_subscribed.html
Checklist:
[PHPBB3-14860](https://tracker.phpbb.com/browse/PHPBB3-14860)
> [ticket/14860] Broken link on subscriptions page on mobile devices

- phpBB/docs/CREDITS.txt
https://tracker.phpbb.com/browse/PHPBB3-14788
> [ticket/14788] Farewell my friendz

- phpBB/includes/functions_posting.php
- phpBB/styles/prosilver/template/posting_topic_review.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14819
PHPBB3-14819
> [ticket/14819] Hide soft-deleted posts in topic review

- phpBB/includes/acp/acp_attachments.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14847
PHPBB3-14847
> [ticket/14847] Add core.acp_attachments_config_edit_add

- phpBB/adm/style/acp_ext_list.html
- phpBB/docs/events.md
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14848
PHPBB3-14848
> [ticket/14848] Add acp_ext_list_disabled/enabled_title_after

- phpBB/styles/prosilver/template/ajax.js
- phpBB/styles/prosilver/template/navbar_header.html
- phpBB/styles/prosilver/theme/colours.css
- phpBB/styles/prosilver/theme/common.css
- tests/functional/notification_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14855
PHPBB3-14855
> [ticket/14855] Update notification and PM alert bubbles

- phpBB/config/auth.yml
- phpBB/phpbb/auth/provider/oauth/oauth.php
- tests/functions/user_delete_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14825
PHPBB3-14825
> Add core.auth_oauth_login_after and core.auth_oauth_link_after

- phpBB/composer.lock
- phpBB/phpbb/template/twig/lexer.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14716
This addresses some issues with symfony that resulted in
issues when open_basedir restrictions were enabled, as well
as issues with JPEG images in fast-image-size.
The phpBB class extending the twig lexer also had to be
modified to ensure compatibility after BC was broken by
the PR https://github.com/twigphp/Twig/pull/2182 for twig
1.27.
PHPBB3-14716
> [ticket/14716] Update dependencies to latest versions

- phpBB/includes/acp/acp_board.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14864
PHPBB3-14864
> [ticket/14864] Set maxlength=64 to dateformat in ACP

- phpBB/includes/acp/acp_extensions.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14849
PHPBB3-14849
> [ticket/14849] Add core.acp_extensions_run_action

- phpBB/docs/coding-guidelines.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14872
PHPBB3-14872
> [ticket/14872] Remove sizeof/count restriction

- phpBB/includes/functions_messenger.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14852">PHPBB3-14852</a>.
> [ticket/14852] Add core event to modify email headers

- phpBB/styles/prosilver/template/posting_attach_body.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14750
PHPBB3-14750
> [ticket/14750] Remove html5 invalid attributes from attachment file input

- phpBB/includes/functions_display.php
- phpBB/styles/prosilver/template/forumlist_body.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-9211
PHPBB3-9211
> [ticket/9211] Use different icon for link subforum in forum legend

- phpBB/includes/functions.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14863
PHPBB3-14863
> [ticket/14863] Properly treat plural rules in confirmation box title

- phpBB/includes/functions_download.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14853">PHPBB3-14853</a>.
> [ticket/14853] Add core event to allow modifying PM attachments download auth

- phpBB/phpbb/textformatter/s9e/factory.php
- tests/text_formatter/s9e/factory_test.php
- tests/text_formatter/s9e/renderer_test.php
- tests/text_processing/generate_text_for_display_test.php
- tests/text_processing/smilies_test.php
- tests/text_processing/tickets_data/PHPBB3-13425.html
- tests/text_processing/tickets_data/PHPBB3-7187.html
- tests/text_processing/tickets_data/PHPBB3-7275.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14873
PHPBB3-14873
> [ticket/14873] Added width/height attributes to smilies

- phpBB/includes/functions_display.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14883
PHPBB3-14883
> [ticket/14883] Do not display empty forum rules (after they've been re-parsed)

- phpBB/styles/prosilver/template/jumpbox.html
- phpBB/styles/prosilver/theme/common.css
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14881
PHPBB3-14881
> [Ticket/14881] Add wrapper to jump actions to clear floats

- phpBB/phpbb/install/helper/iohandler/ajax_iohandler.php
- phpBB/phpbb/install/helper/iohandler/cli_iohandler.php
- phpBB/phpbb/install/helper/iohandler/iohandler_interface.php
- phpBB/phpbb/install/module/obtain_data/task/obtain_database_data.php
- phpBB/phpbb/request/request.php
- phpBB/phpbb/request/request_interface.php
- tests/mock/request.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14875
Due to the pre-encoded input and the escaping of the input, the
string has to be decoded twice for the password.
PHPBB3-14875
> [ticket/14875] Add method for untrimmed input to ajax iohandler

- phpBB/phpbb/db/output_handler/log_wrapper_migrator_output_handler.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14885
> [ticket/14885] Add a line break when writing to the migrator output file

- phpBB/styles/prosilver/template/navbar_header.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14884
PHPBB3-14884
> [ticket/14884] Remove duplicate span from navbar_header

- phpBB/adm/style/tooltip.js
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14736
PHPBB3-14736
> [ticket/14736] Reset role dropdown when modifying permissions

- phpBB/adm/style/ajax.js
Checklist:
Rhea version of #4541 
https://tracker.phpbb.com/browse/PHPBB3-9590
> [ticket/9590] Submit permissions form in chunks -- Rhea version

- phpBB/adm/style/ajax.js
- phpBB/includes/acp/acp_permissions.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-9590
This will add an AJAX call that will submit the permissions form in chunks
of 5 fieldsets when clicking on "Apply all permissions".
PHPBB3-9590
> [ticket/9590] Submit permissions form in chunks

- phpBB/phpbb/log/log.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13149
PHPBB3-13149
> [ticket/13149] Add core.phpbb_log_get_topic_auth_sql_before

- phpBB/viewtopic.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13479
PHPBB3-13479
> [ticket/13479] Add core.viewtopic_highlight_modify

- phpBB/phpbb/profilefields/type/type_string.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14890
This bug was introduced by PHPBB3-14272
PHPBB3-14890
> [ticket/14890] Typo in input validation of profile fields of type string

- phpBB/phpbb/install/helper/iohandler/iohandler_base.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14897
PHPBB3-14897
> [ticket/14897] Add $restart_progress_bar to iohandler base

- phpBB/phpbb/install/installer.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14896
Otherwise the user will be "logged in" again as guest user which will
prevent any redirectiong to the ACP after the installation.
PHPBB3-14896
> [ticket/14896] Do not overwrite login when finishing install

- phpBB/includes/acp/acp_extensions.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14900
Also fixed typo in code that was looming there for a while.
PHPBB3-14900
> [ticket/14900] Do not state missing cached version check means ext is invalid

- phpBB/composer.json
- phpBB/composer.lock
- phpBB/phpbb/di/container_builder.php
- phpBB/phpbb/di/proxy_instantiator.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14981
Also reverted random_compat lib to 1.4.x.
PHPBB3-14891
> [ticket/14891] Use own proxy instantiator for open_basedir compatibility

- phpBB/phpbb/install/module/update_filesystem/task/show_file_status.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14894
PHPBB3-14894
> [ticket/14894] Use correct config name for conflicts archive extension

- phpBB/includes/mcp/mcp_main.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14760
PHPBB3-14760
> [ticket/14760] Add core.mcp_main_modify_fork_sql event

- phpBB/adm/style/acp_help_phpbb.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14908
PHPBB3-14908
> [ticket/14908] Uses lang-variable instead of english text

- phpBB/includes/mcp/mcp_main.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14759
PHPBB3-14759
> [ticket/14759] Add core.mcp_main_modify_shadow_sql event

- phpBB/language/en/acp/extensions.php
Checklist:
Typo doesn't exist in 3.1.x
https://tracker.phpbb.com/browse/PHPBB3-14910
PHPBB3-14910
> [ticket/14910] Fixes typo PLease to Please in EXTENSION_NOT_INSTALLED

- phpBB/viewtopic.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14906">PHPBB3-14906</a>.
> [ticket/14906] Delete redundant sig key in user_cache_data array

- phpBB/phpbb/notification/type/report_pm.php
3.2.x/master variant of https://github.com/phpbb/phpbb/pull/4561.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14893">PHPBB3-14893</a>.
> [ticket/14893] Fix undefined variable on reporting PM notification

- phpBB/phpbb/profilefields/type/type_interface.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14889
Completes the profile fields type interface by defining a missing
required method for all implementations of a type.
PHPBB3-14889
> [ticket/14889] Missing method in profile fields type interface

- phpBB/adm/style/acp_profile.html
- phpBB/docs/events.md
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14887
PHPBB3-14887
> [ticket/14887] ACP profile step one lang specific event

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/mcp_forum.html
- phpBB/styles/subsilver2/template/mcp_forum.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14868
PHPBB3-14868
> [ticket/14868] Add mcp_forum_actions_options template event

- phpBB/includes/ucp/ucp_pm_viewfolder.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14870
PHPBB3-14870
> [ticket/14870] Add events to ucp_pm_viewfolder:get_pm_from

- phpBB/includes/ucp/ucp_remind.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14239
PHPBB3-14239
> [ticket/14239] Add core.ucp_remind_modify_select_sql

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/ucp_main_front.html
- phpBB/styles/subsilver2/template/ucp_main_front.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14390
PHPBB3-14390
> [ticket/14390] Add ucp_main_front_user_activity_append/prepend

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14520
PHPBB3-14520
> [ticket/14520] Add ucp_pm_viewmessage_options_before

- tests/files/types_remote_test.php
PHPBB3-14921
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14921
> [ticket/14921] Use phpbb.com URL to prevent test failures for remote URLs

- phpBB/styles/prosilver/theme/content.css
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14877
PHPBB-14877
> [ticket/14877] Replaces "mono" with "monospace" to avoid bad behaviour

- phpBB/adm/style/ajax.js
PHPBB3-14922
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14922
> [ticket/14922] Make sure to pass hidden input on ajax form submissions

- phpBB/config/default/container/services_text_reparser.yml
- phpBB/phpbb/console/command/reparser/list_all.php
- phpBB/phpbb/console/command/reparser/reparse.php
- phpBB/phpbb/cron/task/text_reparser/reparser.php
- phpBB/phpbb/textreparser/base.php
- phpBB/phpbb/textreparser/manager.php
- phpBB/phpbb/textreparser/reparser_interface.php
PHPBB3-14925
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14925
Discussion starts:
http://area51.phpbb.com/phpBB/viewtopic.php?f=126&t=47666&start=50#p297626
> [ticket/14925] Set reparser names in service definitions

- phpBB/phpbb/plupload/plupload.php
- tests/plupload/plupload_test.php
PHPBB3-14770
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14770
This will reduce the problem in described in the tracker or eliminate it.
> [ticket/14770] Reduce plupload resize quality

- phpBB/includes/ucp/ucp_register.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14524
PHPBB3-14524
> [ticket/14524] Add core.ucp_register_requests_after

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/ucp_register.html
- phpBB/styles/subsilver2/template/ucp_register.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14522
PHPBB3-14522
> [ticket/14522] Add ucp_register_buttons_before

- phpBB/includes/functions_display.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14331
PHPBB3-14331
> [ticket/14331] Add core.get_user_rank_after

- phpBB/includes/ucp/ucp_profile.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13845
PHPBB3-13845
> [ticket/13845] Add core.ucp_profile_avatar_sql

- phpBB/phpbb/db/migration/data/v31x/increase_size_of_emotion.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14874
PHPBB3-14874
> [ticket/14874] Increase size of emotion

- phpBB/phpbb/extension/metadata_manager.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14918
PHPBB3-14918
> [ticket/14918] Simplify access to extension version metadata information

- phpBB/phpbb/install/module/install_finish/task/populate_migrations.php
PHPBB3-14920
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14920
> [ticket/14920] Force installer to only populate core migrations

- phpBB/includes/functions_admin.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14882
PHPBB3-14882
> [ticket/14882] Add core event to MCP after move post sync

- phpBB/phpbb/db/migration/data/v310/notification_options_reconvert.php
- phpBB/phpbb/db/migration/profilefield_base_migration.php
PHPBB3-14923
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14923
> [ticket/14923] Make sure start for queries is always set in migrations

- phpBB/includes/functions_user.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14119
PHPBB3-14119
> [ticket/14119] Add core.user_unban

- phpBB/viewforum.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14468
PHPBB3-14468
> [ticket/14468] Add forum_id to core.viewforum_modify_topics_data

- phpBB/includes/functions_download.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14817
PHPBB3-14817
> [ticket/14817] Add core.send_file_to_browser_before

- phpBB/phpbb/di/proxy_instantiator.php
The symfony methods will cause PHP warnings being thrown.
PHPBB3-14934
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14934
> [ticket/14934] Use bare PHP functions for checking for tmp dir

- phpBB/phpbb/textformatter/s9e/factory.php
- phpBB/styles/prosilver/theme/common.css
- tests/text_formatter/s9e/default_formatting_test.php
PHPBB3-14914
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14914
> [ticket/14914] Made emoji scale in size with text

- phpBB/adm/style/acp_ext_details.html
- phpBB/docs/events.md
PHPBB3-14940
Event to allow the inclusion of extra detailed information on an extension.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14940
> [ticket/14940] Add ACP template event acp_ext_details_end

- phpBB/includes/ucp/ucp_pm_viewfolder.php
PHPBB3-14953
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14953
> [ticket/14953] Use ORDER_BY instead of incorrect ORDER for sql query

- phpBB/config/db.yml
- phpBB/phpbb/di/container_builder.php
- phpBB/phpbb/di/extension/config.php
- tests/di/create_container_test.php
- tests/di/fixtures/config/services.yml
- tests/di/fixtures/other_config/services.yml
PHPBB3-14957
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14957
> [ticket/14957] Do not cache database config entries

- phpBB/config/default/container/services_db.yml
- phpBB/phpbb/di/container_builder.php
- phpBB/phpbb/di/extension/config.php
- tests/di/create_container_test.php
- tests/di/fixtures/config/production/container/environment.yml
- tests/di/fixtures/config/test/container/environment.yml
- tests/di/fixtures/other_config/production/container/environment.yml
- tests/di/fixtures/other_config/test/container/environment.yml
- tests/mock/phpbb_di_container_builder.php
- tests/test_framework/phpbb_functional_test_case.php
Rhea version of #4609 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14957
> [ticket/14957] Do not cache database config entries -- Rhea version

- phpBB/language/en/common.php
- phpBB/phpbb/feed/attachments_base.php
- phpBB/phpbb/feed/forum.php
- phpBB/phpbb/feed/news.php
- phpBB/phpbb/feed/overall.php
- phpBB/phpbb/feed/topic.php
- phpBB/phpbb/feed/topics.php
- phpBB/phpbb/feed/topics_active.php
- tests/feed/attachments_base_test.php
- tests/feed/attachments_mock_feed.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14838
> [icket/14838] Do not query full attachments table in feeds

- phpBB/includes/acp/acp_users.php
- phpBB/includes/ucp/ucp_profile.php
PHPBB3-14945
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14945
> [ticket/14945] Fix bbcode flags in user sig previews

- tests/feed/attachments_base_test.php
- tests/feed/attachments_mock_feed.php
PHPBB3-14838
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14838
> [ticket/14838] Add missing method to mock'ed feed

- phpBB/phpbb/search/fulltext_mysql.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14941
> [ticket/14941] Apply changes individually for MySQL fulltext search

- phpBB/includes/functions_privmsgs.php
- tests/functions_privmsgs/get_max_setting_from_group_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14780
PHPBB3-14780
> [ticket/14780] Correction to let group setting overwrite global PM setting

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/memberlist_team.html
- phpBB/styles/subsilver2/template/memberlist_team.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14662
PHPBB3-14662
> [ticket/14662] Add memberlist_team_username_prepend/append

- phpBB/includes/ucp/ucp_pm_compose.php
PHPBB3-14945
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14945
> [ticket/14945] Parse signature preview with generate_text_for_display()

- phpBB/phpbb/session.php
> [ticket/14946] Make sure to pass integers to max()

- phpBB/includes/mcp/mcp_queue.php
- phpBB/styles/prosilver/template/mcp_queue.html
> [ticket/14954] Properly check if topic has attachments in mcp_queue

- phpBB/phpbb/notification/type/post.php
PHPBB3-14949
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14949
> [ticket/14949] Pass full notification array and post data for updating

- phpBB/phpbb/template/twig/extension.php
PHPBB3-14958
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14958
> [ticket/14958] Optimize Twig extension lang() function

- phpBB/phpbb/textformatter/s9e/utils.php
- phpBB/phpbb/textformatter/utils_interface.php
- phpBB/posting.php
- tests/functional/posting_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14962
> [ticket/14962] Introduces a new helper to check emptyness of bbcode texts

- phpBB/styles/prosilver/template/viewforum_body.html
- phpBB/styles/prosilver/theme/bidi.css
- phpBB/styles/prosilver/theme/common.css
PHPBB3-14772
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14772
> [ticket/14772] Use float to prevent pagination overwriting topic time

- phpBB/phpbb/db/migration/data/v32x/cookie_notice_p2.php
PHPBB3-14967
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14967
> [ticket/14967] Add cookie notice migration fixing invalid previous one

- phpBB/phpbb/pagination.php
- tests/pagination/pagination_test.php
3.2.x/master only
PHPBB3-14971
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14971
> [ticket/14971] Fix pagination PHP warning on PHP 7.1

- phpBB/phpbb/db/tools.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14973
> [ticket/14973] Add BC layer for \phpbb\db\tools

- phpBB/adm/style/overall_header.html
- phpBB/adm/style/simple_header.html
- phpBB/styles/prosilver/template/forum_fn.js
- phpBB/styles/subsilver2/template/memberlist_search.html
- phpBB/styles/subsilver2/template/overall_header.html
PHPBB3-15003
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15003
> [ticket/15003] Do not check disabled checkboxes with marklist function

- phpBB/phpbb/profilefields/type/type_date.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15010
PHPBB3-15010
> [ticket/15010] Fix incorrect use of request

- phpBB/phpbb/install/helper/file_updater/ftp_file_updater.php
PHPBB3-15012
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15012
> [ticket/15012] Use valid constructor in ftp_file_updater

- phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
PHPBB3-14999
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14999
> [ticket/14999] Correct Next PM Iconography

- phpBB/styles/prosilver/template/search_results.html
[ticket/15002] Show topic icons in search results
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15002
PHPBB3-15002
> [ticket/15002] Show topic icons in search results

- phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
- phpBB/styles/prosilver/theme/icons.css
icons.css change is needed for RTL, because inherited float is right
PHPBB3-14984
Checklist:
> [ticket/14984] Correct wrong arrow direction in PM inbox

- phpBB/phpbb/extension/metadata_manager.php
PHPBB3-15011
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15011
> [ticket/15011] Error not checked on metadata load failure

- phpBB/phpbb/textformatter/data_access.php
- phpBB/phpbb/textformatter/s9e/factory.php
- tests/functional/acp_bbcodes_test.php
- tests/functional/acp_smilies_test.php
http://area51.phpbb.com/phpBB/viewtopic.php?f=126&t=50821
This PR supercedes https://github.com/phpbb/phpbb/pull/4628
***
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14985
> [ticket/14985] Decode HTML special chars in plain text columns

- phpBB/includes/acp/acp_board.php
- phpBB/language/en/acp/board.php
- tests/functional/posting_test.php
PHPBB3-14989
This ticket is restoring parts of ticket/13935 which seem to have been lost somewhere.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14989
> [ticket/14989] Allow more admin-configurable schemes in post links

- phpBB/includes/acp/acp_main.php
- phpBB/language/en/acp/common.php
PHPBB3-11076
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-11076
> [ticket/11076] State current and minimum required versions in old PHP notice

- phpBB/phpbb/extension/metadata_manager.php
PHPBB3-15011
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15011
> [ticket/15011] Output meaningful errors when validating all metadata

- phpBB/styles/prosilver/template/viewforum_body.html
- phpBB/styles/prosilver/theme/bidi.css
- phpBB/styles/prosilver/theme/common.css
- phpBB/styles/prosilver/theme/responsive.css
Checklist:
PHPBB3-15023
https://tracker.phpbb.com/browse/PHPBB3-15023
> [ticket/15023] fix responsive post row paging

- phpBB/composer.lock
PHPBB3-15040
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15040
> [ticket/15040] Update s9e\TextFormatter to 0.9.1

- phpBB/composer.lock
- tests/text_processing/tickets_data/PHPBB3-14790.html
- tests/text_processing/tickets_data/PHPBB3-14790.txt
This PR contains commits from—and depends on—https://github.com/phpbb/phpbb/pull/4664
I assume Git will do its thing and it won't cause any conflicts, otherwise I'll rebase.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14790
> [ticket/14790] Added test case

- phpBB/phpbb/install/module/obtain_data/task/obtain_email_data.php
PHPBB3-15015
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15015
> [ticket/15015] Use correct explain string for enable email settings

- phpBB/adm/style/ajax.js
PHPBB3-15006
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15006
> [ticket/15006] Pass inherit settings to form and use correct button

- phpBB/adm/style/acp_main.html
- phpBB/adm/style/acp_update.html
- phpBB/includes/acp/acp_main.php
- phpBB/includes/acp/acp_update.php
- phpBB/language/en/install.php
- phpBB/phpbb/version_helper.php
- tests/version/version_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14968
> [ticket/14968] Distinguish between update/upgrade & show upgrade info in ACP index

- tests/test_framework/phpbb_functional_test_case.php
PHPBB3-15036
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15036
> [ticket/15036] Unlink install_config during functional testing

- tests/version/version_test.php
PHPBB3-15045
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15045
> [ticket/15045] Fix user object instantiation in version_test

- phpBB/phpbb/db/tools/mssql.php
The character limit for index names on MS SQL is 128 so there's not really a need to check it and throw an error if it exceeds 30 characters.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15047
> [ticket/15047] Various db tools fixes for MSSQL

- phpBB/includes/acp/acp_update.php
PHPBB3-14998
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14998
> [ticket/14998] Point only to install dir from acp_update

- phpBB/config/installer/container/services_install_data.yml
- phpBB/language/en/install.php
- phpBB/phpbb/install/module/install_data/task/create_search_index.php
- phpBB/phpbb/search/fulltext_native.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15044
> [ticket/15044] Create search index during installation

- phpBB/adm/style/admin.css
- phpBB/styles/prosilver/theme/stylesheet.css
PHPBB3-15062
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15062
> [ticket/15062] Update to Rhea version the CSS files

- phpBB/styles/prosilver/theme/content.css
PHPBB3-15059
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15059
> [ticket/15059] Preserve code line breaks and scroll overflow

- phpBB/phpbb/auth/auth.php
PHPBB3-13601
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13601
> [ticket/13601] Add core.acl_clear_prefetch_after event

- phpBB/phpbb/cache/driver/file.php
PHPBB3-13250
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13250
> [ticket/13250] Replace slashes in cache file names

- phpBB/posting.php
PHPBB3-14929
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14929
> [ticket/14929] Add error to core.posting_modify_message_text

- phpBB/styles/prosilver/theme/stylesheet.css
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15058
> [ticket/15058] Force browser to redownload stylesheets

- phpBB/includes/acp/info/acp_logs.php
> [ticket/13344] Add core event to acp/info/acp_logs.php

- phpBB/adm/style/acp_ext_list.html
- phpBB/docs/events.md
PHPBB3-14995
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14995
> [ticket/14995] Add ACP template events acp_ext_list_*_name_after

- phpBB/includes/functions_user.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14927
> [ticket/14927] Add notifications_data to core.user_add_modify_data

- phpBB/styles/prosilver/template/display_options.html
- phpBB/styles/prosilver/template/jumpbox.html
- phpBB/styles/prosilver/template/pagination.html
- phpBB/styles/prosilver/theme/bidi.css
display_options.html corrected to move (display and sorting option) to right
jumpbox.html corrected to change arrow direction to left in RTL
pagination.html corrected to change arrows direction on RTL
bidi.css more edittions to correct remain style mistakes
PHPBB3-14975
Checklist:
> [ticket/14975] Correct RTL style css

- phpBB/styles/prosilver/template/forumlist_body.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15106
> [ticket/15106] Remove space before comma in sub-forum list

- phpBB/docs/INSTALL.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15092
PHPBB3-15092
> [ticket/15092] Correct database update instructions

- phpBB/includes/acp/acp_board.php
PHPBB3-15089
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15089
> [ticket/15089] Reverse the order of cookie secure radio buttons

- phpBB/styles/prosilver/theme/links.css
PHPBB3-14979
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14979
> [ticket/14979] Do not display underline for unread icon

- .gitignore
- .travis.yml
- phpBB/package.json
- phpBB/styles/prosilver/theme/common.css
- phpBB/styles/prosilver/theme/content.css
- phpBB/styles/prosilver/theme/responsive.css
- travis/check-stylesheet.sh
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14970
> [ticket/14970] Use stylelint.io in travis CI builds

- phpBB/styles/prosilver/template/jumpbox.html
PHPBB3-15118
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15118
> [ticket/15118] Fix html error in jumpbox.html

- phpBB/styles/prosilver/theme/normalize.css
Checklist:
PHPBB3-14981
https://tracker.phpbb.com/browse/PHPBB3-14981
> [ticket/14981] Update nomalize.css to v5.0

- phpBB/styles/prosilver/theme/links.css
https://tracker.phpbb.com/browse/PHPBB3-15120
PHPBB3-15120
Checklist:
> [ticket/15120] Semicolon missing

- phpBB/adm/style/acp_styles.html
- phpBB/includes/acp/acp_styles.php
- phpBB/language/en/acp/styles.php
PHPBB3-14820
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14820
> [ticket/14820] Add style version in ACP

- phpBB/adm/style/admin.css
- phpBB/styles/prosilver/theme/print.css
PHPBB3-15083
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15083
> [ticket/15083] Fix invalid emoji sizing in ACP & print view

- phpBB/styles/prosilver/template/bbcode.html
- phpBB/styles/prosilver/theme/common.css
PHPBB3-14844
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14844
Replaces #4493
> [ticket/14844] Add CSS classes for strong and italics text to BBCodes

- phpBB/language/en/common.php
- phpBB/styles/prosilver/template/overall_footer.html
PHPBB3-14974
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14974
> [ticket/14974] Make cookie notice configurable via language files

- phpBB/phpbb/cache/driver/memcached.php
PHPBB3-15122
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15122
> [ticket/15122] Add cache driver for memcached

- phpBB/language/en/cli.php
- phpBB/phpbb/console/command/extension/disable.php
- phpBB/phpbb/console/command/extension/enable.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15123
> [ticket/15123] Check if extension was enabled/disabled before enable or disable

- phpBB/includes/acp/acp_extensions.php
PHPBB3-15102
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15102
> [ticket/15102] Missing parameter calling version_check

- phpBB/includes/acp/acp_extensions.php
- phpBB/phpbb/extension/metadata_manager.php
PHPBB3-15135
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15135
> [ticket/15135] Parse language files in acp_extensions instead of md manager

- phpBB/includes/acp/acp_update.php
- phpBB/phpbb/version_helper.php
PHPBB3-15143
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15143
> [ticket/15143] Fix display of version update in ACP

- phpBB/phpbb/avatar/driver/upload.php
PHPBB3-15134
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15134
> [ticket/15134] Replace php native functions for filesystem service methods

- phpBB/includes/functions_posting.php
PHPBB3-15137
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15137
> [ticket/15137] Global Announcements shouldn't always be never ending

- phpBB/phpbb/event/data.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14557
PHPBB3-14557
> [ticket/14557] Simplify updating overloaded events for extensions

- phpBB/adm/style/admin.css
- travis/check-stylesheet.sh
Checklist:
to be merged after #4726
PHPBB3-15116
https://tracker.phpbb.com/browse/PHPBB3-15116
> [ticket/15116] Fix admin errors

- phpBB/composer.json
- phpBB/composer.lock
- vagrant/after.sh
> [ticket/15153] Update to newer homestead for vagrant

- phpBB/styles/prosilver/template/overall_header.html
- phpBB/styles/prosilver/template/simple_header.html
PHPBB3-15157
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15157
> [ticket/15157] Add proper google font call

- .gitignore
PHPBB3-15160
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15160
> [ticket/15160] correct path of node_modules

- phpBB/phpbb/db/migration/data/v320/add_help_phpbb.php
PHPBB3-15090
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15090
> [ticket/15090] Ensure send stats module exists before removing

- phpBB/includes/acp/acp_extensions.php
PHPBB3-14919
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14919
> [ticket/14919] Do not directly use globals in acp_extensions

- tests/mock/extension_manager.php
PHPBB3-14938
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14938
> [ticket/14938] Add missing language class to extension manager mock

- phpBB/config/default/container/services_twig.yml
- phpBB/config/installer/container/services.yml
- phpBB/includes/functions_messenger.php
- phpBB/phpbb/template/twig/environment.php
- tests/controller/common_helper_route.php
- tests/email/email_parsing_test.php
- tests/extension/metadata_manager_test.php
- tests/template/template_allfolder_test.php
- tests/template/template_events_test.php
- tests/template/template_includecss_test.php
- tests/template/template_test_case.php
- tests/template/template_test_case_with_tree.php
PHPBB3-14990
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14990
> [ticket/14990] Add core events to the Twig environment

- phpBB/phpbb/di/extension/core.php
PHPBB3-15180
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15180
> [ticket/15180] Adjust \phpbb\di\extension\core::TWIG_OPTIONS_POSITION

- phpBB/install/phpbbcli.php
> [ticket/15154] Load compatibility globals into the CLI installer

- phpBB/phpbb/request/request.php
PHPBB3-15108
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15108
> [ticket/15108] Remove duplicate code in request->overwrite

- phpBB/posting.php
PHPBB3-15079
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15079
> [ticket/15079] Parse message before inserting it into drafts table

- phpBB/phpbb/module/module_manager.php
PHPBB3-15084
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15084
> [ticket/15084] Fix wrong order of breadcrumbs in module management

- phpBB/assets/javascript/core.js
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15174
> 	[ticket/15174] Increase timeout for loading indicator

- phpBB/styles/prosilver/theme/forms.css
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15173
> [ticket/15173] Fix message area resizing lag

- phpBB/composer.lock
PHPBB3-15158
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15158
> [ticket/15158] Update oauth to v0.8.10

- phpBB/phpbb/profilefields/type/type_date.php
Fix by changing select input field options to match validation range
https://tracker.phpbb.com/browse/PHPBB3-15146
> [ticket/15146] Date profile field validation incorrect

- phpBB/ucp.php
PHPBB3-13609
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13609
> [ticket/13609] Add core.ucp_switch_permissions event

- phpBB/ucp.php
PHPBB3-13608
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13608
> [ticket/13608] Add core.ucp_restore_permissions event

- phpBB/styles/prosilver/template/mcp_front.html
if there are attachments in reports
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15144
PHPBB3-15144
> [ticket/15144] Attachment icon display should only occur

- phpBB/adm/style/acp_main.html
- phpBB/language/en/acp/common.php
PHPBB3-15198
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15198
> [ticket/15198] Add PHP version to board stats in the ACP

- phpBB/includes/ucp/ucp_pm_compose.php
PHPBB3-13605
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13605
> [ticket/13605] Add core.ucp_pm_compose_predefined_message event

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/index_body.html
- phpBB/styles/subsilver2/template/index_body.html
PHPBB3-13603
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13603
> [ticket/13603] Add index_body_stat_blocks_after event

- phpBB/includes/functions_posting.php
PHPBB3-13730
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13730
> [ticket/13730] Add core.delete_post_end event

- phpBB/styles/prosilver/theme/bidi.css
- phpBB/styles/prosilver/theme/colours.css
- phpBB/styles/prosilver/theme/content.css
- phpBB/styles/prosilver/theme/icons.css
Use the Font Awesome icon for a quote rather than the quote.gif file.
I believe I've handled the RTL case as well.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15086
> [ticket/15086] Replace quote.gif with Font Awesome icon

- phpBB/docs/events.md
PHPBB3-13603
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13603
> [ticket/13603] Add missing event to events.md

- phpBB/includes/mcp/mcp_topic.php
- tests/functional/visibility_softdelete_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-7336
> [ticket/7336] Index first post when splitting topics

- phpBB/phpbb/extension/manager.php
PHPBB3-15202
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15202
> [ticket/15202] To disable, an extension must be enabled

- tests/text_processing/generate_text_for_display_test.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15222">PHPBB3-15222</a>.
> [ticket/15222] Fix a typo in generate_text_for_display_test.php

- phpBB/language/en/install.php
in language/en/install.php
PHPBB3-15221
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15221
> [ticket/15221] add missing commas

- phpBB/styles/prosilver/theme/bidi.css
- phpBB/styles/prosilver/theme/content.css
- phpBB/styles/prosilver/theme/icons.css
PHPBB3-15213
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15213
> [ticket/15213] Fix stylelint failures

- phpBB/includes/acp/acp_extensions.php
For the master branch only.
Fixes the #4815 merge bug.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15220">PHPBB3-15220</a>.
> [ticket/15220] Fix undefined variable $phpbb_root_path in acp_extensions.php

- phpBB/phpbb/db/migration/data/v31x/add_latest_topics_index.php
PHPBB3-15226
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15226
> [ticket/15226] Add index for latest topics to topics table

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/search_results.html
PHPBB3-14996
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14996
> [ticket/14996] Add Event for search_results_topic_title_after

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/mcp_topic.html
Add 2 events:
mcp_topic_postrow_post_subject_before
mcp_topic_postrow_post_subject_after
PHPBB3-15020
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15020
> [ticket/15020] Add Event for mcp_topic_postrow_post_subject

- phpBB/styles/prosilver/template/ajax.js
PHPBB3-15056
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15056
> [ticket/15056] Update subforum icons with Mark forums read

- phpBB/styles/prosilver/theme/content.css
[Old PR](https://github.com/phpbb/phpbb/pull/4819)
Checklist:
[PHPBB3-15212](https://tracker.phpbb.com/browse/PHPBB3-15212)
> [ticket/15212] Fix code box double horizontal scrollbars

- phpBB/includes/functions_content.php
https://tracker.phpbb.com/browse/PHPBB3-15107
PHPBB3-15107
Checklist:
> [ticket/15107] Add message_parser to event

- .travis.yml
- phpBB/phpbb/db/migration/data/v32x/user_notifications_table_index_p1.php
- phpBB/phpbb/db/migration/data/v32x/user_notifications_table_index_p2.php
- phpBB/phpbb/db/migration/data/v32x/user_notifications_table_index_p3.php
- phpBB/phpbb/db/migration/data/v32x/user_notifications_table_indexes.php
- phpBB/phpbb/db/migration/data/v32x/user_notifications_table_remove_duplicates.php
- phpBB/phpbb/db/migration/data/v32x/user_notifications_table_temp_index.php
- phpBB/phpbb/db/migration/data/v32x/user_notifications_table_unique_index.php
- phpBB/phpbb/db/tools/tools.php
Testing to see if travis issues will be fixed or at least improved by this.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14992
> [ticket/14992] Improve user_notifications table performance

- phpBB/includes/mcp/mcp_main.php
PHPBB3-15131
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15131
> [ticket/15131] Add variable to the 'core.mcp_main_modify_fork_sql' event

- phpBB/includes/mcp/mcp_main.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15132
> [ticket/15132] Add variable to the 'core.mcp_main_modify_shadow_sql' event

- phpBB/includes/functions_messenger.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15199">PHPBB3-15199</a>.
> [ticket/15199] Add core event to the messenger send() function

- phpBB/phpbb/help/controller/help.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15200">PHPBB3-15200</a>.
> [ticket/15200] Allow extensions using custom templates for help/faq controllers

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/forumlist_body.html
- phpBB/styles/subsilver2/template/forumlist_body.html
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15205">PHPBB3-15205</a>.
> [ticket/15205] Add template events prepending/appending subforum link

- phpBB/includes/ucp/ucp_groups.php
- phpBB/phpbb/avatar/driver/gravatar.php
- phpBB/styles/prosilver/template/notification_dropdown.html
- phpBB/styles/prosilver/theme/common.css
Checklist:
PHPBB3-15234
https://tracker.phpbb.com/browse/PHPBB3-15234
> [ticket/15234] quickfix notification avatar sizes

- phpBB/includes/mcp/mcp_ban.php
- phpBB/includes/mcp/mcp_post.php
- phpBB/memberlist.php
- phpBB/posting.php
- phpBB/viewonline.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15237
PHPBB3-15237
> [ticket/15237] Fix unguarded includes to functions_user

- phpBB/config/console.yml
- phpBB/config/cron.yml
- phpBB/config/password.yml
- phpBB/language/en/cli.php
- phpBB/phpbb/console/command/fixup/update_hashes.php
- phpBB/phpbb/cron/task/core/update_hashes.php
- phpBB/phpbb/db/migration/data/v31x/update_hashes.php
PHPBB3-15219
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15219
> [ticket/15219] Update hashes to bcrypt with cron

- phpBB/config/default/container/services_console.yml
- phpBB/config/default/container/services_cron.yml
- phpBB/config/default/container/services_password.yml
- phpBB/language/en/cli.php
- phpBB/phpbb/console/command/fixup/update_hashes.php
- phpBB/phpbb/cron/task/core/update_hashes.php
- phpBB/phpbb/db/migration/data/v31x/update_hashes.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15219
> [ticket/15219] Update hashes to bcrypt with cron -- Rhea

- phpBB/phpbb/config/config.php
- phpBB/phpbb/lock/db.php
- phpBB/phpbb/lock/flock.php
Add additional check to flock.php and db.php to ensure lock aquiring.
PHPBB3-11515
Checklist:
Tracker ticket (set the ticket ID to 11515):
https://tracker.phpbb.com/browse/PHPBB3-11515
> [ticket/11515] Extra check after acquiring locks.

- phpBB/composer.json
- phpBB/composer.lock
PHPBB3-15178
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15178
> [ticket/15178] Update dependencies for 3.1.x

- phpBB/composer.json
- phpBB/composer.lock
- phpBB/phpbb/console/command/update/check.php
- phpBB/phpbb/template/twig/lexer.php
- phpBB/phpbb/template/twig/loader.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15179
> [ticket/15179] Update dependencies and fix compatibility with newer twig

- phpBB/phpbb/console/command/extension/list_available.php
For master only.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-12345">PHPBB3-15179</a>.
> [ticket/15179] Fix indentation

- phpBB/language/en/install.php
- phpBB/phpbb/install/helper/database.php
PHPBB3-15243
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15243
> [ticket/15243] Check permissions before installing with SQLite

- phpBB/adm/style/acp_profile.html
- phpBB/docs/events.md
Event to place code in Profile Field configuration screen, as additional information for 
Contact Profile Fields.
PHPBB-15241
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15241
> [ticket/15241] Add ACP template event acp_profile_contact_last

- phpBB/posting.php
For 3.2/master only.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15252">PHPBB3-15252</a>.
> [ticket/15252] Fix editing a topic with poll by user not permitted to edit poll

- phpBB/phpbb/user.php
PHPBB3-15217
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15217
> [ticket/15217] Add core.user_format_date_override event

- phpBB/config/default/container/services_console.yml
- phpBB/language/en/cli.php
- phpBB/phpbb/console/command/fixup/fix_left_right_ids.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15238">PHPBB3-15238</a>.
> [ticket/15238] Add console command to fix forums/modules left/right IDs

- phpBB/install/phpbbcli.php
- phpBB/install/startup.php
PHPBB3-15203
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15203
> [ticket/15203] Include missing constants in web installer

- phpBB/phpbb/cache/driver/memcache.php
- phpBB/phpbb/cache/driver/memcached.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15246">PHPBB3-15246</a>.
> [ticket/15246] Allow use of Unix socket as memcache(d) host

- phpBB/includes/mcp/mcp_topic.php
PHPBB3-15250
Checklist:
Tracker ticket (set the ticket ID to **PHPBB3-15250**):
https://tracker.phpbb.com/browse/PHPBB3-15250
> [ticket/15250] Add core event to MCP at the end of merge_posts

- phpBB/phpbb/help/manager.php
Allow TraceableEventDispatcher for webprofiler
PHPBB3-15251
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15251
> [ticket/15251] Use dispatcher_interface in help manager

- phpBB/posting.php
Fixes is_authed and error not behaving as expected by extensions.
PHPBB-15248
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15248
> [ticket/15248] Make use of event parameters of core.modify_posting_auth

- phpBB/phpbb/session.php
PHPBB3-14982
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14982
> [ticket/14982] Always do a ban check except on contact me form

- phpBB/includes/functions_posting.php
- phpBB/viewtopic.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15186">PHPBB3-15186</a>.
> [ticket/15186] Fully implement the force_delete_allowed feature

- vagrant/after.sh
PHPBB3-15269
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15269
> [ticket/15269] Set development environment and enable all debugs when installing with vagrant

- .travis.yml
PHPBB3-15285
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15285
> [ticket/15285] Updates .travis.yml to fix builds issues

- phpBB/adm/style/acp_board.html
- phpBB/adm/style/installer_form.html
- phpBB/phpbb/install/helper/iohandler/ajax_iohandler.php
- phpBB/phpbb/install/module/update_filesystem/task/download_updated_files.php
- phpBB/phpbb/install/module/update_filesystem/task/file_check.php
- phpBB/phpbb/install/module/update_filesystem/task/show_file_status.php
PHPBB3-15293
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15293
> [ticket/15293] Prevent continuing to database update on incomplete file update

- .travis.yml
For master only.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-14972">PHPBB3-14972</a>.
> [ticket/14972] Add PHP 7.2 to the test matrix

- phpBB/phpbb/di/service_collection.php
- tests/di/service_collection_test.php
PHPBB3-15258
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15258
> [ticket/15258] Adds a method to get a service by class in service_collection

- .travis.yml
- travis/setup-database.sh
PHPBB3-15295
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15295
> [ticket/15295] Restore tests on mysql and myisam

- phpBB/phpbb/cache/driver/memcached.php
PHPBB3-15303
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15303
> [ticket/15303] Correctly refer to $memcached and not $memcache

- phpBB/composer.json
- phpBB/composer.lock
https://github.com/s9e/TextFormatter/releases/tag/0.11.0
PHPBB3-15304
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15304
> [ticket/15304] Update s9e/text-formatter dependency

- phpBB/styles/prosilver/theme/content.css
PHPBB3-15292
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15292
> [ticket/15292] Reduce bluriness for forum and topic icons

- .travis.yml
- phpBB/config/default/container/services.yml
- phpBB/config/default/container/services_files.yml
- phpBB/config/default/container/services_storage.yml
- phpBB/language/en/common.php
- phpBB/phpbb/files/filespec_storage.php
- phpBB/phpbb/storage/adapter/adapter_interface.php
- phpBB/phpbb/storage/adapter/local.php
- phpBB/phpbb/storage/adapter_factory.php
- phpBB/phpbb/storage/provider/local.php
- phpBB/phpbb/storage/provider/provider_interface.php
- phpBB/phpbb/storage/storage.php
- tests/storage/adapter/local_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15287
> [ticket/15287] Factory to build storage from DI

- phpBB/phpbb/cache/driver/apcu.php
- tests/RUNNING_TESTS.md
- tests/cache/apcu_driver_test.php
Add new cache driver apcu.php (based closely on existing APC cache driver)
Add new unit test apcu_driver_test.php for the new driver
Update RUNNING_TESTS.md to clarify requirements for apc, apcu and apc_bc extensions
and add a couple of general hints to RUNNING_TESTS.md
PHPBB3-15247
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15247
> [PHPBB3-15247] Add support for php v7 APCu cache API

- phpBB/phpbb/db/extractor/postgres_extractor.php
- phpBB/phpbb/db/tools/postgres.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15319
> [ticket/15319] Add IF EXISTS to Postgres DROP SEQUENCE query

- phpBB/install/convert/convert.php
3.2.x/master only.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15314">PHPBB3-15314</a>.
> [ticket/15314] Fix convert class constructor

- phpBB/phpbb/event/php_exporter.php
PHPBB3-15291
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15291
> [ticket/15291] Allow short array notation in event declarations

- phpBB/styles/prosilver/theme/bidi.css
PHPBB3-15336
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15336
> [ticket/15336] Fix travis fail in bidi.css

- phpBB/phpbb/console/command/extension/enable.php
> [ticket/15349] Check if an extension if enableable before enable with CLI

- phpBB/language/en/cli.php
- phpBB/phpbb/install/module/install_finish/task/install_extensions.php
PHPBB3-15346
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15346
> [ticket/15346] Check if extension is enableable during install

- .stylelintrc
- package.json
- phpBB/adm/style/admin.css
- phpBB/styles/prosilver/template/memberlist_team.html
- phpBB/styles/prosilver/theme/content.css
Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-15344
https://tracker.phpbb.com/browse/PHPBB3-15344
> [ticket/15344] update and fix stylelint

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/viewtopic_body.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15334
> [ticket/15334] Add template event viewtopic_topic_title_before

- phpBB/bin/phpbbcli.php
Fix language by adding set_default_language
PHPBB3-15317
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15317
> [ticket/15317] Fix phpbbcli language

- phpBB/assets/javascript/core.js
PHPBB3-15332
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15332
> [ticket/15332] Don't remove dark background if fadedark is false

- phpBB/phpbb/log/log.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15327">PHPBB3-15327</a>.
> [ticket/15327] Add post anchor to the log postlink

- phpBB/docs/events.md
- phpBB/includes/functions_posting.php
- phpBB/includes/functions_user.php
- phpBB/includes/message_parser.php
- phpBB/memberlist.php
- phpBB/posting.php
- phpBB/styles/prosilver/template/posting_attach_body.html
- phpBB/viewforum.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15324">PHPBB3-15324</a>.
> [ticket/15324] Add more core and template events

- phpBB/assets/javascript/core.js
PHPBB3-15333
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15333
> [ticket/15333] Call callback when confirm dialog is canceled

- phpBB/styles/prosilver/template/forumlist_body.html
- phpBB/styles/prosilver/theme/content.css
Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-15343
https://tracker.phpbb.com/browse/PHPBB3-15343
> [ticket/15343] Fix forum row inner list

- phpBB/styles/prosilver/theme/buttons.css
Checklist:
PHPBB3-15262
https://tracker.phpbb.com/browse/PHPBB3-15262
> [ticket/15262] Update button font-weight

- phpBB/styles/prosilver/theme/colours.css
- phpBB/styles/prosilver/theme/common.css
- phpBB/styles/prosilver/theme/content.css
PHPBB3-15308
Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-15308
https://tracker.phpbb.com/browse/PHPBB3-15308
> [ticket/15308] Remove !important from pagination css class

- phpBB/includes/bbcode.php
- phpBB/phpbb/textformatter/s9e/factory.php
- tests/text_formatter/s9e/factory_test.php
- tests/text_formatter/s9e/fixtures/styles/prosilver/template/bbcode.html
For 3.2/master (as I assume 3.1.x won't get any fixes/improvements anymore because of EOM).
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15323">PHPBB3-15323</a>.
> [ticket/15323] Allow Twig syntax in bbcode.html

- phpBB/docs/coding-guidelines.html
- phpBB/includes/functions_compatibility.php
- phpBB/language/en/common.php
PHPBB3-15350
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15350
> [ticket/15350] Changes outdated wiki-link for plural-rules to new docs/

- phpBB/styles/prosilver/template/viewforum_body.html
PHPBB3-7488
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-7488
> [ticket/7488] Display no forums message if user can't see forums of category

- phpBB/includes/message_parser.php
PHPBB3-7845
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-7845
> [ticket/7845] Ensure config script path is not empty

- phpBB/phpbb/console/command/fixup/update_hashes.php
- phpBB/phpbb/cron/task/core/update_hashes.php
PHPBB3-15347
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15347
> [ticket/15347] Use single quotes in update hashes query

- phpBB/phpbb/template/twig/extension.php
PHPBB3-15330
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15330
> [ticket/15330] Twig function to know if a language string is defined

- phpBB/phpbb/session.php
PHPBB3-15351
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15351
> [ticket/15351] Fix missing global usage

- phpBB/includes/acp/acp_update.php
PHPBB3-15355
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15355
> [ticket/15355] Remove version field when no update is available

- phpBB/assets/javascript/editor.js
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15149
> [ticket/15149] Fix Ctrl+Submit action on posting

- phpBB/phpbb/textformatter/s9e/factory.php
PHPBB3-15301
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15301
> [ticket/15301] Set quotes' nesting limit when configuring a parser

- phpBB/phpbb/textformatter/s9e/factory.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15290
> [ticket/15290] Add core.text_formatter_s9e_configure_finalize event

- phpBB/styles/prosilver/theme/colours.css
Cleanup the colours.css file of deprecated classes and refactor all the colors for better consistency utilizing SASS vars and color functions http://codepen.io/hanakin/pen/oZLLyx?editors=0100
Original PR convo: 
https://github.com/phpbb/phpbb/pull/3867
Screenshots:
https://www.dropbox.com/sh/eeqqn878b700f3x/AAD0tn_Kt9bfJJ9Rd6YBtumya?dl=0
Checklist:
PHPBB3-14131
https://tracker.phpbb.com/browse/PHPBB3-14131
> [ticket/14131] Completely overhaul all colors in Colours.css

- phpBB/adm/style/acp_board.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15353
> [ticket/15353] Fix html in acp_board.html

- phpBB/config/default/container/services_event.yml
- phpBB/language/en/common.php
- phpBB/phpbb/event/kernel_exception_subscriber.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14933
> [ticket/14933] Make "route not found" more user-friendly

- phpBB/adm/style/acp_users.html
- phpBB/docs/events.md
- phpBB/includes/acp/acp_users.php
Includes both PHP and Template events.
PHPBB3-15307
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15307
> [ticket/15307] Extensions may add modes to acp_users

- phpBB/styles/prosilver/theme/content.css
Checklist:
PHPBB3-15271
https://tracker.phpbb.com/browse/PHPBB3-15271
Before:
After:
> [ticket/15271] align forum and topic row columns

- phpBB/styles/prosilver/theme/responsive.css
PHPBB3-13214
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13214
> [ticket/13214] Remove px after 0 from padding property

- phpBB/phpbb/db/tools/mssql.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15368
> [ticket/15368] Correct function reference in MSSQL db tools

- phpBB/phpbb/cache/driver/file.php
PHPBB3-15365
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15365
> [ticket/15365] Fix invalidating OPcache

- phpBB/phpbb/cron/task/text_reparser/reparser.php
- phpBB/phpbb/db/migration/data/v320/text_reparser.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15379
> [ticket/15379] Fix assignments in reparser cron job

- phpBB/phpbb/search/fulltext_sphinx.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15367">PHPBB3-15367</a>.
> [ticket/15367] Escape special characters in Sphinx search backend

- phpBB/includes/ucp/ucp_notifications.php
PHPBB3-15362
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15362
> [ticket/15362] Fix colspan in notification options table

- phpBB/includes/acp/acp_board.php
- phpBB/phpbb/feed/topics_active.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14629
> [PHPBB3-14629] round() the log() explicitly to a proper integer

- phpBB/styles/prosilver/theme/bidi.css
- phpBB/styles/prosilver/theme/colours.css
- phpBB/styles/prosilver/theme/common.css
- phpBB/styles/prosilver/theme/cp.css
- phpBB/styles/prosilver/theme/icons.css
- phpBB/styles/prosilver/theme/responsive.css
PHPBB3-15071
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15071
> [ticket/15071] Consolidate all media queries

- phpBB/phpbb/template/twig/loader.php
- tests/functional/extension_controller_test.php
PHPBB3-15377
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15377
> [ticket/15377] Fix INCLUDECSS and INCLUDEJS

- phpBB/viewtopic.php
PHPBB3-15394
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15394
> [ticket/15394] Add $user_cache

- phpBB/styles/prosilver/theme/content.css
PHPBB3-15391
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15391
> [ticket/15391] image-rendering not needed for Topic/Forum imgs

- phpBB/styles/prosilver/template/memberlist_view.html
- phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
- phpBB/styles/prosilver/template/viewtopic_body.html
PHPBB3-14336
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14336
> [ticket/14336] add title text to online status icon

- phpBB/includes/functions.php
- tests/bbcode/parser_test.php
- tests/bbcode/url_bbcode_test.php
- tests/functions/make_clickable_email_test.php
- tests/functions/make_clickable_test.php
- tests/text_formatter/s9e/factory_test.php
PHPBB3-15172
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15172
> [ticket/15172] Fix redirection to wrong port

- phpBB/includes/acp/acp_users.php
PHPBB3-15306
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15306
> [ticket/15306] Error and missing data in core.acp_users_profile_validate

- .stylelintrc
- phpBB/styles/prosilver/theme/base.css
- phpBB/styles/prosilver/theme/bidi.css
- phpBB/styles/prosilver/theme/buttons.css
- phpBB/styles/prosilver/theme/common.css
- phpBB/styles/prosilver/theme/content.css
- phpBB/styles/prosilver/theme/cp.css
- phpBB/styles/prosilver/theme/forms.css
- phpBB/styles/prosilver/theme/icons.css
- phpBB/styles/prosilver/theme/links.css
- phpBB/styles/prosilver/theme/plupload.css
- phpBB/styles/prosilver/theme/print.css
- phpBB/styles/prosilver/theme/responsive.css
This should be the last major overhaul for standardization but the one that may require the largest review so I want to get it up early to allow ample time for critiques and bug fixes
to be merged after https://github.com/phpbb/phpbb/pull/4726, https://github.com/phpbb/phpbb/pull/4727
Checklist:
PHPBB3-14976
https://tracker.phpbb.com/browse/PHPBB3-14976
> [ticket/14976] Convert all ems to px

- phpBB/composer.json
- phpBB/composer.lock
PHPBB3-15357
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15357
> [ticket/15357] Requires composer/installers in phpBB core for extensions

- phpBB/phpbb/cache/driver/memcached.php
PHPBB3-15401
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15401
> [ticket/15401] Use separate constant for memcached driver config

- phpBB/includes/acp/info/acp_storage.php
- phpBB/install/schemas/schema_data.sql
- phpBB/language/en/acp/permissions_phpbb.php
- phpBB/phpbb/db/migration/data/v330/acp_storage_module.php
- phpBB/phpbb/db/migration/data/v330/add_storage_permission.php
- phpBB/phpbb/permissions.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15289
> [ticket/15289] Allow to configure storage from acp

- phpBB/adm/style/admin.css
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15411
> [ticket/15411] Use lowercase in hex color code

- phpBB/includes/acp/acp_users.php
PHPBB3-15409
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15409
> [ticket/15409] Add u_action to core.acp_users_overview_run_quicktool

- phpBB/index.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15267
> [ticket/15267] Hide birthday list if permission wasn't granted

- phpBB/viewtopic.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15060
> [ticket/15060] Set correct forum id in user session data if f= is missing

- phpBB/config/default/container/services_console.yml
- phpBB/phpbb/console/exception_subscriber.php
PHPBB3-15298
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15298
> [ticket/15298] Never suppress exception trace when using CLI

- phpBB/phpbb/template/twig/extension.php
PHPBB3-15366
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15366
> [ticket/15366] Remove useless code

- phpBB/config/default/container/services_feed.yml
- phpBB/phpbb/feed/feed_quote_helper.php
- phpBB/phpbb/feed/helper.php
- phpBB/phpbb/feed/quote_helper.php
- tests/feed/attachments_base_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15245
> [ticket/15245] Fix images in feeds when accessing via app.php

- phpBB/viewforum.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15374">PHPBB3-15374</a>.
> [ticket/15374] Add core event to modify page title in viewforum.php

- tests/feed/attachments_base_test.php
PHPBB3-15245
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15245
> [ticket/15245] Fix tests after merging into master

- phpBB/language/en/acp/board.php
PHPBB3-15381
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15381
> [ticket/15381] Better explain CONTACT_US_ENABLE_EXPLAIN

- phpBB/phpbb/log/log.php
PHPBB3-13150
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13150
> [ticket/13150] Add core.phpbb_log_get_topic_auth_sql_after

- phpBB/includes/functions_display.php
- phpBB/install/schemas/schema_data.sql
- phpBB/language/en/acp/permissions_phpbb.php
- phpBB/language/en/viewforum.php
- phpBB/phpbb/db/migration/data/v32x/f_list_topics_permission_add.php
- phpBB/phpbb/pagination.php
- phpBB/phpbb/permissions.php
- phpBB/styles/prosilver/template/viewforum_body.html
- phpBB/viewforum.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15372
> [ticket/15372] Add permission for listing topics without being able to read them

- gulpfile.js
- package.json
Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-15403
https://tracker.phpbb.com/browse/PHPBB3-15403
> [ticket/15403] Add useful front-end build tools

- phpBB/composer.lock
Fixes various issues with JPEG, TIFF, and adds WebP support.
PHPBB3-15133
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15133
> [ticket/15133] Update fast-image-size to 1.1.4

- phpBB/styles/prosilver/theme/content.css
Refactored version of https://github.com/phpbb/phpbb/pull/4983 with fixed commit messages.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15387
> [ticket/15387] Make vertical bars full height on board index forum rows

- phpBB/includes/ucp/ucp_pm_viewmessage.php
PHPBB3-15111
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15111
> [ticket/15111] Fix the typo in ucp_pm_view_messsage

- phpBB/styles/prosilver/template/viewforum_body.html
PHPBB3-15423
https://tracker.phpbb.com/browse/PHPBB3-15423
> [ticket/15423] Fix wrong title for topic's "Unappproved posts" icon

- phpBB/styles/prosilver/template/ucp_notifications.html
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15415">PHPBB3-15415</a>.
> [ticket/15415] Fix styling in ucp_notifications.html

- phpBB/styles/prosilver/theme/common.css
- phpBB/styles/prosilver/theme/content.css
- phpBB/styles/prosilver/theme/plupload.css
- phpBB/styles/prosilver/theme/responsive.css
Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-15414
https://tracker.phpbb.com/browse/PHPBB3-15414
> [ticket/15414] Remove useless redundant css properties

- phpBB/phpbb/template/context.php
- tests/template/template_test.php
- tests/template/templates/loop_nested.html
Refactored version of #4634 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14994
> [ticket/14994] Refactor template->assign_block_var

- phpBB/styles/prosilver/theme/content.css
PHPBB3-15387
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15387
> [ticket/15387] Fix CSS for master branch

- phpBB/adm/style/acp_attachments.html
- phpBB/includes/acp/acp_attachments.php
PHPBB3-15041
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15041
> [ticket/15041] Add pagination to orphaned attachments

- phpBB/styles/prosilver/theme/bidi.css
Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-15406
https://tracker.phpbb.com/browse/PHPBB3-15406
> [ticket/15406] Fix/standardize bidi.css classes

- phpBB/styles/prosilver/template/ucp_pm_viewmessage_print.html
- phpBB/styles/prosilver/template/viewtopic_print.html
- phpBB/styles/prosilver/theme/bidi.css
- phpBB/styles/prosilver/theme/print.css
I hate css.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15195
> [ticket/15195] Fix code block in rtl print version

- phpBB/styles/prosilver/theme/buttons.css
- phpBB/styles/prosilver/theme/colours.css
- phpBB/styles/prosilver/theme/common.css
- phpBB/styles/prosilver/theme/content.css
- phpBB/styles/prosilver/theme/forms.css
- phpBB/styles/prosilver/theme/links.css
- phpBB/styles/prosilver/theme/responsive.css
Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-15404
https://tracker.phpbb.com/browse/PHPBB3-15404
> [ticket/15404] autoprefix browser compatibility

- phpBB/adm/style/installer_form.html
- phpBB/phpbb/install/helper/iohandler/ajax_iohandler.php
- phpBB/phpbb/install/module/update_filesystem/task/diff_files.php
- phpBB/phpbb/install/module/update_filesystem/task/download_updated_files.php
PHPBB3-15353
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15353
> [ticket/15353] Make sure users can continue update after merging file diff

- phpBB/includes/acp/acp_styles.php
- phpBB/install/schemas/schema_data.sql
- phpBB/phpbb/db/migration/data/v32x/update_prosilver_bitfield.php
- phpBB/phpbb/textformatter/s9e/factory.php
- phpBB/styles/prosilver/style.cfg
- tests/functional/posting_test.php
PHPBB3-15171
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15171
> [ticket/15171] Replace all BBCode templates by default

- phpBB/docs/CREDITS.txt
PHPBB3-15461
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15461
> [ticket/15461] Add Derky to the list of contributors.

- phpBB/phpbb/textreparser/base.php
- tests/text_reparser/base_test.php
- tests/text_reparser/fixtures/base.xml
PHPBB3-15464
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15464
> [ticket/15464] Detect BBCodes in uppercase when reparsing

- phpBB/docs/CREDITS.txt
PHPBB3-15463
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15463
> [ticket/15463] Add MichaelC and Hanakin to the dev credits

- phpBB/phpbb/files/filespec_storage.php
- phpBB/phpbb/files/types/form_storage.php
PHPBB3-14972
Checklist:
Parent: #4862 
https://tracker.phpbb.com/browse/PHPBB3-14972
> [ticket/14972] replace all occurrences of sizeof() with the count()

- phpBB/styles/prosilver/theme/content.css
PHPBB3-15470
Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-15470
https://tracker.phpbb.com/browse/PHPBB3-15470
> [ticket/15470] Add font-size prop to .attachbox

- phpBB/styles/prosilver/template/ucp_footer.html
PHPBB3-15455
Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-15455
https://tracker.phpbb.com/browse/PHPBB3-15455
> [ticket/15455] Fix UCP padding issues

- phpBB/search.php
PHPBB3-15476
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15476
> [ticket/15476] Add event core.search_modify_post_row

- phpBB/includes/ucp/ucp_register.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15484
> [ticket/15484] Remove empty lines from includes/ucp/ucp_register.php

- phpBB/assets/javascript/core.js
PHPBB3-15478
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15478
> [ticket/15478] Fix core.js $loadingIndicator JavaScript errors

- phpBB/phpbb/search/fulltext_mysql.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15224">PHPBB3-15224</a>.
> [ticket/15224] Fix some MySQL fulltext index searching errors

- phpBB/phpbb/textformatter/s9e/factory.php
- tests/text_formatter/s9e/factory_test.php
- tests/text_formatter/s9e/fixtures/styles/unsafe/template/bbcode.html
- tests/text_formatter/s9e/fixtures/unsafe_default_bbcodes.xml
PHPBB3-15442
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15442
> [ticket/15442] Allow unsafe HTML in bbcode.html

- vagrant/after.sh
PHPBB3-15400
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15400
> [ticket/15400] Make app.php routes work in vagrant

- phpBB/includes/functions_user.php
Additionally, fix some typos in two other events docblocks.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15486">PHPBB3-15486</a>.
> [ticket/15486] Add core event to the user_add() to modify notifications data

- phpBB/adm/style/acp_prune_forums.html
- phpBB/docs/events.md
- phpBB/includes/acp/acp_prune.php
- phpBB/includes/functions_admin.php
PHPBB3-15471
Checklist:
Tracker ticket (set the ticket ID to **15471**):
https://tracker.phpbb.com/browse/PHPBB3-15471
> [ticket/15471] Add core events to ACP when pruning a forum

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/mcp_topic.html
PHPBB3-15452
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15452
>  [ticket/15452] Add template event mcp_topic_postrow_post_before

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/mcp_topic.html
PHPBB3-15451
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15451
> [ticket/15451] Add template event mcp_topic_postrow_attachments_before/after

- phpBB/includes/acp/acp_profile.php
PHPBB3-15447
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15447
> [ticket/15447] Add event core.acp_profile_modify_profile_row

- phpBB/includes/acp/acp_profile.php
PHPBB3-15446
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15446
> [ticket/15446] Add event core.acp_profile_action

- README.md
Update Coding  and Git  Guidelines URIs in README.md
PHPBB3-15445
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15445
> [ticket/15445] Update URIs in README.md

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/forumlist_body.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15485
> [ticket/15485] Add template event for forum images

- phpBB/includes/mcp/mcp_queue.php
PHPBB3-15454
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15454
> [ticket/15454] Add core.mcp_queue_approve_details_template

- phpBB/phpbb/db/migration/data/v30x/release_3_0_6_rc1.php
- phpBB/phpbb/db/migration/data/v30x/release_3_0_8_rc1.php
- phpBB/phpbb/db/migration/data/v310/auth_provider_oauth.php
- phpBB/phpbb/db/migration/data/v310/contact_admin_acp_module.php
- phpBB/phpbb/db/migration/data/v310/dev.php
- phpBB/phpbb/db/migration/data/v310/extensions.php
- phpBB/phpbb/db/migration/data/v310/notifications.php
- phpBB/phpbb/db/migration/data/v310/softdelete_mcp_modules.php
- phpBB/phpbb/db/migration/data/v320/add_help_phpbb.php
- phpBB/phpbb/db/migration/data/v330/acp_storage_module.php
- phpBB/phpbb/db/migration/tool/module.php
- tests/dbal/migrator_tool_module_test.php
3.2 PR is here: #4971 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15339
> [ticket/15339] Use manual method when adding modules

- phpBB/composer.lock
PHPBB3-15179
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15179
> [ticket/15179] Update dependencies for 3.2.x

- .appveyor.yml
- tests/test_framework/phpbb_functional_test_case.php
PHPBB3-15055
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15055
> [ticket/15055] Display content on unexpted server error

- .travis.yml
- travis/setup-phpbb.sh
- travis/setup-webserver.sh
Let's speed up our testing a little bit by removing the always failing HHVM build.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15499
> [ticket/15499] Remove HHVM from Travis build matrix

- phpBB/phpbb/db/migration/data/v32x/fix_user_styles.php
- phpBB/phpbb/db/migration/data/v32x/merge_duplicate_bbcodes.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15502">PHPBB3-15502</a>.
> [ticket/15502] Fix migrations

- phpBB/phpbb/template/assets_bag.php
- tests/template/template_includecss_test.php
- tests/template/template_includejs_test.php
PHPBB3-15099
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15099
> [ticket/15099] Remove type attr from INCLUDECSS and INCLUDEJS

- phpBB/phpbb/textreparser/plugins/poll_title.php
- tests/text_reparser/plugins/fixtures/polls.xml
PHPBB3-15512
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15512
> [ticket/15512] Avoid reparsing non-existent polls

- phpBB/docs/INSTALL.html
- phpBB/docs/README.html
PHPBB3-15500
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15500
> [ticket/15500] Updates PHP requirements to 5.4.7+ in docs/

- phpBB/composer.json
PHPBB3-15525
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15525
> [ticket/15525] Update to valid SPDX license name GPL-2.0-only

- .github/PULL_REQUEST_TEMPLATE.md
PHPBB3-15532
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15532
> [ticket/15532] PR-template: Updates the links for guidelines and message format

- phpBB/adm/style/acp_groups.html
- phpBB/includes/acp/acp_groups.php
PHPBB3-15529
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15529
> [ticket/15529] Color groups in ACP

- phpBB/adm/style/acp_styles.html
- phpBB/includes/acp/acp_styles.php
- phpBB/language/en/acp/styles.php
PHPBB3-15528
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15528
> [ticket/15528] Display style phpBB version

- phpBB/phpbb/db/migration/data/v32x/merge_duplicate_bbcodes.php
PHPBB3-15526
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15526
> [ticket/15526] Cast bbcode id to INT in merge bbcodes migration 

- phpBB/config/default/container/services_text_formatter.yml
- phpBB/language/en/acp/common.php
- phpBB/phpbb/textformatter/s9e/factory.php
- tests/test_framework/phpbb_test_case_helpers.php
- tests/text_formatter/s9e/factory_test.php
- tests/text_formatter/s9e/fixtures/malformed_bbcode.xml
PR is against 3.2.x. Note that it adds a dependency to the service.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15531
> [ticket/15531] Log malformed BBCodes

- phpBB/styles/prosilver/template/viewtopic_topic_tools.html
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15533">PHPBB3-15533</a>.
> [ticket/15533] Fix typo in viewtopic_topic_tools.html

- phpBB/adm/style/acp_ext_list.html
- phpBB/adm/style/acp_language.html
- phpBB/adm/style/acp_styles.html
For 3.2.x only as for the master branch this is not the case.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15534">PHPBB3-15534</a>.
> [ticket/15534] Update extensions database link in ACP for phpBB 3.2

- phpBB/language/en/install.php
PHPBB3-14936
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14936
> [ticket/14936] Add missing error message INST_ERR_DB to language files

- phpBB/viewtopic.php
PHPBB3-15535
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15535
> [ticket/15535] Add S_FIRST_POST to postrow in viewtopic

- phpBB/adm/style/admin.css
- phpBB/adm/style/permission_mask.html
- phpBB/adm/style/tooltip.js
- phpBB/assets/javascript/core.js
Varius fixes to css and js for correct
displaying permission role combbox in RTL mode
PHPBB3-15435
PHPBB3-15492
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15435
https://tracker.phpbb.com/browse/PHPBB3-15492
> [ticket/15492] Fix permission role combobox in RTL

- phpBB/phpbb/auth/provider/oauth/oauth.php
PHPBB3-15398
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15398
> [ticket/15398] Add core.oauth_login_after_check_if_provider_id_has_match

- phpBB/assets/javascript/core.js
PHPBB3-15522
Master PR: https://github.com/phpbb/phpbb/pull/5136
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15522
> [ticket/15522] Allow multiple color palettes on one page

- phpBB/phpbb/avatar/driver/upload.php
[ticket/15547] Add file object to event
Add file object to core.avatar_driver_upload_move_file_before.
PHPBB3-15547
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15547
> [ticket/15547] Add file object to event

- phpBB/phpbb/search/fulltext_mysql.php
- phpBB/phpbb/search/fulltext_native.php
- phpBB/phpbb/search/fulltext_postgres.php
- phpBB/phpbb/search/fulltext_sphinx.php
PHPBB3-15537
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15537
> [ticket/15537] Add core.search_(native|mysql|postgres|sphinx)_index_before

- phpBB/phpbb/db/driver/driver.php
Fixes PHPBB3-15520
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15520
> [ticket/15520] sql_build_query build subquery

- phpBB/styles/prosilver/theme/content.css
PHPBB3-15535
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15535
> [ticket/15535] Fix quote font sizes

- tests/RUNNING_TESTS.md
PHPBB3-15516
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15516
> [ticket/15516] Add instructions for running UI tests

- phpBB/phpbb/install/helper/database.php
PHPBB3-15563
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15563
> [ticket/15563] Check if database file is writable only if exists

- phpBB/docs/CREDITS.txt
PHPBB3-15466
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15466
> [ticket/15466] Update CREDITS.txt to reflect Nils leaving [ci skip]

- phpBB/composer.lock
PHPBB3-15568
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15568
> [ticket/15568] Update dependencies to latest versions

- phpBB/phpbb/file_downloader.php
PHPBB3-15570
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15570
> [ticket/15570] Allow file downloader to use TLS greater than 1.0

- .appveyor.yml
PHPBB3-15604
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15604
> [ticket/15604] Use HTTPS links for download SQL server drivers

- phpBB/styles/prosilver/theme/content.css
PHPBB3-15647
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15647
> [ticket/15647] fix post font-size and line-height

- phpBB/config/default/container/services_attachment.yml
- phpBB/config/default/container/services_storage.yml
- phpBB/docs/lighttpd.sample.conf
- phpBB/docs/nginx.sample.conf
- phpBB/download/file.php
- phpBB/includes/acp/acp_attachments.php
- phpBB/includes/constants.php
- phpBB/includes/functions.php
- phpBB/includes/functions_acp.php
- phpBB/includes/functions_content.php
- phpBB/includes/functions_convert.php
- phpBB/includes/functions_download.php
- phpBB/includes/functions_posting.php
- phpBB/includes/functions_privmsgs.php
- phpBB/install/convertors/convert_phpbb20.php
- phpBB/install/schemas/schema_data.sql
- phpBB/phpbb/attachment/delete.php
- phpBB/phpbb/attachment/upload.php
- phpBB/phpbb/cache/service.php
- phpBB/phpbb/db/migration/data/v330/remove_attachment_download_mode.php
- phpBB/phpbb/db/migration/data/v330/storage_attachment.php
- phpBB/phpbb/files/filespec_storage.php
- phpBB/phpbb/files/types/local_storage.php
- tests/attachment/delete_test.php
- tests/attachment/fixtures/resync.xml
- tests/attachment/upload_test.php
- tests/content_visibility/delete_post_test.php
- tests/functions_user/delete_user_test.php
- tests/notification/submit_post_base.php
- tests/privmsgs/delete_user_pms_test.php
Checklist:
Depends on #4895 
https://tracker.phpbb.com/browse/PHPBB3-15286
> [ticket/15286] Use storage in attachments

- phpBB/phpbb/storage/adapter/adapter_interface.php
- phpBB/phpbb/storage/adapter/local.php
- phpBB/phpbb/storage/storage.php
PHPBB3-15553
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15553
> [ticket/15553] Add method to get direct link

- phpBB/phpbb/debug/error_handler.php
PHPBB3-15504
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15504
> [ticket/15504] Fix warning message

- phpBB/language/en/captcha_recaptcha.php
PHPBB3-15629
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15629
> [ticket/15629] Add info to RECAPTCHA_LANG and change to en-GB

- phpBB/language/en/acp/board.php
PHPBB3-15630
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15630
> [ticket/15630] ACP_COOKIE_SETTINGS_EXPLAIN change <b> to <strong>

- phpBB/includes/acp/acp_storage.php
- phpBB/install/schemas/schema_data.sql
- phpBB/language/en/acp/storage.php
- phpBB/phpbb/db/migration/data/v330/storage_adapter_local_depth.php
- phpBB/phpbb/storage/adapter/local.php
- phpBB/phpbb/storage/provider/local.php
- tests/storage/adapter/local_test.php
PHPBB3-15371
Checklist:
Depends on #4916 #4899 
https://tracker.phpbb.com/browse/PHPBB3-15371
> [ticket/15371] Split uploaded files into subdirectories

- phpBB/includes/mcp/mcp_queue.php
PHPBB3-15657
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15657
> [ticket/15657] Add MCP queue events

- phpBB/includes/functions.php
- tests/random/gen_rand_string_test.php
PHPBB3-15693
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15693
> [ticket/15693] Fix get_rand_string()

- phpBB/composer.json
- phpBB/composer.lock
PHPBB3-15686
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15686
> [ticket/15686] Update homestead

- phpBB/includes/functions.php
PHPBB3-15695
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15695
> [ticket/15695] Fix gen_rand_string returning less characters than expected

- phpBB/phpbb/filesystem/filesystem.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15678">PHPBB3-15678</a>.
> [ticket/15678] Fix PHP warning in filesystem.php

- phpBB/adm/style/acp_avatar_options_upload.html
- phpBB/phpbb/avatar/driver/upload.php
- phpBB/styles/prosilver/template/ucp_avatar_options_upload.html
PHPBB3-15671
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15671
> [ticket/15671] Limit accepted formats for avatar upload

- phpBB/download/file.php
PHPBB3-15688
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15688
> [ticket/15688] Fix event location in attachments download

- phpBB/assets/javascript/core.js
Fix Notification dropdown said to be not RTL compliant
this bug is related to https://github.com/phpbb/phpbb/pull/5081
PHPBB3-15613
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15613
> [ticket/15613] Fix Notification dropdown said to be not RTL compliant

- phpBB/adm/style/admin.css
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15638
PHPBB3-15638
> [ticket/15638] Add word-break for overflowing.

- phpBB/adm/style/acp_contact.html
- phpBB/adm/style/acp_groups.html
- phpBB/adm/style/acp_users_signature.html
- phpBB/assets/javascript/core.js
- phpBB/styles/prosilver/template/posting_buttons.html
- phpBB/styles/prosilver/template/ucp_groups_manage.html
PHPBB3-15522
3.2 PR: https://github.com/phpbb/phpbb/pull/5107
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15522
> [ticket/15522] Improve color palette syntax

- phpBB/styles/prosilver/theme/buttons.css
- phpBB/styles/prosilver/theme/forms.css
Fix no vertical space between format buttons
PHPBB3-15545
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15545
> [ticket/15545] Fix no vertical space between format buttons

- phpBB/styles/prosilver/theme/content.css
[master] List boxes internal corners rounded
Improve the visual style commonality by making the internal corners of the forum and topic list boxes rounded to match the rounded outer corners.
PHPBB3-15388
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15388
> [ticket/15388] List boxes internal corners rounded

- phpBB/phpbb/event/php_exporter.php
- tests/event/fixtures/extra_description.test
- tests/event/php_exporter_test.php
PHPBB3-15637
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15637
> [ticket/15637] Extract multi-line PHP event descriptions

- .github/CONTRIBUTING.md
PHPBB3-15718
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15718
> [ticket/15718] Update CONTRIBUTING.md

- phpBB/common.php
- phpBB/config/development/config.yml
- phpBB/includes/functions.php
- phpBB/phpbb/db/driver/driver.php
- phpBB/phpbb/db/driver/driver_interface.php
- phpBB/phpbb/db/driver/factory.php
- phpBB/phpbb/db/driver/mssql_odbc.php
- phpBB/phpbb/db/driver/mssqlnative.php
- phpBB/phpbb/db/driver/mysql.php
- phpBB/phpbb/db/driver/mysqli.php
- phpBB/phpbb/db/driver/oracle.php
- phpBB/phpbb/db/driver/postgres.php
- phpBB/phpbb/db/driver/sqlite3.php
- phpBB/phpbb/di/extension/container_configuration.php
- phpBB/phpbb/install/module/install_filesystem/task/create_config_file.php
- tests/mock/container_builder.php
- vagrant/after.sh
PHPBB3-12624
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-12624
> [ticket/12624] Add debug.load_time parameter

- phpBB/includes/functions_display.php
- phpBB/includes/functions_module.php
- phpBB/mcp.php
- phpBB/memberlist.php
- phpBB/phpbb/help/controller/bbcode.php
- phpBB/phpbb/help/controller/faq.php
- phpBB/search.php
- phpBB/styles/prosilver/template/navbar_header.html
- phpBB/ucp.php
- phpBB/viewonline.php
PHPBB3-12591
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-12591
> [ticket/12591] Improve breadcrumb naming and extend it's usage

- phpBB/styles/prosilver/template/navbar_header.html
PHPBB3-15606
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15606
> [ticket/15606] Hide viewprofile link when unavailable

- phpBB/viewforum.php
PHPBB3-15670
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15670
> [ticket/15670] Group forum permission: Can see forum gives NO SQL ERROR

- phpBB/phpbb/db/migrator.php
- tests/migrator/get_callable_from_step_test.php
PHPBB3-15696
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15696
> [ticket/15696] 'if' module tool should support calling other tools

- phpBB/language/en/email/newtopic_notify.txt
PHPBB3-15628
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15628
> [ticket/15628] Add topic link to newtopic_notify.txt

- phpBB/phpbb/db/migration/data/v320/add_help_phpbb.php
PHPBB3-15651
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15651
> [ticket/15651] Remove unnecessary condition

- phpBB/styles/prosilver/template/mcp_ban.html
- phpBB/styles/prosilver/template/overall_footer.html
- phpBB/styles/prosilver/template/plupload.html
- phpBB/styles/prosilver/template/posting_buttons.html
- phpBB/styles/prosilver/template/posting_smilies.html
- phpBB/styles/prosilver/template/posting_topic_review.html
- phpBB/styles/prosilver/template/simple_footer.html
- phpBB/styles/prosilver/template/ucp_agreement.html
- phpBB/styles/prosilver/template/ucp_pm_history.html
- phpBB/styles/prosilver/template/ucp_prefs_personal.html
- phpBB/styles/prosilver/template/ucp_register.html
PHPBB3-13043
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13043
> [ticket/13043] Improve HTML5

- .gitignore
PHPBB3-15694
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15694
> [ticket/15694] Ignore lang files in prosilver/theme dir

- phpBB/phpbb/avatar/driver/local.php
PHPBB3-15620
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15620
> [ticket/15620] Use separate local avatar cache file for every lang

- phpBB/includes/functions.php
PHPBB3-15618
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15618
> [ticket/15618] Display The team link only to users with permission

- phpBB/phpbb/template/twig/extension.php
PHPBB3-15666
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15666
> [ticket/15666] Language system is not fully supported in Twig

- phpBB/phpbb/template/context.php
- tests/template/context_test.php
PHPBB3-15659
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15659
> [ticket/15659] Fix retrieve_block_vars()

- phpBB/styles/prosilver/template/ucp_notifications.html
- phpBB/styles/prosilver/theme/cp.css
Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-15679
https://tracker.phpbb.com/browse/PHPBB3-15679
> [ticket/15679] notifications ucp front-page looks poor due to cp styling inheritance

- phpBB/docs/INSTALL.html
The old link pointed to 3.1 documentation
PHPBB3-15680
> [ticket/15680] Point to 3.2 documentation

- phpBB/includes/functions_download.php
PHPBB3-15286
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15286
> [ticket/15286] Download remote attachments properly

- phpBB/config/default/container/services_storage.yml
- phpBB/config/default/container/tables.yml
- phpBB/includes/acp/acp_database.php
- phpBB/includes/acp/acp_main.php
- phpBB/includes/constants.php
- phpBB/phpbb/attachment/upload.php
- phpBB/phpbb/db/migration/data/v330/storage_track.php
- phpBB/phpbb/files/filespec_storage.php
- phpBB/phpbb/storage/adapter/adapter_interface.php
- phpBB/phpbb/storage/adapter/local.php
- phpBB/phpbb/storage/exception/exception.php
- phpBB/phpbb/storage/file_info.php
- phpBB/phpbb/storage/provider/provider_interface.php
- phpBB/phpbb/storage/storage.php
- phpBB/phpbb/storage/stream_interface.php
- tests/attachment/delete_test.php
- tests/attachment/upload_test.php
- tests/avatar/manager_test.php
- tests/content_visibility/delete_post_test.php
- tests/functions_user/delete_user_test.php
- tests/notification/submit_post_base.php
- tests/privmsgs/delete_user_pms_test.php
Checklist:
Depends on #4916, also need to be updated after #4899 
https://tracker.phpbb.com/browse/PHPBB3-15342
> [ticket/15342] Track storage files

- phpBB/adm/style/acp_storage.html
- phpBB/includes/acp/acp_storage.php
- phpBB/language/en/acp/storage.php
- phpBB/phpbb/template/twig/extension.php
Checklist:
Depends on #4933 
https://tracker.phpbb.com/browse/PHPBB3-15689
> [ticket/15689] Show statistics of storages on acp_storage

- phpBB/composer.lock
PHPBB3-15677
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15677
> [ticket/15677] Update symfony  to 2.8.42, others to latest

- tests/functional/extension_acp_test.php
- tests/test_framework/phpbb_functional_test_case.php
- tests/test_framework/phpbb_ui_test_case.php
For the ```master``` branch only.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15725">PHPBB3-15725</a>.
> [ticket/15725] Fix installing ext in tests for master branch

- phpBB/includes/acp/acp_search.php
- phpBB/language/en/acp/search.php
PHPBB3-15731
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15731
> [ticket/15731] Fix language string parameters

- phpBB/phpbb/db/migration/data/v310/auth_provider_oauth.php
PHPBB3-11847
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-11847
> [ticket/11847] Add depends_on() to auth_provider_oauth

- phpBB/styles/prosilver/template/overall_footer.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15740
> [ticket/15740] Fix hardcoded Terms/Privacy

- phpBB/composer.lock
- tests/template/template_test.php
PHPBB3-15746
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15746
Requires separate PR for merging into master.
> [ticket/15746] Update symfony to 2.8.44 & others to latest

- phpBB/composer.lock
- phpBB/styles/prosilver/template/overall_footer.html
- tests/template/template_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15746
master version of #5315, depends on prep-release-3.2.3 being merged into 3.2.x.
> [ticket/15746] Update symfony & other dependencies to latest

- phpBB/composer.lock
PHPBB3-15746
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15746
> [ticket/15746] Update to Symfony 2.8.45

- phpBB/composer.lock
- phpBB/phpbb/di/container_builder.php
Also fixed incorrect creation of dumped container (Container instead of
ContainerBuilder).
PHPBB3-15746
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15746
> [ticket/15746] Update symfony to latest on master

- phpBB/config/development/config.yml
- phpBB/config/test/config.yml
- phpBB/phpbb/di/extension/container_configuration.php
- phpBB/phpbb/di/extension/core.php
- phpBB/phpbb/user.php
PHPBB3-12623
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-12623
> [ticket/12623] Add allow_install_dir

- phpBB/includes/acp/acp_database.php
- phpBB/phpbb/attachment/upload.php
- phpBB/phpbb/files/filespec_storage.php
- phpBB/phpbb/storage/adapter/local.php
- phpBB/phpbb/storage/storage.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15760
> [ticket/15760] Fix write_stream 

- phpBB/phpbb/composer/installer.php
- phpBB/phpbb/db/migration/data/v330/extensions_composer_2.php
Also always installs composer/installers in vendor-ext too.
PHPBB3-15536
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15536
> [ticket/15536] Catalog: adds satis.phpbb.com to repositories

- phpBB/includes/acp/acp_attachments.php
PHPBB3-15566
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15566
> [ticket/15566] Set category to none if extension don't exist

- phpBB/assets/javascript/core.js
PHPBB3-15748
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15748
> [ticket/15748] Fix toggle alt text

- phpBB/phpbb/db/migration/data/v320/remove_outdated_media.php
PHPBB3-15744
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15744
> [ticket/15744] Remove useless sql_freeresults

- phpBB/phpbb/db/migration/data/v310/auth_provider_oauth.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15767
> [ticket/15767] Fix effictively_installed condition for oauth_tokens

- phpBB/assets/javascript/plupload.js
PHPBB3-15721
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15721
> [ticket/15721] Make plupload more versatile

- phpBB/includes/acp/acp_bbcodes.php
PHPBB3-15590
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15590
> [ticket/15590] Add events core.acp_bbcodes_(modify_create|delete)_after

- phpBB/includes/functions.php
PHPBB3-15413
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15413
> [ticket/15413] Login redirect to previous page

- phpBB/cron.php
- phpBB/feed.php
- phpBB/report.php
PHPBB3-15720
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15720
> [ticket/15720] Don't escape ampersands on redirections

- phpBB/includes/functions_download.php
- phpBB/language/en/common.php
- phpBB/phpbb/db/migration/data/v330/storage_track.php
- phpBB/phpbb/storage/adapter/adapter_interface.php
- phpBB/phpbb/storage/adapter/local.php
- phpBB/phpbb/storage/storage.php
- tests/attachment/delete_test.php
- tests/attachment/upload_test.php
- tests/avatar/manager_test.php
- tests/notification/submit_post_base.php
- tests/privmsgs/delete_user_pms_test.php
Checklist:
todo: do the renames with storage in the migration to update it in the table too
Depends on #4933 
https://tracker.phpbb.com/browse/PHPBB3-15692
> [ticket/15692] Move checks if file exists from adapter to storage

- phpBB/includes/ucp/ucp_register.php
- phpBB/language/en/ucp.php
- phpBB/phpbb/auth/provider/oauth/oauth.php
- phpBB/styles/prosilver/template/ucp_register.html
PHPBB3-11838
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-11838
> [ticket/11838] OAuth registration from ucp_register

- phpBB/phpbb/notification/method/messenger_base.php
- phpBB/phpbb/user_loader.php
PHPBB3-11453
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-11453
> [ticket/11453] Improve performance of notification.method.messenger_base

- phpBB/phpbb/install/module/requirements/task/check_update.php
PHPBB3-15751
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15751
> [ticket/15751] Fix warning when update with CLI

- phpBB/language/en/acp/common.php
- phpBB/language/en/common.php
- phpBB/phpbb/filesystem/filesystem.php
PHPBB3-15255
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15255
> [ticket/15255] Move language strings from acp/common to common

- phpBB/includes/acp/acp_main.php
- tests/test_framework/phpbb_ui_test_case.php
PHPBB3-15772
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15772
> [ticket/15772] Hide warning in acp when allow_install_dir is true

- phpBB/includes/ucp/ucp_main.php
PHPBB3-15579
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15579
> [ticket/15579] Add ucp_front events

- phpBB/viewtopic.php
PHPBB3-15661
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15661
> [ticket/15661] Add core.viewtopic_modify_poll_ajax_data

- phpBB/includes/functions_messenger.php
PHPBB3-15662
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15662
> [ticket/15662] Add $this->template to core.modify_notification_message

- phpBB/assets/javascript/core.js
- phpBB/styles/prosilver/template/forum_fn.js
PHPBB3-15668
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15668
> [ticket/15668] Replace .load() with .on('load')

- phpBB/adm/style/acp_profile.html
- tests/functional/acp_profile_field_test.php
PHPBB3-11500
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-11500
> [ticket/11500] Remove unnamed input

- phpBB/includes/functions_posting.php
PHPBB3-15420
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15420
> [ticket/15420] Only update quote notification with original author

- phpBB/phpbb/request/request.php
- phpBB/phpbb/request/type_cast_helper.php
- phpBB/phpbb/request/type_cast_helper_interface.php
- tests/request/type_cast_helper_test.php
PHPBB3-15742
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15742
> [ticket/15742] Remove get_magic_quotes_gpc() call

- phpBB/includes/functions_user.php
- tests/console/user/base.php
- tests/functions/user_delete_test.php
- tests/functions_user/delete_user_test.php
PHPBB3-15716
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15716
> [ticket/15716] Remove OAuth data upon user deletion

- LICENSE
PHPBB3-15768
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15768
> [ticket/15768] Add a license to a repository

- phpBB/ucp.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15607
> [ticket/15607] Skip ban and disabled checks when deleting cookies

- phpBB/includes/ucp/ucp_main.php
- phpBB/includes/ucp/ucp_pm_compose.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15329
> [ticket/15329] Parse drafts before saving them (and decode)

- phpBB/phpbb/search/fulltext_sphinx.php
PHPBB3-15770
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15770
> [ticket/15770] Make sure sphinx limits are cast to int

- phpBB/includes/functions.php
PHPBB3-15805
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15805
> [ticket/15805] Add result to core.login_box_redirect

- phpBB/includes/acp/acp_forums.php
- phpBB/phpbb/db/migration/data/v32x/forum_topics_per_page_type.php
PHPBB3-15762
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15762
> [ticket/15762] Update type for forum_topics_per_page

- phpBB/viewtopic.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-12430
> [ticket/12430] Remove hilit param from topic title link

- phpBB/includes/acp/acp_bbcodes.php
PHPBB3-15410
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15410
> [ticket/15410] Remove obsolete code from BBCodes ACP

- phpBB/viewtopic.php
Event added in viewtopic.php so you can modify post_list sql
The query, sql limit, sql start, sort keys and days are editable
PHPBB3-15719
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15719
> [ticket/15719] Add core events to viewtopic to edit the post_list sql query

- phpBB/config/development/config.yml
- phpBB/includes/functions.php
- phpBB/install/convert/convertor.php
- phpBB/phpbb/di/extension/container_configuration.php
Also fix one debug.sql_explain missing from the previous PR
PHPBB3-12628
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-12628
> [ticket/12628] Introduce debug.memory

- phpBB/styles/prosilver/template/ajax.js
PHPBB3-15799
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15799
> [ticket/15799] Find correct poll for voting animation

- phpBB/includes/functions.php
PHPBB3-15700
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15700
> [ticket/15700] Use correct T_THEME_LANG_NAME

- phpBB/language/en/acp/board.php
PHPBB3-15642
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15642
> [ticket/15642] Replace > with &gt;

- phpBB/styles/prosilver/template/navbar_header.html
PHPBB3-15596
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15596
> [ticket/15596] Migrate from data-vocabulary.org to schema.org

- phpBB/phpbb/event/md_exporter.php
PHPBB3-15809
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15809
> [ticket/15809] Allow twig syntax for template events

- phpBB/includes/functions.php
- tests/security/redirect_test.php
PHPBB3-15758
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15758
> [ticket/15758] Show translated msg for INSECURE_REDIRECT

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/confirm_delete_body.html
PHPBB3-15792
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15792
> [ticket/15792] Add confirm_delete_body_delete_reason_before

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/mcp_post.html
Needs https://github.com/phpbb/phpbb/pull/5386 to pass tests
________________________________
PHPBB3-15706
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15706
> [ticket/15706] Add mcp_post_report_buttons_top_* events

- phpBB/includes/functions.php
PHPBB3-15616
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15616
> [ticket/15616] Remove jumpbox from login_forum.html

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/simple_footer.html
Needs https://github.com/phpbb/phpbb/pull/5386 to pass tests
________________________________
PHPBB3-15554
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15554
> [ticket/15554] Add simple_footer_body_after

- phpBB/styles/prosilver/template/forum_fn.js
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15552
> [ticket/15552] Call insert_single_user when appropriate

- phpBB/includes/functions_user.php
PHPBB3-15494
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15494
> [ticket/15494] Allow user to be removed from NEWLY_REGISTERED multiple times

- tests/test_framework/phpbb_ui_test_case.php
PHPBB3-15824
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15824
> [ticket/15824] Fix and update UI framework

- phpBB/language/en/posting.php
- phpBB/posting.php
- phpBB/styles/prosilver/template/posting_layout.html
PHPBB3-15244
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15244
> [ticket/15244] Remove unglobalise related code

- phpBB/includes/mcp/mcp_post.php
- phpBB/includes/mcp/mcp_reports.php
PHPBB3-15701
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15701
> [ticket/15701] Display signature in MCP

- phpBB/includes/ucp/ucp_pm_compose.php
- phpBB/styles/prosilver/template/mcp_post.html
- phpBB/styles/prosilver/template/posting_pm_header.html
- phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
PHPBB3-15621
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15621
> [ticket/15621] Remove graphical inconsistencies

- phpBB/phpbb/cron/task/core/prune_all_forums.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14812
> [ticket/14812] Prune shadow topics during system cron too

- phpBB/includes/functions_messenger.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15836
> [ticket/15836] Event to send message via external transport

- phpBB/install/schemas/schema_data.sql
`downloadable` extension group has id 5 not 6
PHPBB3-15846
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15846
> [ticket/15846] Fix Wrong id for downldable extensions group

- phpBB/phpbb/notification/manager.php
- phpBB/phpbb/notification/method/board.php
PHPBB3-15850
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15850
> [ticket/15850] Fix "Duplicate entry" for notification types

- build/build_helper.php
- phpBB/includes/acp/acp_inactive.php
- phpBB/includes/acp/acp_users.php
- phpBB/includes/acp/auth.php
- phpBB/includes/bbcode.php
- phpBB/includes/diff/diff.php
- phpBB/includes/diff/renderer.php
- phpBB/includes/functions_compress.php
- phpBB/includes/functions_content.php
- phpBB/includes/functions_messenger.php
- phpBB/includes/functions_module.php
- phpBB/includes/functions_transfer.php
- phpBB/includes/hooks/index.php
- phpBB/includes/mcp/mcp_logs.php
- phpBB/includes/mcp/mcp_main.php
- phpBB/includes/mcp/mcp_notes.php
- phpBB/includes/mcp/mcp_pm_reports.php
- phpBB/includes/mcp/mcp_queue.php
- phpBB/includes/mcp/mcp_reports.php
- phpBB/includes/mcp/mcp_warn.php
- phpBB/includes/message_parser.php
- phpBB/includes/questionnaire/questionnaire.php
- phpBB/includes/sphinxapi.php
- phpBB/includes/ucp/ucp_main.php
- tests/cache/cache_memory.php
PHPBB3-15849
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15849
> [ticket/15849] Stop using php4 constructors

- phpBB/includes/mcp/mcp_main.php
PHPBB3-15826
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15826
> [ticket/15826] Add core.mcp_main_fork_sql_after

- phpBB/includes/functions_messenger.php
- phpBB/language/en/email/forum_notify.txt
- phpBB/language/en/email/newtopic_notify.txt
- phpBB/language/en/email/topic_notify.txt
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14656
> [ticket/14656] Add List-Unsubscribe header to emails

- phpBB/styles/prosilver/template/memberlist_body.html
I have no idea why it suddenly works with TWIG, some sorcery behind it...
______________________________
PHPBB3-15619
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15619
> [ticket/15619] Always display CPF legend

- phpBB/includes/ucp/ucp_pm.php
- phpBB/language/en/ucp.php
- phpBB/language/en/viewtopic.php
- phpBB/viewtopic.php
PHPBB3-15593
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15593
> [ticket/15593] Do not allow print view with direct URL

- phpBB/phpbb/install/helper/database.php
Fix installtion failed with Oracle
PHPBB3-15817
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15817
> [ticket/15817] Fix installtion failed with Oracle

- phpBB/includes/acp/acp_forums.php
PHPBB3-15825
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15825
> [ticket/15825] Add core.acp_manage_forums_move_content_sql_before

- phpBB/includes/functions_messenger.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15830
> [ticket/15830] Move event to a more useful place

- phpBB/includes/acp/acp_users.php
PHPBB3-15831
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15831
> [ticket/15831] Add core.acp_users_modify_signature_sql_ary event

- phpBB/includes/acp/acp_users.php
PHPBB3-15832
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15832
> [ticket/15832] Add core.acp_users_avatar_sql event

- phpBB/includes/ucp/ucp_register.php
PHPBB3-15837
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15837
> [ticket/15837] Add core.ucp_register_welcome_email_before

- phpBB/includes/ucp/ucp_register.php
PHPBB3-15838
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15838
> [ticket/15838] Add core.ucp_register_register_after

- phpBB/config/default/container/services_avatar.yml
- phpBB/phpbb/avatar/manager.php
- tests/avatar/manager_test.php
PHPBB3-15833
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15833
> [ticket/15833] Add core.avatar_manager_avatar_delete_after event

- phpBB/docs/CREDITS.txt
[ci skip]
PHPBB3-15857
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15857
> [ticket/15857] Add rubencm to CREDITS.txt

- phpBB/includes/acp/acp_database.php
- phpBB/includes/functions.php
PHPBB3-15860
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15860
> [ticket/15860] Fix format of backup files

- phpBB/includes/bbcode.php
- phpBB/includes/functions_content.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15875">PHPBB3-15875</a>.
Caused by https://github.com/phpbb/phpbb/pull/5424.
> [ticket/15875] Fix PHP fatal error on BBCode parsing

- phpBB/viewtopic.php
PHPBB3-15870
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15870
> [ticket/15870] Add core.viewtopic_modify_forum_id

- phpBB/includes/mcp/mcp_reports.php
PHPBB3-15873
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15873
> [ticket/15873] Add core.mcp_report_template_data

- phpBB/phpbb/template/twig/node/includeasset.php
PHPBB3-15542
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15542
> [ticket/15542] Always append assets versions to assets

- phpBB/includes/ucp/ucp_activate.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15881">PHPBB3-15881</a>.
> [ticket/15881] Reset login keys for new password activation

- phpBB/phpbb/db/driver/mssql_base.php
Add cast_expr_to_bigint() to mssql_base
as in tracker
tested on MS SQL Server 2008
PHPBB3-15665
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15665
> [ticket/15665] Fix MSSQL crashes if upload dir>2GB

- phpBB/memberlist.php
PHPBB3-15858
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15858
> [ticket/15858] Unapproved User(s) appearing as Guest in Team Page

- phpBB/styles/prosilver/template/memberlist_email.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15867
> [ticket/15867] Add class for message field in the contact form

- phpBB/includes/functions_content.php
PHPBB3-15892
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15892
> [ticket/15892] Rename variable to commonly used $storage_attachment

- phpBB/includes/functions_content.php
- phpBB/includes/ucp/ucp_pm_compose.php
- phpBB/posting.php
- tests/functions_content/phpbb_format_quote_test.php
> [ticket/15893] Pass needed language class directly to format quote

- phpBB/language/en/acp/permissions.php
PHPBB3-15888
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15888
> [ticket/15888] Changing ACP link from 3.1 to 3.2 docs

- phpBB/includes/functions_user.php
- phpBB/phpbb/db/migration/data/v30x/release_3_0_8_rc1.php
- phpBB/phpbb/notification/method/email.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15911
>  [ticket/15911] Prevent errors when trying to delete from non-existent tables

- phpBB/phpbb/template/context.php
PHPBB3-15904
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15904
> [ticket/15904] Fix counting empty template blocks

- phpBB/includes/acp/acp_inactive.php
- phpBB/includes/acp/acp_permissions.php
- phpBB/includes/acp/acp_profile.php
- phpBB/includes/acp/acp_users.php
- phpBB/includes/functions_compatibility.php
- phpBB/includes/functions_mcp.php
- phpBB/includes/mcp/mcp_logs.php
- phpBB/includes/mcp/mcp_main.php
- phpBB/includes/mcp/mcp_notes.php
- phpBB/includes/mcp/mcp_pm_reports.php
- phpBB/includes/mcp/mcp_queue.php
- phpBB/includes/mcp/mcp_reports.php
- phpBB/includes/mcp/mcp_warn.php
- phpBB/includes/ucp/ucp_main.php
- phpBB/phpbb/captcha/plugins/gd.php
- phpBB/phpbb/captcha/plugins/gd_wave.php
- phpBB/phpbb/captcha/plugins/nogd.php
- phpBB/phpbb/captcha/plugins/qa.php
- phpBB/phpbb/captcha/plugins/recaptcha.php
- phpBB/phpbb/files/upload.php
- tests/upload/filespec_test.php
PHPBB3-15910
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15910
> [ticket/15910] Pass object arguments by reference implicitly

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/mcp_post.html
PHPBB3-15901
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15901
> [ticket/15901] Add mcp_post_ template events

- phpBB/phpbb/user.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15509
> [ticket/15509] Don't show disabled board when in install

- phpBB/includes/ucp/ucp_pm_compose.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15898
> [ticket/15898] Add core.ucp_pm_compose_template

- phpBB/composer.lock
PHPBB3-15921
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15921
> [ticket/15921] Fix master build

- travis/check-stylesheet.sh
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15924
> [ticket/15924] Fix stylelint after switching to trusty builds

- tests/lint_test.php
Also, make sure to correctly handle opendir returning false instead of
the stream handle.
PHPBB3-15919
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15919
> [ticket/15919] Don't run lint test against node_modules

- phpBB/styles/prosilver/template/overall_header.html
- phpBB/styles/prosilver/template/simple_header.html
- phpBB/styles/prosilver/theme/stylesheet.css
Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-15462
https://tracker.phpbb.com/browse/PHPBB3-15462
should be merge prior to https://github.com/phpbb/phpbb/pull/5033
> [ticket/15462] add bidi.css to stylesheet.css

- phpBB/adm/style/acp_main.html
- phpBB/adm/style/admin.css
PHPBB3-15927
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15927
> [ticket/15927] Fix acp style tables width issue

- phpBB/includes/message_parser.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15899
> [ticket/15899] Add core.modify_attachment_sql_ary_on_* events

- phpBB/language/en/email/report_pm.txt
- phpBB/phpbb/notification/type/report_pm.php
PHPBB3-15931
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15931
> [ticket/15931] Fix PM report emails

- tests/network/checkdnsrr_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15959
>  [ticket/15959] Fix invalid CNAME record

- phpBB/includes/functions_admin.php
PHPBB3-15960
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15960
> [ticket/15960] Add SQL transactions to functions_admin.php

- tests/test_framework/phpbb_database_test_case.php
- tests/test_framework/phpbb_test_case.php
PHPBB3-15938
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15938
> [ticket/15938] Update classes in backupStaticAttributesBlacklist

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/memberlist_body.html
PHPBB3-15884
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15884
> [ticket/15884] Add memberlist_body_* events

- phpBB/includes/functions_user.php
- tests/console/user/base.php
- tests/functions/user_delete_test.php
- tests/functions_user/delete_user_test.php
PHPBB3-15975
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15975
> [ticket/15975] Remove user notification data upon user deletion

- .stylelintrc
- package-lock.json
- package.json
- phpBB/styles/prosilver/theme/icons.css
- phpBB/styles/prosilver/theme/plupload.css
PHPBB3-15980
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15980
> [ticket/15980] update and move all npm dependencies to dev

- phpBB/config/default/container/services_console.yml
- phpBB/phpbb/console/command/thumbnail/delete.php
- phpBB/phpbb/console/command/thumbnail/generate.php
- tests/console/thumbnail_test.php
PHPBB3-15965
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15965
> [ticket/15965] Fix hardcoded directory [3.2.x only]

- phpBB/phpbb/pagination.php
PHPBB3-15939
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15939
> [ticket/15939] Fix Pagination docblocks

- phpBB/language/en/posting.php
PHPBB3-15986
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15986
> [ticket/15986] Add missing language key for posting.php

- phpBB/phpbb/install/module/obtain_data/task/obtain_database_data.php
- phpBB/phpbb/install/module/obtain_data/task/obtain_email_data.php
- phpBB/phpbb/install/module/obtain_data/task/obtain_server_data.php
- phpBB/phpbb/install/module/obtain_data/task/obtain_update_ftp_data.php
PHPBB3-15869
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15869
> [ticket/15869] Allow multibyte characters in hostname during installation

- phpBB/includes/mcp/mcp_main.php
PHPBB3-15950
And simultaneously remove a duplicated UPDATE query.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15950
> [ticket/15950] Add SQL transactions to mcp_main.php

- phpBB/styles/prosilver/template/navbar_header.html
Based on: https://developers.google.com/search/docs/data-types/breadcrumb
PHPBB3-15992
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15992
> [ticket/15992] Fix breadcrumb structured data

- phpBB/adm/style/acp_users_prefs.html
Disable both choice input when jabber is disabled in general settings
PHPBB3-15957
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15957
> [ticket/15957] Disabling both choice

- phpBB/memberlist.php
PHPBB3-15891
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15891
> [ticket/15891] Add core.memberlist_modify_view_profile_template_vars

- tests/dbal/migrator_tool_permission_test.php
PHPBB3-15996
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15996
> [ticket/15996] Rename dataProvider to not start with test_

- tests/test_framework/phpbb_ui_test_case.php
PHPBB3-15997
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15997
> [ticket/15997] Use higher than default timeout for webdriver connections

- phpBB/includes/ucp/ucp_pm_viewfolder.php
- phpBB/language/en/ucp.php
- phpBB/styles/prosilver/theme/cp.css
PHPBB-15953
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15953
> [ticket/15953] add reported pm message borders

- phpBB/index.php
PHPBB3-15978
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15978
> [ticket/15978] Add core.index_mark_notification_after

- phpBB/config/default/container/services_content.yml
- phpBB/phpbb/message/admin_form.php
PHPBB3-15970
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15970
> [ticket/15970] Add core.message_admin_form_submit_before

- phpBB/styles/prosilver/template/login_body_oauth.html
PHPBB3-16009
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16009
> [ticket/16009] Display OAuth login's buttons in a row

- phpBB/phpbb/auth/provider/oauth/oauth.php
- phpBB/styles/prosilver/template/ucp_auth_link_oauth.html
PHPBB3-16006
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16006
> [ticket/16006] Create unique ID's for OAuth (un)linking

- phpBB/phpbb/auth/provider/oauth/oauth.php
PHPBB3-16001
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16001
> [ticket/16001] Append data to the OAuth's redirect URL

- phpBB/memberlist.php
PHPBB3-15995
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15995
> [ticket/15995] Add core.memberlist_modify_sort_pagination_params

- phpBB/includes/functions.php
PHPBB3-15972
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15972
> [ticket/15972] Add core.markread_after

- phpBB/posting.php
Allow modification of the quote attributes of the current post being quoted
Any information in there can be changed without affecting the rest of the page
New attributes can also be added if an extension needed to as well
PHPBB3-15944
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15944
> [ticket/15944] Add core.posting_modify_quote_attributes

- phpBB/docs/events.md
- phpBB/phpbb/event/md_exporter.php
PHPBB3-16010
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16010
> [ticket/16010] Enforce alphabetical order for events in events.md

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/posting_attach_body.html
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15915">PHPBB3-15915</a>.
> [ticket/15915] Add template events to posting_attach_body.html

- phpBB/includes/compatibility_globals.php
- phpBB/includes/functions.php
- phpBB/includes/mcp/mcp_main.php
PHPBB3-15942
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15942
> [ticket/15942] Allow array in confirm_box title

- phpBB/includes/functions_user.php
- phpBB/phpbb/auth/provider/oauth/oauth.php
- phpBB/phpbb/session.php
- tests/session/check_ban_test.php
PHPBB3-16007
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16007
> [ticket/16007] Show ban message for OAuth login

- phpBB/styles/prosilver/template/viewforum_body.html
PHPBB3-16020
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16020
> [ticket/16020] Fix some mistake from PHPBB3-15827

- tests/test_framework/phpbb_functional_test_case.php
PHPBB3-16027
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16027
> [ticket/16027] Force clearing of cache folder on install for functional

- phpBB/includes/mcp/mcp_main.php
PHPBB3-16039
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16039
> [ticket/16039] Global dispatcher

- phpBB/includes/ucp/ucp_pm_viewfolder.php
PHPBB3-16037
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16037
> [ticket/16037] Fix UCP PM ViewFolder PHP Notice error

- phpBB/includes/functions.php
- phpBB/styles/prosilver/template/login_forum.html
- phpBB/styles/prosilver/template/viewforum_body.html
- phpBB/viewforum.php
PHPBB3-16036
Checklist:
I haven't added it to ucp_login_link.php because i don't know what is that file for
https://tracker.phpbb.com/browse/PHPBB3-16036
> [ticket/16036] Add S_FORM_TOKEN_LOGIN to all login forms

- phpBB/includes/functions.php
PHPBB3-16042
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16042
> [ticket/16042] Use S_LOGIN_REDIRECT to output login form token

- phpBB/includes/mcp/mcp_ban.php
For both 3.2.x/master.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16050">PHPBB3-16050</a>.
> [ticket/16050] Fix PHP warning in MCP Banning tab on PHP 7.2+

- phpBB/includes/acp/acp_database.php
PHPBB3-16048
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16048
> [ticket/16048] Fix restore backup from ACP

- .travis.yml
PHPBB3-16067
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16067
> [ticket/16067] Specify trusty build environment

- phpBB/composer.lock
- tests/text_processing/tickets_data/PHPBB3-16053.html
- tests/text_processing/tickets_data/PHPBB3-16053.txt
- tests/text_processing/tickets_data/PHPBB3-16053.xml
PHPBB3-16053
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16053
> [ticket/16053] Update s9e/text-formatter

- phpBB/phpbb/auth/provider/oauth/oauth.php
Via forum, memberlist, topic or post etc..
PHPBB3-16055
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16055
> [ticket/16055] Fix Oauth's logins in 3.2.x

- phpBB/composer.json
- phpBB/composer.lock
- phpBB/phpbb/textformatter/s9e/bbcode_merger.php
PHPBB3-16072
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16072
> [ticket/16072] Update s9e/text-formatter

- phpBB/includes/acp/acp_attachments.php
PHPBB3-16071
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16071
> [ticket/16071] Undefined index for custom attachments groups

- phpBB/styles/prosilver/template/ucp_agreement.html
PHPBB3-15974
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15974
> [ticket/15974] Remove Back to previous page link

- phpBB/includes/ucp/ucp_attachments.php
- phpBB/language/en/ucp.php
- phpBB/styles/prosilver/template/ucp_attachments.html
PHPBB3-15932
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15932
> [ticket/15932] Disallow deleting locked attachments

- phpBB/includes/acp/acp_update.php
PHPBB3-16073
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16073
> [ticket/16073] Fix warning in ACP version check

- tests/test_framework/phpbb_ui_test_case.php
PHPBB3-16078
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16078
> [ticket/16078] Use chrome as webdriver

- phpBB/language/en/acp/board.php
- phpBB/language/en/ucp.php
PHPBB3-16000
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16000
> [ticket/16000] Link to php's date()

- phpBB/includes/functions_posting.php
PHPBB3-16024
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16024
> [ticket/16024] Add core.topic_review_modify_sql_ary

- phpBB/phpbb/db/tools/tools.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16061">PHPBB3-16061</a>.
> [ticket/16061] Migrator to drop unique indexes when needed

- phpBB/phpbb/db/migration/data/v310/timezone_p3.php
- phpBB/phpbb/db/migration/data/v32x/timezone_p3.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16063">PHPBB3-16063</a>.
> [ticket/16063] Remove board_dst config value since unused

- phpBB/phpbb/auth/provider/oauth/oauth.php
PHPBB3-16065
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16065
> [ticket/16065] Add user_ip to SQL query

- phpBB/includes/functions_messenger.php
- phpBB/phpbb/auth/provider/provider_interface.php
PHPBB3-16068
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16068
> [ticket/16068] Adjust DocBlock @param's

- phpBB/language/en/acp/permissions_phpbb.php
PHPBB3-16047
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16047
> [ticket/16047] Improve wording for PM permissions

- phpBB/includes/functions_posting.php
PHPBB3-16003
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16003
> [ticket/16003] Fix num_posts sync

- phpBB/includes/functions_download.php
PHPBB3-15984
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15984
> [ticket/15984] Use private cache-control

- phpBB/includes/functions_privmsgs.php
PHPBB3-16075
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16075
> [ticket/16075] Fix warning in PM filter

- phpBB/language/en/email/admin_activate.txt
PHPBB3-15967
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15967
> [ticket/15967] Improve admin activate email wording

- tests/test_framework/phpbb_ui_test_case.php
This is to hopefully get rid of some of the issues with timeouts.
PHPBB3-16078
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16078
> [ticket/16078] Use headless chrome and disable gpu acceleration

- phpBB/docs/events.md
- phpBB/phpbb/event/md_exporter.php
PHPBB3-16021
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16021
> [ticket/16021] Recognize number of Template Event instances in events.md file

- phpBB/styles/prosilver/template/posting_attach_body.html
- phpBB/styles/prosilver/theme/plupload.css
PHPBB3-16093
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16093
> [ticket/16093] Do not display attach-row-tpl

- phpBB/includes/functions_privmsgs.php
PHPBB3-16023
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16023
> [ticket/16023] Add core.message_history_modify_template_vars

- phpBB/includes/ucp/ucp_profile.php
PHPBB3-15976
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15976
> [ticket/15976] Reset user_passchg only if user changed password

- phpBB/posting.php
PHPBB3-15946
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15946
> [ticket/15946] Add core.posting_modify_row_data

- phpBB/includes/functions.php
PHPBB3-16070
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16070
> [ticket/16070] Remove support for WebSTAR and Xitami

- phpBB/phpbb/passwords/driver/argon2i.php
- phpBB/phpbb/passwords/driver/base_native.php
PHPBB3-16016
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16016
> [ticket/16016] Add a base class for native password hashing

- phpBB/posting.php
PHPBB3-16102
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16102
> [ticket/16102] Add core.posting_modify_post_subject

- phpBB/includes/ucp/ucp_pm_compose.php
PHPBB3-16103
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16103
> [ticket/16103] Add core.pm_modify_message_subject

- phpBB/includes/mcp/mcp_main.php
PHPBB3-16106
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16106
> [ticket/16106] Add core.mcp_main_before

- phpBB/includes/acp/acp_users.php
- phpBB/includes/functions_user.php
PHPBB3-16013
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16013
> [ticket/16013] Allow admins to use disallowed username

- phpBB/config/default/container/parameters.yml
- phpBB/config/default/container/services_password.yml
- phpBB/phpbb/passwords/driver/argon2i.php
- phpBB/phpbb/passwords/driver/argon2id.php
- phpBB/phpbb/passwords/driver/base_native.php
- tests/passwords/drivers_test.php
Depends on PHPBB3-16016 / #5565 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16017
> [ticket/16017] Add support for Argon2id as default password hashing

- phpBB/adm/style/acp_attachments.html
- phpBB/includes/acp/acp_attachments.php
Checklist:
Replaces #4198 
https://tracker.phpbb.com/browse/PHPBB3-14459
> [ticket/14459] Check language input for group and fix template logic

- phpBB/phpbb/extension/manager.php
- tests/test_framework/phpbb_functional_test_case.php
PHPBB3-15088
Replaces #4699, in honor of javiexin.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15088
> [ticket/15088] Avoid code repetitions in extension manager

- phpBB/memberlist.php
PHPBB3-15885
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15885
---
---
> [ticket/15885] Display group rank on memberlist_body

- phpBB/viewtopic.php
PHPBB3-16097
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16097
> [ticket/16097] Add core.viewtopic_gen_sort_selects_before

- phpBB/composer.json
- phpBB/composer.lock
PHPBB3-16112
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16112
> [ticket/16112] Update composer dependencies for 3.2.x

- phpBB/composer.json
- phpBB/composer.lock
3.3.x version (see https://github.com/phpbb/phpbb/pull/5638 for 3.2.x version)
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16112
> [ticket/16112] Update composer dependencies for 3.3.x

- phpBB/composer.json
- phpBB/composer.lock
- tests/notification/group_request_test.php
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16112
> [ticket/16112] Update composer dependencies in master

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/mcp_move.html
PHPBB3-16107
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16107
> [ticket/16107] Add mcp_move_destination_forum_before|after

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/mcp_forum.html
- phpBB/styles/prosilver/template/search_results.html
- phpBB/styles/prosilver/template/viewforum_body.html
PHPBB3-16108
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16108
> [ticket/16108] Add topiclist_row_topic_by_author_before|after

- phpBB/includes/functions.php
- phpBB/includes/functions_acp.php
PHPBB3-16101
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16101
> [ticket/16101] Add Referrer-Policy header to phpBB's headers

- .travis.yml
PHPBB3-16115
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16115
> [ticket/16115] Add PHP 7.4snapshot to travis CI build matrix

- phpBB/styles/prosilver/template/posting_poll_body.html
PHPBB3-16119
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16119
> [ticket/16119] Prevent error message for Poll Title

- .appveyor.yml
PHPBB3-16126
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16126
> [ticket/16126] Downgrade chocolatey to a working version

- phpBB/includes/functions_privmsgs.php
PHPBB3-16111
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16111
> [ticket/16111] Add core.message_history_modify_sql_ary

- phpBB/includes/functions_posting.php
- phpBB/language/en/posting.php
PHPBB3-15897
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15897
> [ticket/15897] Fix Emojis' SQL Error in Attachment Comment

- phpBB/docs/events.md
- phpBB/styles/prosilver/template/mcp_topic.html
PHPBB3-16114
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16114
> [ticket/16114] mcp_topic_post_author_full_{append/prepend}

- phpBB/includes/mcp/mcp_topic.php
PHPBB3-16113
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16113
> [ticket/16113] Add core.mcp_topic_modify_sql_ary

- phpBB/memberlist.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16124">PHPBB3-16124</a>.
> [ticket/16124] Fix users search by last visit time in memberlist.php

- phpBB/language/en/acp/profile.php
PHPBB3-16109
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16109
> [ticket/16109] Fix Custom Profile Field visibility's explain

- phpBB/assets/javascript/plupload.js
PHPBB3-16093
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16093
> [ticket/16093] Ensure attach row is visible after upload with javascript

- phpBB/styles/prosilver/template/attachment.html
PHPBB3-16129
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16129
> [ticket/16129] Enhance attachment's ALT tag

- phpBB/adm/style/installer_footer.html
- phpBB/styles/prosilver/template/ucp_pm_viewmessage_print.html
- phpBB/styles/prosilver/template/viewtopic_print.html
PHPBB3-15745
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15745
> [ticket/15745] Uses {{ CREDIT_LINE }} instead of hardcoded language

- phpBB/language/en/common.php
- phpBB/phpbb/auth/provider/oauth/oauth.php
PHPBB3-13175
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13175
> [ticket/13175] Check if account is already linked when using OAuth

- phpBB/includes/acp/acp_prune.php
PHPBB3-16134
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16134
> [ticket/16134] Exclude group leaders on group member purge

- vagrant/after.sh
PHPBB3-16131
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16131
> [ticket/16131] Force vagrant to install phpBB with php7.2

- phpBB/includes/functions_user.php
- tests/functions/fixtures/validate_email.xml
- tests/functions/validate_user_email_test.php
PHPBB3-16123
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16123
---
It might or might not have been me who broke it in the first place. 🙄
> [ticket/16123] Show proper banned email message

- phpBB/adm/style/permission_mask.html
- phpBB/adm/style/permissions.js
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15467">PHPBB3-15467</a>.
> [ticket/15467] Fix JS for permissions setting

- build/generate_package_json.php
PHPBB3-16160
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16160
> [ticket/16160] Add script for generating package json file

- phpBB/styles/prosilver/template/navbar_header.html
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16156">PHPBB3-16156</a>.
> [ticket/16156] Fix bots seeing register and logout links

- phpBB/phpbb/message/form.php
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16157">PHPBB3-16157</a>.
> [ticket/16157] Fix FORM_INVALID error in the sending email form

- phpBB/phpbb/filesystem/filesystem.php
PHPBB3-15643
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15643
> [ticket/15643] Fix open_basedir warnings

- phpBB/includes/functions_admin.php
Checklist:
Fixed RP for #5668 
https://tracker.phpbb.com/browse/PHPBB3-16143
> [ticket/16143] Add new events before and after move topics

- phpBB/viewtopic.php
PHPBB3-16139
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16139
> [ticket/16139] Add core.viewtopic_modify_quick_reply_template_vars

- phpBB/adm/style/acp_groups.html
- phpBB/docs/events.md
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16148">PHPBB3-16148</a>.
> [ticket/16148] Add template events to acp_groups.html

- phpBB/index.php
PHPBB3-15436
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15436
> [ticket/15436] Remove folder icons code from index

- phpBB/phpbb/notification/type/approve_post.php
- phpBB/phpbb/notification/type/approve_topic.php
PHPBB3-15940
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15940
> [ticket/15940] Expose user_id to notif method's is_available()

- tests/template/extension_test.php
PHPBB3-15905
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15905
> [ticket/15905] Adjust tests for twig extensions for master branch

- phpBB/adm/style/acp_attachments.html
- phpBB/adm/style/acp_ban.html
- phpBB/adm/style/acp_contact.html
- phpBB/adm/style/acp_database.html
- phpBB/adm/style/acp_forums.html
- phpBB/adm/style/acp_icons.html
- phpBB/adm/style/acp_modules.html
- phpBB/adm/style/acp_permission_roles.html
- phpBB/adm/style/acp_posting_buttons.html
- phpBB/adm/style/acp_ranks.html
- phpBB/adm/style/acp_search.html
- phpBB/adm/style/acp_users_overview.html
- phpBB/adm/style/acp_users_prefs.html
- phpBB/adm/style/acp_users_signature.html
- phpBB/adm/style/installer_footer.html
- phpBB/adm/style/overall_footer.html
- phpBB/adm/style/overall_header.html
- phpBB/adm/style/permission_mask.html
- phpBB/adm/style/progress_bar.html
- phpBB/adm/style/simple_footer.html
- phpBB/adm/style/simple_header.html
- phpBB/styles/prosilver/template/navbar_header.html
- phpBB/styles/prosilver/template/overall_footer.html
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16083
> [ticket/16083] Remove common W3C validation errors and warnings

- phpBB/composer.lock
PHPBB3-16175
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16175
> [ticket/16175] Update composer dependencies for 3.3.0-b1

- .travis.yml
- travis/check-executable-files.sh
- travis/setup-mariadb.sh
PHPBB3-16185
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16185
> [ticket/16185] Use xenial for builds on travis

- phpBB/includes/functions_display.php
- phpBB/viewforum.php
PHPBB3-16184
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16184
> [ticket/16184] Don't entity-encode & character in AJAX response
