phpbb/phpbb

tests/test_framework/phpbb_ui_test_case.php

The timeout only seems to occur on the first test so let's see what a
retry can do to help with this issue.
PHPBB3-16078
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16078

[ticket/16078] Try using retries for timeout issue

---

phpBB/includes/functions_posting.php

PHPBB3-16182
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16182

[ticket/16182] Add core.generate_smilies_modify_rowset

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/ucp_profile_profile_info.html

PHPBB3-16140
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16140

[ticket/16140] Add ucp_profile_profile_info_birthday_label_append

---

phpBB/phpbb/session.php

PHPBB3-16174
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16174

[ticket/16174] Add core.set_cookie

---

phpBB/styles/prosilver/template/memberlist_body.html

PHPBB3-16172
Before:
After:
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16172

[ticket/16172] Add group rank label to group view

---

phpBB/language/en/acp/posting.php

PHPBB3-16147
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16147

[ticket/16147] Updated tokens legend in BBCodes ACP

---

phpBB/includes/functions_posting.php

PHPBB3-16183
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16183

[ticket/16183] Add core.generate_smilies_count_sql_before

---

phpBB/includes/acp/acp_bbcodes.php
phpBB/language/en/acp/posting.php

PHPBB3-16161
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16161

[ticket/16161] Enable BBcodes without closing tag

---

phpBB/phpbb/console/command/extension/enable.php

PHPBB3-16192
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16192

[ticket/16192] Fix CLI extension not enableable messages

---

phpBB/includes/acp/acp_forums.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16146

[ticket/16146] New core event: after move forum

---

phpBB/includes/acp/acp_forums.php
phpBB/includes/utf/utf_tools.php

PHPBB3-16151
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16151

[ticket/16151] Enable Emojis and rich text in forum name

---

phpBB/phpbb/auth/provider/oauth/oauth.php

PHPBB3-16181
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16181

[ticket/16181] Enforce string for OAuth provider id

---

phpBB/composer.json
phpBB/composer.lock

PHPBB3-16196
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16196

[ticket/16196] Remove paragonie/random_compat

---

phpBB/adm/style/admin.css

Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-16188
https://tracker.phpbb.com/browse/PHPBB3-16188

[ticket/16188] fix acp responsive stats

---

phpBB/adm/style/permission_forum_copy.html

PHPBB3-16195
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16195

[ticket/16195] Copy forum permissions' missing paragraph

---

phpBB/styles/prosilver/template/ucp_register.html

PHPBB3-16187
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16187

[ticket/16187] Correctly display registration using external services

---

phpBB/assets/javascript/core.js
phpBB/styles/prosilver/template/memberlist_search.html
phpBB/styles/prosilver/theme/colours.css
phpBB/styles/prosilver/theme/forms.css

PHPBB3-12539
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-12539
---
This will add the ability to navigate the search results in the _Live Member Search_ in the _Memberlist > Find a Member_ functionallity.
Able to navigate with the `arrow keys` (up and down).
Set the value of the selected row with `enter`
Close the dropdown with `escape`.
Show the loading indicator
--- 
Branch is set to 3.3.x as it is rather pointless for 4.0 as it is stated that entire JS will be redone for that version.

[ticket/12539] Live member search improvements

---

phpBB/posting.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16199">PHPBB3-16199</a>.

[ticket/16199] Init guest posting CAPTCHA only if guest posting is allowed

---

phpBB/includes/ucp/ucp_register.php

PHPBB3-16210
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16210

[ticket/16210] Ensure terms of use is not skipped by enforcing form token

---

phpBB/config/default/container/services_auth.yml
phpBB/language/en/common.php
phpBB/phpbb/auth/provider/base.php
phpBB/phpbb/auth/provider/oauth/oauth.php
phpBB/phpbb/auth/provider/oauth/service/base.php
phpBB/phpbb/auth/provider/oauth/service/bitly.php
phpBB/phpbb/auth/provider/oauth/service/facebook.php
phpBB/phpbb/auth/provider/oauth/service/google.php
phpBB/phpbb/auth/provider/oauth/service/service_interface.php
phpBB/phpbb/auth/provider/oauth/service/twitter.php
phpBB/phpbb/auth/provider/oauth/token_storage.php
phpBB/phpbb/auth/provider/provider_interface.php
tests/functions/user_delete_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16008
Area51 topic:
http://area51.phpbb.com/phpBB/viewtopic.php?f=81&t=66866

[ticket/16008] Clean up OAuth system

---

phpBB/search.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16205

[ticket/16205] Fix undefined $zebra variable

---

travis/setup-php-extensions.sh

PHPBB3-16216
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16216

[ticket/16216] Disable xdebug on travis

---

travis/setup-php-extensions.sh

PHPBB3-16216
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16216

[ticket/16216] Ignore not being able to disable xdebug

---

travis/setup-php-extensions.sh

PHPBB3-16217
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16217

[ticket/16217] Enable opcache on travis tests again

---

phpBB/assets/javascript/core.js

PHPBB3-12539
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-12539

[ticket/12539] Rebind live member search navigation

---

phpBB/phpbb/textformatter/s9e/bbcode_merger.php
tests/text_formatter/s9e/bbcode_merger_test.php

PHPBB3-16228
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16228

[ticket/16228] Fix BBCodes merging

---

phpBB/includes/functions.php

PHPBB3-16227
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16227

[ticket/16227] Fix undefined vars on login

---

phpBB/includes/functions_messenger.php

PHPBB3-16203
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16203

[ticket/16203] Enable Emojis and rich text in sent Emails

---

phpBB/assets/javascript/core.js

PHPBB3-16241
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16241

[ticket/16241] Color Palette backwards compatibility

---

phpBB/docs/INSTALL.html

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16236">PHPBB3-16236</a>.

[ticket/16236] Bump phpBB 3.3 max PHP version requirement to PHP 7.4

---

README.md

PHPBB3-16246
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16246
This should be merged up through the higher versions as well.

[ticket/16246] Update automated testing section of Readme

---

phpBB/docs/nginx.sample.conf

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16242

[ticket/16242] Fix nginx redirection loop

---

phpBB/includes/ucp/ucp_pm_compose.php
phpBB/phpbb/textformatter/s9e/factory.php
phpBB/phpbb/textformatter/s9e/quote_helper.php
phpBB/styles/prosilver/template/bbcode.html
tests/functional/private_messages_test.php

PHPBB3-16247
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16247

[ticket/16247] Quote PM has no identifier

---

phpBB/includes/ucp/ucp_register.php
phpBB/styles/prosilver/template/ucp_agreement.html
tests/functional/registration_test.php

PHPBB3-16211
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16211

[ticket/16211] Prevent skipping COPPA via URL parameter

---

phpBB/.htaccess

PHPBB3-16226
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16226

[ticket/16226] Prevent Apache servers from using MultiViews

---

phpBB/phpbb/textformatter/s9e/parser.php
tests/text_processing/tickets_data/PHPBB3-16252.after.php
tests/text_processing/tickets_data/PHPBB3-16252.before.php
tests/text_processing/tickets_data/PHPBB3-16252.html
tests/text_processing/tickets_data/PHPBB3-16252.txt

[ticket/16252] Ignore non-BBCodes when looking for unauthorized markup

---

phpBB/phpbb/textformatter/s9e/link_helper.php
tests/text_formatter/s9e/link_helper_test.php

PHPBB3-16251
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16251

[ticket/16251] Prevent shortened links from overriding other plugins

---

travis/ext-sniff.sh

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16235

[ticket/16235] Fix PHP CodeSniffer ignore patterns

---

phpBB/includes/functions.php

PHPBB3-16238
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16238

[ticket/16238] Update version for deprecation

---

phpBB/phpbb/captcha/non_gd.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16255

[ticket/16255] Fix PHP 7.4 deprecation warning

---

phpBB/phpbb/session.php
tests/session/fixtures/sessions_garbage.xml
tests/session/garbage_collection_test.php
tests/test_framework/phpbb_session_test_case.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15294">PHPBB3-15294</a>.

[ticket/15294] Fix session_gc() selecting expired sessions for unique users

---

phpBB/docs/sphinx.sample.conf

PHPBB3-16258
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16258

[ticket/16258] Fix sample Sphinx configuration file

---

phpBB/phpbb/install/module_base.php

PHPBB3-16261
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16261

[ticket/16261] Missing check whether the index exists in install - PHP 7.4

---

phpBB/includes/functions.php

PHPBB3-16238
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16238

[ticket/16238] Remove S_REDIRECT_LOGIN work around

---

phpBB/includes/acp/acp_board.php

PHPBB3-16260
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16260

[ticket/16260] Missing check whether the index exists in ACP - PHP 7.4

---

phpBB/phpbb/db/migration/data/v330/remove_email_hash.php

PHPBB3-16263
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16263

[ticket/16263] Ensure that remove_email_hash depends on migration adding hash

---

phpBB/phpbb/search/fulltext_sphinx.php

The reporter he's waiting this fix to be in the core.
I created this PR based on trusting his report.
I can't test it.
PHPBB3-15902
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15902

[ticket/15902] Out of range error with Sphinx search

---

phpBB/phpbb/avatar/driver/remote.php

Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-16015
https://tracker.phpbb.com/browse/PHPBB3-16015

[ticket/16015] Add new hook core.ucp_profile_avatar_upload_validation

---

build/sami-all.conf.php

PHPBB3-16271
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16271

[ticket/16271] Enable support for 3.3.x API documentation

---

phpBB/includes/acp/acp_bbcodes.php

PHPBB3-16267
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16267

[ticket/16267] Check whether the index exists in ACP BBcodes - PHP 7.4

---

phpBB/adm/style/acp_main.html
phpBB/adm/style/admin.css

PHPBB3-16221
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16221

[ticket/16221] Fix ACP statistics layout

---

build/sami-checkout.conf.php
phpBB/composer.json
phpBB/composer.lock
phpBB/includes/bbcode.php
phpBB/phpbb/auth/provider/ldap.php
phpBB/phpbb/auth/provider/oauth/service/service_interface.php
phpBB/phpbb/console/command/cron/run.php
phpBB/phpbb/console/command/update/check.php
phpBB/phpbb/language/language_file_loader.php
phpBB/phpbb/plupload/plupload.php
phpBB/phpbb/request/request.php
phpBB/phpbb/request/request_interface.php
phpBB/phpbb/search/fulltext_mysql.php
phpBB/phpbb/search/fulltext_native.php

PHPBB3-16271
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16271

[ticket/16271] Add Sami 4.x and update necessary dependencies

---

phpBB/memberlist.php

PHPBB3-16273
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16273

[ticket/16273] Check whether the index exists in memberlist - PHP 7.4

---

phpBB/includes/acp/acp_storage.php
phpBB/phpbb/attachment/upload.php
phpBB/phpbb/files/filespec_storage.php

PHPBB3-16271
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16271

[ticket/16271] Fix sami parse errors in master

---

phpBB/includes/functions_module.php
phpBB/includes/message_parser.php
tests/bbcode/parser_test.php
tests/console/cron/run_test.php
tests/console/user/base.php
tests/content_visibility/delete_post_test.php
tests/controller/common_helper_route.php
tests/files/types_base_test.php
tests/functions/obtain_online_test.php
tests/functions/validate_username_test.php
tests/functions_user/delete_user_test.php
tests/functions_user/group_user_attributes_test.php
tests/log/delete_test.php
tests/log/function_view_log_test.php
tests/migrator/get_callable_from_step_test.php
tests/migrator/schema_generator_test.php
tests/passwords/drivers_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16276">PHPBB3-16276</a>.

[ticket/16276] Fix bbcode_firstpass undefined mode property

---

phpBB/phpbb/passwords/driver/argon2i.php
phpBB/phpbb/passwords/driver/base_native.php
tests/passwords/drivers_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16266">PHPBB3-16266</a>.

[ticket/16266] Fix argon2 driver issue for Sodium implementation

---

phpBB/includes/mcp/mcp_topic.php
phpBB/phpbb/search/fulltext_native.php
phpBB/search.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16262

Ticket/16262 compact() calls with undefined variables causing error page

---

phpBB/docs/INSTALL.html

A few typos and not fully up to date information has been updated.
PHPBB3-16278
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16278

[ticket/16278] Clearly state config.php exception and update INSTALL.html

---

phpBB/phpbb/feed/controller/feed.php
phpBB/search.php

PHPBB3-16274
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16274

[ticket/16274] Fix compact() call to undefined variables in search.php

---

phpBB/includes/acp/acp_permissions.php
phpBB/includes/acp/auth.php
phpBB/includes/diff/engine.php
phpBB/includes/functions_convert.php
phpBB/includes/mcp/mcp_logs.php
phpBB/includes/mcp/mcp_notes.php
phpBB/includes/mcp/mcp_warn.php
phpBB/includes/ucp/ucp_groups.php
phpBB/mcp.php
phpBB/phpbb/request/type_cast_helper.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16277">PHPBB3-16277</a>.

[ticket/16277] Move from each() function

---

phpBB/install/schemas/schema_data.sql

PHPBB3-16282
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16282

[ticket/16282] Adjust jQuery cdn url in schema_data

---

phpBB/adm/style/acp_ext_actions.html
phpBB/includes/acp/acp_extensions.php

PHPBB3-16281
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16281

[ticket/16281] Fix Ajax refresh-data for extensions' Tab

---

phpBB/common.php
phpBB/docs/README.html
phpBB/includes/startup.php
phpBB/install/app.php
phpBB/language/en/install.php
phpBB/phpbb/install/module/requirements/task/check_server_environment.php

PHPBB3-16283
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16283

[ticket/16283] Update requirements for 3.3.0

---

phpBB/phpbb/db/migration/data/v330/add_display_unapproved_posts_config.php
phpBB/phpbb/db/migration/data/v330/remove_attachment_flash.php
phpBB/phpbb/db/migration/data/v330/v330b2.php

PHPBB3-16285
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16285

[ticket/16285] Add sanity checks to migrations for 3.3

---

phpBB/language/en/common.php
phpBB/language/en/install.php

PHPBB3-16230
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16230

[ticket/16230] Improve wording of FILESYSTEM_CANNOT_ lang strings

---

phpBB/phpbb/cron/task/core/update_hashes.php

PHPBB3-16293
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16293

[ticket/16293] Do not update to hashes that don't support combined hashing

---

phpBB/phpbb/passwords/driver/argon2i.php

PHPBB3-16266
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16266

[ticket/16266] Remove extra declaration of constants

---

phpBB/phpbb/ucp/controller/reset_password.php
phpBB/styles/prosilver/template/ucp_reset_password.html

PHPBB3-16308
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16308

[ticket/16308] Fix UCP reset password

---

phpBB/styles/prosilver/template/mcp_front.html

PHPBB3-16291
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16291

[ticket/16291] Add missing report time

---

phpBB/phpbb/template/twig/lexer.php
phpBB/styles/prosilver/template/navbar_footer.html

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16323

[ticket/16323] Replace the spaceless tag with its homologue filter

---

phpBB/includes/acp/acp_main.php

PHPBB3-16328
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16328

[ticket/16328] Inform admins about PHP requirements in phpBB 3.3

---

phpBB/includes/functions_privmsgs.php
phpBB/includes/ucp/ucp_pm.php
phpBB/includes/ucp/ucp_pm_viewfolder.php

PHPBB3-16296
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16296

[ticket/16296] Adjust form token check for mark actions

---

phpBB/includes/ucp/ucp_pm_compose.php

PHPBB3-15712
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15712

[ticket/15712] Fix Emoji and rich text in PM subject & draft

---

phpBB/posting.php

PHPBB3-15079
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15079

[ticket/15079] Fix Emoji and rich text in subject of post draft

---

phpBB/language/en/common.php
phpBB/language/en/viewtopic.php
tests/text_formatter/s9e/default_formatting_test.php
tests/text_processing/tickets_data/PHPBB3-11742.html

PHPBB3-16332
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16332

[ticket/16332] Code and Quote language strings globally available

---

phpBB/styles/prosilver/template/navbar_header.html

PHPBB3-16316
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16316

[ticket/16316] Fix breadcrumbs markup validation

---

phpBB/includes/acp/acp_bbcodes.php
phpBB/includes/functions_display.php

PHPBB3-16337
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16337

[ticket/16337] Fix Emoji in BBcode Helpline

---

phpBB/docs/nginx.sample.conf
travis/setup-webserver.sh

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16313

[ticket/16313] Remove http block from sample Nginx configuration file

---

phpBB/adm/style/ajax.js

PHPBB3-15370
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15370

[ticket/15370] Loading indicator when submitting permissions

---

phpBB/adm/style/permissions.js
phpBB/adm/style/tooltip.js

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15766
Perhaps I should explain a bit better what this actually does. 
When you change a permission, it checks if the new group of permissions matches a permission role and indicates it as such in the dropdown. Rather than always defaulting to ‘No role assigned...’

[ticket/15766] Check for role on changing permission settings

---

phpBB/styles/prosilver/template/viewtopic_body.html

PHPBB3-16339
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16339

[ticket/16339] Fix Poll's voting options refresh

---

phpBB/phpbb/captcha/gd_wave.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16360">PHPBB3-16360</a>.

[ticket/16360] Fix allocating color for GD 3D image CAPTCHA

---

phpBB/includes/acp/acp_attachments.php
phpBB/styles/prosilver/template/posting_attach_body.html

[ticket/16349] Fix merge issues in acp_attachments and posting_attach_body.html

---

phpBB/phpbb/search/fulltext_postgres.php

PHPBB3-15395
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15395

[ticket/15395] change GIN tsvector indexes in Postgres Fulltext Search

---

phpBB/includes/functions_user.php

PHPBB3-16348
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16348

[ticket/16348] Prevent double freeing database results on user_ban

---

phpBB/includes/acp/acp_attachments.php
phpBB/includes/constants.php
phpBB/includes/functions_compress.php
phpBB/includes/functions_messenger.php
phpBB/includes/functions_posting.php
phpBB/phpbb/cache/driver/file.php
phpBB/phpbb/files/filespec.php

PHPBB3-16351
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16351

[ticket/16351] Use CHMOD constants from filesystem_interface

---

phpBB/includes/ucp/ucp_pm_compose.php

PHPBB3-10506
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-10506

[ticket/10506] Preserve attachments on not-saving PM draft

---

phpBB/includes/ucp/ucp_pm_compose.php
phpBB/posting.php

PHPBB3-16356
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16356

[ticket/16356] Delete attachments on saving a draft

---

phpBB/styles/prosilver/template/ucp_register.html

PHPBB3-15887
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15887

[ticket/15887] Reposition email after passwords in registration form

---

phpBB/phpbb/di/container_builder.php

PHPBB3-16368
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16368

[ticket/16368] Container isFresh check order

---

phpBB/includes/functions_display.php

PHPBB3-16376
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16376

[ticket/16376] Add default for display_subforum_limit

---

phpBB/phpbb/event/dispatcher.php

PHPBB3-16379
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16379

[ticket/16379] Update deprecated event dispatcher class

---

phpBB/phpbb/console/exception_subscriber.php

PHPBB3-16378
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16378

[ticket/16378] Update deprecated console exception_subscriber event

---

phpBB/phpbb/exception/exception_interface.php

PHPBB3-16380
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16380

[ticket/16380] Exception_interface extends \Throwable

---

phpBB/config/default/container/services_twig.yml
phpBB/phpbb/feed/controller/feed.php
phpBB/phpbb/template/twig/environment.php
phpBB/phpbb/template/twig/extension.php
phpBB/phpbb/template/twig/extension/avatar.php
phpBB/phpbb/template/twig/extension/config.php
phpBB/phpbb/template/twig/extension/username.php
phpBB/phpbb/template/twig/lexer.php
phpBB/phpbb/template/twig/loader.php
phpBB/phpbb/template/twig/node/definenode.php
phpBB/phpbb/template/twig/node/event.php
phpBB/phpbb/template/twig/node/expression/binary/equalequal.php
phpBB/phpbb/template/twig/node/expression/binary/notequalequal.php
phpBB/phpbb/template/twig/node/includeasset.php
phpBB/phpbb/template/twig/node/includenode.php
phpBB/phpbb/template/twig/node/includephp.php
phpBB/phpbb/template/twig/node/php.php
phpBB/phpbb/template/twig/tokenparser/defineparser.php
phpBB/phpbb/template/twig/tokenparser/event.php
phpBB/phpbb/template/twig/tokenparser/includecss.php
phpBB/phpbb/template/twig/tokenparser/includejs.php
phpBB/phpbb/template/twig/tokenparser/includeparser.php
phpBB/phpbb/template/twig/tokenparser/includephp.php
phpBB/phpbb/template/twig/tokenparser/php.php
phpBB/phpbb/template/twig/twig.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16382

[ticket/16382] Update deprecated Twig_ classes

---

phpBB/viewforum.php

PHPBB3-16381
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16381

[ticket/16381] Add core event to Modify Topics SQL

---

phpBB/ucp.php

PHPBB3-16383
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16383

[ticket/16383] Add core events to modify friends list

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/ucp_header.html

PHPBB3-16384
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16384

[ticket/16384] Add template events friends list username {prepend/append}

---

phpBB/phpbb/notification/type/report_pm.php
phpBB/phpbb/notification/type/report_post.php

PHPBB3-16289
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16289

[ticket/16289] Correct ampersand in report notification email

---

phpBB/styles/prosilver/template/mcp_topic.html

PHPBB3-16163
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16163

[ticket/16163] Notice when no posts inside MCP topic

---

phpBB/styles/prosilver/template/navbar_header.html

PHPBB3-16377
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16377
Replaces #5865 
No need to check length if the variable in the for statement is amended.

[ticket/16377] Rename navlinks loop variable

---

phpBB/phpbb/lock/flock.php

PHPBB3-16325
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16325

[ticket/16325] Ensure lock file is opened for updating

---

phpBB/adm/style/acp_attachments.html
phpBB/includes/acp/acp_attachments.php
phpBB/language/en/acp/attachments.php
phpBB/styles/prosilver/template/plupload.html
phpBB/styles/prosilver/template/posting_editor.html
phpBB/styles/prosilver/template/posting_layout.html
phpBB/styles/prosilver/template/posting_pm_layout.html

PHPBB3-16358
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16358

[ticket/16358] Hide attachment tab with no filters and display ACP notice

---

phpBB/language/en/acp/common.php

PHPBB3-15438
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15438

[ticket/15438] Correct log language strings: from > for

---

phpBB/includes/ucp/ucp_notifications.php
phpBB/phpbb/notification/manager.php

This core events allow extensions to control & manipulate Notifications.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16370

[ticket/16370] Add core events for Notification

---

phpBB/styles/prosilver/template/simple_footer.html

PHPBB3-16121
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16121
Adding same classes introduced in #5231 for overall_footer

[ticket/16121] Footer classes in simple_footer

---

phpBB/composer.json
phpBB/composer.lock

Master Version of #5886 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16396

[ticket/16396] Use new php-webdriver instead of facebook webdriver

---

phpBB/mcp.php

PHPBB3-16394
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16394

[ticket/16394] Fix access array offset in MCP topic approval - PHP 7.4

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/viewforum_body.html
phpBB/styles/prosilver/template/viewtopic_body.html

PHPBB3-16388
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16388

[ticket/16388] Add online_list_before template events

---

phpBB/includes/acp/acp_attachments.php

PHPBB3-16245
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16245

[ticket/16245] Cast attachment filesize to bigint

---

phpBB/adm/style/acp_styles.html
phpBB/includes/acp/acp_styles.php

PHPBB3-16225
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16225

[ticket/16225] Display style version in ACP

---

package-lock.json
package.json

PHPBB3-16405
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16405

[ticket/16405] Update npm dependencies to latest versions

---

phpBB/phpbb/user.php

PHPBB3-13914
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13914
See: https://github.com/phpbb/phpbb/pull/3679

[ticket/13914] Cast to INT mixed style ID data in user setup

---

phpBB/styles/prosilver/template/mcp_reports.html

PHPBB3-16403
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16403

[ticket/16403] Fix attachment icon in MCP reports

---

phpBB/includes/mcp/mcp_topic.php

PHPBB3-16399
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16399

[ticket/16399] Fix Emoji in topic title for MCP split topic

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/posting_editor.html

PHPBB3-16400
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16400

[ticket/16400] Add posting_editor_* events

---

phpBB/includes/mcp/mcp_post.php
phpBB/styles/prosilver/template/mcp_post.html

PHPBB3-15275
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15275

[ticket/15275] Fix IP lookup pagination

---

phpBB/phpbb/notification/manager.php

PHPBB3-16406
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16406

[ticket/16406] Fix Core Event of notification

---

phpBB/assets/javascript/core.js

PHPBB3-16222
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16222
Ticket indicates 3.3.0-b2, but the issue is also present on 3.2.x

[ticket/16222] Fix timezone suggestion for 00:00

---

phpBB/styles/prosilver/template/mcp_post.html

PHPBB3-16407
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16407

[ticket/16407] Fix MCP Post reported message

---

phpBB/docs/CREDITS.txt

PHPBB3-16419
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16419

[ticket/16419] Add mrgoldy to CREDITS.txt

---

phpBB/includes/mcp/mcp_notes.php

PHPBB3-16122
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16122

[ticket/16122] Display user rank in MCP user notes

---

phpBB/styles/prosilver/theme/content.css
phpBB/styles/prosilver/theme/forms.css

PHPBB3-16404
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16404

[ticket/16404] Small bug in prosilver

---

phpBB/includes/acp/acp_board.php
phpBB/language/en/email/test.txt

PHPBB3-16180
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16180

[ticket/16180] Allow adding message to test email

---

gulpfile.js
package-lock.json
package.json
phpBB/adm/style/admin.js
phpBB/adm/style/permissions.js
phpBB/adm/style/timezone.js
phpBB/adm/style/tooltip.js
phpBB/assets/javascript/editor.js
phpBB/styles/prosilver/template/timezone.js

PHPBB3-16414
Checklist:
Tracker ticket: https://tracker.phpbb.com/browse/PHPBB3-16414

[ticket/16414] update pkg.json & gulpjs deps

---

phpBB/includes/acp/acp_main.php

PHPBB3-16418
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16418

[ticket/16418] Fix non-numeric value - ACP board start date

---

phpBB/includes/acp/acp_attachments.php

PHPBB3-16416
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16416

[ticket/16416] Fix non-numeric value encountered - ACP attachments

---

.travis.yml

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16440

[ticket/16440] Run tests on a stable PHP 7.4 version

---

phpBB/styles/prosilver/template/ucp_reset_password.html

PHPBB3-16326
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16326

[ticket/16326] Add 'inputbox narrow' to ucp_reset_password

---

.appveyor.yml

PHPBB3-16415
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16415

[ticket/16415] Add COMPOSER_AUTH token to appveyor builds

---

phpBB/styles/prosilver/theme/responsive.css

PHPBB3-16319
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16319

[ticket/16319] Responsive post profile

---

phpBB/styles/prosilver/theme/responsive.css

PHPBB3-16442
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16442

[ticket/16442] Remove redundant longhand value

---

phpBB/includes/acp/acp_board.php
phpBB/phpbb/textformatter/s9e/factory.php
tests/text_formatter/s9e/default_formatting_test.php

This PR is for illustration. It contains a fix in https://github.com/phpbb/phpbb/commit/d836677342a1b767f007cc9158f17e1b5b6da559 and a new behaviour which may or may not be considered a new feature in https://github.com/phpbb/phpbb/commit/a5f1ff43b55fd7d7513e7d8fe8d4be86ff16cf70. The branch is based on 3.3.x.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16361

[ticket/16361] Change the link shortener

---

phpBB/phpbb/session.php

PHPBB3-16397
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16397

[ticket/16397] Expose user identifier

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/viewtopic_body.html

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16421">PHPBB3-16421</a>.

[ticket/16421] Add contact field icon template events to viewtopic_body.html

---

phpBB/config/default/container/services_console.yml
phpBB/language/en/cli.php
phpBB/phpbb/cache/driver/apcu.php
phpBB/phpbb/console/command/extension/command.php
phpBB/phpbb/console/command/extension/disable.php
phpBB/phpbb/console/command/extension/enable.php
phpBB/phpbb/console/command/extension/purge.php

PHPBB3-16432
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16432

[ticket/16432] Display APCu Cache notice when handling extensions through CLI

---

phpBB/phpbb/search/fulltext_mysql.php

PHPBB3-16423
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16423

[ticket/16423] Add Aria Engine to list of Fulltext Supported

---

phpBB/includes/functions_convert.php
phpBB/phpbb/db/migration/data/v33x/bot_update.php
phpBB/phpbb/install/module/install_data/task/add_bots.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16338

[ticket/16338] Add DuckDuckGo bot

---

phpBB/includes/functions_posting.php

PHPBB3-16424
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16424

[ticket/16424] Add base_url to generate_smilies events

---

phpBB/phpbb/textformatter/s9e/factory.php

PHPBB3-16428
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16428

[ticket/16428] Fix invalid scheme name (empty value)

---

phpBB/includes/acp/acp_users.php

PHPBB3-16429
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16429

[ticket/16429] Add vars to 2 ACP User core events

---

phpBB/phpbb/request/type_cast_helper.php

PHPBB3-16422
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16422

[ticket/16422] Strip BOM characters

---

phpBB/includes/acp/acp_permissions.php

PHPBB3-16453
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16453

[ticket/16453] Load permission lang files before core.permissions

---

phpBB/includes/functions_posting.php

PHPBB3-16425
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16425

[ticket/16425] Add event core.generate_smilies_modify_sql

---

phpBB/phpbb/feed/controller/feed.php

[ticket/16367] Add charset to Content-Type response header in feed controller
PHPBB3-16367
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16367

[ticket/16367] Add charset to Content-Type response header in feed controller

---

phpBB/posting.php

PHPBB3-16310
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16310

[ticket/16310] Fix soft delete check when editing a post

---

phpBB/adm/style/captcha_recaptcha_v3.html
phpBB/adm/style/captcha_recaptcha_v3_acp.html
phpBB/assets/javascript/core.js
phpBB/config/default/container/services_captcha.yml
phpBB/language/en/captcha_recaptcha.php
phpBB/phpbb/captcha/plugins/recaptcha_v3.php
phpBB/phpbb/db/migration/data/v330/google_recaptcha_v3.php
phpBB/styles/prosilver/template/captcha_recaptcha.html
phpBB/styles/prosilver/template/captcha_recaptcha_v3.html

https://tracker.phpbb.com/browse/PHPBB3-15937
These tickets are however made for reCAPTCHA v2, but implemented in this PR for v3. 
Not sure if they should be implemented for v2 plugin aswell, cause then I'll have to refactor.
- [Use "global" reCAPTCHA domain to circumvent blocking in some countries](https://tracker.phpbb.com/browse/PHPBB3-16105)
- [Google reCaptcha URL wrong when behind an HTTPS proxy](https://tracker.phpbb.com/browse/PHPBB3-15426)
- [Allow selecting ReCaptcha's "RequestMethod" rather than using the default POST method](https://tracker.phpbb.com/browse/PHPBB3-14988)
I made this ticket against the 3.3 branch as I feel like we should not wait until 4.0 to provide this captcha plugin.
Actually my first time having to …

[ticket/15937] Google reCAPTCHA v3 Plugin

---

phpBB/docs/events.md
phpBB/includes/ucp/ucp_notifications.php
phpBB/phpbb/notification/manager.php
phpBB/styles/prosilver/template/ucp_notifications.html
phpBB/ucp.php
phpBB/viewforum.php

PHPBB3-16411
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16411

[ticket/16411] Add vars to notification core events

---

phpBB/styles/prosilver/template/viewtopic_body.html
phpBB/styles/prosilver/theme/colours.css

PHPBB3-16439
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16439

[ticket/16439] fix post target h3 color

---

phpBB/includes/mcp/mcp_main.php

PHPBB3-15560
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15560

[ticket/15560] Correct redirect on perma-deleting posts

---

phpBB/styles/prosilver/template/viewtopic_body.html

PHPBB3-16445
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16445

[ticket/16445] remove un-semantic erroneous hr.divider from viewtopic_body

---

tests/auth/provider_ldap_test.php

PHPBB3-16462
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16462

[ticket/16462] Skip tests that require the LDAP extension

---

.gitignore

PHPBB3-16461
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16461

[ticket/16461] Update .gitignore to ignore node_modules and idea

---

phpBB/adm/style/admin.css

PHPBB3-16450
Before
After
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16450

[ticket/16450] Fix layout of ACP permission tabs

---

phpBB/includes/ucp/ucp_pm_compose.php

PHPBB3-16447
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16447

[ticket/16447] Add core.ucp_pm_compose_compose_pm_basic_info_query_after

---

phpBB/phpbb/db/driver/postgres.php

PHPBB3-16467
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16467

[ticket/16467] Fix PostgreSQL connection password

---

phpBB/includes/ucp/ucp_pm_compose.php

PHPBB3-16443
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16443

[ticket/16443] Add event core.ucp_pm_compose_modify_parse_after

---

phpBB/includes/ucp/ucp_pm_viewmessage.php

PHPBB3-16444
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16444

[ticket/16444] Add event core.ucp_pm_view_message_before

---

phpBB/includes/functions_privmsgs.php

PHPBB3-16446
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16446

[ticket/16446] Add event core.message_history_modify_rowset

---

phpBB/includes/functions_mcp.php

PHPBB3-16448
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16448

[ticket/16448] Add event core.mcp_get_post_data_after

---

phpBB/adm/style/acp_profile.html
phpBB/docs/events.md

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16458">PHPBB3-16458</a>.

[ticket/16458] Add template events to acp_profile.html

---

phpBB/includes/acp/acp_board.php

PHPBB3-16463
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16463

[ticket/16463] Fix "acp_board.php" for "ACP_SUBMIT_CHANGES".

---

phpBB/adm/style/acp_attachments.html
phpBB/adm/style/acp_ban.html
phpBB/adm/style/acp_contact.html
phpBB/adm/style/acp_database.html
phpBB/adm/style/acp_groups_position.html
phpBB/adm/style/acp_help_phpbb.html
phpBB/adm/style/acp_jabber.html
phpBB/adm/style/acp_permissions.html
phpBB/adm/style/acp_prune_users.html
phpBB/adm/style/acp_search.html
phpBB/includes/acp/acp_board.php

PHPBB3-15672
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15672

[ticket/15672] Keep same format in Submit changes.

---

phpBB/styles/prosilver/template/viewforum_body.html
phpBB/viewforum.php

PHPBB3-16434
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16434

[ticket/16434] Add forum id to advanced search in viewforum

---

phpBB/includes/ucp/ucp_register.php

PHPBB3-16433
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16433

[ticket/16433] Add data array to core.ucp_register_user_row_after

---

phpBB/adm/style/acp_search.html
phpBB/includes/acp/acp_search.php
phpBB/install/schemas/schema_data.sql
phpBB/language/en/acp/search.php
phpBB/language/en/search.php
phpBB/phpbb/db/migration/data/v330/default_search_return_chars.php
phpBB/phpbb/db/migration/data/v33x/default_search_return_chars.php
phpBB/search.php
phpBB/styles/prosilver/template/search_body.html

PHPBB3-16426
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16426

[ticket/16426] Search results return characters as input box

---

phpBB/includes/functions_user.php

PHPBB3-16468
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16468

[ticket/16468] Amend DocBlocks for user_delete()

---

phpBB/phpbb/install/helper/container_factory.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16478">PHPBB3-16478</a>.

[ticket/16478] Fix phpBB Debug warning in installer

---

phpBB/styles/prosilver/template/viewforum_body.html

PHPBB3-16437
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16437

[ticket/16437] Display forum permissions

---

phpBB/includes/functions_display.php
phpBB/memberlist.php

We want to make jabber address unvisible for those users who are not allowed
to send instant (jabber) messages
PHPBB3-15591
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15591

[ticket/15591] Add jabber permission check

---

phpBB/phpbb/report/controller/report.php

PHPBB3-16480
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16480

[ticket/16480] Fix Emoji in report post

---

phpBB/includes/mcp/mcp_warn.php

PHPBB3-16485
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16485

[ticket/16485] Fix Emoji in logs for warning message

---

phpBB/phpbb/db/migration/data/v320/v320a1.php

PHPBB3-16486
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16486

[ticket/16486] Fix migration 3.2.0-a1

---

phpBB/phpbb/db/migration/data/v320/font_awesome_update.php
phpBB/phpbb/db/migration/data/v32x/font_awesome_update_cdn.php

PHPBB3-16487
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16487

[ticket/16487] Fix URL for fontawesome 3.2.0 migration

---

phpBB/phpbb/db/migration/data/v33x/font_awesome_5_update.php

PHPBB3-16487
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16487

[ticket/16487] Fix URL for fontawesome 3.2.0 migration - for 3.3.x

---

phpBB/includes/mcp/mcp_main.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16500">PHPBB3-16500</a>.

[ticket/16500] Fix attachments ordering for copy topic feature

---

phpBB/includes/functions_user.php

PHPBB3-16503
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16503

[ticket/16503] Fix WhoIs lookup

---

phpBB/docs/CREDITS.txt

PHPBB3-16506
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16506

[ticket/16506] Update credits to latest state

---

phpBB/phpbb/search/fulltext_sphinx.php

PHPBB3-16507
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16507

[ticket/16507] Fix incorrect call to sphinx_clean_search_string()

---

phpBB/includes/functions_user.php

PHPBB3-16511
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16511

[ticket/16511] Fix typo when checking for phpbb_delete_users_pms()

---

phpBB/phpbb/language/language.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16505">PHPBB3-16505</a>.

[ticket/16505] Fix use of count() on non-Countable

---

phpBB/phpbb/db/migration/data/v33x/google_recaptcha_v3.php

PHPBB3-16514
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16514

[ticket/16514] Move google_recaptcha_v3 migration from v330 to v33x

---

phpBB/phpbb/db/migration/data/v33x/fix_display_unapproved_posts_config.php

PHPBB3-16510
Follow-up of #6000
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16510

[ticket/16510] [3.3.x] Add migration that makes sure config entry exists

---

phpBB/includes/ucp/ucp_register.php

PHPBB3-16441
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16441

[ticket/16441] Remove deprecated core.ucp_register_agreement event

---

phpBB/phpbb/install/module/install_finish/task/install_extensions.php
phpBB/phpbb/install/module/install_finish/task/notify_user.php
phpBB/phpbb/session.php
phpBB/phpbb/user.php

This replaces the previously added public property.
PHPBB3-16397
PHPBB3-16530
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16397

[ticket/16397] Add method for retrieving user ID

---

phpBB/phpbb/install/module/install_finish/task/install_extensions.php

PHPBB3-16530
Previous PR #6008 caused another issue during installation and did not fully fix the issues in this ticket.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16530

[ticket/16530] Ensure extensions can be installed during installation

---

phpBB/phpbb/db/migration/data/v310/passwords_convert_p1.php

PHPBB3-16534
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16534

[ticket/16534] Add conversion prefix to all passwords that need conversion

---

phpBB/includes/functions_posting.php
tests/functional/smilies_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16539">PHPBB3-16539</a>.

[ticket/16539] Fix general SQL error for smilies mode on posting

---

phpBB/includes/functions_privmsgs.php

PHPBB3-16550
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16550

[ticket/16550] Fix undefined variable url in PMs [3.2.x]

---

phpBB/styles/prosilver/theme/bidi.css

Adding new rule in bidi.css to handle changes caused by [[ticket/16319]](https://github.com/phpbb/phpbb/pull/5914)
PHPBB3-16540
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16540

[ticket/16540] Fix wrong postbody margin RTL

---

phpBB/includes/functions_privmsgs.php

PHPBB3-16550
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16550

[ticket/16550] Fix undefined variable url in PMs

---

phpBB/bin/phpbbcli.php
phpBB/install/phpbbcli.php
phpBB/phpbb/console/application.php

PHPBB3-16417
3.2.x version of https://github.com/phpbb/phpbb/pull/5926
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16417

[ticket/16417] Fix CLI database migration for phpBB 3.0.x

---

phpBB/includes/mcp/mcp_queue.php

PHPBB3-16559
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16559

[ticket/16559] Ensure event variables are defined in mcp_queue

---

phpBB/includes/acp/auth.php

PHPBB3-16430
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16430
And the _(old)_ RFC:
http://area51.phpbb.com/phpBB/viewtopic.php?f=108&t=43295

[ticket/16430] Sort permissions

---

build/build_changelog.php

PHPBB3-16557
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16557

[ticket/16557] Support piping tracker XML to build_changelog.php

---

phpBB/composer.lock

PHPBB3-16571
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16571

[ticket/16571] Update s9e/text-formatter to 2.7.3

---

phpBB/adm/style/admin.js
phpBB/styles/prosilver/template/forum_fn.js

PHPBB3-16568
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16568

[ticket/16568] Fix responsive tabs

---

phpBB/styles/prosilver/theme/responsive.css

PHPBB3-16569
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16569

[ticket/16569] Fix massive margin between zoomed posts

---

package-lock.json
package.json

PHPBB3-16572
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16572

[ticket/16572] Update node modules to latest versions

---

phpBB/phpbb/db/migration/tool/permission.php
tests/dbal/migrator_tool_permission_test.php

PHPBB3-16527
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16527

[ticket/16527] Add a role_exists method to permissions migrator tool

---

phpBB/docs/events.md
phpBB/includes/ucp/ucp_profile.php
phpBB/phpbb/session.php
phpBB/styles/prosilver/template/ucp_profile_autologin_keys.html
tests/functional/ucp_profile_test.php
tests/test_framework/phpbb_functional_test_case.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16533">PHPBB3-16533</a>.

[ticket/16533] Add autologin keys management UCP module events

---

phpBB/adm/style/acp_search.html
phpBB/includes/acp/acp_search.php

PHPBB3-16583
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16583

[ticket/16583] Fix cancel button

---

phpBB/docs/coding-guidelines.html
phpBB/includes/functions_compatibility.php
phpBB/language/en/common.php

PHPBB3-16588
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16588

[ticket/16588] Updates link to plural rules from 3.2.x to 3.3.x

---

phpBB/includes/functions_acp.php
tests/functions_acp/build_cfg_template_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16488">PHPBB3-16488</a>.

[ticket/16488] Fix not displaying min input element attribute when 0

---

phpBB/config/default/container/services_routing.yml
phpBB/config/development/config.yml
phpBB/phpbb/di/extension/container_configuration.php
phpBB/phpbb/routing/router.php
tests/controller/common_helper_route.php
tests/controller/controller_test.php
tests/pagination/pagination_test.php

PHPBB3-15765
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15765

[ticket/15765] Add debug.url_generator

---

phpBB/includes/acp/acp_board.php
phpBB/includes/functions_acp.php
phpBB/language/en/acp/common.php
phpBB/phpbb/textformatter/s9e/factory.php
tests/functional/acp_post_settings_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16526">PHPBB3-16526</a>.

[ticket/16526] Correctly handle ACP CSV settings

---

phpBB/config/default/container/services_routing.yml
phpBB/config/development/config.yml
phpBB/phpbb/di/extension/container_configuration.php
phpBB/phpbb/routing/router.php
tests/controller/common_helper_route.php
tests/controller/controller_test.php
tests/pagination/pagination_test.php

PHPBB3-12630
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-12630

[ticket/12630] Add debug.url_matcher

---

phpBB/includes/functions_posting.php
phpBB/language/en/posting.php
phpBB/styles/prosilver/template/posting_attach_body.html

PHPBB3-15300
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15300

[ticket/15300] Show maximum attachment filesize

---

phpBB/config/default/container/services_notification.yml
phpBB/includes/functions.php
phpBB/includes/functions_posting.php
phpBB/install/schemas/schema_data.sql
phpBB/language/en/ucp.php
phpBB/phpbb/notification/type/forum.php
phpBB/phpbb/notification/type/post.php
tests/notification/base.php
tests/notification/fixtures/submit_post_notification.type.forum.xml
tests/notification/fixtures/submit_post_notification.type.post.xml
tests/notification/notification_method_email_test.php
tests/notification/notification_test.php
tests/notification/submit_post_base.php
tests/notification/submit_post_type_forum_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16544">PHPBB3-16544</a>.

[ticket/16544] Use forum_notify.txt for forum subscription email notifications

---

build/sami-all.conf.php

PHPBB3-16597
3.2.x version of #6044 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16597

[ticket/16597] Stop building docs with sami for 3.3 and above

---

build/doctum-all.conf.php

PHPBB3-16597
Depends on: https://github.com/phpbb/phpbb/pull/6045
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16597

[ticket/16597] Remove not supported branches from doctum-all.conf.php

---

phpBB/config/default/container/services_cron.yml
phpBB/phpbb/cron/manager.php
tests/console/cron/cron_list_test.php
tests/console/cron/run_test.php
tests/controller/common_helper_route.php
tests/cron/manager_test.php
tests/pagination/pagination_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16565

[ticket/16565] Lazy-load cron.task_collection

---

phpBB/language/en/common.php
phpBB/language/en/email/report_closed.txt
phpBB/language/en/email/report_pm_closed.txt
phpBB/language/en/ucp.php
phpBB/phpbb/notification/type/report_pm.php
phpBB/phpbb/notification/type/report_pm_closed.php
phpBB/phpbb/notification/type/report_post_closed.php

Checklist:
TODO:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16208">PHPBB3-16208</a>.

[ticket/16208] Fix posts/PM report notifications

---

phpBB/phpbb/ucp/controller/reset_password.php
phpBB/styles/prosilver/template/ucp_reset_password.html

Credits to thecoalman:
https://www.phpbb.com/community/viewtopic.php?p=15560491#p15560491
PHPBB3-16562
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16562

[ticket/16562] Add password requirements to reset

---

phpBB/phpbb/install/module/install_data/task/create_search_index.php

PHPBB3-16593
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16593

[ticket/16593] Define params in the constructor

---

phpBB/includes/functions_content.php
tests/functions/make_clickable_test.php
tests/functions_user/whois_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16512">PHPBB3-16512</a>.

[ticket/16512] Fix make_clickable() to make use of custom link classes

---

package-lock.json
package.json

PHPBB3-16615
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16615

[ticket/16615] Update xo, yargs-parser, and dependencies

---

phpBB/viewforum.php

Changes topicrow pagination to use values from topicrow
This allows pagination to reflect values from core.viewforum_modify_row
PHPBB3-15722
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15722

[ticket/15722] Allow forum topicrow pagination to use topicrow values

---

.travis.yml
phpBB/includes/functions_posting.php
phpBB/install/convert/convertor.php
phpBB/phpbb/db/driver/driver_interface.php
phpBB/phpbb/db/driver/factory.php
phpBB/phpbb/db/driver/mssql_base.php
phpBB/phpbb/db/driver/mysqli.php
phpBB/phpbb/db/driver/oracle.php
phpBB/phpbb/db/driver/postgres.php
phpBB/phpbb/db/driver/sqlite3.php
tests/functional/smilies_test.php
travis/setup-mysql8.sh
travis/setup-phpbb.sh

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16538">PHPBB3-16538</a>.
<a href="https://tracker.phpbb.com/browse/PHPBB3-16535">PHPBB3-16535</a>.

[ticket/16538] Add MySQL 8 tests

---

phpBB/docs/INSTALL.html

PHPBB3-16625
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16625

[ticket/16625] Add mbstring to install docs

---

phpBB/includes/functions_admin.php
tests/functional/acp_main_test.php

PHPBB3-16629
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16629

[ticket/16629] Fix ACP get_database_size() for MySql 8

---

.github/PULL_REQUEST_TEMPLATE.md

PHPBB3-16633
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16633

[ticket/16633] Update pull request template to remove 3.2.x

---

.travis.yml
travis/setup-phpbb.sh

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16636">PHPBB3-16636</a>.

[ticket/16636] Add PHP 8.0 builds to TravisCI

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/ucp_pm_viewmessage.html

Replacement for #6050.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16606">PHPBB3-16606</a>.

[ticket/16606] Add template events to ucp_pm_viewmessage.html

---

phpBB/phpbb/db/driver/oracle.php

**Needs testing on Oracle database**.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16607">PHPBB3-16607</a>.

[ticket/16607] Update Oracle DBAL driver OCI8 aliases and functions

---

phpBB/mcp.php

PHPBB3-16640
Fix MCP link in menubar when viewing a post report
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16640

[ticket/16640] Show MCP link in menu

---

phpBB/phpbb/profilefields/manager.php
tests/functional/registration_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16582">PHPBB3-16582</a>.

[ticket/16582] Fix SQL error on registration with Numbers CPF with no default value set

---

phpBB/includes/acp/acp_board.php

PHPBB3-16665
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16665

[ticket/16665] Fix Emoji for strings in board settings + new event

---

phpBB/phpbb/attachment/delete.php
phpBB/phpbb/attachment/upload.php
phpBB/phpbb/avatar/driver/upload.php
phpBB/phpbb/composer/extension_manager.php
phpBB/phpbb/console/command/extension/install.php
phpBB/phpbb/console/command/extension/manage.php
phpBB/phpbb/console/command/extension/remove.php
phpBB/phpbb/console/command/extension/update.php
phpBB/phpbb/filesystem/helper.php
phpBB/phpbb/install/module/install_data/task/add_modules.php
phpBB/phpbb/storage/adapter/local.php
phpBB/phpbb/storage/adapter_factory.php
phpBB/phpbb/storage/file_info.php
phpBB/phpbb/storage/storage.php

PHPBB3-16671
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16671

[ticket/16671] Code style fixes

---

phpBB/phpbb/install/helper/container_factory.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16646">PHPBB3-16646</a>.

[ticket/16646] Fix PHP fatal error on installation

---

tests/test_framework/phpbb_test_case_helpers.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16648">PHPBB3-16648</PHPBB3-16648>.

[ticket/16648] Fix possible Access to undeclared static property error in tests

---

phpBB/language/en/captcha_recaptcha.php
phpBB/phpbb/captcha/plugins/recaptcha_v3.php

PHPBB3-16653
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16653

[ticket/16653] Fix Recaptcha-v3 default request method

---

phpBB/styles/prosilver/template/forum_fn.js

PHPBB3-16677
See docs for [jQuery's clone()](https://api.jquery.com/clone/) function.
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16677

[ticket/16677] Copy event listeners and element data when populating dropdown

---

phpBB/includes/acp/acp_board.php

PHPBB3-16670
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16670

[ticket/16670] Fix ACP check-in for OAuth provider keys - PHP 8

---

.github/workflows/tests.yml

[ticket/16676] Cache composer dependencies for github actions

---

phpBB/composer.lock

PHPBB3-16674
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16674

[ticket/16674] Update text-formatter

---

build/code_sniffer/phpbb/Sniffs/Namespaces/UnusedUseSniff.php

PHPBB3-16678
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16678

[ticket/16678] Allow using traits

---

.github/workflows/tests.yml
git-tools/commit-msg-hook-range.sh

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16675">PHPBB3-16675</a>.

[ticket/16675] Restore commit message checks

---

phpBB/adm/style/acp_main.html
phpBB/includes/acp/acp_main.php
phpBB/language/en/acp/common.php

PHPBB3-16656
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16656

[ticket/16656] Fix ACP check-in for mbstring http_input & output

---

.github/workflows/tests.yml

PHPBB3-16666
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16666

[ticket/16666] Exclude PGDATA directory in Windows Defender

---

phpBB/composer.json
phpBB/composer.lock
phpBB/phpbb/db/migration/schema_generator.php
tests/dbal/migration/dummy_order_0.php
tests/dbal/migration/dummy_order_1.php
tests/dbal/migration/dummy_order_2.php
tests/dbal/migration/dummy_order_3.php
tests/dbal/migration/dummy_order_4.php
tests/dbal/migration/dummy_order_5.php

PHPBB3-16668
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16668

[ticket/16668] Refactor schema_generator

---

.github/workflows/tests.yml

Check commit messages on both 'push' and 'pull_request' events.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16675">PHPBB3-16675</a>.

[ticket/16675] Adjust checking commit messages

---

phpBB/includes/functions.php
phpBB/index.php

PHPBB3-16679
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16679

[ticket/16679] Respect "allow password reset" setting on login

---

phpBB/includes/functions_admin.php

Checklist:
[PHPBB3-16686](https://tracker.phpbb.com/browse/PHPBB3-16686)

[ticket/16686] Simplify get_database_size() SQL query for PostgreSQL

---

phpBB/includes/functions_admin.php

PHPBB3-16685
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16685

[ticket/16685] Fix SQL error in ACP for DB name if not correctly escaped

---

.github/workflows/tests.yml

PHPBB3-16675
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16675

[ticket/16675] Restore rxu's fix

---

.github/check-stylesheet.sh
.github/workflows/tests.yml

PHPBB3-16687
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16687

[ticket/16687] Add check stylesheet with stylelint to github workflow

---

phpBB/phpbb/composer/installer.php

PHPBB3-16650
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16650

[ticket/16650] Adjust code for retrieving packagist info for composer 2

---

.github/workflows/tests.yml
tests/functional/extension_acp_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16650">PHPBB3-16650</a>.

[ticket/16650] Add simple functional test

---

phpBB/phpbb/notification/type/report_pm_closed.php

PHPBB3-16691
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16691

[ticket/16691] Fix illegal offset for report_pm_closed notification

---

phpBB/language/en/common.php
phpBB/phpbb/auth/provider/oauth/service/bitly.php

PHPBB3-16689
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16689

[ticket/16689] Fix SQL errors for Bitly OAuth

---

phpBB/phpbb/version_helper.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-11063
PHPBB3-11063

[ticket/11063] Use HTTPS for phpBB's version check

---

phpBB/phpbb/console/command/dev/migration_tips.php

PHPBB3-16620
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16620

[ticket/16620] Output short array syntax in dev:migration-tips

---

.github/workflows/tests.yml

PHPBB3-16707
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16707

[ticket/16707] Disable unstable PHP 8.1 builds

---

phpBB/includes/acp/acp_main.php

PHPBB3-16698
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16698

[ticket/16698] Enhance check for default charset

---

phpBB/includes/functions.php
phpBB/phpbb/auth/provider/oauth/token_storage.php
phpBB/phpbb/session.php

PHPBB3-16706
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16706

[ticket/16706] Fix undefined array keys on user IP ban

---

phpBB/composer.lock

PHPBB3-16709
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16709

[ticket/16709] Update s9e/text-formatter 2.8.1 => 2.8.3

---

phpBB/phpbb/files/upload.php

PHPBB3-16710
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16710

[ticket/16710] Allow WEBP images in attachments

---

phpBB/includes/functions_posting.php

PHPBB3-16712
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16712

[ticket/16712] Implement thumbnails for WEBP images in attachments

---

.github/setup-webserver.sh
.github/workflows/tests.yml

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16711">PHPBB3-16711</a>.

[ticket/16711] Fix PHP 8.1 builds

---

phpBB/adm/style/acp_storage.html
phpBB/composer.json
phpBB/composer.lock
phpBB/phpbb/template/twig/environment.php
phpBB/phpbb/template/twig/lexer.php
phpBB/phpbb/template/twig/loader.php
phpBB/phpbb/template/twig/node/event.php
phpBB/phpbb/template/twig/node/expression/binary/equalequal.php
phpBB/phpbb/template/twig/node/expression/binary/notequalequal.php
phpBB/phpbb/template/twig/node/includenode.php
phpBB/phpbb/template/twig/tokenparser/defineparser.php
phpBB/phpbb/template/twig/tokenparser/includeparser.php
phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
tests/template/template_test.php

This requires merging #6087.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16654">PHPBB3-16654</a>.

[ticket/16654] Upgrade Twig to version 3

---

phpBB/phpbb/console/exception_subscriber.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15298

[ticket/15298] Makes sure CLI exceptions are never suppressed by Symfony

---

phpBB/phpbb/install/module/install_data/task/create_search_index.php

PHPBB3-16717
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16717

[ticket/16717] Set posts_table in indexing installer task

---

phpBB/install/app.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16719">PHPBB3-16719</a>.

[ticket/16719] Fix PHP notice/warning on installation

---

phpBB/language/en/posting.php
phpBB/phpbb/attachment/upload.php
tests/attachment/upload_test.php

PHPBB3-16705
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16705

[ticket/16705] Fix check_disk_space function - PHP 8

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/mcp_forum.html
phpBB/styles/prosilver/template/search_results.html

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16724

[ticket/16724] Add some template events

---

phpBB/includes/mcp/mcp_forum.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16725

[ticket/16725] Add MCP core event

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/search_results.html

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16728

[ticket/16728] Add search result template event

---

vagrant/after.sh
vagrant/bootstrap.yaml
vagrant/phpbb-install-config.yml

PHPBB3-16732
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16732

[ticket/16732] Fix vagrant

---

build/code_sniffer/phpbb/Sniffs/ControlStructures/StaticKeywordSniff.php
build/code_sniffer/ruleset-php-legacy.xml
phpBB/phpbb/db/migration/data/v330/add_display_unapproved_posts_config.php
phpBB/phpbb/db/migration/data/v330/remove_attachment_flash.php
phpBB/phpbb/db/migration/data/v330/remove_max_pass_chars.php
phpBB/phpbb/db/migration/data/v33x/default_search_return_chars.php
phpBB/phpbb/db/migration/data/v33x/google_recaptcha_v3.php
phpBB/phpbb/db/tools/mssql.php
phpBB/phpbb/db/tools/postgres.php
phpBB/phpbb/debug/debug.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16736

[ticket/16736] Add sniffer for visibilitiy qualifiers before static keyword

---

phpBB/phpbb/composer/io/html_output_formatter.php
phpBB/phpbb/config_php_file.php
phpBB/phpbb/db/doctrine/connection_factory.php
phpBB/phpbb/db/doctrine/connection_parameter_factory.php
phpBB/phpbb/db/doctrine/driver_convertor.php
phpBB/phpbb/db/migration/schema_generator.php
phpBB/phpbb/filesystem/helper.php
phpBB/phpbb/install/database_task.php

PHPBB3-16736
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16736

[ticket/16736] Fix static declarations on master

---

build/build_changelog.php

PHPBB3-16730
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16730

[ticket/16730] Don't do additional sorting or output without any tickets

---

phpBB/includes/acp/acp_search.php

[ticket/15540] Change method name with the new one

---

phpBB/phpbb/filesystem/filesystem.php
phpBB/phpbb/filesystem/filesystem_interface.php
phpBB/phpbb/filesystem/helper.php
phpBB/phpbb/storage/adapter/adapter_interface.php
phpBB/phpbb/storage/adapter/local.php
phpBB/phpbb/storage/stream_interface.php
tests/filesystem/realpath_test.php
tests/storage/adapter/local_subfolders_test.php
tests/storage/adapter/local_test.php
tests/storage/adapter/local_test_case.php

PHPBB3-16639
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16639

[ticket/16639] Pass absolute paths to make_path_relative

---

phpBB/language/en/email/short/report_pm.txt

PHPBB3-16739
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16739

[ticket/16739] Replaces TOPIC_TITLE by SUBCJECT in short/report_pm.txt

---

.github/workflows/tests.yml

PHPBB3-16675
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16675

[ticket/16675] Use github base branch head rev for commit message check

---

phpBB/phpbb/files/filespec.php

PHPBB3-16743
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16743

[ticket/16743] Properly check if TMP file exists - PHP 8

---

phpBB/phpbb/auth/provider/db.php

PHPBB3-16735
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16735

[ticket/16735] Fix access array offset on value of type bool on login

---

.github/workflows/tests.yml
phpBB/phpbb/db/driver/postgres.php
phpBB/phpbb/db/tools/postgres.php
tests/test_framework/phpbb_database_test_case.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16740

[ticket/16740] Add method for ensuring resource is not passed to cache

---

.github/check-stylesheet.sh
package-lock.json
package.json

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16746

[ticket/16746] Update node modules to latest versions

---

phpBB/language/en/email/post_in_queue.txt
phpBB/language/en/email/short/post_in_queue.txt

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16747

[ticket/16747] Fix typo in post_in_queue.txt email template

---

build/code_sniffer/phpbb/Sniffs/ControlStructures/StaticKeywordSniff.php
phpBB/docs/coding-guidelines.html

PHPBB3-16748
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16748

[ticket/16748] Adjust coding guidelines to put static after visibility

---

phpBB/phpbb/db/driver/mysqli.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16749">PHPBB3-16749</a>.

[ticket/16749] Explicitly set default MySQLi error mode

---

phpBB/develop/export_events_for_rst.php
phpBB/phpbb/event/md_exporter.php
phpBB/phpbb/event/php_exporter.php
phpBB/phpbb/event/rst_exporter.php
tests/event/php_exporter_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16752

[ticket/16752] Add exporter for event into to restructured text

---

phpBB/styles/prosilver/template/mcp_notes_user.html
phpBB/styles/prosilver/template/mcp_warn_post.html
phpBB/styles/prosilver/template/mcp_warn_user.html
phpBB/styles/prosilver/template/memberlist_body.html
phpBB/styles/prosilver/template/memberlist_view.html
phpBB/styles/prosilver/template/ucp_pm_viewmessage.html
phpBB/styles/prosilver/template/viewtopic_body.html
phpBB/styles/prosilver/theme/content.css

PHPBB3-16751
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16751

[ticket/16751] add rank-img class to template files for consistency with area51 and .com

---

phpBB/styles/prosilver/template/pagination.html

PHPBB3-16761
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16761

[ticket/16761] add missing closing a tag to page-jump

---

phpBB/styles/prosilver/template/mcp_forum.html
phpBB/styles/prosilver/template/ucp_main_bookmarks.html
phpBB/styles/prosilver/template/ucp_main_front.html
phpBB/styles/prosilver/template/ucp_main_subscribed.html
phpBB/styles/prosilver/template/viewforum_body.html

PHPBB3-16762
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16762
before

[ticket/16762] fix topicrow paging

---

phpBB/adm/style/captcha_qa_acp.html

PHPBB3-16757
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16757

[ticket/16757] Properly handle RTL text in ACP QA Captcha HTML

---

phpBB/install/startup.php

PHPBB3-16766
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16766

[ticket/16766] Show long error messages during install/update

---

phpBB/phpbb/db/migration/data/v33x/v334.php

PHPBB3-16770
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16770

[ticket/16770] Rearrange static qualifier in 3.3.4 migration

---

.github/workflows/tests.yml

PHPBB3-16740
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16740

[ticket/16740] Remove no longer supported and duplicate runs

---

phpBB/phpbb/db/extractor/postgres_extractor.php

Checklist:
Tracker ticket: [PHPBB3-16773](https://tracker.phpbb.com/browse/PHPBB3-16773)

[ticket/16773] Add missing constraints in PostgreSQL backups

---

phpBB/includes/mcp/mcp_front.php
phpBB/includes/mcp/mcp_reports.php
phpBB/includes/mcp/mcp_topic.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16771">PHPBB3-16771</a>.

[ticket/16771] Add MCP core events

---

phpBB/includes/mcp/mcp_topic.php

PHPBB3-16771
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16771

[ticket/16771] Add missing phpbb_dispatcher to globals

---

phpBB/includes/acp/acp_board.php

PHPBB3-16772
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16772

[ticket/16772] Fix Emoji for Email signature

---

phpBB/phpbb/install/module/update_filesystem/task/diff_files.php
phpBB/phpbb/install/module/update_filesystem/task/download_updated_files.php
phpBB/phpbb/install/module/update_filesystem/task/update_files.php

PHPBB3-16570
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16570

[ticket/16570] Support continuing update on manually merging files

---

phpBB/styles/prosilver/theme/stylesheet.css

PHPBB3-16778
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16778

[ticket/16778] fix stylesheet.css

---

.gitignore

PHPBB3-17684
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16784

[ticket/16784] ignore .vscode

---

build/build.xml

PHPBB3-16785
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16785

[ticket/16785] Use correct versions in build.xml for 3.3.x branch

---

phpBB/adm/style/acp_database.html
phpBB/includes/acp/acp_database.php
phpBB/language/en/acp/database.php

PHPBB3-16783
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16783

[ticket/16783] Remove structure only backup

---

phpBB/phpbb/file_downloader.php

PHPBB3-16787
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16787

[ticket/16787] Properly check if fsockopen() is enabled - PHP 8

---

phpunit.xml.dist

PHPBB3-16786
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16786

[ticket/16786] Migrate phpunit xml configuration to latest schema

---

phpBB/download/file.php
phpBB/includes/functions_download.php
phpBB/phpbb/content_visibility.php

PHPBB3-16793
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16793

[ticket/16793] Fix topic/post attachments visibility - PHP 8

---

package-lock.json

PHPBB3-16746
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16746

[ticket/16746] Update node packages

---

README.md

PHPBB3-16798
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16798

[ticket/16798] Scale down phpbb logo on readme

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/viewtopic_body.html

PHPBB3-16795
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16795

[ticket/16795] Add template events around signature in viewtopic

---

phpBB/composer.lock

PHPBB3-16788
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16788

[ticket/16788] Update s9e/text-formatter to 2.9.3

---

phpBB/includes/functions_user.php

PHPBB3-16789
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16789

[ticket/16789] Update user_delete() doc-block

---

phpBB/phpbb/log/log.php

PHPBB3-16729
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16729

[ticket/16729] Fix Unknown named parameter in Log - PHP 8

---

phpBB/includes/functions.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16808

[ticket/16808] Make sure we have a container before using it

---

phpBB/phpbb/auth/provider/base.php
phpBB/phpbb/auth/provider/oauth/oauth.php
phpBB/phpbb/auth/provider/provider_interface.php
tests/functional/auth_test.php
tests/test_framework/phpbb_functional_test_case.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16799">PHPBB3-16799</a>.
Replacement for #6232.

[ticket/16799] Fix OAuth external account linking PHP fatal error

---

tests/functional/ucp_preferences_test.php

PHPBB3-16809
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16809

[ticket/16809] Reset display options at the end of preferences test

---

tests/functional/auth_test.php

PHPBB3-16817
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16817

[ticket/16817] Adjust selectors and expected strings on oauth test

---

phpBB/adm/style/acp_inactive.html
phpBB/adm/style/acp_styles.html
phpBB/adm/style/overall_footer.html
phpBB/styles/prosilver/template/simple_footer.html

Fix acp style html validation errors and warnings
PHPBB3-16816
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16816

[ticket/16816] acp style html validation fixes

---

phpBB/memberlist.php

PHPBB3-16657
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16657

[ticket/16657] Properly decode usernames in member list live-search

---

phpBB/includes/functions_display.php

PHPBB3-16810
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16810

[ticket/16810] Fix No end tag in Custom BBCodes

---

phpBB/includes/acp/acp_extensions.php

PHPBB3-12075
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-12075

[ticket/12075] Add acp/modules language file to extensions page

---

phpBB/adm/style/acp_bbcodes.html
phpBB/includes/acp/acp_bbcodes.php
phpBB/phpbb/db/migration/data/v33x/extend_bbcode_tooltip.php

Reopened version of #6236
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16804

[ticket/16804] Extend bbcode help line tooltip

---

phpBB/phpbb/db/migration/data/v33x/extend_bbcode_tooltip.php

PHPBB3-16804
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16804

[ticket/16804] Reorder static keyword to fit with guidelines

---

phpBB/phpbb/datetime.php
tests/datetime/from_format_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16823">PHPBB3-16823</a>.

[ticket/16823] Make datetime class correctly handle edge cases

---

phpBB/phpbb/template/twig/extension/icon.php
phpBB/styles/prosilver/template/overall_header.html

PHPBB3-16834
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16834

[ticket/16834] Fix tag svg invalid in Entity - PHP8

---

.github/setup-webserver.sh
.github/workflows/tests.yml
phpBB/phpbb/db/driver/postgres.php

For `3.3` branch only.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16840">PHPBB3-16840</a>.

[ticket/16840] Add more PHP 8.x builds to tests matrix

---

phpBB/styles/prosilver/template/overall_header.html

PHPBB3-16850
Replaces https://github.com/phpbb/phpbb/pull/6136
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16850

[ticket/16850][3.3] Update webfont loader

---

phpBB/styles/prosilver/template/overall_header.html

PHPBB3-16850
Replaces https://github.com/phpbb/phpbb/pull/6136
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16850

[ticket/16850][4.0] Update webfont loader

---

phpBB/styles/prosilver/theme/base.css
phpBB/styles/prosilver/theme/bidi.css
phpBB/styles/prosilver/theme/buttons.css
phpBB/styles/prosilver/theme/colours.css
phpBB/styles/prosilver/theme/common.css
phpBB/styles/prosilver/theme/content.css
phpBB/styles/prosilver/theme/cp.css
phpBB/styles/prosilver/theme/forms.css
phpBB/styles/prosilver/theme/icons.css
phpBB/styles/prosilver/theme/links.css
phpBB/styles/prosilver/theme/print.css
phpBB/styles/prosilver/theme/responsive.css
phpBB/styles/prosilver/theme/stylesheet.css
phpBB/styles/prosilver/theme/utilities.css

this is just to fix tabs, missing delimiters, and remove old commented classes in css files
PHPBB3-16831
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16831

[ticket/16831] fix tabs missing delimiters and remove commented class

---

phpBB/adm/style/mentions_templates.html

PHPBB3-16835
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16835

[ticket/16835] Add missing template file in ACP

---

phpBB/includes/acp/acp_main.php
phpBB/includes/functions.php
phpBB/includes/functions_acp.php
phpBB/phpbb/session.php
phpBB/styles/prosilver/template/index_body.html
phpBB/styles/prosilver/template/login_body.html
phpBB/styles/prosilver/template/viewforum_body.html
phpBB/ucp.php
tests/functional/auth_test.php
tests/functional/mcp_test.php
tests/functional/report_post_captcha_test.php
tests/functional/ucp_profile_test.php
tests/test_framework/phpbb_functional_test_case.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16825

[ticket/16825] Adjust handling of session ID when requiring cookies

---

phpBB/phpbb/storage/adapter/local.php
phpBB/phpbb/storage/stream_interface.php
tests/functional/acp_storage_test.php

PHPBB3-16836
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16836

[ticket/16836] Use absolute paths in local adapter

---

phpBB/styles/prosilver/template/navbar_footer.html
phpBB/styles/prosilver/template/viewtopic_topic_tools.html
phpBB/styles/prosilver/theme/icons.css

PHPBB3-16833
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16833

[ticket/16833][4.0.x] Improve subscribe to forum or topic icons

---

phpBB/includes/ucp/ucp_attachments.php

PHPBB3-16832
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16832

[ticket/16832] Fix UCP attachments plural rules

---

phpBB/includes/functions_messenger.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-15729">PHPBB3-15729</a>.

[ticket/15729] Avoid unnecessary email headers encoding in Base64

---

phpBB/phpbb/db/migration/data/v33x/jquery_update_v2.php

[ticket/16858] Fix coding style

---

phpBB/composer.lock

PHPBB3-16867
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16867

[ticket/16867] Update symfony and text-formatter to latest versions

---

phpBB/composer.lock

Master version of #6284 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16867

[ticket/16867] Update symfony and text-formatter to latest versions -- master version

---

phpBB/phpbb/config/db.php
phpBB/phpbb/db/migration/data/v33x/google_recaptcha_v3.php

PHPBB3-16870
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16870

[ticket/16870] Ensure to properly escape values when running db:migrate

---

.github/PULL_REQUEST_TEMPLATE.md

PHPBB3-16868
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16868

[ticket/16868] Fix links to coding guidelines

---

phpBB/phpbb/passwords/driver/argon2i.php

PHPBB3-16878
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16878

[ticket/16878] Default to threads value of 1 when using argon with libsodium

---

phpBB/includes/functions_messenger.php

PHPBB3-16879
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16879

[ticket/16879] Add events to phpbb_mail()

---

phpBB/adm/style/acp_main.html
phpBB/includes/acp/acp_main.php

PHPBB3-16881
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16881

[ticket/16881] Fix ACP statistics

---

phpBB/phpbb/db/driver/sqlite3.php

PHPBB3-16897
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16897

[ticket/16897] Ignores sqlite3 warnings when an explain query plan query fails

---

.gitignore

PHPBB3-16896
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16896

[ticket/16896] Adds comments in .gitignore and excludes custom envs

---

phpBB/includes/functions_messenger.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16900">PHPBB3-16900</a>.

[ticket/16900] Fix quoted_printable_encode() behavior

---

.github/workflows/tests.yml
tests/functional/auth_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16909">PHPBB3-16909</a>.

[ticket/16909] Add PHP 8.2 builds to test matrix

---

phpBB/adm/style/acp_attachments.html
phpBB/includes/acp/acp_attachments.php
phpBB/language/en/acp/attachments.php
tests/functional/acp_attachments_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16910">PHPBB3-16910</a>.

[ticket/16910] Fix PHP warnings on uploading orphaned files to posts

---

tests/functional/acp_attachments_test.php

Tests fix for `master` branch only.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16910">PHPBB3-16910</a>.

[ticket/16910] Fix ACP orphan attachments module tests

---

phpBB/docs/vagrant.md
vagrant/after.sh
vagrant/bootstrap.yaml
vagrant/phpbb-install-config.yml

PHPBB3-16906
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16906

[ticket/16906] Update vagrant ip

---

phpBB/includes/functions_mcp.php
phpBB/includes/functions_module.php
tests/functional/mcp/mcp_logs_test.php
tests/functional/mcp/mcp_main_test.php
tests/functional/mcp/mcp_quickmod_tools_test.php
tests/functional/mcp/mcp_test.php
tests/test_framework/phpbb_functional_test_case.php
tests/text_formatter/s9e/mention_helper_test.php

`master` version for #6323.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16904">PHPBB3-16904</a>.

[ticket/16904] Fix regression in MCP for topics selection

---

phpBB/posting.php
tests/functional/posting_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16908">PHPBB3-16908</a>.

[ticket/16908] Fix PHP warning on non-existent post id requests

---

.github/workflows/tests.yml
phpBB/docs/INSTALL.html

PHPBB3-16921
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16921

[ticket/16921] Increase PHP requirements in the DOCS

---

phpBB/language/en/migrator.php
phpBB/phpbb/db/migration/data/v33x/remove_non_existant_assigned_roles.php
phpBB/phpbb/db/migration/data/v33x/remove_orphaned_roles.php
phpBB/phpbb/db/migration/tool/permission.php
tests/dbal/migrator_tool_permission_role_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16895">PHPBB3-16895</a>.

[ticket/16895] Fix role removal for migrator permission tool

---

phpBB/phpbb/config/db.php
tests/config/db_test.php
tests/config/db_text_test.php

PHPBB3-16924
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16924

[ticket/16924] Do not double escape values inserted into config table

---

.github/workflows/tests.yml

PHPBB3-16939
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16939

[ticket/16939] Wait for postgresql service to start on windows CI runners

---

phpBB/adm/style/acp_icons.html
phpBB/adm/style/acp_ranks.html
phpBB/includes/acp/acp_icons.php
phpBB/includes/acp/acp_ranks.php
phpBB/includes/functions_admin.php
phpBB/styles/prosilver/theme/content.css

PHPBB3-16899
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16899

[ticket/16899] Add SVG and WEBP to ranks, smilies and topic icons

---

build/psalm_bootstrap.php
phpBB/composer.json
phpBB/composer.lock
psalm.xml

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16936

[ticket/16936] Add psalm dependency and basic configuration file

---

phpBB/phpbb/search/fulltext_native.php
tests/functional/search/base.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16933">PHPBB3-16933</a>.

[ticket/16933] Consistent handling of hyphen by phpBB Native search backend

---

tests/functional/download_test.php

PHPBB3-16950
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16950

[ticket/16950] Make download_test URLs work without URL rewrite

---

phpBB/viewforum.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16930

[ticket/16930] Remove redundant topic ID from last post URL

---

phpBB/phpbb/search/fulltext_mysql.php
phpBB/phpbb/search/fulltext_native.php
phpBB/phpbb/search/fulltext_postgres.php
tests/functional/feed_test.php
tests/functional/mcp/mcp_main_test.php
tests/functional/search/base.php
tests/functional/visibility_disapprove_test.php
tests/functional/visibility_reapprove_test.php
tests/functional/visibility_unapproved_posts_test.php
tests/test_framework/phpbb_functional_test_case.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16902">PHPBB3-16902</a>.

[ticket/16902] Improve search results count - 3.3.x

---

phpBB/phpbb/search/backend/fulltext_mysql.php
phpBB/phpbb/search/backend/fulltext_native.php
phpBB/phpbb/search/backend/fulltext_postgres.php
tests/functional/feed_test.php
tests/functional/mcp/mcp_main_test.php
tests/functional/search/base.php
tests/functional/visibility_disapprove_test.php
tests/functional/visibility_reapprove_test.php
tests/functional/visibility_unapproved_posts_test.php
tests/test_framework/phpbb_functional_test_case.php

`master` version of #6321.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16902">PHPBB3-16902</a>.

[ticket/16902] Improve search results count - master

---

phpBB/adm/style/acp_ext_list.html
phpBB/includes/acp/acp_extensions.php
phpBB/phpbb/composer/installer.php
phpBB/phpbb/composer/manager.php
tests/functional/extension_acp_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16688">PHPBB3-16688</a>.
<a href="https://tracker.phpbb.com/browse/PHPBB3-16943">PHPBB3-16943</a>.

[ticket/16688] Fix PHP fatal errors on installing extensions via catalog

---

phpBB/phpbb/extension/manager.php
tests/extension/manager_test.php

PHPBB3-16956
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16956

[ticket/16956] Remove use of recently changed status for extensions

---

phpBB/phpbb/di/container_builder.php

PHPBB3-16960
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16960

[ticket/16960] Set config.php service even if container is not compiled

---

phpBB/config/default/container/services.yml
phpBB/phpbb/extension/manager.php
phpBB/phpbb/routing/router.php
tests/dbal/migrator_test.php
tests/extension/manager_test.php
tests/extension/metadata_manager_test.php
tests/mock/extension_manager.php
tests/test_framework/phpbb_functional_test_case.php

The deferred purge will be used in the future instead. The cache flag in the
router only causes additional issues by trying to rebuild the routing
mid-request
PHPBB3-16956
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16956

[ticket/16956] Remove router cache flag

---

phpBB/config/default/container/services.yml
phpBB/phpbb/cache/service.php
phpBB/phpbb/extension/manager.php
tests/attachment/upload_test.php
tests/cache/common_test_case.php
tests/cache/dummy_driver_test.php
tests/dbal/migrator_tool_module_test.php
tests/dbal/migrator_tool_permission_role_test.php
tests/dbal/migrator_tool_permission_test.php
tests/extension/manager_test.php
tests/extension/metadata_manager_test.php
tests/notification/base.php
tests/notification/notification_method_email_test.php
tests/notification/submit_post_base.php
tests/notification/user_list_trim_test.php
tests/session/check_ban_test.php
tests/test_framework/phpbb_functional_test_case.php
tests/version/version_helper_remote_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16891

ticket/16891] Add new method for deferring cache purge to end of request

---

phpBB/config/default/container/services.yml
phpBB/phpbb/cache/service.php
phpBB/phpbb/extension/manager.php
tests/attachment/upload_test.php
tests/cache/common_test_case.php
tests/cache/dummy_driver_test.php
tests/dbal/migrator_tool_module_test.php
tests/dbal/migrator_tool_permission_role_test.php
tests/dbal/migrator_tool_permission_test.php
tests/extension/manager_test.php
tests/extension/metadata_manager_test.php
tests/mention/controller_test.php
tests/notification/base.php
tests/notification/notification_method_email_test.php
tests/notification/submit_post_base.php
tests/notification/user_list_trim_test.php
tests/session/check_ban_test.php
tests/test_framework/phpbb_functional_test_case.php
tests/version/version_helper_remote_test.php

Master version of https://github.com/phpbb/phpbb/pull/6359
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16891

[ticket/16891] Add new method for deferring cache purge to end of request -- Master version

---

phpBB/develop/export_events_for_bbcode.php
phpBB/phpbb/event/md_exporter.php
phpBB/phpbb/event/php_exporter.php

PHPBB3-16872
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16872

[ticket/16872] Add event exporter for BBCode

---

phpBB/phpbb/db/doctrine/connection_parameter_factory.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16965">PHPBB3-16965</a>.

[ticket/16965] Allow empty value as default database server name on installing

---

tests/datetime/from_format_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16962">PHPBB3-16962</a>.

[ticket/16962] Fix datetime format test

---

phpBB/includes/mcp/mcp_main.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16966">PHPBB3-16966</a>.

[ticket/16966] Fix redirect link after permanently deleting posts

---

phpBB/phpbb/search/fulltext_mysql.php
phpBB/phpbb/search/fulltext_native.php
phpBB/phpbb/search/fulltext_postgres.php
tests/functional/search/base.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16976">PHPBB3-16976</a>.

[ticket/16976] Fix search results count

---

phpBB/phpbb/search/backend/fulltext_mysql.php
phpBB/phpbb/search/backend/fulltext_native.php
phpBB/phpbb/search/backend/fulltext_postgres.php
tests/functional/search/base.php

`master` version of #6374.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16976">PHPBB3-16976</a>.

[ticket/16976] Fix search results count - master

---

.stylelintrc
package-lock.json
package.json
phpBB/adm/style/admin.css
phpBB/assets/javascript/mentions.js
phpBB/styles/prosilver/theme/common.css
phpBB/styles/prosilver/theme/print.css

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16405

[ticket/16405] Update npm dependencies

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/ucp_main_bookmarks.html
phpBB/styles/prosilver/template/ucp_main_subscribed.html

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16991

[ticket/16991] Add events for bookmarks and subscribed topics in UCP

---

phpBB/docs/coding-guidelines.html

PHPBB3-16967
3.3 version of https://github.com/phpbb/phpbb/pull/6369
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16967

[ticket/16967] Deprecate PHP in templates

---

git-tools/hooks/prepare-commit-msg

PHPBB3-16988
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16988

[ticket/16988] Improve handling of appended branch info and security branches

---

phpBB/styles/prosilver/template/posting_pm_header.html

Checklist:
Tracker ticket (set the ticket ID to **your ticket ID**): PHPBB3-16978
https://tracker.phpbb.com/browse/PHPBB3-16978

[ticket/16978] add missing ul closeing tag

---

phpBB/styles/prosilver/template/posting_pm_header.html

master version of https://github.com/phpbb/phpbb/pull/6378
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16978

[ticket/16978] add missing ul closeing tag & convert to twig

---

phpBB/composer.lock

master version of https://github.com/phpbb/phpbb/pull/6399
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16987

[ticket/16987] Update composer dependencies to latest versions - master version

---

phpBB/includes/functions_messenger.php

PHPBB3-16932
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16932

[ticket/16932] Ensure special characters are encoded for ASCII in emails

---

phpBB/phpbb/db/migration/data/v33x/profilefield_youtube_update.php

PHPBB3-17019
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17019

[ticket/17019] Treat removed youtube profile field as effectively installed

---

phpBB/phpbb/composer/installer.php

PHPBB3-17024
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17024

[ticket/17024] Add composer/installers to allowed plugins

---

phpBB/composer.json
phpBB/composer.lock

PHPBB3-17023
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17023

[ticket/17023] Adds PHP >=8.0  to composer require php version

---

phpBB/phpbb/feed/helper.php

PHPBB3-17030
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17030

[ticket/17030] Fix feed to return valid RFC-3339 dates

---

phpBB/phpbb/user_loader.php
tests/user/fixtures/user_loader_no_guest.xml
tests/user/user_loader_no_guest_test.php

PHPBB3-17032
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17032

[ticket/17032] Prevent endlessly cycling to load user

---

phpBB/composer.lock

PHPBB3-17048
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17048

[ticket/17048] Update composer dependencies for 3.3.9

---

phpBB/phpbb/textformatter/s9e/renderer.php

PHPBB3-17051
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17051

[ticket/17051] Fallback to default values for possible undefined user data

---

phpBB/phpbb/template/assets_bag.php
tests/template/template_includecss_test.php

PHPBB3-17050
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17050

[ticket/17050] Remove trailing slash from generated css includes

---

phpBB/config/default/container/services_cron.yml
phpBB/phpbb/cron/task/core/tidy_search.php

PHPBB3-17062
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17062

[ticket/17062] Call search service using dependency injection

---

phpBB/adm/style/captcha_recaptcha_acp.html
phpBB/phpbb/captcha/plugins/recaptcha.php
phpBB/phpbb/captcha/plugins/recaptcha_v3.php

PHPBB3-16105
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16105

[ticket/16105] Use Google reCAPTCHA globally

---

phpBB/includes/mcp/mcp_notes.php

PHPBB3-17065
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17065

[ticket/17065] Add utf8_encode_ucr to $usernotes

---

.github/workflows/tests.yml

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17066

[ticket/17066] Update actions to resolve deprecation warnings

---

phpBB/styles/prosilver/template/ajax.js

PHPBB3-13291
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13291

[ticket/13291] Close notifications dropdown during mark all read

---

phpBB/phpbb/mimetype/extension_guesser.php

PHPBB3-17069
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17069

[ticket/17069] Fix duplicate key in array

---

phpBB/includes/acp/acp_permission_roles.php

PHPBB3-17074
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17074

[ticket/17074] Don't allow to create two roles with the same name

---

phpBB/adm/style/overall_footer.html
phpBB/adm/style/simple_footer.html
phpBB/docs/events.md

PHPBB3-17075
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17075

[ticket/17075] Add template events to ACP footers after $SCRIPT

---

phpBB/includes/functions_posting.php

PHPBB3-17081
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17081

[ticket/17081] Fix accept attribute in upload input

---

phpBB/adm/style/acp_users_warnings.html

PHPBB3-16938
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16938

[ticket/16938] Replace invalid nowrap with white-space css

---

phpBB/styles/prosilver/template/ucp_groups_manage.html

PHPBB3-17039
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17039

[ticket/17039] Use correct template var for group colour in ucp groups manage

---

.github/setup-phpbb.sh
.github/workflows/tests.yml
phpBB/cron.php
phpBB/phpbb/session.php

PHPBB3-17091
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17091

[ticket/17091] Limit doctrine/instantiator to 1.x versions

---

phpBB/language/en/acp/common.php
phpBB/phpbb/session.php

Master version of #6453
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17092

[ticket/17092] Check for Spamhaus error codes

---

phpBB/styles/prosilver/template/mcp_post.html
phpBB/styles/prosilver/template/ucp_main_front.html

PHPBB3-17085
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17085

[ticket/17085] Fix invalid icon names

---

phpBB/adm/style/acp_search_index.html
phpBB/adm/style/acp_search_index_inprogress.html
phpBB/adm/style/acp_search_index_progress.html
phpBB/includes/acp/acp_search.php
phpBB/language/en/acp/search.php
tests/functional/search/base.php

Based on #6410 for master, replaces #6411
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16913

[ticket/16913] Add Search Index Progress Bar with Stats [master]

---

phpBB/styles/prosilver/theme/content.css

Master version of #6457 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16796

[ticket/16796] Fixing misalignment of header items in category on index -- master version

---

phpBB/styles/prosilver/template/ucp_pm_viewmessage_print.html

PHPBB3-17098
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17098

[ticket/17098] Add class S_CONTENT_DIRECTION to body in ucp_pm_viewmessage_print.html

---

phpBB/includes/mcp/mcp_warn.php

PHPBB3-17089
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17089

[ticket/17089] If user warned without post assume 0 for forum/topic_id

---

phpBB/language/en/cli.php
phpBB/phpbb/console/command/searchindex/create.php
phpBB/phpbb/console/command/searchindex/delete.php

PHPBB3-17067
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17067

[ticket/17067] Add lang variable for rows per second & searchindex:

---

phpBB/styles/prosilver/template/simple_header.html

PHPBB3-17046
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17046

[ticket/17046] Use tweaks.css for IE9 in overall_ and simple_header

---

phpBB/styles/prosilver/theme/bidi.css

PHPBB3-17043
The same is rule is 100% the same in line 732 to 739 in the same file. 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17043

[ticket/17043] Remove unnecessary cp navi CSS rule in bidi.css

---

phpBB/styles/prosilver/template/memberlist_body.html
phpBB/styles/prosilver/theme/content.css

PHPBB3-17042
**Before:**
**After:**
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17042

[ticket/17042] Add CSS rules for group desc and list

---

phpBB/styles/prosilver/template/pagination.html

PHPBB3-17041
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17041

[ticket/17041] Add if to show other arrow for RTL languages

---

phpBB/styles/prosilver/template/ucp_pm_viewmessage_print.html

PHPBB3-17040
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17040

[ticket/17040] Include bidi.css to pm print only in RTL languages

---

phpBB/phpbb/db/tools/doctrine.php

PHPBB3-17105
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17105

[ticket/17105] Fix order of arguments for schema changes on indexes

---

phpBB/phpbb/search/backend/fulltext_native.php
tests/functional/search/base.php

`master` version of #6472.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17115">PHPBB3-17115</a>.

[ticket/17115] Fix PHP warning for space+hyphen ending search query - master

---

tests/RUNNING_TESTS.md

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17126

Fix filename in instructions about running all tests

---

phpBB/adm/style/acp_search_index.html
phpBB/composer.lock
phpBB/includes/acp/acp_search.php
phpBB/phpbb/template/twig/extension.php
tests/functional/search/base.php
tests/test_framework/phpbb_test_case_helpers.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17108

[ticket/17108] Update composer dependencies and expect trigger error code 

---

phpBB/includes/ucp/ucp_profile.php
phpBB/phpbb/ucp/controller/reset_password.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17127">PHPBB3-17127</a>.

[ticket/17127] Do not purge guest sessions when resetting password

---

phpBB/language/en/install.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17132">PHPBB3-17132</a>.

[ticket/17132] Restore language entries missing in phpBB 2.0 converter

---

phpBB/includes/functions_transfer.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17139">PHPBB3-17139</a>.

[ticket/17139] Fix PHP fatal error for file transfer tool of updater

---

phpBB/config/default/container/services_content.yml
phpBB/phpbb/viewonline_helper.php
phpBB/viewonline.php
tests/functional/viewonline_test.php
tests/viewonline/helper_test.php

For 3.3.x branch.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17107">PHPBB3-17107</a>.

[ticket/17107] Fix viewonline page locations for posting modes - 3.3.x

---

.github/PULL_REQUEST_TEMPLATE.md
phpBB/docs/CREDITS.txt

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17149

[ticket/17149] Update authors list and simplify pull request template

---

phpBB/phpbb/cache/driver/base.php
phpBB/phpbb/cache/driver/driver_interface.php
phpBB/phpbb/db/driver/driver.php
phpBB/phpbb/db/driver/driver_interface.php
phpBB/phpbb/db/driver/factory.php
phpBB/phpbb/db/driver/mssql_odbc.php
phpBB/phpbb/db/driver/mssqlnative.php
phpBB/phpbb/db/driver/mysqli.php
phpBB/phpbb/db/driver/oracle.php
phpBB/phpbb/db/driver/postgres.php
phpBB/phpbb/db/driver/sqlite3.php
tests/mock/cache.php

`master` version of #6488.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17142">PHPBB3-17142</a>.

[ticket/17142] Fix DBMS+cache related PHP warnings while installing - master

---

phpBB/phpbb/notification/method/jabber.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17146

Fix 'undefined array key' php8 warning

---

phpBB/phpbb/db/migration/data/v30x/local_url_bbcode.php

PHPBB3-17140
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17140

[ticket/17140] Add missing parameter phpbb_root_path

---

phpBB/styles/prosilver/theme/content.css

PHPBB3-17150
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17150

[ticket/17150] Set max width for forum-image img

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/viewtopic_body.html

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17152">PHPBB3-17152</a>.

[ticket/17152] Add template event to viewtopic_body.html

---

phpBB/common.php
phpBB/phpbb/di/container_builder.php

PHPBB3-17053
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17053

[ticket/17053] Add simple check for writable cache directory

---

phpBB/config/default/routing/storage.yml
phpBB/download/file.php
phpBB/includes/acp/acp_attachments.php
phpBB/includes/acp/acp_users.php
phpBB/includes/functions_content.php
phpBB/includes/functions_posting.php
phpBB/includes/message_parser.php
phpBB/includes/ucp/ucp_attachments.php
phpBB/phpbb/storage/controller/attachment.php
tests/functional/acp_attachments_test.php

This will also fix the invalid requirements for the file parameter of the URL.
PHPBB3-15687
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15687

[ticket/15687] Add attachment filename to attachment URL

---

phpBB/styles/prosilver/template/mcp_front.html

PHPBB3-17160
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17160

[ticket/17160] Add missing mark column header

---

phpBB/includes/functions.php
tests/functions/short_ipv6__test.php

PHPBB3-11765
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-11765

[ticket/11765] Support IPv4 embedded IPv6 addresses in short_ipv6()

---

phpBB/language/en/acp/permissions.php

PHPBB3-11184
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-11184

[ticket/11184] Add note about effect of admin permissions for founders

---

phpBB/phpbb/template/twig/extension/forms.php
phpBB/styles/all/template/macros/forms/input.twig
phpBB/styles/all/template/macros/forms/select.twig
phpBB/styles/all/template/macros/forms/textarea.twig

PHPBB3-17151
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17151

[ticket/17151] Adjust form macros to adhere to coding guidelines

---

phpBB/styles/prosilver/theme/responsive.css

Master version of #6519 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17171

[ticket/17171] Remove unsupported CSS rules for placeholder -- master version

---

phpBB/includes/mcp/mcp_topic.php

PHPBB3-13364
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13364

[ticket/13364] Force sync forum after splitting topic

---

phpBB/styles/prosilver/template/search_results.html
phpBB/styles/prosilver/template/ucp_main_bookmarks.html
phpBB/styles/prosilver/template/ucp_main_front.html
phpBB/styles/prosilver/template/ucp_main_subscribed.html
phpBB/styles/prosilver/template/viewforum_body.html
phpBB/styles/prosilver/theme/colours.css
phpBB/styles/prosilver/theme/links.css

Also removed the unread post icon and instead opted for playing with font weight and color for indication.
PHPBB3-17155
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17155

[ticket/17155] Default to first unread post on topics

---

phpBB/includes/functions_admin.php
phpBB/phpbb/notification/manager.php
tests/mock/notification_manager.php

PHPBB3-11449
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-11449

[ticket/11449] Add separate method for deleting notifications by multiple types

---

phpBB/phpbb/db/driver/driver.php

PHPBB3-12439
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-12439

[ticket/12439] Unify behavior and deduplicate sql_multi_insert

---

phpBB/includes/functions.php
phpBB/includes/functions_content.php
phpBB/includes/functions_posting.php
phpBB/phpbb/avatar/driver/local.php
phpBB/phpbb/avatar/driver/upload.php
phpBB/phpbb/path_helper.php
phpBB/phpbb/textformatter/s9e/renderer.php

PHPBB3-13276
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13276

[ticket/13276] Support PHPBB_USE_BOARD_URL_PATH in web root path

---

phpBB/includes/functions.php
phpBB/includes/functions_content.php
phpBB/includes/functions_posting.php
phpBB/phpbb/avatar/driver/local.php
phpBB/phpbb/avatar/driver/upload.php
phpBB/phpbb/avatar/helper.php
phpBB/phpbb/path_helper.php
phpBB/phpbb/template/twig/extension/icon.php
phpBB/phpbb/textformatter/s9e/renderer.php

Master version of https://github.com/phpbb/phpbb/pull/6501
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13276

[ticket/13276] Support PHPBB_USE_BOARD_URL_PATH in web root path -- master version

---

phpBB/includes/ucp/ucp_attachments.php
phpBB/includes/ucp/ucp_pm_viewmessage.php
tests/functional/ucp_attachments_test.php

PHPBB3-17137
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17137

[ticket/17137] Allow deleting user files only when post/pm can be changed

---

phpBB/includes/ucp/ucp_attachments.php
phpBB/includes/ucp/ucp_pm_viewmessage.php
tests/functional/ucp_attachments_test.php

master version of #6516 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17137

[ticket/17137] Allow deleting user files only when post/pm can be changed -- master version

---

phpBB/includes/acp/acp_modules.php
phpBB/includes/functions_module.php
phpBB/phpbb/template/twig/extension/forms.php
phpBB/phpbb/template/twig/extension/icon.php
tests/functional/extension_controller_test.php
tests/functional/extension_global_lang_test.php
tests/functional/extension_module_test.php
tests/functional/extension_permission_lang_test.php
tests/functional/fixtures/ext/foo/bar/acp/main_info.php
tests/functional/fixtures/ext/foo/bar/acp/main_module.php
tests/functional/fixtures/ext/foo/bar/adm/style/foobar.html
tests/functional/fixtures/ext/foo/bar/mcp/main_info.php
tests/functional/fixtures/ext/foo/bar/mcp/main_module.php
tests/functional/fixtures/ext/foo/bar/migrations/add_acp_module.php
tests/functional/fixtures/ext/foo/bar/migrations/add_mcp_module.php
tests/functional/fixtures/ext/foo/bar/migrations/add_permission.php
tests/functional/fixtures/ext/foo/bar/migrations/add_ucp_module.php
tests/functional/fixtures/ext/foo/bar/styles/prosilver/template/foobar_mcp.html
tests/functional/fixtures/ext/foo/bar/ucp/main_info.php
tests/functional/metadata_manager_test.php
tests/test_framework/phpbb_functional_test_case.php

Also add tests and error reporting.
PHPBB3-17151
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17151

[ticket/17151] Make macros available for extensions

---

phpBB/common.php
phpBB/includes/functions_messenger.php
phpBB/phpbb/install/module/obtain_data/task/obtain_server_data.php

PHPBB3-12785
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-12785

[ticket/12785] Prefer REQUEST_URI over PHP_SELF in early redirects

---

.gitignore
build/build.xml
build/generate_package_json.php
build/generate_signature.php
build/verify_signature.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17173

[ticket/17173]  Add functionality for signing build packages

---

.github/workflows/tests.yml
phpBB/composer.lock

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17193

[ticket/17193] Reduce amount of unit test runners

---

vagrant/bootstrap.yaml

PHPBB3-17194
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17194

[ticket/17194] Move php version in vagrant from folders to sites

---

phpBB/composer.json
phpBB/composer.lock

PHPBB3-16923
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-16923

[ticket/16923] Fix composer.json requirements

---

phpBB/styles/prosilver/template/forumlist_body.html

Per discussion with @marc1706, we'll use Twig syntax even if it means mixing with the old templating syntax.
PHPBB3-17172
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17172

[ticket/17172] Use correct lang for forum links

---

phpBB/index.php

PHPBB3-15973
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15973

[ticket/15973] Add canonical URL for index

---

phpBB/phpbb/avatar/driver/remote.php
tests/avatar/manager_test.php

PHPBB3-17198
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17198

[ticket/17198] Use https instead of http as default in remote avatar

---

phpBB/styles/prosilver/template/ucp_pm_history.html

PHPBB3-17116
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17116

[ticket/17116] Remove always TRUE if-sentence

---

phpBB/includes/mcp/mcp_topic.php

PHPBB3-17113
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17113

[ticket/17113] Write icon_id to split topic's posts

---

phpBB/includes/functions_posting.php
phpBB/phpbb/content_visibility.php
tests/content_visibility/delete_post_test.php
tests/content_visibility/fixtures/delete_post.xml
tests/content_visibility/set_post_visibility_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17029

[ticket/17029] Update post count when changing post visibility

---

phpBB/phpbb/profilefields/manager.php
phpBB/styles/prosilver/template/ucp_register.html

PHPBB3-12904
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-12904

[ticket/12904] Do not display info about required fields without any

---

phpBB/install/startup.php
phpBB/phpbb/cache/driver/file.php
phpBB/phpbb/filesystem/filesystem.php
phpBB/phpbb/install/module/requirements/task/check_filesystem.php

PHPBB3-17189
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17189

[Ticket/17189] Improve installer file permission checks

---

phpBB/includes/acp/acp_users.php
phpBB/includes/ucp/ucp_profile.php
phpBB/includes/ucp/ucp_register.php
phpBB/language/en/common.php

PHPBB3-13399
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13399

[ticket/13399] Add separate plural rules for characters count

---

phpBB/includes/mcp/mcp_forum.php
phpBB/includes/mcp/mcp_topic.php
phpBB/styles/prosilver/template/mcp_topic.html

PHPBB3-17187
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17187

[ticket/17187] Repair mcp link to first unread post

---

phpBB/viewonline.php

PHPBB3-17200
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17200

[ticket/17200] Fix color parse error in viewonline legend

---

phpBB/common.php
phpBB/includes/functions.php
tests/functions/phpbb_get_install_redirect_test.php

PHPBB3-17201
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17201

[ticket/17201] Do not run dirname() on dir path during install redirect

---

phpBB/styles/prosilver/template/viewtopic_print.html

PHPBB3-17202
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17202

[ticket/17202] Include bidi.css to print only in RTL languages

---

phpBB/styles/prosilver/theme/content.css

PHPBB3-17203
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17203

[ticket/17203] Add CSS ol for group desc

---

phpBB/phpbb/db/migration/data/v33x/profilefield_youtube_update.php
phpBB/phpbb/db/migration/data/v33x/profilefields_update.php

PHPBB3-17208
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17208

[ticket/17208] Skip profile field data update if youtube cpf doesn't exist

---

phpBB/phpbb/template/twig/environment.php

PHPBB3-17207
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17207

[ticket/17207] Lazily call get_web_root_path() in twig environment

---

phpBB/includes/functions_jabber.php

PHPBB3-14047
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-14047

[ticket/14047] Check for stream close handshake before closing stream

---

phpBB/composer.lock

PHPBB3-17236
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17236

[ticket/17236] Update composer dependencies to improve PHP 8.3 compatibility

---

phpBB/composer.lock

Master version of #6569 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17236

[ticket/17236] Update composer dependencies to impove PHP 8.3 compatibility -- master version

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/ucp_footer.html
phpBB/styles/prosilver/template/ucp_header.html
phpBB/styles/prosilver/template/ucp_notifications.html

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17277">PHPBB3-17277</a>.

[ticket/17277] Add template events to UCP

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/ucp_footer.html
phpBB/styles/prosilver/template/ucp_header.html
phpBB/styles/prosilver/template/ucp_notifications.html

`master` version of #6575.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17277">PHPBB3-17277</a>.

[ticket/17277] Add template events to UCP - master version

---

git-tools/hooks/prepare-commit-msg

PHPBB3-17280
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17280

[ticket/17280] Fall back to branch when no valid title found

---

phpBB/phpbb/session.php
phpBB/posting.php
tests/functional/viewonline_test.php

PHPBB3-17212
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17212

[ticket/17212] Support updating session info when editing post with p=

---

phpBB/config/default/container/services_event.yml
phpBB/phpbb/event/kernel_exception_subscriber.php
tests/event/exception_listener_test.php
tests/functional/session_page_update_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17286">PHPBB3-17286</a>.

[ticket/17286] Do not update user session page if it does not exist

---

phpBB/config/default/container/services_console.yml
phpBB/config/default/container/services_search.yml
phpBB/develop/fill.php
phpBB/develop/repair_bots.php
phpBB/includes/acp/acp_forums.php
phpBB/includes/acp/acp_icons.php
phpBB/includes/acp/acp_main.php
phpBB/includes/acp/acp_permissions.php
phpBB/includes/functions_admin.php
phpBB/includes/functions_compatibility.php
phpBB/includes/functions_convert.php
phpBB/includes/functions_user.php
phpBB/install/convert/controller/convertor.php
phpBB/install/convert/convertor.php
phpBB/phpbb/console/command/cache/purge.php
phpBB/phpbb/db/tools/doctrine.php
phpBB/phpbb/db/tools/tools_interface.php
phpBB/phpbb/install/module/install_data/task/create_search_index.php
phpBB/phpbb/search/backend/fulltext_native.php
tests/console/cache/purge_test.php
tests/dbal/db_tools_test.php
tests/search/native_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-13162

[ticket/13162] Add truncate table functionality to database tools

---

phpBB/phpbb/session.php

PHPBB3-17292
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17292

[ticket/17292] Use new spamhaus.org check url

---

phpBB/adm/index.php
phpBB/phpbb/event/kernel_exception_subscriber.php
phpBB/phpbb/path_helper.php
tests/functional/session_page_update_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17296

[ticket/17296] Reduce complexity of relative paths on adm pages 

---

phpBB/adm/index.php
phpBB/phpbb/event/kernel_exception_subscriber.php
phpBB/phpbb/path_helper.php
tests/functional/session_page_update_test.php

master version of #6588 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17296

[ticket/17296] Reduce complexity of relative paths on adm pages

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/viewtopic_body.html

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17284">PHPBB3-17284</a>.

[ticket/17284] Add viewtopic_body_online_list_after template event

---

phpBB/phpbb/ucp/controller/reset_password.php

Password reset function does not update all necessary data
PHPBB3-17302
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17302

[ticket/17302] Fix password reset function

---

phpBB/includes/functions_messenger.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17299">PHPBB3-17299</a>.

[ticket/17299] Allow event to modify email core vars before sending a message

---

phpBB/phpbb/avatar/helper.php

PHPBB3-17297
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17297

[ticket/17297] Fix broken no avatar source tag in HTML

---

phpBB/search.php

PHPBB3-17305
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17305

[ticket/17305] Improve queries for unanswered posts/topics

---

phpBB/search.php

PHPBB3-17305
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17305

[ticket/17305] Change sql_sort to be more in line with previous code

---

phpBB/search.php

PHPBB3-17305
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17305

[ticket/17305] Add missing space to sql_sort

---

phpBB/includes/functions_content.php

PHPBB3-17306
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17306

[ticket/17306] Add type declaration to get_context and array for $words

---

phpBB/includes/functions_content.php

PHPBB3-17306
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17306

[ticket/17306] Add type declaration to get_context and array for $words (for Master)

---

phpBB/phpbb/textreparser/base.php
tests/text_reparser/plugins/post_text_test.php
tests/text_reparser/plugins/test_row_based_plugin.php

PHPBB3-17130
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17130

[ticket/17130] Reparse magic urls in posts based on actual content

---

phpBB/config/default/container/services_content.yml
phpBB/phpbb/lock/posting.php
phpBB/posting.php
phpBB/styles/prosilver/template/ajax.js
phpBB/styles/prosilver/template/posting_editor.html
tests/lock/posting_test.php
tests/test_framework/phpbb_functional_test_case.php
tests/test_framework/phpbb_test_case_helpers.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17077

[ticket/17077] Improve handling of posting to reduce double submit possibility

---

phpBB/includes/acp/auth.php
phpBB/language/en/acp/permissions_phpbb.php
phpBB/phpbb/auth/auth.php
tests/functional/acp_permissions_test.php

PHPBB3-15325
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15325

[ticket/15325] Do not show non-local permissions for local data

---

.github/workflows/tests.yml

Master version of #6607 
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17310

[ticket/17310] Update workflow actions to v4 -- master version

---

phpBB/docs/INSTALL.html
phpBB/docs/README.html

PHPBB3-17176
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17176

[ticket/17311] Update PHP requirements and tested version

---

phpBB/phpbb/db/migration/data/v400/add_webpush.php

PHPBB3-17313
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17313

[ticket/17313] Add Push Module to Correct Parent

---

phpBB/styles/prosilver/template/notification_dropdown.html

PHPBB3-17318
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17318

[ticket/17318] Fix notification avatars in dropdown

---

phpBB/includes/acp/acp_search.php

PHPBB3-17323
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17323

[ticket/17323] Fix division by 0 when there is 0 posts

---

phpBB/docs/events.md
phpBB/phpbb/event/md_exporter.php
phpBB/styles/prosilver/template/notification_dropdown.html

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17324">PHPBB3-17324</a>.

[ticket/17324] Add template event to notification_dropdown.html

---

phpBB/adm/style/acp_main.html
phpBB/includes/acp/acp_main.php

Show explicit message for "Re-Check version" if installed version is still up to date
PHPBB3-17325
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17325

[ticket/17325] Show message for "Re-Check version" if phpBB is still up to date

---

phpBB/phpbb/console/command/user/add.php

PHPBB3-17327
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17327

[ticket/17327] Use class name from use statement

---

phpBB/develop/export_events_for_bbcode.php
phpBB/develop/export_events_for_rst.php
phpBB/develop/export_events_for_wiki.php

PHPBB-17328
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17328

[ticket/17328] Update requires for exporting events

---

phpBB/phpbb/notification/method/webpush.php
phpBB/phpbb/ucp/controller/webpush.php
phpBB/styles/all/js/push_worker.js.twig

PHPBB-17321
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17321

[ticket/17321] Add versioning to push worker to force updates

---

phpBB/phpbb/notification/method/webpush.php
tests/notification/notification_method_webpush_test.php

PHPBB-17330
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17330

[ticket/17330] Handle mozilla not properly handling webpush padding

---

phpBB/phpbb/composer/installer.php

PHPBB-17336
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17336

[ticket/17336] Fix dev extensions not showing versions correctly in catalog

---

phpBB/phpbb/db/migration/tool/permission.php
tests/dbal/migrator_tool_permission_role_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17332">PHPBB-17332</a>.

[ticket/17332] Fix permission migrator tool to work with copied permissions

---

.github/workflows/tests.yml

3.3.x version of #6645 
PHPBB-17342
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17342

[ticket/17342] Add tests for PHP 8.4 to GitHub Actions

---

phpBB/phpbb/cache/driver/file.php
tests/cache/file_driver_test.php

PHPBB-17301
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17301

[ticket/17301] Ensure reading invalid cache files is aborted

---

phpBB/phpbb/cache/driver/file.php
tests/cache/file_driver_test.php

Master version of #6639 
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17301

[ticket/17301] Ensure reading invalid cache files is aborted -- master version

---

phpBB/phpbb/db/migration/data/v400/add_webpush_token.php
phpBB/phpbb/notification/method/webpush.php
phpBB/phpbb/ucp/controller/webpush.php
phpBB/styles/all/js/push_worker.js.twig

PHPBB-17339
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17339

[ticket/17339] Support receiving push notifications if not logged in

---

phpBB/assets/javascript/webpush.js
phpBB/language/en/common.php
phpBB/styles/prosilver/template/notification_dropdown.html
phpBB/styles/prosilver/template/ucp_notifications_options.html
phpBB/styles/prosilver/theme/buttons.css
phpBB/styles/prosilver/theme/colours.css
phpBB/styles/prosilver/theme/common.css
phpBB/styles/prosilver/theme/responsive.css
tests/functional/notification_webpush_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17344

Ticket/17344 User Experience improvements to web push subscriptions

---

phpBB/phpbb/console/command/fixup/update_hashes.php
phpBB/phpbb/cron/task/core/update_hashes.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17351">PHPBB-17351</a>.

[ticket/17351] Correctly handle md5 passwords rehashing - 3.3.x

---

phpBB/phpbb/console/command/fixup/update_hashes.php
phpBB/phpbb/cron/task/core/update_hashes.php

`master` version of #6658.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17351">PHPBB-17351</a>.

[ticket/17351] Correctly handle md5 passwords rehashing - master

---

phpBB/phpbb/extension/manager.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17362

[ticket/17362] Declare property to avoid PHP 8.2 deprecation notice

---

phpBB/phpbb/console/command/user/delete_id.php

PHPBB-17347
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17347

[ticket/17347] Fix psalm error for user delete by ID command

---

phpBB/includes/functions.php
phpBB/install/startup.php

PHPBB-17356
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17356

[ticket/17356] Correctly handle errors hidden with at

---

phpBB/docs/lighttpd.sample.conf
phpBB/docs/nginx.sample.conf

PHPBB-16890
Checklist:
https://tracker.phpbb.com/browse/PHPBB-16890

[ticket/16890] Deny access to config file and folder in nginx sample

---

phpBB/adm/style/acp_forums.html
phpBB/includes/acp/acp_board.php

PHPBB-17364
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17364

[ticket/17364] Correctly handle styles list in ACP Forums

---

phpBB/posting.php

PHPBB-13916
Checklist:
https://tracker.phpbb.com/browse/PHPBB-13916

[ticket/13916] Add notify to fields to store during save draft

---

phpBB/web.config

PHPBB-16907
Checklist:
https://tracker.phpbb.com/browse/PHPBB-16907

[ticket/16907] Adjust request filtering for phpbb paths

---

phpBB/includes/functions_content.php
phpBB/includes/utf/utf_tools.php
tests/functional/search/base.php
tests/functions_content/get_context_test.php

PHPBB3-15043
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-15043

[ticket/15043] Rewrite get_context()

---

phpBB/composer.json
phpBB/includes/functions_content.php
phpBB/includes/utf/utf_tools.php
tests/functional/search/base.php
tests/functions_content/get_context_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB-12345

[ticket/15043] Rewrite get_context() [master version]

---

phpBB/phpbb/avatar/driver/gravatar.php
tests/avatar/driver_gravatar_test.php

Will also need porting of the fix to 3.3.x.
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17353
https://tracker.phpbb.com/browse/PHPBB-17355

[ticket/17353] Get gravatar img src and fix incorrect treatment of height

---

tests/avatar/driver_gravatar_test.php

master version of #6660 
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17353
https://tracker.phpbb.com/browse/PHPBB-17355

[ticket/17353] Get gravatar img src and fix incorrect treatment of height -- master version

---

phpBB/includes/functions.php

PHPBB-17022
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17022

[ticket/17022] Fix SQL report link

---

phpBB/includes/acp/acp_logs.php

PHPBB-17374
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17374

[ticket/17374] Only delete marked logs if entries have been marked

---

phpBB/config/default/container/services_ucp.yml
phpBB/config/default/routing/ucp.yml
phpBB/includes/functions.php
phpBB/phpbb/ucp/controller/delete_cookies.php
phpBB/ucp.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17370

[ticket/17370] Move delete cookies functionality to controller

---

phpBB/includes/functions_module.php
tests/functional/switch_permissions_test.php

PHPBB-14454
Checklist:
https://tracker.phpbb.com/browse/PHPBB-14454

[ticket/14454] Handle special case of testing user permissions in ACP modules

---

phpBB/includes/functions_privmsgs.php

PHPBB-15576
Checklist:
https://tracker.phpbb.com/browse/PHPBB-15576

[ticket/15576] Handle subject max length same as in form input

---

build/build.xml
phpBB/phpbb/.htaccess

PHPBB-16213
Checklist:
https://tracker.phpbb.com/browse/PHPBB-16213

[ticket/16213] Add .htaccess for phpbb and vendor folders

---

phpBB/phpbb/captcha/plugins/recaptcha_v3.php
phpBB/styles/prosilver/template/ajax.js
phpBB/styles/prosilver/template/posting_editor.html

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17366

[ticket/17366] Resolve issues with form submissions and recaptcha

---

build/build.xml
phpBB/docs/lighttpd.sample.conf
phpBB/docs/nginx.sample.conf
phpBB/phpbb/.htaccess
phpBB/vendor-ext/.htaccess

Master version of https://github.com/phpbb/phpbb/pull/6681
Checklist:
https://tracker.phpbb.com/browse/PHPBB-16213

[ticket/16213] Add .htaccess for phpbb and vendor folders -- master version

---

phpBB/phpbb/cache/driver/redis.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17358">PHPBB-17358</a>.

[ticket/17358] Properly handle Redis cache expiration time - 3.3.x

---

phpBB/phpbb/session.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17375

[ticket/17375] Ensure user last visit does not get updated for active sessions in session gc

---

.github/workflows/tests.yml

PHPBB-17377
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17377

[ticket/17377] Use specific mssql docker images to have uniform builds

---

.github/workflows/tests.yml

Master version of #6700 
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17377

[ticket/17377] Use specific mssql docker images to have uniform builds 

---

phpBB/styles/prosilver/template/ucp_pm_viewmessage.html

This removes some templating code for posts which had slipped into the view PM page (where it cannot function).
PHPBB-17181
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17181

[ticket/17181] Remove unused PM report code

---

tests/test_framework/phpbb_test_case.php

PHPBB-17384
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17384

[ticket/17384] Stop overriding error handler in test case

---

phpBB/adm/style/acp_posting_buttons.html
phpBB/includes/constants.php
phpBB/styles/prosilver/template/posting_buttons.html

PHPBB-17379
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17379

[ticket/17379] Use correct number of predefined BBCodes in posting editor

---

phpBB/adm/style/acp_ext_list.html
phpBB/docs/events.md
phpBB/includes/acp/acp_extensions.php
phpBB/language/en/acp/extensions.php
tests/functional/extension_acp_test.php

<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17359">PHPBB-17359</a>.

[ticket/17359] Distinct disabled and available extensions list

---

phpBB/phpbb/auth/auth.php
tests/functional/acp_permissions_test.php

Fix a bug caused by #6549.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17386">PHPBB-17386</a>.

[ticket/17386] Fix resulting permission for user-based tracing

---

tests/functional/acp_permissions_test.php

Unify #6709 tests for `3.3.x` and `master`.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17386">PHPBB-17386</a>.

[ticket/17386] Unify user based permissions test for 3.3.x and master branches

---

phpBB/includes/functions_content.php
tests/functions_content/get_context_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17387">PHPBB-17387</a>.

[ticket/17387] Fix PHP warnings in search results

---

.github/workflows/tests.yml

PHPBB-17394
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17394

[ticket/17394] Check mergeability of 3.3.x PRs

---

.github/workflows/check_merge_to_master.yml
.github/workflows/merge_3.3.x_to_master.yml
.github/workflows/tests.yml

PHPBB-17396
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17396

[ticket/17396] Add workflow for merging 3.3.x into master

---

.github/workflows/merge_3.3.x_to_master.yml

PHPBB-17396
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17396

[ticket/17396] Only try pushing if merge was successful

---

.github/workflows/merge_3.3.x_to_master.yml
.github/workflows/tests.yml

PHPBB-17396
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17396

[ticket/17396] Fetch full history and branch 3.3.x if merging to master

---

.github/workflows/check_merge_to_master.yml

PHPBB-17394
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17394

[ticket/17394] Merge local 3.3.x and not remote into master

---

phpBB/includes/functions.php

This fixes DST transition seasonal tests failures.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17405">PHPBB-17405</a>.

[ticket/17405] Fix getting UTC date/time information logic

---

.github/workflows/merge_3.3.x_to_master.yml

[skip actions] Due to no code changes that run in PRs.
PHPBB-17396
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17396

[ticket/17396] Use GitHub App to merge to master

---

README.md

PHPBB-17404
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17404

[ticket/17404] Update workflow test badges

---

.github/workflows/tests.yml

PHPBB-17400
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17400

[ticket/17400] Use fixed version for mssql 2017 tests

---

package-lock.json
phpBB/composer.json
phpBB/composer.lock

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17403

[ticket/17403] Update composer and node dependencies

---

phpBB/includes/functions_messenger.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17383">PHPBB-17383</a>.

[ticket/17383] Fix HELO/EHLO error in email messenger on PHP8

---

phpBB/phpbb/file_downloader.php
tests/version/fixture/30x.txt
tests/version/version_helper_remote_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17385

[ticket/17385] Backport file_downloader with guzzle for versioncheck with redirect support

---

phpBB/includes/acp/acp_board.php
phpBB/includes/message_parser.php
phpBB/includes/questionnaire/questionnaire.php
phpBB/install/schemas/schema_data.sql
phpBB/language/en/acp/board.php
phpBB/phpbb/db/migration/data/v400/remove_max_img_size.php
phpBB/phpbb/textformatter/parser_interface.php
phpBB/phpbb/textformatter/s9e/factory.php
tests/functional/manifest_test.php
tests/text_processing/message_parser_test.php

PHPBB-16777
Checklist:
https://tracker.phpbb.com/browse/PHPBB-16777

[ticket/16777] Remove remainders of max image size

---

.github/workflows/check_merge_to_master.yml

PHPBB-17407
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17407

[ticket/17407] Update comment in merge check if possible

---

.github/workflows/check_merge_to_master.yml

[skip ci] Since this change won't run until merged.
PHPBB-17407
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17407

[ticket/17407] Combine create and update step and use replace edit-mode

---

phpBB/config/default/container/services_ucp.yml
phpBB/phpbb/notification/method/webpush.php
phpBB/phpbb/ucp/controller/webpush.php

PHPBB-17343
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17343

[ticket/17343] Display push notifications in user language

---

phpBB/assets/javascript/installer.js
phpBB/phpbb/install/module/install_database/task/add_config_settings.php
phpBB/phpbb/install/module/install_database/task/update_user_and_post_data.php
phpBB/phpbb/install/module/obtain_data/task/obtain_admin_data.php

PHPBB-14404
Checklist:
https://tracker.phpbb.com/browse/PHPBB-14404

[ticket/14404] Set board & admin timezone based on browser timezone

---

phpBB/viewforum.php

PHPBB-17397
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17397

[ticket/17397] Add core.viewforum_modify_sql event

---

phpBB/includes/functions.php
phpBB/phpbb/path_helper.php
tests/path_helper/path_helper_test.php

PHPBB-17398
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17398

[ticket/17398] Add referer to delete cookies route to ensure proper URLs

---

phpBB/includes/functions_module.php
tests/functional/switch_permissions_test.php

PHPBB-17410
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17410

[ticket/17410] Only fall back acp main page when in ACP with test permission

---

phpBB/search.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17411">PHPBB-17411</a>.

[ticket/17411] Add core event to search.php

---

phpBB/includes/functions_content.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-16852">PHPBB-16852</a>.
<a href="https://tracker.phpbb.com/browse/PHPBB-17388">PHPBB-17388</a>.

[ticket/17388] Add core events to bump_topic_allowed()

---

phpBB/adm/style/acp_ext_list.html
phpBB/docs/events.md
phpBB/includes/acp/acp_extensions.php
phpBB/language/en/acp/extensions.php
tests/functional/extension_acp_test.php

PHPBB-17421
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17421

[ticket/17421] Rename extensions section to "not installed"

---

phpBB/phpbb/search/base.php
tests/functional/search/base.php
tests/functional/ucp_attachments_test.php
tests/test_framework/phpbb_functional_test_case.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17422">PHPBB-17422</a>.

[ticket/17422] Fix search results sorting - 3.3.x

---

phpBB/phpbb/search/backend/base.php
tests/functional/search/base.php
tests/test_framework/phpbb_functional_test_case.php

`master` version of #6744.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17422">PHPBB-17422</a>.

[ticket/17422] Fix search results sorting - master

---

Vagrantfile

PHPBB-17434
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17434

[ticket/17434] Update Vagrantfile ruby syntax

---

phpBB/install/convertors/functions_phpbb20.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17436">PHPBB-17436</a>.

[ticket/17436] Fix phpBB 2.0 converter PHP fatal error

---

phpBB/includes/acp/acp_board.php
phpBB/language/en/acp/board.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17433">PHPBB-17433</a>.

[ticket/17433] Clarify wording for use system cron ACP setting

---

phpBB/adm/style/admin.js
phpBB/phpbb/manifest.php
phpBB/styles/prosilver/template/overall_header.html

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17449

[ticket/17449] Better handling of emoji and mb chars in PWA manifest

---

phpBB/includes/acp/acp_board.php

Event added for additional account activation methods.
PHPBB-17446
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17446

[ticket/17446] Add acp_account_activation_edit_add event

---

phpBB/includes/acp/acp_board.php

Master version. Event added for additional account activation methods.
PHPBB-17446
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17446

[ticket/17446] Master: Add acp_account_activation_edit_add event

---

phpBB/phpbb/file_downloader.php
phpBB/phpbb/version_helper.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17443">PHPBB-17443</a>.

[ticket/17443] Fix various Guzzle client issues for version checks

---

phpBB/styles/prosilver/template/overall_header.html

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17457">PHPBB-17457</a>.

[ticket/17457] Protect manifest request by CORS to prevent guest sessions

---

phpBB/config/default/container/services.yml
phpBB/phpbb/manifest.php
tests/functional/manifest_test.php

PHPBB-17457
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17457

[ticket/17457] Cache manifest file

---

phpBB/phpbb/ucp/controller/webpush.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17454">PHPBB-17454</a>.

[ticket/17454] Fix displaying emojis in sitename within webpush header

---

phpBB/composer.json
phpBB/composer.lock

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17450

[ticket/17450] Remove obsolete requirement for JSON extension

---

phpBB/includes/functions_user.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17429

[ticket/17429] Added trigger for event "group_add_user_before"

---

phpBB/phpbb/db/driver/mysqli.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17455">PHPBB-17455</a>.

[ticket/17455] Fix PHP warning on MySQLi connection failure

---

phpBB/styles/prosilver/template/bbcode.html
tests/text_formatter/s9e/default_formatting_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17460">PHPBB3-17460</a>.

[ticket/17460] Fix fa-arrow-circle-up icon rendering in Quote BBCode

---

phpBB/includes/functions.php
phpBB/styles/prosilver/template/overall_header.html

PHPBB-17464
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17464

[ticket/17464] Update PWA-related meta tags

---

phpBB/phpbb/ucp/controller/reset_password.php

This fix is only relevant for `3.3.x`.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17468">PHPBB-17468</a>.

[ticket/17468] Send reset password link to email only

---

phpBB/phpbb/ucp/controller/webpush.php
tests/ucp/controller_webpush_test.php
tests/ucp/fixtures/webpush.xml

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17465

[ticket/17465] Add unit tests for handling of web push notifications

---

phpBB/includes/functions_messenger.php

The fix is only relevant for `3.3.x`.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17467">PHPBB-17467</a>.

[ticket/17467] Provide TLS v.1.3 support for SMTP connections

---

phpBB/styles/prosilver/template/forumlist_body.html

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17471

[ticket/17471] Fix feed link href for feed icon

---

tests/functional/feed_test.php

Symfony DomCrawler component validates form values and throws InvalidArgumentException for impossible values set.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17470">PHPBB-17470</a>.

[ticket/17470] Fix feed functional tests for master

---

phpBB/includes/acp/acp_main.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17461">PHPBB-17461</a>.

[ticket/17461] Add core events to acp_main

---

phpBB/memberlist.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17227">PHPBB-17227</a>.

[ticket/17227] Fix rows duplication in memberlist

---

SECURITY.md

PHPBB-17478
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17478

[ticket/17478] Add security policy file

---

phpBB/includes/acp/acp_extensions.php
phpBB/includes/acp/acp_main.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17480">PHPBB-17480</a>.

[ticket/17480] Fix PHP fatal error in version check failure

---

phpBB/language/en/common.php
phpBB/phpbb/file_downloader.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-17480">PHPBB3-17480</a>.
Before:
After:

[ticket/17480] Properly catch RuntimeException if no http handler is available

---

phpBB/includes/acp/acp_attachments.php
phpBB/includes/acp/acp_forums.php
phpBB/includes/acp/acp_main.php
phpBB/includes/functions_convert.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17475">PHPBB-17475</a>.

[ticket/17475] Fix MSSQL arithmetic overflow error on counting attachments size

---

phpBB/includes/acp/acp_email.php
phpBB/includes/acp/acp_inactive.php
phpBB/includes/ucp/ucp_activate.php
phpBB/includes/ucp/ucp_resend.php
phpBB/phpbb/message/message.php
phpBB/phpbb/messenger/method/base.php
phpBB/phpbb/messenger/method/email.php
phpBB/phpbb/messenger/method/messenger_interface.php
phpBB/phpbb/messenger/queue.php
phpBB/phpbb/notification/method/messenger_base.php
tests/functional/memberlist_test.php

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17487">PHPBB-17487</a>.
<a href="https://tracker.phpbb.com/browse/PHPBB-17489">PHPBB-17489</a>.

[ticket/17489] Fix various messenger issues

---

phpBB/phpbb/messenger/method/base.php
phpBB/phpbb/messenger/method/email.php
tests/messenger/method_base_test.php
tests/messenger/method_email_test.php
tests/messenger/method_jabber_test.php
tests/messenger/queue_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17490

[ticket/17490] Add unit tests for symfony mailer classes

---

phpBB/styles/prosilver/template/navbar_footer.html
phpBB/styles/prosilver/template/viewtopic_topic_tools.html

PHPBB3-17492
Checklist:
https://tracker.phpbb.com/browse/PHPBB3-17492

[ticket/17492] Unintuitive checkbox status inverted for forum/topic subscriptions

---

phpBB/styles/prosilver/template/navbar_footer.html
phpBB/styles/prosilver/template/viewtopic_topic_tools.html

Master version of #6797 
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17492

[ticket/17492] Show current state of topic subscription in dropdown -- master version

---

build/build.xml
build/build_changelog.php
build/build_helper.php
build/compare.sh

PHPBB-17481
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17481

[ticket/17481] Make build package directory version independent

---

.github/setup-sphinx.sh
.github/workflows/tests.yml
phpBB/phpbb/search/fulltext_sphinx.php
tests/functional/search/base.php
tests/functional/search/sphinx_test.php
tests/functional/visibility_softdelete_test.php
tests/test_framework/phpbb_functional_test_case.php

Also adjust Sphinx keywords splitting to be consistent with other search backends when it comes to handling hyphen (like ignoring hyphen when it hasn't NOT meaning and ignoring hyphen wrapped with spaces).
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16941">PHPBB3-16941</a>.

[ticket/16941] Add sphinx tests to 3.3.x

---

.github/setup-sphinx.sh
phpBB/phpbb/search/backend/fulltext_sphinx.php
tests/functional/search/base.php
tests/functional/search/sphinx_test.php
tests/functional/visibility_softdelete_test.php
tests/test_framework/phpbb_functional_test_case.php

`master` version of #6807. Sphinx tests were added to `master` with #6345, so this is only adjusting the tests and handling hyphen in search.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB3-16941">PHPBB3-16941</a>.

[ticket/16941] Add sphinx tests - master

---

.github/setup-exiftool.sh
.github/setup-sphinx.sh
.github/setup-unbuffer.sh
.github/setup-webserver.sh
.github/workflows/tests.yml

Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17504">PHPBB-17504</a>.

[ticket/17504] Fix tests failure caused by ondrej/php PPA repo label changed

---

phpBB/phpbb/search/base.php
phpBB/phpbb/search/fulltext_mysql.php
phpBB/phpbb/search/fulltext_native.php
phpBB/phpbb/search/fulltext_postgres.php
tests/functional/search/base.php

For `3.3.x`. This will require a separate PR for `master`.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17491">PHPBB-17491</a>.

[ticket/17491] Fix caching search results - 3.3.x

---

phpBB/phpbb/search/backend/base.php
phpBB/phpbb/search/backend/fulltext_mysql.php
phpBB/phpbb/search/backend/fulltext_native.php
phpBB/phpbb/search/backend/fulltext_postgres.php
tests/functional/search/base.php

`master` version of #6799.
Checklist:
<a href="https://tracker.phpbb.com/browse/PHPBB-17491">PHPBB-17491</a>.

[ticket/17491] Fix caching search results - master

---

phpBB/includes/acp/acp_profile.php
tests/functional/acp_profile_field_test.php

Related to #6225.
Checklist:
[PHPBB-17508](https://tracker.phpbb.com/browse/PHPBB-17508).

[ticket/17508] Fix PHP warning on custom profile fields edit

---

build/code_sniffer/phpbb/Sniffs/Commenting/FileCommentSniff.php
build/code_sniffer/phpbb/Sniffs/ControlStructures/OpeningBraceBsdAllmanSniff.php
build/code_sniffer/phpbb/Sniffs/ControlStructures/OpeningParenthesisSniff.php
build/code_sniffer/phpbb/Sniffs/ControlStructures/StaticKeywordSniff.php
build/code_sniffer/phpbb/Sniffs/Namespaces/UnusedUseSniff.php
build/code_sniffer/ruleset-php-legacy.xml
phpBB/composer.lock

PHPBB-17510
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17510

[ticket/17510] Fix Code Sniffer deprecations

---

build/code_sniffer/phpbb/Sniffs/Commenting/FileCommentSniff.php
build/code_sniffer/phpbb/Sniffs/ControlStructures/OpeningBraceBsdAllmanSniff.php
build/code_sniffer/phpbb/Sniffs/ControlStructures/OpeningParenthesisSniff.php
build/code_sniffer/phpbb/Sniffs/ControlStructures/StaticKeywordSniff.php
build/code_sniffer/phpbb/Sniffs/Namespaces/UnusedUseSniff.php
build/code_sniffer/ruleset-php-legacy.xml
phpBB/composer.lock

Master version of #6814 
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17510

[ticket/17510] Fix Code Sniffer deprecations -- master version

---

build/code_sniffer/phpbb/Sniffs/CodeLayout/UnionTypesCheckSniff.php
build/code_sniffer/ruleset-php-strict.xml
phpBB/phpbb/routing/loader_resolver.php

Checklist:
[PHPBB-17512](https://tracker.phpbb.com/browse/PHPBB-17512).

[ticket/17512] Add PHP Sniffer coding standard for union types

---

phpBB/composer.json
phpBB/composer.lock
phpBB/phpbb/db/migration/schema_generator.php

PHPBB-17516
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17516

[ticket/17516] Remove dependency on topological sort library

---

phpBB/composer.json
phpBB/composer.lock
phpBB/language/en/install.php
phpBB/phpbb/db/doctrine/connection_parameter_factory.php
phpBB/phpbb/db/driver/sqlite3.php
phpBB/phpbb/db/tools/doctrine.php
phpBB/phpbb/install/helper/database.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17509

[ticket/17509] Bump DBMS supported versions

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/ucp_pm_viewmessage.html

`master` version of #6818.
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17515

[ticket/17515] Add template event before PM text - master

---

phpBB/docs/events.md
phpBB/styles/prosilver/template/ucp_pm_viewmessage.html

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17515

[ticket/17515] Add template event before PM text - 3.3.x

---

phpBB/phpbb/template/twig/twig.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17527

[ticket/17527] Add Twig extensions existence check while registering

---

phpBB/styles/all/template/cron.html
tests/cron/wrapper_test.php

PHPBB-17519
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17519

[ticket/17519] Revert cron url escape back to html_attr

---

phpBB/phpbb/di/container_builder.php

This should help with checking whether the ConfigCache is still fresh.
PHPBB-17537
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17537

[ticket/17537] Cache extensions paths as metadata for ConfigCache

---

phpBB/phpbb/session.php

PHPBB-17451
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17451

[ticket/17451] Web push service worker shouldn't update user activity

---

tests/mock/event_dispatcher.php

PHPBB-17542
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17542

[ticket/17542] Mock event dispatcher override early exits

---

phpBB/includes/functions_user.php
tests/functions_user/whois_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17477

[ticket/17477] Support non-prefixed whois servers

---

phpBB/adm/style/acp_ext_list.html
phpBB/language/en/acp/extensions.php

PHPBB-17552
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17552

[ticket/17552] Remove plural rule structure in extensions.php

---

phpBB/phpbb/db/migration/data/v400/storage_track.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB-17557

[ticket/17557] Add error suppression to avatars in storage_track migration

---

.github/workflows/tests.yml
tests/avatar/manager_test.php
tests/console/update/check_test.php

Opted for this now since this issue seems to return randomly for functional tests on windows and we're fine with just unit tests on that platform.
PHPBB-17555
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17555

[ticket/17555] Only run unit tests on windows runners

---

.gitignore
.phpunit.result.cache
git-tools/hooks/commit-msg
phpBB/config/default/container/services_feed.yml
phpBB/language/en/acp/board.php
phpBB/phpbb/feed/event/http_auth_subscriber.php
tests/feed/http_auth_subscriber_test.php

Checklist:
https://tracker.phpbb.com/browse/PHPBB-15085

[ticket/15085] Add back http authentication support for feeds

---

phpBB/styles/prosilver/theme/colours.css

See linked ticket to effects of the change.
PHPBB-17564
Checklist:
https://tracker.phpbb.com/browse/PHPBB-17564

[ticket/17564] Adjust text-shadow of header profile for better contrast
